  ('ADMIN_HISTORY_ADDRESS', 'Endereço'),
  ('ADMIN_HISTORY_BACK', '← Admin'),
  ('ADMIN_HISTORY_CLEAR', 'Limpar'),
  ('ADMIN_HISTORY_CLIENT_NAME', 'Nome do cliente'),
  ('ADMIN_HISTORY_EMPTY', 'Nenhum pedido encontrado.'),
  ('ADMIN_HISTORY_FILTER', 'Filtrar'),
  ('ADMIN_HISTORY_FILTERS', 'Filtros'),
  ('ADMIN_HISTORY_FOUND_MULTI', 'pedidos encontrados'),
  ('ADMIN_HISTORY_FOUND_SINGLE', 'pedido encontrado'),
  ('ADMIN_HISTORY_FROM', 'De'),
  ('ADMIN_HISTORY_HALF_HALF', 'Meio a Meio'),
  ('ADMIN_HISTORY_MARK_PAID', '✓ Pago'),
  ('ADMIN_HISTORY_NOTES', 'Obs'),
  ('ADMIN_HISTORY_PAYMENT_MARKED', 'Pagamento marcado como aprovado'),
  ('ADMIN_HISTORY_PAYMENT_UPDATE_ERROR', 'Falha ao atualizar pagamento'),
  ('ADMIN_HISTORY_PIZZA', 'Pizza'),
  ('ADMIN_HISTORY_REFUND_PENDING', 'ESTORNO PENDENTE'),
  ('ADMIN_HISTORY_SHOW_ALL', 'Ver todos'),
  ('ADMIN_HISTORY_SHOW_REFUNDS', 'Ver só estornos'),
  ('ADMIN_HISTORY_TITLE', 'Histórico de Pedidos'),
  ('ADMIN_HISTORY_TO', 'Até'),
  ('ADMIN_HISTORY_TOTAL', 'Total'),
  ('ADMIN_MESAS_BACK_PANEL', '← Painel Admin'),
  ('ADMIN_MESAS_EMPTY', 'Nenhuma mesa cadastrada ainda.'),
  ('ADMIN_MESAS_HELP_TITLE', 'Como achar o ID da maquininha?'),
  ('ADMIN_MESAS_LOAD_ERROR', 'Falha ao carregar mesas.'),
  ('ADMIN_MESAS_LOADING', 'Carregando mesas...'),
  ('ADMIN_MESAS_NEW_BUTTON', 'Nova Mesa'),
  ('ADMIN_MESAS_TITLE', 'Mesas'),
  ('ADMIN_PRODUCTS_ACTIVE', 'Ativo'),
  ('ADMIN_PRODUCTS_ACTIVE_COUNT', '{{count}} ativos'),
  ('ADMIN_PRODUCTS_CATEGORY_LABEL', 'Categoria'),
  ('ADMIN_PRODUCTS_COST_OPTIONAL', 'Custo (opcional)'),
  ('ADMIN_PRODUCTS_CREATE', 'Criar'),
  ('ADMIN_PRODUCTS_CREATED', 'Produto criado!'),
  ('ADMIN_PRODUCTS_DESCRIPTION_LABEL', 'Descrição'),
  ('ADMIN_PRODUCTS_DISABLE', 'Desativar'),
  ('ADMIN_PRODUCTS_DISABLED', 'Produto desativado'),
  ('ADMIN_PRODUCTS_EDIT_TITLE', 'Editar Produto'),
  ('ADMIN_PRODUCTS_EMPTY', 'Nenhum produto cadastrado ainda.'),
  ('ADMIN_PRODUCTS_IMAGE_URL', 'URL da Imagem'),
  ('ADMIN_PRODUCTS_INACTIVE', 'Inativo'),
  ('ADMIN_PRODUCTS_INACTIVE_COUNT', '{{count}} inativos'),
  ('ADMIN_PRODUCTS_LOAD_ERROR', 'Falha ao carregar produtos.'),
  ('ADMIN_PRODUCTS_NAME_LABEL', 'Nome *'),
  ('ADMIN_PRODUCTS_NEW_BUTTON', 'Novo Produto'),
  ('ADMIN_PRODUCTS_NEW_TITLE', 'Novo Produto'),
  ('ADMIN_PRODUCTS_PRICE_COST', 'Preço e custo *'),
  ('ADMIN_PRODUCTS_PRICES_BY_SIZE', 'Preços por Tamanho *'),
  ('ADMIN_PRODUCTS_RESTORE', 'Reativar'),
  ('ADMIN_PRODUCTS_RESTORED', 'Produto reativado'),
  ('ADMIN_PRODUCTS_SALE_PRICE', 'Preço de venda'),
  ('ADMIN_PRODUCTS_SAVE_ERROR', 'Erro ao salvar produto'),
  ('ADMIN_PRODUCTS_SAVING', 'Salvando...'),
  ('ADMIN_PRODUCTS_STATUS_ERROR', 'Falha ao alterar status'),
  ('ADMIN_PRODUCTS_TITLE', 'Produtos'),
  ('ADMIN_PRODUCTS_TYPE_CRUST', 'Borda recheada'),
  ('ADMIN_PRODUCTS_TYPE_FLAVOR', 'Sabor'),
  ('ADMIN_PRODUCTS_TYPE_LABEL', 'Tipo do produto'),
  ('ADMIN_PRODUCTS_TYPE_OTHER', 'Outros'),
  ('ADMIN_PRODUCTS_TYPE_PIZZA', 'Pizza'),
  ('ADMIN_PRODUCTS_UPDATED', 'Produto atualizado!'),
  ('ADMIN_USERS_BACK_PANEL', '← Painel Admin'),
  ('ADMIN_USERS_CREATE_ANOTHER', 'Criar outro usuário'),
  ('ADMIN_USERS_CREATE_BUTTON', 'Criar'),
  ('ADMIN_USERS_CREATED_SUCCESS', 'Usuário criado com sucesso!'),
  ('ADMIN_USERS_CREATING', 'Criando...'),
  ('ADMIN_USERS_EMAIL_LABEL', 'E-mail'),
  ('ADMIN_USERS_EMAIL_PLACEHOLDER', 'ex@email.com'),
  ('ADMIN_USERS_FIELD_EMAIL', 'E-mail'),
  ('ADMIN_USERS_FIELD_NAME', 'Nome'),
  ('ADMIN_USERS_FIELD_PASSWORD', 'Senha'),
  ('ADMIN_USERS_FIELD_PHONE', 'Telefone'),
  ('ADMIN_USERS_FIELD_ROLE', 'Perfil'),
  ('ADMIN_USERS_GENERIC_USER', 'Usuário'),
  ('ADMIN_USERS_NAME_LABEL', 'Nome completo *'),
  ('ADMIN_USERS_NAME_PLACEHOLDER', 'Ex: João Silva'),
  ('ADMIN_USERS_PASSWORD_LABEL', 'Senha *'),
  ('ADMIN_USERS_PHONE_LABEL', 'Telefone'),
  ('ADMIN_USERS_ROLE_LABEL', 'Perfil *'),
  ('ADMIN_USERS_TITLE', 'Criar Usuário'),
  ('APP_BRAND_NAME', 'Pizzaria Fellice'),
  ('CHECKOUT_RETURN_BACK_MENU', 'Voltar ao cardápio'),
  ('CHECKOUT_RETURN_CONFIRM_ERROR', 'Erro ao confirmar'),
  ('CHECKOUT_RETURN_FAILURE_BUTTON', 'Tentar novamente'),
  ('CHECKOUT_RETURN_FAILURE_TITLE', 'Pagamento não concluído'),
  ('CHECKOUT_RETURN_ORDER_PREFIX', 'Pedido'),
  ('CHECKOUT_RETURN_PENDING_BUTTON', 'Ver meus pedidos'),
  ('CHECKOUT_RETURN_PENDING_TITLE', 'Pagamento em análise'),
  ('CHECKOUT_RETURN_SUCCESS_BUTTON', 'Acompanhar meu pedido'),
  ('CHECKOUT_RETURN_SUCCESS_TITLE', 'Pagamento confirmado!'),
  ('CLIENT_DASHBOARD_ASK_REASON', 'Perguntar motivo'),
  ('CLIENT_DASHBOARD_CLIENT', 'Cliente'),
  ('CLIENT_DASHBOARD_CONFIRM', 'Confirmar?'),
  ('CLIENT_DASHBOARD_CRUST', 'Borda'),
  ('CLIENT_DASHBOARD_DELIVERY', 'Entrega'),
  ('CLIENT_DASHBOARD_EMPTY_ALL', 'Voce ainda nao possui pedidos.'),
  ('CLIENT_DASHBOARD_FILTER_ALL', 'Todos'),
  ('CLIENT_DASHBOARD_HALF_HALF', 'Meio a Meio'),
  ('CLIENT_DASHBOARD_HELLO', 'Ola'),
  ('CLIENT_DASHBOARD_LOAD_ERROR', 'Erro ao carregar pedidos.'),
  ('CLIENT_DASHBOARD_ORDER_PREFIX', 'Pedido'),
  ('CLIENT_DASHBOARD_PAYMENT', 'Pagamento'),
  ('CLIENT_DASHBOARD_PIZZA', 'Pizza'),
  ('CLIENT_DASHBOARD_REPEAT_ORDER', 'Repetir pedido'),
  ('DELETE', 'Excluir'),
  ('EDIT', 'Editar'),
  ('FIRST_HALF_SELECTED_MSG', 'Primeira metade selecionada:'),
  ('KITCHEN_ADVANCE_TO_TABLE', 'Levar para a Mesa'),
  ('KITCHEN_CLEAR_ALERTS', 'Limpar alertas'),
  ('KITCHEN_DELIVERED_AT_TABLE', 'Entregue na Mesa'),
  ('KITCHEN_DELIVERY', 'Entrega'),
  ('KITCHEN_LIVE', 'Ao vivo'),
  ('KITCHEN_LOAD_ERROR', 'Falha ao carregar pedidos.'),
  ('KITCHEN_MARK_PICKED_UP', 'Marcar Retirado'),
  ('KITCHEN_NEW_ORDER', 'Novo pedido'),
  ('KITCHEN_NO_ACTIVE_ORDERS', 'Sem pedidos ativos no momento.'),
  ('KITCHEN_NO_ALERTS', 'Nenhum alerta pendente'),
  ('KITCHEN_NO_ORDER', 'Nenhum pedido'),
  ('KITCHEN_NO_OVERDUE', 'Sem pedidos em atraso'),
  ('KITCHEN_OFF', 'desligado'),
  ('KITCHEN_ON', 'ligado'),
  ('KITCHEN_ORDERS_IN_STAGE', 'Pedidos nesta etapa'),
  ('KITCHEN_PAYMENT_PENDING', 'Pag. pendente'),
  ('KITCHEN_PICKUP', 'Retirada'),
  ('KITCHEN_READY_PICKUP', 'Pronto p/ Retirada'),
  ('KITCHEN_SOUND', 'Som'),
  ('KITCHEN_TITLE', 'Cozinha'),
  ('KITCHEN_UPDATING', 'Atualizando...'),
  ('MESA_ACCESS_INVALID_QR_TITLE', 'QR Code inválido'),
  ('MESA_ACCESS_LOADING', 'Identificando mesa...'),
  ('MESA_CHECKOUT_BACK_MENU', '← Cardápio'),
  ('MESA_CHECKOUT_CONFIRM_ORDER', 'Confirmar pedido'),
  ('MESA_CHECKOUT_NOTES_LABEL', 'Observações (opcional)'),
  ('MESA_CHECKOUT_ORDER_ERROR', 'Erro ao fazer pedido.'),
  ('MESA_CHECKOUT_ORDER_SENT', 'Pedido enviado para a cozinha!'),
  ('MESA_CHECKOUT_PAY_LATER', 'Pagar depois'),
  ('MESA_CHECKOUT_PAY_NOW', 'Deseja pagar agora?'),
  ('MESA_CHECKOUT_PAYMENT_CONFIRMED', 'MESA_CHECKOUT_PAYMENT_CONFIRMED'),
  ('MESA_CHECKOUT_PENDING_TOTAL', 'Total pendente'),
  ('MESA_CHECKOUT_PIX_SHORT', 'PIX'),
  ('MESA_CHECKOUT_SENDING', 'Enviando...'),
  ('MESA_CHECKOUT_SESSION_ORDERS', 'Pedidos desta sessão'),
  ('MESA_CHECKOUT_TABLE', 'Mesa'),
  ('MESA_CHECKOUT_TERMINAL_SHORT', 'Maquininha'),
  ('MESA_CHECKOUT_VIEW_MENU', 'Ver cardápio'),
  ('MESA_CHECKOUT_YOUR_ORDER', 'Seu pedido'),
  ('MESA_PIX_COPIED', 'Código copiado!'),
  ('MESA_PIX_COPY_BUTTON', 'Copiar código PIX'),
  ('MESA_PIX_COPY_HINT', 'Ou copie o código:'),
  ('MESA_PIX_ERROR', 'Erro ao gerar PIX. Tente novamente.'),
  ('MESA_PIX_GENERATING', 'Gerando QR Code...'),
  ('MESA_PIX_QR_ALT', 'QR Code PIX'),
  ('MESA_PIX_TITLE', 'Pagar com PIX'),
  ('MESA_PIX_WAITING', 'Aguardando confirmação do pagamento...'),
  ('MESA_TERMINAL_SEND_BUTTON', 'Enviar para maquininha'),
  ('MESA_TERMINAL_SEND_ERROR', 'Erro ao enviar para maquininha.'),
  ('MESA_TERMINAL_SENDING', 'Enviando...'),
  ('MESA_TERMINAL_SENT', 'Cobrança enviada para a maquininha!'),
  ('MESA_TERMINAL_TITLE', 'Pagar na Maquininha'),
  ('MONTH_LABEL_APR', 'Abril'),
  ('MONTH_LABEL_AUG', 'Agosto'),
  ('MONTH_LABEL_DEC', 'Dezembro'),
  ('MONTH_LABEL_FEB', 'Fevereiro'),
  ('MONTH_LABEL_JAN', 'Janeiro'),
  ('MONTH_LABEL_JUL', 'Julho'),
  ('MONTH_LABEL_JUN', 'Junho'),
  ('MONTH_LABEL_MAR', 'Março'),
  ('MONTH_LABEL_MAY', 'Maio'),
  ('MONTH_LABEL_NOV', 'Novembro'),
  ('MONTH_LABEL_OCT', 'Outubro'),
  ('MONTH_LABEL_SEP', 'Setembro'),
  ('MONTH_SHORT_APR', 'Abr'),
  ('MONTH_SHORT_AUG', 'Ago'),
  ('MONTH_SHORT_DEC', 'Dez'),
  ('MONTH_SHORT_FEB', 'Fev'),
  ('MONTH_SHORT_JAN', 'Jan'),
  ('MONTH_SHORT_JUL', 'Jul'),
  ('MONTH_SHORT_JUN', 'Jun'),
  ('MONTH_SHORT_MAR', 'Mar'),
  ('MONTH_SHORT_MAY', 'Mai'),
  ('MONTH_SHORT_NOV', 'Nov'),
  ('MONTH_SHORT_OCT', 'Out'),
  ('MONTH_SHORT_SEP', 'Set'),
  ('MOTOBOY_ADDRESS', 'Endereço'),
  ('MOTOBOY_ALREADY_PAID', 'Já pago'),
  ('MOTOBOY_CODE_PLACEHOLDER', 'Ex.: 1234'),
  ('MOTOBOY_CONFIRM', 'Confirmar'),
  ('MOTOBOY_CONFIRM_PAYMENT_TITLE', 'Confirmar pagamento?'),
  ('MOTOBOY_CONFIRMING', 'Confirmando...'),
  ('MOTOBOY_DELIVERY_CONFIRMED', 'Entrega confirmada com sucesso.'),
  ('MOTOBOY_DELIVERY_FEE', 'Frete'),
  ('MOTOBOY_GOOGLE_MAPS', 'Google Maps'),
  ('MOTOBOY_LOADING', 'Carregando...'),
  ('MOTOBOY_MARK_PAID', 'Marcar como pago'),
  ('MOTOBOY_ORDER_PREFIX', 'Pedido'),
  ('MOTOBOY_ORDER_TOTAL', 'Total do pedido'),
  ('MOTOBOY_PAYMENT_MARKED', 'Pagamento marcado como aprovado.'),
  ('MOTOBOY_REFRESH', 'Atualizar'),
  ('MOTOBOY_SAVING', 'Salvando...'),
  ('MOTOBOY_TITLE', 'Entregas'),
  ('MOTOBOY_WAZE', 'Waze'),
  ('NO', 'Não'),
  ('SALES_ANALYTICS_AVG_TICKET', 'Ticket Médio'),
  ('SALES_ANALYTICS_BACK_PANEL', 'Painel'),
  ('SALES_ANALYTICS_BY_MONTH', 'Por mês'),
  ('SALES_ANALYTICS_COST_PREFIX', 'Custo'),
  ('SALES_ANALYTICS_COST_TOTAL', 'Custo Total'),
  ('SALES_ANALYTICS_FULL_YEAR', 'Ano todo'),
  ('SALES_ANALYTICS_GO_PRODUCTS', 'Produtos'),
  ('SALES_ANALYTICS_LEGEND_COST', 'Custo'),
  ('SALES_ANALYTICS_LEGEND_PROFIT', 'Lucro'),
  ('SALES_ANALYTICS_LEGEND_REVENUE', 'Receita'),
  ('SALES_ANALYTICS_MONTH', 'Mês'),
  ('SALES_ANALYTICS_PROFIT_HINT', 'Receita − Custo'),
  ('SALES_ANALYTICS_PROFIT_PREFIX', 'Lucro'),
  ('SALES_ANALYTICS_PROFIT_TOTAL', 'Lucro Líquido'),
  ('SALES_ANALYTICS_REVENUE_TOTAL', 'Receita Total'),
  ('SALES_ANALYTICS_STATUS_TITLE', 'Status dos Pedidos'),
  ('SALES_ANALYTICS_TITLE', 'Análise de Vendas'),
  ('SALES_ANALYTICS_TODAY', 'Hoje'),
  ('SALES_ANALYTICS_TOP_FLAVORS', 'Top Sabores'),
  ('YES', 'Sim')
