-- =============================================================
-- I18n API — Traduções completas do site Pizzaria Fellice
-- Sistema: 'website'  |  6 idiomas
-- Execute após schema.sql e seed.sql (que já cria o sistema 'website')
-- =============================================================

-- Garante que o sistema 'website' existe
INSERT INTO sistemas (codigo, nome, descricao)
VALUES ('website', 'Website Principal', 'Portal público da aplicação')
ON CONFLICT (codigo) DO NOTHING;

-- Garante que todos os idiomas existem
INSERT INTO idiomas (codigo, nome, direcao) VALUES
    ('en-US', 'English (United States)',    'ltr'),
    ('it-IT', 'Italiano',                  'ltr'),
    ('pt-PT', 'Português (Portugal)',       'ltr'),
    ('pt-BR', 'Português (Brasil)',         'ltr'),
    ('es-ES', 'Español (España)',           'ltr'),
    ('ar-MA', 'العربية المغربية (Darija)',  'rtl')
ON CONFLICT (codigo) DO NOTHING;

-- =============================================================
-- Inserção em lote via VALUES — cleaner e upsafe
-- Formato: (chave, codigo_idioma, valor)
-- =============================================================
INSERT INTO traducoes (chave, valor, sistema_id, idioma_id)
SELECT t.chave, t.valor, s.id, i.id
FROM sistemas s
JOIN idiomas   i ON i.codigo = t.codigo_idioma
JOIN (VALUES

  -- ─── NAVEGAÇÃO ─────────────────────────────────────────────
  ('NAV_HOME',        'pt-BR', 'Início'),
  ('NAV_HOME',        'pt-PT', 'Início'),
  ('NAV_HOME',        'en-US', 'Home'),
  ('NAV_HOME',        'it-IT', 'Home'),
  ('NAV_HOME',        'es-ES', 'Inicio'),
  ('NAV_HOME',        'ar-MA', 'الرئيسية'),

  ('NAV_CARDAPIO',    'pt-BR', 'Cardápio'),
  ('NAV_CARDAPIO',    'pt-PT', 'Ementa'),
  ('NAV_CARDAPIO',    'en-US', 'Menu'),
  ('NAV_CARDAPIO',    'it-IT', 'Menu'),
  ('NAV_CARDAPIO',    'es-ES', 'Carta'),
  ('NAV_CARDAPIO',    'ar-MA', 'قائمة الطعام'),

  ('NAV_PAINEL',      'pt-BR', 'Painel'),
  ('NAV_PAINEL',      'pt-PT', 'Painel'),
  ('NAV_PAINEL',      'en-US', 'Panel'),
  ('NAV_PAINEL',      'it-IT', 'Pannello'),
  ('NAV_PAINEL',      'es-ES', 'Panel'),
  ('NAV_PAINEL',      'ar-MA', 'لوحة التحكم'),

  ('NAV_SAIR',        'pt-BR', 'Sair'),
  ('NAV_SAIR',        'pt-PT', 'Sair'),
  ('NAV_SAIR',        'en-US', 'Sign Out'),
  ('NAV_SAIR',        'it-IT', 'Esci'),
  ('NAV_SAIR',        'es-ES', 'Salir'),
  ('NAV_SAIR',        'ar-MA', 'خروج'),

  ('NAV_ENTRAR',      'pt-BR', 'Entrar'),
  ('NAV_ENTRAR',      'pt-PT', 'Entrar'),
  ('NAV_ENTRAR',      'en-US', 'Sign In'),
  ('NAV_ENTRAR',      'it-IT', 'Accedi'),
  ('NAV_ENTRAR',      'es-ES', 'Entrar'),
  ('NAV_ENTRAR',      'ar-MA', 'دخول'),

  ('NAV_CARRINHO',    'pt-BR', 'Carrinho'),
  ('NAV_CARRINHO',    'pt-PT', 'Carrinho'),
  ('NAV_CARRINHO',    'en-US', 'Cart'),
  ('NAV_CARRINHO',    'it-IT', 'Carrello'),
  ('NAV_CARRINHO',    'es-ES', 'Carrito'),
  ('NAV_CARRINHO',    'ar-MA', 'سلة التسوق'),

  ('NAV_PAGAR',       'pt-BR', 'Pagar'),
  ('NAV_PAGAR',       'pt-PT', 'Pagar'),
  ('NAV_PAGAR',       'en-US', 'Pay'),
  ('NAV_PAGAR',       'it-IT', 'Paga'),
  ('NAV_PAGAR',       'es-ES', 'Pagar'),
  ('NAV_PAGAR',       'ar-MA', 'دفع'),

  ('NAV_WHATSAPP_TITLE','pt-BR','Falar no WhatsApp'),
  ('NAV_WHATSAPP_TITLE','pt-PT','Falar no WhatsApp'),
  ('NAV_WHATSAPP_TITLE','en-US','Chat on WhatsApp'),
  ('NAV_WHATSAPP_TITLE','it-IT','Parla su WhatsApp'),
  ('NAV_WHATSAPP_TITLE','es-ES','Hablar en WhatsApp'),
  ('NAV_WHATSAPP_TITLE','ar-MA','تحدث عبر واتساب'),

  -- ─── BOTÕES GLOBAIS ─────────────────────────────────────────
  ('BTN_CONFIRM',     'pt-BR', 'Confirmar'),
  ('BTN_CONFIRM',     'pt-PT', 'Confirmar'),
  ('BTN_CONFIRM',     'en-US', 'Confirm'),
  ('BTN_CONFIRM',     'it-IT', 'Conferma'),
  ('BTN_CONFIRM',     'es-ES', 'Confirmar'),
  ('BTN_CONFIRM',     'ar-MA', 'تأكيد'),

  ('BTN_CANCEL',      'pt-BR', 'Cancelar'),
  ('BTN_CANCEL',      'pt-PT', 'Cancelar'),
  ('BTN_CANCEL',      'en-US', 'Cancel'),
  ('BTN_CANCEL',      'it-IT', 'Annulla'),
  ('BTN_CANCEL',      'es-ES', 'Cancelar'),
  ('BTN_CANCEL',      'ar-MA', 'إلغاء'),

  ('BTN_SAVE',        'pt-BR', 'Guardar'),
  ('BTN_SAVE',        'pt-PT', 'Guardar'),
  ('BTN_SAVE',        'en-US', 'Save'),
  ('BTN_SAVE',        'it-IT', 'Salva'),
  ('BTN_SAVE',        'es-ES', 'Guardar'),
  ('BTN_SAVE',        'ar-MA', 'حفظ'),

  ('BTN_SEND',        'pt-BR', 'Enviar'),
  ('BTN_SEND',        'pt-PT', 'Enviar'),
  ('BTN_SEND',        'en-US', 'Send'),
  ('BTN_SEND',        'it-IT', 'Invia'),
  ('BTN_SEND',        'es-ES', 'Enviar'),
  ('BTN_SEND',        'ar-MA', 'إرسال'),

  ('BTN_REMOVE',      'pt-BR', 'remover'),
  ('BTN_REMOVE',      'pt-PT', 'remover'),
  ('BTN_REMOVE',      'en-US', 'remove'),
  ('BTN_REMOVE',      'it-IT', 'rimuovi'),
  ('BTN_REMOVE',      'es-ES', 'eliminar'),
  ('BTN_REMOVE',      'ar-MA', 'إزالة'),

  ('BTN_BACK',        'pt-BR', '← Voltar'),
  ('BTN_BACK',        'pt-PT', '← Voltar'),
  ('BTN_BACK',        'en-US', '← Back'),
  ('BTN_BACK',        'it-IT', '← Indietro'),
  ('BTN_BACK',        'es-ES', '← Volver'),
  ('BTN_BACK',        'ar-MA', '→ رجوع'),

  ('BTN_CLOSE',       'pt-BR', 'Fechar'),
  ('BTN_CLOSE',       'pt-PT', 'Fechar'),
  ('BTN_CLOSE',       'en-US', 'Close'),
  ('BTN_CLOSE',       'it-IT', 'Chiudi'),
  ('BTN_CLOSE',       'es-ES', 'Cerrar'),
  ('BTN_CLOSE',       'ar-MA', 'إغلاق'),

  ('BTN_ADD',         'pt-BR', 'Adicionar'),
  ('BTN_ADD',         'pt-PT', 'Adicionar'),
  ('BTN_ADD',         'en-US', 'Add'),
  ('BTN_ADD',         'it-IT', 'Aggiungi'),
  ('BTN_ADD',         'es-ES', 'Agregar'),
  ('BTN_ADD',         'ar-MA', 'إضافة'),

  -- ─── HOMEPAGE ───────────────────────────────────────────────
  ('HOME_SINCE_1997', 'pt-BR', 'Desde 1997 · 27 anos de tradição italiana'),
  ('HOME_SINCE_1997', 'pt-PT', 'Desde 1997 · 27 anos de tradição italiana'),
  ('HOME_SINCE_1997', 'en-US', 'Since 1997 · 27 years of Italian tradition'),
  ('HOME_SINCE_1997', 'it-IT', 'Dal 1997 · 27 anni di tradizione italiana'),
  ('HOME_SINCE_1997', 'es-ES', 'Desde 1997 · 27 años de tradición italiana'),
  ('HOME_SINCE_1997', 'ar-MA', 'منذ 1997 · 27 عامًا من التقليد الإيطالي'),

  ('HOME_HERO_TITLE_1','pt-BR','Autêntica'),
  ('HOME_HERO_TITLE_1','pt-PT','Autêntica'),
  ('HOME_HERO_TITLE_1','en-US','Authentic'),
  ('HOME_HERO_TITLE_1','it-IT','Autentica'),
  ('HOME_HERO_TITLE_1','es-ES','Auténtica'),
  ('HOME_HERO_TITLE_1','ar-MA','أصيلة'),

  ('HOME_HERO_TITLE_2','pt-BR','pizza italiana'),
  ('HOME_HERO_TITLE_2','pt-PT','pizza italiana'),
  ('HOME_HERO_TITLE_2','en-US','Italian pizza'),
  ('HOME_HERO_TITLE_2','it-IT','pizza italiana'),
  ('HOME_HERO_TITLE_2','es-ES','pizza italiana'),
  ('HOME_HERO_TITLE_2','ar-MA','بيتزا إيطالية'),

  ('HOME_HERO_DESC',  'pt-BR', 'Massa de fermentação lenta, ingredientes selecionados e o sabor que faz você se sentir feliz.'),
  ('HOME_HERO_DESC',  'pt-PT', 'Massa de fermentação lenta, ingredientes seleccionados e o sabor que o faz sentir feliz.'),
  ('HOME_HERO_DESC',  'en-US', 'Slow-fermented dough, handpicked ingredients and the flavor that makes you feel happy.'),
  ('HOME_HERO_DESC',  'it-IT', 'Impasto a lievitazione lenta, ingredienti selezionati e il sapore che ti fa sentire felice.'),
  ('HOME_HERO_DESC',  'es-ES', 'Masa de fermentación lenta, ingredientes seleccionados y el sabor que te hace sentir feliz.'),
  ('HOME_HERO_DESC',  'ar-MA', 'عجينة بتخمير بطيء، مكونات مختارة والنكهة التي تجعلك سعيدًا.'),

  ('HOME_BTN_ORDER',  'pt-BR', 'Fazer Pedido Agora'),
  ('HOME_BTN_ORDER',  'pt-PT', 'Fazer Pedido Agora'),
  ('HOME_BTN_ORDER',  'en-US', 'Order Now'),
  ('HOME_BTN_ORDER',  'it-IT', 'Ordina Ora'),
  ('HOME_BTN_ORDER',  'es-ES', 'Pedir Ahora'),
  ('HOME_BTN_ORDER',  'ar-MA', 'اطلب الآن'),

  ('HOME_ABOUT_LABEL','pt-BR', 'Nossa história'),
  ('HOME_ABOUT_LABEL','pt-PT', 'A nossa história'),
  ('HOME_ABOUT_LABEL','en-US', 'Our story'),
  ('HOME_ABOUT_LABEL','it-IT', 'La nostra storia'),
  ('HOME_ABOUT_LABEL','es-ES', 'Nuestra historia'),
  ('HOME_ABOUT_LABEL','ar-MA', 'قصتنا'),

  ('HOME_ABOUT_TITLE','pt-BR', 'Pizzaria Fellice – 27 Anos de Tradição'),
  ('HOME_ABOUT_TITLE','pt-PT', 'Pizzaria Fellice – 27 Anos de Tradição'),
  ('HOME_ABOUT_TITLE','en-US', 'Pizzaria Fellice – 27 Years of Tradition'),
  ('HOME_ABOUT_TITLE','it-IT', 'Pizzaria Fellice – 27 Anni di Tradizione'),
  ('HOME_ABOUT_TITLE','es-ES', 'Pizzaria Fellice – 27 Años de Tradición'),
  ('HOME_ABOUT_TITLE','ar-MA', 'بيتزاريا فيليشي – 27 عامًا من التقليد'),

  ('HOME_ABOUT_P1',   'pt-BR', 'Desde 1997, a Pizzaria Fellice é sinônimo de qualidade e sabor. Combinamos ingredientes frescos e selecionados com receitas exclusivas para criar pizzas que encantam a todos. Seja em nosso salão, que oferece um ambiente aconchegante para momentos especiais, ou através do nosso eficiente serviço de delivery, garantimos uma experiência gastronômica única.'),
  ('HOME_ABOUT_P1',   'pt-PT', 'Desde 1997, a Pizzaria Fellice é sinónimo de qualidade e sabor. Combinamos ingredientes frescos e seleccionados com receitas exclusivas para criar pizzas que encantam a todos. Seja no nosso salão, que oferece um ambiente acolhedor para momentos especiais, ou através do nosso eficiente serviço de entrega, garantimos uma experiência gastronómica única.'),
  ('HOME_ABOUT_P1',   'en-US', 'Since 1997, Pizzaria Fellice has been synonymous with quality and flavor. We combine fresh, handpicked ingredients with exclusive recipes to create pizzas that delight everyone. Whether in our welcoming dining room for special moments, or through our efficient delivery service, we guarantee a unique gastronomic experience.'),
  ('HOME_ABOUT_P1',   'it-IT', 'Dal 1997, la Pizzaria Fellice è sinonimo di qualità e sapore. Combiniamo ingredienti freschi e selezionati con ricette esclusive per creare pizze che incantano tutti. Che sia nel nostro salone accogliente per momenti speciali, o attraverso il nostro efficiente servizio di consegna, garantiamo un''esperienza gastronomica unica.'),
  ('HOME_ABOUT_P1',   'es-ES', 'Desde 1997, la Pizzaria Fellice es sinónimo de calidad y sabor. Combinamos ingredientes frescos y seleccionados con recetas exclusivas para crear pizzas que encantan a todos. Ya sea en nuestro salón acogedor para momentos especiales, o a través de nuestro eficiente servicio de entrega, garantizamos una experiencia gastronómica única.'),
  ('HOME_ABOUT_P1',   'ar-MA', 'منذ عام 1997، أصبحت بيتزاريا فيليشي مرادفًا للجودة والنكهة. نجمع بين المكونات الطازجة والوصفات الحصرية لنقدم بيتزا تسحر الجميع. سواء في قاعة طعامنا الدافئة أو عبر خدمة التوصيل، نضمن تجربة طعام استثنائية.'),

  ('HOME_ABOUT_P2',   'pt-BR', 'Além das nossas pizzas, oferecemos uma deliciosa variedade de porções, beirutes, petiscos, batatas e sobremesas, tudo preparado com o mesmo cuidado e dedicação que nos tornaram referência na região.'),
  ('HOME_ABOUT_P2',   'pt-PT', 'Além das nossas pizzas, oferecemos uma deliciosa variedade de porções, beirutes, petiscos, batatas e sobremesas, tudo preparado com o mesmo cuidado e dedicação que nos tornaram referência na região.'),
  ('HOME_ABOUT_P2',   'en-US', 'Beyond our pizzas, we offer a delicious variety of sides, sandwiches, snacks, fries and desserts, all prepared with the same care and dedication that made us a regional reference.'),
  ('HOME_ABOUT_P2',   'it-IT', 'Oltre alle nostre pizze, offriamo una deliziosa varietà di antipasti, panini, stuzzichini, patatine e dessert, tutto preparato con la stessa cura e dedizione che ci ha reso un punto di riferimento nella regione.'),
  ('HOME_ABOUT_P2',   'es-ES', 'Además de nuestras pizzas, ofrecemos una deliciosa variedad de porciones, sándwiches, aperitivos, papas fritas y postres, todo preparado con el mismo cuidado y dedicación que nos convirtió en referencia en la región.'),
  ('HOME_ABOUT_P2',   'ar-MA', 'بالإضافة إلى بيتزاتنا، نقدم تشكيلة رائعة من المقبلات والسندويشات والوجبات الخفيفة والبطاطا والحلويات، كلها محضّرة بنفس الاهتمام والتفاني.'),

  ('HOME_ABOUT_P3',   'pt-BR', 'Descubra por que a Pizzaria Fellice é a escolha certa para quem busca tradição, qualidade e um toque de exclusividade. Visite-nos ou faça seu pedido online e saboreie o melhor da gastronomia italiana com o nosso toque especial.'),
  ('HOME_ABOUT_P3',   'pt-PT', 'Descubra por que a Pizzaria Fellice é a escolha certa para quem procura tradição, qualidade e um toque de exclusividade. Visite-nos ou faça o seu pedido online e saboreie o melhor da gastronomia italiana com o nosso toque especial.'),
  ('HOME_ABOUT_P3',   'en-US', 'Discover why Pizzaria Fellice is the right choice for those seeking tradition, quality and a touch of exclusivity. Visit us or order online and savor the best Italian cuisine with our special touch.'),
  ('HOME_ABOUT_P3',   'it-IT', 'Scopri perché la Pizzaria Fellice è la scelta giusta per chi cerca tradizione, qualità e un tocco di esclusività. Vieni a trovarci o ordina online e assapora il meglio della gastronomia italiana con il nostro tocco speciale.'),
  ('HOME_ABOUT_P3',   'es-ES', 'Descubra por qué la Pizzaria Fellice es la elección correcta para quienes buscan tradición, calidad y un toque de exclusividad. Visítenos u ordene en línea y saboree lo mejor de la gastronomía italiana con nuestro toque especial.'),
  ('HOME_ABOUT_P3',   'ar-MA', 'اكتشف لماذا بيتزاريا فيليشي هي الخيار الصحيح لمن يبحث عن التقليد والجودة ولمسة من التميز. زرنا أو اطلب عبر الإنترنت واستمتع بأفضل ما في المطبخ الإيطالي.'),

  ('HOME_BTN_MENU',   'pt-BR', 'Ver Cardápio Completo'),
  ('HOME_BTN_MENU',   'pt-PT', 'Ver Ementa Completa'),
  ('HOME_BTN_MENU',   'en-US', 'View Full Menu'),
  ('HOME_BTN_MENU',   'it-IT', 'Vedi il Menu Completo'),
  ('HOME_BTN_MENU',   'es-ES', 'Ver Carta Completa'),
  ('HOME_BTN_MENU',   'ar-MA', 'عرض القائمة الكاملة'),

  ('FOOTER_COPYRIGHT','pt-BR', 'Pizzaria Fellice © 2024 · O seu momento de ser feliz!'),
  ('FOOTER_COPYRIGHT','pt-PT', 'Pizzaria Fellice © 2024 · O seu momento de ser feliz!'),
  ('FOOTER_COPYRIGHT','en-US', 'Pizzaria Fellice © 2024 · Your moment to be happy!'),
  ('FOOTER_COPYRIGHT','it-IT', 'Pizzaria Fellice © 2024 · Il tuo momento di essere felice!'),
  ('FOOTER_COPYRIGHT','es-ES', 'Pizzaria Fellice © 2024 · ¡Tu momento de ser feliz!'),
  ('FOOTER_COPYRIGHT','ar-MA', 'بيتزاريا فيليشي © 2024 · لحظتك لتكون سعيدًا!'),

  -- ─── CARDÁPIO ───────────────────────────────────────────────
  ('CARDAPIO_SINCE',  'pt-BR', 'Desde 1997 · 27 anos de tradição'),
  ('CARDAPIO_SINCE',  'pt-PT', 'Desde 1997 · 27 anos de tradição'),
  ('CARDAPIO_SINCE',  'en-US', 'Since 1997 · 27 years of tradition'),
  ('CARDAPIO_SINCE',  'it-IT', 'Dal 1997 · 27 anni di tradizione'),
  ('CARDAPIO_SINCE',  'es-ES', 'Desde 1997 · 27 años de tradición'),
  ('CARDAPIO_SINCE',  'ar-MA', 'منذ 1997 · 27 عامًا من التقليد'),

  ('CARDAPIO_TITLE',  'pt-BR', 'Nosso Cardápio'),
  ('CARDAPIO_TITLE',  'pt-PT', 'A Nossa Ementa'),
  ('CARDAPIO_TITLE',  'en-US', 'Our Menu'),
  ('CARDAPIO_TITLE',  'it-IT', 'Il Nostro Menu'),
  ('CARDAPIO_TITLE',  'es-ES', 'Nuestra Carta'),
  ('CARDAPIO_TITLE',  'ar-MA', 'قائمة طعامنا'),

  ('CARDAPIO_SEARCH_LABEL','pt-BR','Buscar no cardápio'),
  ('CARDAPIO_SEARCH_LABEL','pt-PT','Pesquisar na ementa'),
  ('CARDAPIO_SEARCH_LABEL','en-US','Search menu'),
  ('CARDAPIO_SEARCH_LABEL','it-IT','Cerca nel menu'),
  ('CARDAPIO_SEARCH_LABEL','es-ES','Buscar en la carta'),
  ('CARDAPIO_SEARCH_LABEL','ar-MA','البحث في القائمة'),

  ('CARDAPIO_SEARCH_PH','pt-BR','Ex: calabresa, frango, doce...'),
  ('CARDAPIO_SEARCH_PH','pt-PT','Ex: frango, queijo, doce...'),
  ('CARDAPIO_SEARCH_PH','en-US','E.g.: pepperoni, chicken, sweet...'),
  ('CARDAPIO_SEARCH_PH','it-IT','Es.: salame, pollo, dolce...'),
  ('CARDAPIO_SEARCH_PH','es-ES','Ej.: pepperoni, pollo, dulce...'),
  ('CARDAPIO_SEARCH_PH','ar-MA','مثال: دجاج، لحم، حلو...'),

  ('CARDAPIO_CAT_ALL','pt-BR','Todos'),
  ('CARDAPIO_CAT_ALL','pt-PT','Todos'),
  ('CARDAPIO_CAT_ALL','en-US','All'),
  ('CARDAPIO_CAT_ALL','it-IT','Tutti'),
  ('CARDAPIO_CAT_ALL','es-ES','Todos'),
  ('CARDAPIO_CAT_ALL','ar-MA','الكل'),

  ('CARDAPIO_TOP_LABEL','pt-BR','Favoritas da casa'),
  ('CARDAPIO_TOP_LABEL','pt-PT','Favoritas da casa'),
  ('CARDAPIO_TOP_LABEL','en-US','House favorites'),
  ('CARDAPIO_TOP_LABEL','it-IT','I preferiti della casa'),
  ('CARDAPIO_TOP_LABEL','es-ES','Favoritas de la casa'),
  ('CARDAPIO_TOP_LABEL','ar-MA','مفضلات المطعم'),

  ('CARDAPIO_TOP_TITLE','pt-BR','Mais Pedidas'),
  ('CARDAPIO_TOP_TITLE','pt-PT','Mais Pedidas'),
  ('CARDAPIO_TOP_TITLE','en-US','Most Ordered'),
  ('CARDAPIO_TOP_TITLE','it-IT','Le Più Richieste'),
  ('CARDAPIO_TOP_TITLE','es-ES','Más Pedidas'),
  ('CARDAPIO_TOP_TITLE','ar-MA','الأكثر طلبًا'),

  ('CARDAPIO_TOP_DESC','pt-BR','Os sabores que mais saem no momento'),
  ('CARDAPIO_TOP_DESC','pt-PT','Os sabores que mais saem no momento'),
  ('CARDAPIO_TOP_DESC','en-US','The flavors most ordered right now'),
  ('CARDAPIO_TOP_DESC','it-IT','I sapori più richiesti al momento'),
  ('CARDAPIO_TOP_DESC','es-ES','Los sabores más pedidos en este momento'),
  ('CARDAPIO_TOP_DESC','ar-MA','النكهات الأكثر طلبًا حاليًا'),

  ('CARDAPIO_ERROR',  'pt-BR', 'Não foi possível carregar o cardápio. Tente novamente.'),
  ('CARDAPIO_ERROR',  'pt-PT', 'Não foi possível carregar a ementa. Tente novamente.'),
  ('CARDAPIO_ERROR',  'en-US', 'Could not load the menu. Please try again.'),
  ('CARDAPIO_ERROR',  'it-IT', 'Impossibile caricare il menu. Riprova.'),
  ('CARDAPIO_ERROR',  'es-ES', 'No se pudo cargar la carta. Inténtelo de nuevo.'),
  ('CARDAPIO_ERROR',  'ar-MA', 'تعذّر تحميل القائمة. حاول مرة أخرى.'),

  ('CARDAPIO_EMPTY_CAT','pt-BR','Nenhum item nesta categoria.'),
  ('CARDAPIO_EMPTY_CAT','pt-PT','Nenhum item nesta categoria.'),
  ('CARDAPIO_EMPTY_CAT','en-US','No items in this category.'),
  ('CARDAPIO_EMPTY_CAT','it-IT','Nessun articolo in questa categoria.'),
  ('CARDAPIO_EMPTY_CAT','es-ES','Ningún artículo en esta categoría.'),
  ('CARDAPIO_EMPTY_CAT','ar-MA','لا توجد عناصر في هذه الفئة.'),

  ('CARDAPIO_PAYMENT_PENDING','pt-BR','Pagamento pendente'),
  ('CARDAPIO_PAYMENT_PENDING','pt-PT','Pagamento pendente'),
  ('CARDAPIO_PAYMENT_PENDING','en-US','Payment pending'),
  ('CARDAPIO_PAYMENT_PENDING','it-IT','Pagamento in attesa'),
  ('CARDAPIO_PAYMENT_PENDING','es-ES','Pago pendiente'),
  ('CARDAPIO_PAYMENT_PENDING','ar-MA','الدفع معلّق'),

  -- ─── TAMANHOS / TIPOS DE PIZZA ──────────────────────────────
  ('SIZE_BROTO',      'pt-BR', 'Broto'),
  ('SIZE_BROTO',      'pt-PT', 'Pequena'),
  ('SIZE_BROTO',      'en-US', 'Small'),
  ('SIZE_BROTO',      'it-IT', 'Piccola'),
  ('SIZE_BROTO',      'es-ES', 'Pequeña'),
  ('SIZE_BROTO',      'ar-MA', 'صغيرة'),

  ('SIZE_GRANDE',     'pt-BR', 'Grande'),
  ('SIZE_GRANDE',     'pt-PT', 'Grande'),
  ('SIZE_GRANDE',     'en-US', 'Large'),
  ('SIZE_GRANDE',     'it-IT', 'Grande'),
  ('SIZE_GRANDE',     'es-ES', 'Grande'),
  ('SIZE_GRANDE',     'ar-MA', 'كبيرة'),

  ('SIZE_INTEIRA',    'pt-BR', 'Inteira'),
  ('SIZE_INTEIRA',    'pt-PT', 'Inteira'),
  ('SIZE_INTEIRA',    'en-US', 'Whole'),
  ('SIZE_INTEIRA',    'it-IT', 'Intera'),
  ('SIZE_INTEIRA',    'es-ES', 'Entera'),
  ('SIZE_INTEIRA',    'ar-MA', 'كاملة'),

  ('SIZE_METADE',     'pt-BR', 'Metade'),
  ('SIZE_METADE',     'pt-PT', 'Metade'),
  ('SIZE_METADE',     'en-US', 'Half'),
  ('SIZE_METADE',     'it-IT', 'Metà'),
  ('SIZE_METADE',     'es-ES', 'Mitad'),
  ('SIZE_METADE',     'ar-MA', 'نصف'),

  ('BTN_ADD_CART',    'pt-BR', 'Adicionar ao Carrinho'),
  ('BTN_ADD_CART',    'pt-PT', 'Adicionar ao Carrinho'),
  ('BTN_ADD_CART',    'en-US', 'Add to Cart'),
  ('BTN_ADD_CART',    'it-IT', 'Aggiungi al Carrello'),
  ('BTN_ADD_CART',    'es-ES', 'Agregar al Carrito'),
  ('BTN_ADD_CART',    'ar-MA', 'أضف إلى السلة'),

  ('BTN_SAVE_FIRST_HALF','pt-BR','Salvar primeira metade'),
  ('BTN_SAVE_FIRST_HALF','pt-PT','Guardar primeira metade'),
  ('BTN_SAVE_FIRST_HALF','en-US','Save first half'),
  ('BTN_SAVE_FIRST_HALF','it-IT','Salva prima metà'),
  ('BTN_SAVE_FIRST_HALF','es-ES','Guardar primera mitad'),
  ('BTN_SAVE_FIRST_HALF','ar-MA','حفظ النصف الأول'),

  ('BTN_COMPLETE_HALF','pt-BR','Completar meio a meio'),
  ('BTN_COMPLETE_HALF','pt-PT','Completar meio a meio'),
  ('BTN_COMPLETE_HALF','en-US','Complete half and half'),
  ('BTN_COMPLETE_HALF','it-IT','Completa metà e metà'),
  ('BTN_COMPLETE_HALF','es-ES','Completar mitad y mitad'),
  ('BTN_COMPLETE_HALF','ar-MA','إكمال النصف والنصف'),

  ('FIRST_HALF_SAVED','pt-BR','Primeira metade salva. Escolha o próximo sabor.'),
  ('FIRST_HALF_SAVED','pt-PT','Primeira metade guardada. Escolha o próximo sabor.'),
  ('FIRST_HALF_SAVED','en-US','First half saved. Choose the next flavor.'),
  ('FIRST_HALF_SAVED','it-IT','Prima metà salvata. Scegli il prossimo gusto.'),
  ('FIRST_HALF_SAVED','es-ES','Primera mitad guardada. Elige el próximo sabor.'),
  ('FIRST_HALF_SAVED','ar-MA','تم حفظ النصف الأول. اختر النكهة التالية.'),

  ('CANCEL_HALF',     'pt-BR', 'Cancelar metade'),
  ('CANCEL_HALF',     'pt-PT', 'Cancelar metade'),
  ('CANCEL_HALF',     'en-US', 'Cancel half'),
  ('CANCEL_HALF',     'it-IT', 'Annulla metà'),
  ('CANCEL_HALF',     'es-ES', 'Cancelar mitad'),
  ('CANCEL_HALF',     'ar-MA', 'إلغاء النصف'),

  ('PIZZA_HALF_HALF', 'pt-BR', 'Pizza Meio a Meio'),
  ('PIZZA_HALF_HALF', 'pt-PT', 'Pizza Meio a Meio'),
  ('PIZZA_HALF_HALF', 'en-US', 'Half and Half Pizza'),
  ('PIZZA_HALF_HALF', 'it-IT', 'Pizza Metà e Metà'),
  ('PIZZA_HALF_HALF', 'es-ES', 'Pizza Mitad y Mitad'),
  ('PIZZA_HALF_HALF', 'ar-MA', 'بيتزا نصف ونصف'),

  -- ─── LOGIN / REGISTO ────────────────────────────────────────
  ('LOGIN_TAGLINE',   'pt-BR', 'O seu momento de ser feliz!'),
  ('LOGIN_TAGLINE',   'pt-PT', 'O seu momento de ser feliz!'),
  ('LOGIN_TAGLINE',   'en-US', 'Your moment to be happy!'),
  ('LOGIN_TAGLINE',   'it-IT', 'Il tuo momento di essere felice!'),
  ('LOGIN_TAGLINE',   'es-ES', '¡Tu momento de ser feliz!'),
  ('LOGIN_TAGLINE',   'ar-MA', 'لحظتك لتكون سعيدًا!'),

  ('LOGIN_ENTER',     'pt-BR', 'Entrar'),
  ('LOGIN_ENTER',     'pt-PT', 'Entrar'),
  ('LOGIN_ENTER',     'en-US', 'Sign In'),
  ('LOGIN_ENTER',     'it-IT', 'Accedi'),
  ('LOGIN_ENTER',     'es-ES', 'Entrar'),
  ('LOGIN_ENTER',     'ar-MA', 'دخول'),

  ('LOGIN_CREATE_ACCOUNT','pt-BR','Criar conta'),
  ('LOGIN_CREATE_ACCOUNT','pt-PT','Criar conta'),
  ('LOGIN_CREATE_ACCOUNT','en-US','Create account'),
  ('LOGIN_CREATE_ACCOUNT','it-IT','Crea account'),
  ('LOGIN_CREATE_ACCOUNT','es-ES','Crear cuenta'),
  ('LOGIN_CREATE_ACCOUNT','ar-MA','إنشاء حساب'),

  ('LOGIN_TITLE',     'pt-BR', 'Bem-vindo'),
  ('LOGIN_TITLE',     'pt-PT', 'Bem-vindo'),
  ('LOGIN_TITLE',     'en-US', 'Welcome'),
  ('LOGIN_TITLE',     'it-IT', 'Benvenuto'),
  ('LOGIN_TITLE',     'es-ES', 'Bienvenido'),
  ('LOGIN_TITLE',     'ar-MA', 'مرحبًا'),

  ('LOGIN_SUBTITLE',  'pt-BR', 'Entre com email ou telefone para continuar.'),
  ('LOGIN_SUBTITLE',  'pt-PT', 'Entre com email ou telefone para continuar.'),
  ('LOGIN_SUBTITLE',  'en-US', 'Sign in with email or phone to continue.'),
  ('LOGIN_SUBTITLE',  'it-IT', 'Accedi con email o telefono per continuare.'),
  ('LOGIN_SUBTITLE',  'es-ES', 'Ingrese con email o teléfono para continuar.'),
  ('LOGIN_SUBTITLE',  'ar-MA', 'ادخل بالبريد الإلكتروني أو الهاتف للمتابعة.'),

  ('LOGIN_PH_IDENTIFIER','pt-BR','Email ou telefone'),
  ('LOGIN_PH_IDENTIFIER','pt-PT','Email ou telefone'),
  ('LOGIN_PH_IDENTIFIER','en-US','Email or phone'),
  ('LOGIN_PH_IDENTIFIER','it-IT','Email o telefono'),
  ('LOGIN_PH_IDENTIFIER','es-ES','Email o teléfono'),
  ('LOGIN_PH_IDENTIFIER','ar-MA','البريد الإلكتروني أو الهاتف'),

  ('LOGIN_PH_PASSWORD','pt-BR','Senha'),
  ('LOGIN_PH_PASSWORD','pt-PT','Palavra-passe'),
  ('LOGIN_PH_PASSWORD','en-US','Password'),
  ('LOGIN_PH_PASSWORD','it-IT','Password'),
  ('LOGIN_PH_PASSWORD','es-ES','Contraseña'),
  ('LOGIN_PH_PASSWORD','ar-MA','كلمة المرور'),

  ('LOGIN_BTN',       'pt-BR', 'Entrar'),
  ('LOGIN_BTN',       'pt-PT', 'Entrar'),
  ('LOGIN_BTN',       'en-US', 'Sign In'),
  ('LOGIN_BTN',       'it-IT', 'Accedi'),
  ('LOGIN_BTN',       'es-ES', 'Entrar'),
  ('LOGIN_BTN',       'ar-MA', 'دخول'),

  ('LOGIN_BTN_LOADING','pt-BR','Entrando...'),
  ('LOGIN_BTN_LOADING','pt-PT','A entrar...'),
  ('LOGIN_BTN_LOADING','en-US','Signing in...'),
  ('LOGIN_BTN_LOADING','it-IT','Accesso in corso...'),
  ('LOGIN_BTN_LOADING','es-ES','Entrando...'),
  ('LOGIN_BTN_LOADING','ar-MA','جارٍ الدخول...'),

  ('REG_TITLE',       'pt-BR', 'Criar conta'),
  ('REG_TITLE',       'pt-PT', 'Criar conta'),
  ('REG_TITLE',       'en-US', 'Create account'),
  ('REG_TITLE',       'it-IT', 'Crea account'),
  ('REG_TITLE',       'es-ES', 'Crear cuenta'),
  ('REG_TITLE',       'ar-MA', 'إنشاء حساب'),

  ('REG_SUBTITLE',    'pt-BR', 'Preencha os dados para se cadastrar.'),
  ('REG_SUBTITLE',    'pt-PT', 'Preencha os dados para se registar.'),
  ('REG_SUBTITLE',    'en-US', 'Fill in your details to register.'),
  ('REG_SUBTITLE',    'it-IT', 'Compila i dati per registrarti.'),
  ('REG_SUBTITLE',    'es-ES', 'Rellene los datos para registrarse.'),
  ('REG_SUBTITLE',    'ar-MA', 'أدخل بياناتك للتسجيل.'),

  ('REG_PH_NAME',     'pt-BR', 'Nome completo'),
  ('REG_PH_NAME',     'pt-PT', 'Nome completo'),
  ('REG_PH_NAME',     'en-US', 'Full name'),
  ('REG_PH_NAME',     'it-IT', 'Nome completo'),
  ('REG_PH_NAME',     'es-ES', 'Nombre completo'),
  ('REG_PH_NAME',     'ar-MA', 'الاسم الكامل'),

  ('REG_PH_EMAIL',    'pt-BR', 'Email (opcional se informar telefone)'),
  ('REG_PH_EMAIL',    'pt-PT', 'Email (opcional se informar telefone)'),
  ('REG_PH_EMAIL',    'en-US', 'Email (optional if phone provided)'),
  ('REG_PH_EMAIL',    'it-IT', 'Email (opzionale se inserisci il telefono)'),
  ('REG_PH_EMAIL',    'es-ES', 'Email (opcional si informa teléfono)'),
  ('REG_PH_EMAIL',    'ar-MA', 'البريد الإلكتروني (اختياري إذا أدخلت الهاتف)'),

  ('REG_PH_PHONE',    'pt-BR', 'Telefone (opcional se informar email)'),
  ('REG_PH_PHONE',    'pt-PT', 'Telefone (opcional se informar email)'),
  ('REG_PH_PHONE',    'en-US', 'Phone (optional if email provided)'),
  ('REG_PH_PHONE',    'it-IT', 'Telefono (opzionale se inserisci l''email)'),
  ('REG_PH_PHONE',    'es-ES', 'Teléfono (opcional si informa email)'),
  ('REG_PH_PHONE',    'ar-MA', 'الهاتف (اختياري إذا أدخلت البريد الإلكتروني)'),

  ('REG_NOTE',        'pt-BR', '* Informe ao menos email ou telefone'),
  ('REG_NOTE',        'pt-PT', '* Informe pelo menos email ou telefone'),
  ('REG_NOTE',        'en-US', '* Provide at least email or phone'),
  ('REG_NOTE',        'it-IT', '* Inserisci almeno email o telefono'),
  ('REG_NOTE',        'es-ES', '* Informe al menos email o teléfono'),
  ('REG_NOTE',        'ar-MA', '* أدخل على الأقل البريد الإلكتروني أو الهاتف'),

  ('REG_PH_PASSWORD', 'pt-BR', 'Senha (mínimo 6 caracteres)'),
  ('REG_PH_PASSWORD', 'pt-PT', 'Palavra-passe (mínimo 6 caracteres)'),
  ('REG_PH_PASSWORD', 'en-US', 'Password (minimum 6 characters)'),
  ('REG_PH_PASSWORD', 'it-IT', 'Password (minimo 6 caratteri)'),
  ('REG_PH_PASSWORD', 'es-ES', 'Contraseña (mínimo 6 caracteres)'),
  ('REG_PH_PASSWORD', 'ar-MA', 'كلمة المرور (6 أحرف على الأقل)'),

  ('REG_PH_ADDRESS',  'pt-BR', 'Endereço de entrega'),
  ('REG_PH_ADDRESS',  'pt-PT', 'Morada de entrega'),
  ('REG_PH_ADDRESS',  'en-US', 'Delivery address'),
  ('REG_PH_ADDRESS',  'it-IT', 'Indirizzo di consegna'),
  ('REG_PH_ADDRESS',  'es-ES', 'Dirección de entrega'),
  ('REG_PH_ADDRESS',  'ar-MA', 'عنوان التسليم'),

  ('REG_BTN',         'pt-BR', 'Criar conta'),
  ('REG_BTN',         'pt-PT', 'Criar conta'),
  ('REG_BTN',         'en-US', 'Create account'),
  ('REG_BTN',         'it-IT', 'Crea account'),
  ('REG_BTN',         'es-ES', 'Crear cuenta'),
  ('REG_BTN',         'ar-MA', 'إنشاء حساب'),

  ('REG_BTN_LOADING', 'pt-BR', 'Criando conta...'),
  ('REG_BTN_LOADING', 'pt-PT', 'A criar conta...'),
  ('REG_BTN_LOADING', 'en-US', 'Creating account...'),
  ('REG_BTN_LOADING', 'it-IT', 'Creazione in corso...'),
  ('REG_BTN_LOADING', 'es-ES', 'Creando cuenta...'),
  ('REG_BTN_LOADING', 'ar-MA', 'جارٍ إنشاء الحساب...'),

  ('LOGIN_BACK',      'pt-BR', '← Voltar para o cardápio'),
  ('LOGIN_BACK',      'pt-PT', '← Voltar para a ementa'),
  ('LOGIN_BACK',      'en-US', '← Back to menu'),
  ('LOGIN_BACK',      'it-IT', '← Torna al menu'),
  ('LOGIN_BACK',      'es-ES', '← Volver a la carta'),
  ('LOGIN_BACK',      'ar-MA', '← العودة إلى القائمة'),

  -- ─── CARRINHO ───────────────────────────────────────────────
  ('CART_TITLE',      'pt-BR', 'Seu Carrinho'),
  ('CART_TITLE',      'pt-PT', 'O Seu Carrinho'),
  ('CART_TITLE',      'en-US', 'Your Cart'),
  ('CART_TITLE',      'it-IT', 'Il Tuo Carrello'),
  ('CART_TITLE',      'es-ES', 'Tu Carrito'),
  ('CART_TITLE',      'ar-MA', 'سلة التسوق'),

  ('CART_CLOSE',      'pt-BR', 'Fechar'),
  ('CART_CLOSE',      'pt-PT', 'Fechar'),
  ('CART_CLOSE',      'en-US', 'Close'),
  ('CART_CLOSE',      'it-IT', 'Chiudi'),
  ('CART_CLOSE',      'es-ES', 'Cerrar'),
  ('CART_CLOSE',      'ar-MA', 'إغلاق'),

  ('CART_EMPTY',      'pt-BR', 'Seu carrinho está vazio.'),
  ('CART_EMPTY',      'pt-PT', 'O seu carrinho está vazio.'),
  ('CART_EMPTY',      'en-US', 'Your cart is empty.'),
  ('CART_EMPTY',      'it-IT', 'Il tuo carrello è vuoto.'),
  ('CART_EMPTY',      'es-ES', 'Tu carrito está vacío.'),
  ('CART_EMPTY',      'ar-MA', 'سلة التسوق فارغة.'),

  ('CART_STUFFED_CRUST','pt-BR','Borda recheada'),
  ('CART_STUFFED_CRUST','pt-PT','Bordo recheado'),
  ('CART_STUFFED_CRUST','en-US','Stuffed crust'),
  ('CART_STUFFED_CRUST','it-IT','Bordo ripieno'),
  ('CART_STUFFED_CRUST','es-ES','Borde relleno'),
  ('CART_STUFFED_CRUST','ar-MA','حافة محشوة'),

  ('CART_NO_CRUST',   'pt-BR', 'Sem borda'),
  ('CART_NO_CRUST',   'pt-PT', 'Sem bordo'),
  ('CART_NO_CRUST',   'en-US', 'No crust'),
  ('CART_NO_CRUST',   'it-IT', 'Senza bordo'),
  ('CART_NO_CRUST',   'es-ES', 'Sin borde'),
  ('CART_NO_CRUST',   'ar-MA', 'بدون حافة'),

  ('CART_NOTES_LABEL','pt-BR','Observação'),
  ('CART_NOTES_LABEL','pt-PT','Observação'),
  ('CART_NOTES_LABEL','en-US','Notes'),
  ('CART_NOTES_LABEL','it-IT','Note'),
  ('CART_NOTES_LABEL','es-ES','Observación'),
  ('CART_NOTES_LABEL','ar-MA','ملاحظة'),

  ('CART_NOTES_PH',   'pt-BR', 'Ex: sem cebola, sem azeitona...'),
  ('CART_NOTES_PH',   'pt-PT', 'Ex: sem cebola, sem azeitona...'),
  ('CART_NOTES_PH',   'en-US', 'E.g.: no onion, no olives...'),
  ('CART_NOTES_PH',   'it-IT', 'Es.: senza cipolla, senza olive...'),
  ('CART_NOTES_PH',   'es-ES', 'Ej.: sin cebolla, sin aceitunas...'),
  ('CART_NOTES_PH',   'ar-MA', 'مثال: بدون بصل، بدون زيتون...'),

  ('CART_SUBTOTAL',   'pt-BR', 'Subtotal'),
  ('CART_SUBTOTAL',   'pt-PT', 'Subtotal'),
  ('CART_SUBTOTAL',   'en-US', 'Subtotal'),
  ('CART_SUBTOTAL',   'it-IT', 'Subtotale'),
  ('CART_SUBTOTAL',   'es-ES', 'Subtotal'),
  ('CART_SUBTOTAL',   'ar-MA', 'المجموع الجزئي'),

  ('CART_FREIGHT',    'pt-BR', 'Frete'),
  ('CART_FREIGHT',    'pt-PT', 'Frete'),
  ('CART_FREIGHT',    'en-US', 'Shipping'),
  ('CART_FREIGHT',    'it-IT', 'Spedizione'),
  ('CART_FREIGHT',    'es-ES', 'Envío'),
  ('CART_FREIGHT',    'ar-MA', 'التوصيل'),

  ('CART_TOTAL',      'pt-BR', 'Total'),
  ('CART_TOTAL',      'pt-PT', 'Total'),
  ('CART_TOTAL',      'en-US', 'Total'),
  ('CART_TOTAL',      'it-IT', 'Totale'),
  ('CART_TOTAL',      'es-ES', 'Total'),
  ('CART_TOTAL',      'ar-MA', 'الإجمالي'),

  ('CART_BTN_CHECKOUT','pt-BR','Finalizar Compra'),
  ('CART_BTN_CHECKOUT','pt-PT','Finalizar Compra'),
  ('CART_BTN_CHECKOUT','en-US','Checkout'),
  ('CART_BTN_CHECKOUT','it-IT','Procedi all''acquisto'),
  ('CART_BTN_CHECKOUT','es-ES','Finalizar Compra'),
  ('CART_BTN_CHECKOUT','ar-MA','إتمام الشراء'),

  -- ─── CHECKOUT ───────────────────────────────────────────────
  ('CHECKOUT_EMPTY',  'pt-BR', 'Seu carrinho está vazio.'),
  ('CHECKOUT_EMPTY',  'pt-PT', 'O seu carrinho está vazio.'),
  ('CHECKOUT_EMPTY',  'en-US', 'Your cart is empty.'),
  ('CHECKOUT_EMPTY',  'it-IT', 'Il tuo carrello è vuoto.'),
  ('CHECKOUT_EMPTY',  'es-ES', 'Tu carrito está vacío.'),
  ('CHECKOUT_EMPTY',  'ar-MA', 'سلة التسوق فارغة.'),

  ('CHECKOUT_DELIVERY','pt-BR','🛵 Entrega'),
  ('CHECKOUT_DELIVERY','pt-PT','🛵 Entrega'),
  ('CHECKOUT_DELIVERY','en-US','🛵 Delivery'),
  ('CHECKOUT_DELIVERY','it-IT','🛵 Consegna'),
  ('CHECKOUT_DELIVERY','es-ES','🛵 Entrega'),
  ('CHECKOUT_DELIVERY','ar-MA','🛵 توصيل'),

  ('CHECKOUT_PICKUP', 'pt-BR', '🏠 Retirada no local'),
  ('CHECKOUT_PICKUP', 'pt-PT', '🏠 Retirada no local'),
  ('CHECKOUT_PICKUP', 'en-US', '🏠 Pickup'),
  ('CHECKOUT_PICKUP', 'it-IT', '🏠 Ritiro in loco'),
  ('CHECKOUT_PICKUP', 'es-ES', '🏠 Retiro en tienda'),
  ('CHECKOUT_PICKUP', 'ar-MA', '🏠 استلام من المحل'),

  ('CHECKOUT_PICKUP_FREE','pt-BR','Retirada no local — Frete grátis'),
  ('CHECKOUT_PICKUP_FREE','pt-PT','Retirada no local — Frete grátis'),
  ('CHECKOUT_PICKUP_FREE','en-US','Pickup — Free shipping'),
  ('CHECKOUT_PICKUP_FREE','it-IT','Ritiro in loco — Spedizione gratuita'),
  ('CHECKOUT_PICKUP_FREE','es-ES','Retiro en tienda — Envío gratis'),
  ('CHECKOUT_PICKUP_FREE','ar-MA','استلام من المحل — توصيل مجاني'),

  ('CHECKOUT_ADDRESS_TITLE','pt-BR','Endereço de Entrega'),
  ('CHECKOUT_ADDRESS_TITLE','pt-PT','Morada de Entrega'),
  ('CHECKOUT_ADDRESS_TITLE','en-US','Delivery Address'),
  ('CHECKOUT_ADDRESS_TITLE','it-IT','Indirizzo di Consegna'),
  ('CHECKOUT_ADDRESS_TITLE','es-ES','Dirección de Entrega'),
  ('CHECKOUT_ADDRESS_TITLE','ar-MA','عنوان التوصيل'),

  ('CHECKOUT_CEP',    'pt-BR', 'CEP *'),
  ('CHECKOUT_CEP',    'pt-PT', 'Código Postal *'),
  ('CHECKOUT_CEP',    'en-US', 'ZIP Code *'),
  ('CHECKOUT_CEP',    'it-IT', 'CAP *'),
  ('CHECKOUT_CEP',    'es-ES', 'Código Postal *'),
  ('CHECKOUT_CEP',    'ar-MA', 'الرمز البريدي *'),

  ('CHECKOUT_NUMBER', 'pt-BR', 'Número *'),
  ('CHECKOUT_NUMBER', 'pt-PT', 'Número *'),
  ('CHECKOUT_NUMBER', 'en-US', 'Number *'),
  ('CHECKOUT_NUMBER', 'it-IT', 'Numero *'),
  ('CHECKOUT_NUMBER', 'es-ES', 'Número *'),
  ('CHECKOUT_NUMBER', 'ar-MA', 'الرقم *'),

  ('CHECKOUT_STREET', 'pt-BR', 'Rua'),
  ('CHECKOUT_STREET', 'pt-PT', 'Rua'),
  ('CHECKOUT_STREET', 'en-US', 'Street'),
  ('CHECKOUT_STREET', 'it-IT', 'Via'),
  ('CHECKOUT_STREET', 'es-ES', 'Calle'),
  ('CHECKOUT_STREET', 'ar-MA', 'الشارع'),

  ('CHECKOUT_COMPLEMENT','pt-BR','Complemento'),
  ('CHECKOUT_COMPLEMENT','pt-PT','Complemento'),
  ('CHECKOUT_COMPLEMENT','en-US','Apt / Suite'),
  ('CHECKOUT_COMPLEMENT','it-IT','Interno / Scala'),
  ('CHECKOUT_COMPLEMENT','es-ES','Complemento'),
  ('CHECKOUT_COMPLEMENT','ar-MA','تفاصيل إضافية'),

  ('CHECKOUT_NEIGHBORHOOD','pt-BR','Bairro'),
  ('CHECKOUT_NEIGHBORHOOD','pt-PT','Bairro'),
  ('CHECKOUT_NEIGHBORHOOD','en-US','Neighborhood'),
  ('CHECKOUT_NEIGHBORHOOD','it-IT','Quartiere'),
  ('CHECKOUT_NEIGHBORHOOD','es-ES','Barrio'),
  ('CHECKOUT_NEIGHBORHOOD','ar-MA','الحي'),

  ('CHECKOUT_REFERENCE','pt-BR','Ponto de referência'),
  ('CHECKOUT_REFERENCE','pt-PT','Ponto de referência'),
  ('CHECKOUT_REFERENCE','en-US','Reference point'),
  ('CHECKOUT_REFERENCE','it-IT','Punto di riferimento'),
  ('CHECKOUT_REFERENCE','es-ES','Punto de referencia'),
  ('CHECKOUT_REFERENCE','ar-MA','نقطة مرجعية'),

  ('CHECKOUT_NOTES_LABEL','pt-BR','Observações do pedido'),
  ('CHECKOUT_NOTES_LABEL','pt-PT','Observações do pedido'),
  ('CHECKOUT_NOTES_LABEL','en-US','Order notes'),
  ('CHECKOUT_NOTES_LABEL','it-IT','Note sull''ordine'),
  ('CHECKOUT_NOTES_LABEL','es-ES','Notas del pedido'),
  ('CHECKOUT_NOTES_LABEL','ar-MA','ملاحظات الطلب'),

  ('BTN_CALC_FREIGHT','pt-BR','Calcular Frete 🛵'),
  ('BTN_CALC_FREIGHT','pt-PT','Calcular Frete 🛵'),
  ('BTN_CALC_FREIGHT','en-US','Calculate Shipping 🛵'),
  ('BTN_CALC_FREIGHT','it-IT','Calcola la Spedizione 🛵'),
  ('BTN_CALC_FREIGHT','es-ES','Calcular Envío 🛵'),
  ('BTN_CALC_FREIGHT','ar-MA','حساب التوصيل 🛵'),

  ('BTN_CALC_FREIGHT_LOADING','pt-BR','Calculando frete...'),
  ('BTN_CALC_FREIGHT_LOADING','pt-PT','A calcular frete...'),
  ('BTN_CALC_FREIGHT_LOADING','en-US','Calculating shipping...'),
  ('BTN_CALC_FREIGHT_LOADING','it-IT','Calcolo in corso...'),
  ('BTN_CALC_FREIGHT_LOADING','es-ES','Calculando envío...'),
  ('BTN_CALC_FREIGHT_LOADING','ar-MA','جارٍ حساب التوصيل...'),

  ('CHECKOUT_WAITING_TITLE','pt-BR','Aguardando pagamento'),
  ('CHECKOUT_WAITING_TITLE','pt-PT','A aguardar pagamento'),
  ('CHECKOUT_WAITING_TITLE','en-US','Waiting for payment'),
  ('CHECKOUT_WAITING_TITLE','it-IT','In attesa di pagamento'),
  ('CHECKOUT_WAITING_TITLE','es-ES','Esperando pago'),
  ('CHECKOUT_WAITING_TITLE','ar-MA','في انتظار الدفع'),

  ('CHECKOUT_WAITING_DESC','pt-BR','A página do Mercado Pago foi aberta em outra aba. Conclua o pagamento por lá e aguarde a confirmação aqui.'),
  ('CHECKOUT_WAITING_DESC','pt-PT','A página do Mercado Pago foi aberta noutra aba. Conclua o pagamento por lá e aguarde a confirmação aqui.'),
  ('CHECKOUT_WAITING_DESC','en-US','The Mercado Pago page has been opened in another tab. Complete the payment there and wait for confirmation here.'),
  ('CHECKOUT_WAITING_DESC','it-IT','La pagina di Mercado Pago è stata aperta in un''altra scheda. Completa il pagamento lì e attendi la conferma qui.'),
  ('CHECKOUT_WAITING_DESC','es-ES','La página de Mercado Pago se abrió en otra pestaña. Complete el pago allí y espere la confirmación aquí.'),
  ('CHECKOUT_WAITING_DESC','ar-MA','تم فتح صفحة Mercado Pago في علامة تبويب أخرى. أكمل الدفع هناك وانتظر التأكيد هنا.'),

  ('CHECKOUT_WAITING_UPDATE','pt-BR','Esta página atualiza automaticamente a cada poucos segundos.'),
  ('CHECKOUT_WAITING_UPDATE','pt-PT','Esta página atualiza automaticamente a cada poucos segundos.'),
  ('CHECKOUT_WAITING_UPDATE','en-US','This page updates automatically every few seconds.'),
  ('CHECKOUT_WAITING_UPDATE','it-IT','Questa pagina si aggiorna automaticamente ogni pochi secondi.'),
  ('CHECKOUT_WAITING_UPDATE','es-ES','Esta página se actualiza automáticamente cada pocos segundos.'),
  ('CHECKOUT_WAITING_UPDATE','ar-MA','تتحدث هذه الصفحة تلقائيًا كل بضع ثوانٍ.'),

  -- ─── MODAL PIN (MESA) ────────────────────────────────────────
  ('MODAL_END_SESSION','pt-BR','Encerrar sessão'),
  ('MODAL_END_SESSION','pt-PT','Terminar sessão'),
  ('MODAL_END_SESSION','en-US','End session'),
  ('MODAL_END_SESSION','it-IT','Termina sessione'),
  ('MODAL_END_SESSION','es-ES','Cerrar sesión'),
  ('MODAL_END_SESSION','ar-MA','إنهاء الجلسة'),

  ('MODAL_PIN_DESC',  'pt-BR', 'Digite o PIN de funcionário para sair'),
  ('MODAL_PIN_DESC',  'pt-PT', 'Digite o PIN de funcionário para sair'),
  ('MODAL_PIN_DESC',  'en-US', 'Enter the staff PIN to sign out'),
  ('MODAL_PIN_DESC',  'it-IT', 'Inserisci il PIN del personale per uscire'),
  ('MODAL_PIN_DESC',  'es-ES', 'Ingrese el PIN de empleado para salir'),
  ('MODAL_PIN_DESC',  'ar-MA', 'أدخل رقم PIN الموظف للخروج'),

  ('MODAL_PIN_WRONG', 'pt-BR', 'PIN incorreto. Tente novamente.'),
  ('MODAL_PIN_WRONG', 'pt-PT', 'PIN incorreto. Tente novamente.'),
  ('MODAL_PIN_WRONG', 'en-US', 'Incorrect PIN. Try again.'),
  ('MODAL_PIN_WRONG', 'it-IT', 'PIN errato. Riprova.'),
  ('MODAL_PIN_WRONG', 'es-ES', 'PIN incorrecto. Inténtelo de nuevo.'),
  ('MODAL_PIN_WRONG', 'ar-MA', 'رقم PIN غير صحيح. حاول مرة أخرى.')

) AS t(chave, codigo_idioma, valor) ON TRUE
WHERE s.codigo = 'website'
ON CONFLICT (chave, sistema_id, idioma_id)
  DO UPDATE SET valor = EXCLUDED.valor, atualizado_em = NOW();
