-- =============================================================
-- Seed: Novas chaves frontendHamburgueria
-- 49 chaves × 6 idiomas = 294 entradas
-- Uso: rodar no DBeaver (PostgreSQL)
-- ON CONFLICT: ignora se a entrada já existir (idempotente)
-- =============================================================

INSERT INTO traducoes (chave, valor, sistema_id, idioma_id)
SELECT t.chave, t.valor,
  (SELECT id FROM sistemas WHERE codigo = 'website'),
       (SELECT id FROM idiomas  WHERE codigo = t.idioma)
FROM (VALUES

  -- ─── HOME ────────────────────────────────────────────────────────────────
  ('HOME_TAGLINE_H', 'Feito na hora · Ingredientes premium',       'pt-BR'),
  ('HOME_TAGLINE_H', 'Feito na hora · Ingredientes premium',       'pt-PT'),
  ('HOME_TAGLINE_H', 'Made fresh · Premium ingredients',           'en-US'),
  ('HOME_TAGLINE_H', 'Fatto al momento · Ingredienti premium',     'it-IT'),
  ('HOME_TAGLINE_H', 'Hecho al momento · Ingredientes premium',   'es-ES'),
  ('HOME_TAGLINE_H', 'مصنوع طازج · مكونات ممتازة',                'ar-MA'),

  -- ─── CLIENT DASHBOARD ────────────────────────────────────────────────────
  ('CLIENT_DASHBOARD_ITEM', 'Item',     'pt-BR'),
  ('CLIENT_DASHBOARD_ITEM', 'Item',     'pt-PT'),
  ('CLIENT_DASHBOARD_ITEM', 'Item',     'en-US'),
  ('CLIENT_DASHBOARD_ITEM', 'Articolo', 'it-IT'),
  ('CLIENT_DASHBOARD_ITEM', 'Artículo', 'es-ES'),
  ('CLIENT_DASHBOARD_ITEM', 'عنصر',    'ar-MA'),

  -- ─── ADMIN HISTORY ───────────────────────────────────────────────────────
  ('ADMIN_HISTORY_ITEM', 'Item',     'pt-BR'),
  ('ADMIN_HISTORY_ITEM', 'Item',     'pt-PT'),
  ('ADMIN_HISTORY_ITEM', 'Item',     'en-US'),
  ('ADMIN_HISTORY_ITEM', 'Articolo', 'it-IT'),
  ('ADMIN_HISTORY_ITEM', 'Artículo', 'es-ES'),
  ('ADMIN_HISTORY_ITEM', 'عنصر',    'ar-MA'),

  -- ─── ADMIN PRODUCTS ──────────────────────────────────────────────────────
  ('ADMIN_PRODUCTS_STOCK', 'Estoque',   'pt-BR'),
  ('ADMIN_PRODUCTS_STOCK', 'Stock',     'pt-PT'),
  ('ADMIN_PRODUCTS_STOCK', 'Stock',     'en-US'),
  ('ADMIN_PRODUCTS_STOCK', 'Scorte',    'it-IT'),
  ('ADMIN_PRODUCTS_STOCK', 'Stock',     'es-ES'),
  ('ADMIN_PRODUCTS_STOCK', 'المخزون',  'ar-MA'),

  ('ADMIN_PRODUCTS_BASE_LANGUAGE', 'Idioma base',       'pt-BR'),
  ('ADMIN_PRODUCTS_BASE_LANGUAGE', 'Idioma base',       'pt-PT'),
  ('ADMIN_PRODUCTS_BASE_LANGUAGE', 'Base language',     'en-US'),
  ('ADMIN_PRODUCTS_BASE_LANGUAGE', 'Lingua base',       'it-IT'),
  ('ADMIN_PRODUCTS_BASE_LANGUAGE', 'Idioma base',       'es-ES'),
  ('ADMIN_PRODUCTS_BASE_LANGUAGE', 'اللغة الأساسية',   'ar-MA'),

  ('ADMIN_PRODUCTS_REAPPLY_TRANSLATION', 'Reaplicar tradução',    'pt-BR'),
  ('ADMIN_PRODUCTS_REAPPLY_TRANSLATION', 'Reaplicar tradução',    'pt-PT'),
  ('ADMIN_PRODUCTS_REAPPLY_TRANSLATION', 'Reapply translation',   'en-US'),
  ('ADMIN_PRODUCTS_REAPPLY_TRANSLATION', 'Riapplica traduzione',  'it-IT'),
  ('ADMIN_PRODUCTS_REAPPLY_TRANSLATION', 'Reaplicar traducción',  'es-ES'),
  ('ADMIN_PRODUCTS_REAPPLY_TRANSLATION', 'إعادة تطبيق الترجمة', 'ar-MA'),

  ('ADMIN_PRODUCTS_REAPPLY_TRANSLATION_LOADING', 'Reaplicando...',          'pt-BR'),
  ('ADMIN_PRODUCTS_REAPPLY_TRANSLATION_LOADING', 'Reaplicando...',          'pt-PT'),
  ('ADMIN_PRODUCTS_REAPPLY_TRANSLATION_LOADING', 'Reapplying...',           'en-US'),
  ('ADMIN_PRODUCTS_REAPPLY_TRANSLATION_LOADING', 'Riapplicando...',         'it-IT'),
  ('ADMIN_PRODUCTS_REAPPLY_TRANSLATION_LOADING', 'Reaplicando...',          'es-ES'),
  ('ADMIN_PRODUCTS_REAPPLY_TRANSLATION_LOADING', 'جاري إعادة التطبيق...', 'ar-MA'),

  -- ─── ADMIN MESAS ─────────────────────────────────────────────────────────
  ('ADMIN_MESAS_CANCEL', 'Cancelar', 'pt-BR'),
  ('ADMIN_MESAS_CANCEL', 'Cancelar', 'pt-PT'),
  ('ADMIN_MESAS_CANCEL', 'Cancel',   'en-US'),
  ('ADMIN_MESAS_CANCEL', 'Annulla',  'it-IT'),
  ('ADMIN_MESAS_CANCEL', 'Cancelar', 'es-ES'),
  ('ADMIN_MESAS_CANCEL', 'إلغاء',   'ar-MA'),

  ('ADMIN_MESAS_CREATED', 'Mesa criada com sucesso!',    'pt-BR'),
  ('ADMIN_MESAS_CREATED', 'Mesa criada com sucesso!',    'pt-PT'),
  ('ADMIN_MESAS_CREATED', 'Table created successfully!', 'en-US'),
  ('ADMIN_MESAS_CREATED', 'Tavolo creato con successo!', 'it-IT'),
  ('ADMIN_MESAS_CREATED', '¡Mesa creada con éxito!',     'es-ES'),
  ('ADMIN_MESAS_CREATED', 'تم إنشاء الطاولة بنجاح!',   'ar-MA'),

  ('ADMIN_MESAS_EDIT_BUTTON', 'Editar',   'pt-BR'),
  ('ADMIN_MESAS_EDIT_BUTTON', 'Editar',   'pt-PT'),
  ('ADMIN_MESAS_EDIT_BUTTON', 'Edit',     'en-US'),
  ('ADMIN_MESAS_EDIT_BUTTON', 'Modifica', 'it-IT'),
  ('ADMIN_MESAS_EDIT_BUTTON', 'Editar',   'es-ES'),
  ('ADMIN_MESAS_EDIT_BUTTON', 'تعديل',   'ar-MA'),

  ('ADMIN_MESAS_ERROR_NAME', 'O nome da mesa é obrigatório.',          'pt-BR'),
  ('ADMIN_MESAS_ERROR_NAME', 'O nome da mesa é obrigatório.',          'pt-PT'),
  ('ADMIN_MESAS_ERROR_NAME', 'Table name is required.',                'en-US'),
  ('ADMIN_MESAS_ERROR_NAME', 'Il nome del tavolo è obbligatorio.',     'it-IT'),
  ('ADMIN_MESAS_ERROR_NAME', 'El nombre de la mesa es obligatorio.',   'es-ES'),
  ('ADMIN_MESAS_ERROR_NAME', 'اسم الطاولة مطلوب.',                    'ar-MA'),

  ('ADMIN_MESAS_ERROR_NUMBER', 'O número da mesa é obrigatório.',        'pt-BR'),
  ('ADMIN_MESAS_ERROR_NUMBER', 'O número da mesa é obrigatório.',        'pt-PT'),
  ('ADMIN_MESAS_ERROR_NUMBER', 'Table number is required.',              'en-US'),
  ('ADMIN_MESAS_ERROR_NUMBER', 'Il numero del tavolo è obbligatorio.',   'it-IT'),
  ('ADMIN_MESAS_ERROR_NUMBER', 'El número de la mesa es obligatorio.',   'es-ES'),
  ('ADMIN_MESAS_ERROR_NUMBER', 'رقم الطاولة مطلوب.',                    'ar-MA'),

  ('ADMIN_MESAS_ERROR_SAVE', 'Erro ao salvar mesa.',                        'pt-BR'),
  ('ADMIN_MESAS_ERROR_SAVE', 'Erro ao guardar mesa.',                       'pt-PT'),
  ('ADMIN_MESAS_ERROR_SAVE', 'Error saving table.',                         'en-US'),
  ('ADMIN_MESAS_ERROR_SAVE', 'Errore durante il salvataggio del tavolo.',   'it-IT'),
  ('ADMIN_MESAS_ERROR_SAVE', 'Error al guardar mesa.',                      'es-ES'),
  ('ADMIN_MESAS_ERROR_SAVE', 'خطأ في حفظ الطاولة.',                       'ar-MA'),

  ('ADMIN_MESAS_FORM_NAME_LABEL', 'Nome da mesa',      'pt-BR'),
  ('ADMIN_MESAS_FORM_NAME_LABEL', 'Nome da mesa',      'pt-PT'),
  ('ADMIN_MESAS_FORM_NAME_LABEL', 'Table name',        'en-US'),
  ('ADMIN_MESAS_FORM_NAME_LABEL', 'Nome del tavolo',   'it-IT'),
  ('ADMIN_MESAS_FORM_NAME_LABEL', 'Nombre de la mesa', 'es-ES'),
  ('ADMIN_MESAS_FORM_NAME_LABEL', 'اسم الطاولة',      'ar-MA'),

  ('ADMIN_MESAS_FORM_NAME_PH', 'Ex: Mesa do canto',    'pt-BR'),
  ('ADMIN_MESAS_FORM_NAME_PH', 'Ex: Mesa do canto',    'pt-PT'),
  ('ADMIN_MESAS_FORM_NAME_PH', 'E.g.: Corner table',   'en-US'),
  ('ADMIN_MESAS_FORM_NAME_PH', 'Es: Tavolo d''angolo', 'it-IT'),
  ('ADMIN_MESAS_FORM_NAME_PH', 'Ej: Mesa del rincón',  'es-ES'),
  ('ADMIN_MESAS_FORM_NAME_PH', 'مثال: طاولة الزاوية', 'ar-MA'),

  ('ADMIN_MESAS_FORM_NUMBER_LABEL', 'Número da mesa',  'pt-BR'),
  ('ADMIN_MESAS_FORM_NUMBER_LABEL', 'Número da mesa',  'pt-PT'),
  ('ADMIN_MESAS_FORM_NUMBER_LABEL', 'Table number',    'en-US'),
  ('ADMIN_MESAS_FORM_NUMBER_LABEL', 'Numero del tavolo', 'it-IT'),
  ('ADMIN_MESAS_FORM_NUMBER_LABEL', 'Número de mesa',  'es-ES'),
  ('ADMIN_MESAS_FORM_NUMBER_LABEL', 'رقم الطاولة',    'ar-MA'),

  ('ADMIN_MESAS_FORM_TITLE_EDIT', 'Editar mesa',     'pt-BR'),
  ('ADMIN_MESAS_FORM_TITLE_EDIT', 'Editar mesa',     'pt-PT'),
  ('ADMIN_MESAS_FORM_TITLE_EDIT', 'Edit table',      'en-US'),
  ('ADMIN_MESAS_FORM_TITLE_EDIT', 'Modifica tavolo', 'it-IT'),
  ('ADMIN_MESAS_FORM_TITLE_EDIT', 'Editar mesa',     'es-ES'),
  ('ADMIN_MESAS_FORM_TITLE_EDIT', 'تعديل الطاولة',  'ar-MA'),

  ('ADMIN_MESAS_FORM_TITLE_NEW', 'Nova mesa',     'pt-BR'),
  ('ADMIN_MESAS_FORM_TITLE_NEW', 'Nova mesa',     'pt-PT'),
  ('ADMIN_MESAS_FORM_TITLE_NEW', 'New table',     'en-US'),
  ('ADMIN_MESAS_FORM_TITLE_NEW', 'Nuovo tavolo',  'it-IT'),
  ('ADMIN_MESAS_FORM_TITLE_NEW', 'Nueva mesa',    'es-ES'),
  ('ADMIN_MESAS_FORM_TITLE_NEW', 'طاولة جديدة',  'ar-MA'),

  ('ADMIN_MESAS_INACTIVE', 'Inativa',   'pt-BR'),
  ('ADMIN_MESAS_INACTIVE', 'Inativa',   'pt-PT'),
  ('ADMIN_MESAS_INACTIVE', 'Inactive',  'en-US'),
  ('ADMIN_MESAS_INACTIVE', 'Inattivo',  'it-IT'),
  ('ADMIN_MESAS_INACTIVE', 'Inactiva',  'es-ES'),
  ('ADMIN_MESAS_INACTIVE', 'غير نشطة', 'ar-MA'),

  ('ADMIN_MESAS_NEW_QR_BUTTON', 'Novo QR Code', 'pt-BR'),
  ('ADMIN_MESAS_NEW_QR_BUTTON', 'Novo QR Code', 'pt-PT'),
  ('ADMIN_MESAS_NEW_QR_BUTTON', 'New QR Code',  'en-US'),
  ('ADMIN_MESAS_NEW_QR_BUTTON', 'Nuovo QR Code','it-IT'),
  ('ADMIN_MESAS_NEW_QR_BUTTON', 'Nuevo QR Code','es-ES'),
  ('ADMIN_MESAS_NEW_QR_BUTTON', 'رمز QR جديد', 'ar-MA'),

  ('ADMIN_MESAS_NO_TERMINAL', 'Sem terminal',     'pt-BR'),
  ('ADMIN_MESAS_NO_TERMINAL', 'Sem terminal',     'pt-PT'),
  ('ADMIN_MESAS_NO_TERMINAL', 'No terminal',      'en-US'),
  ('ADMIN_MESAS_NO_TERMINAL', 'Nessun terminale', 'it-IT'),
  ('ADMIN_MESAS_NO_TERMINAL', 'Sin terminal',     'es-ES'),
  ('ADMIN_MESAS_NO_TERMINAL', 'بدون طرفية',      'ar-MA'),

  ('ADMIN_MESAS_PRINT', 'Imprimir', 'pt-BR'),
  ('ADMIN_MESAS_PRINT', 'Imprimir', 'pt-PT'),
  ('ADMIN_MESAS_PRINT', 'Print',    'en-US'),
  ('ADMIN_MESAS_PRINT', 'Stampa',   'it-IT'),
  ('ADMIN_MESAS_PRINT', 'Imprimir', 'es-ES'),
  ('ADMIN_MESAS_PRINT', 'طباعة',   'ar-MA'),

  ('ADMIN_MESAS_QR_BUTTON', 'Ver QR Code',  'pt-BR'),
  ('ADMIN_MESAS_QR_BUTTON', 'Ver QR Code',  'pt-PT'),
  ('ADMIN_MESAS_QR_BUTTON', 'View QR Code', 'en-US'),
  ('ADMIN_MESAS_QR_BUTTON', 'Vedi QR Code', 'it-IT'),
  ('ADMIN_MESAS_QR_BUTTON', 'Ver QR Code',  'es-ES'),
  ('ADMIN_MESAS_QR_BUTTON', 'عرض رمز QR',  'ar-MA'),

  ('ADMIN_MESAS_QR_ERROR', 'Erro ao gerar QR Code.',                    'pt-BR'),
  ('ADMIN_MESAS_QR_ERROR', 'Erro ao gerar QR Code.',                    'pt-PT'),
  ('ADMIN_MESAS_QR_ERROR', 'Error generating QR Code.',                 'en-US'),
  ('ADMIN_MESAS_QR_ERROR', 'Errore nella generazione del QR Code.',     'it-IT'),
  ('ADMIN_MESAS_QR_ERROR', 'Error al generar QR Code.',                 'es-ES'),
  ('ADMIN_MESAS_QR_ERROR', 'خطأ في إنشاء رمز QR.',                    'ar-MA'),

  ('ADMIN_MESAS_QR_GENERATED', 'QR Code gerado!',    'pt-BR'),
  ('ADMIN_MESAS_QR_GENERATED', 'QR Code gerado!',    'pt-PT'),
  ('ADMIN_MESAS_QR_GENERATED', 'QR Code generated!', 'en-US'),
  ('ADMIN_MESAS_QR_GENERATED', 'QR Code generato!',  'it-IT'),
  ('ADMIN_MESAS_QR_GENERATED', '¡QR Code generado!', 'es-ES'),
  ('ADMIN_MESAS_QR_GENERATED', 'تم إنشاء رمز QR!',  'ar-MA'),

  ('ADMIN_MESAS_REMOVE_BUTTON', 'Remover',  'pt-BR'),
  ('ADMIN_MESAS_REMOVE_BUTTON', 'Remover',  'pt-PT'),
  ('ADMIN_MESAS_REMOVE_BUTTON', 'Remove',   'en-US'),
  ('ADMIN_MESAS_REMOVE_BUTTON', 'Rimuovi',  'it-IT'),
  ('ADMIN_MESAS_REMOVE_BUTTON', 'Eliminar', 'es-ES'),
  ('ADMIN_MESAS_REMOVE_BUTTON', 'إزالة',   'ar-MA'),

  ('ADMIN_MESAS_REMOVE_ERROR', 'Erro ao remover mesa.',                      'pt-BR'),
  ('ADMIN_MESAS_REMOVE_ERROR', 'Erro ao remover mesa.',                      'pt-PT'),
  ('ADMIN_MESAS_REMOVE_ERROR', 'Error removing table.',                      'en-US'),
  ('ADMIN_MESAS_REMOVE_ERROR', 'Errore durante la rimozione del tavolo.',    'it-IT'),
  ('ADMIN_MESAS_REMOVE_ERROR', 'Error al eliminar mesa.',                    'es-ES'),
  ('ADMIN_MESAS_REMOVE_ERROR', 'خطأ في إزالة الطاولة.',                    'ar-MA'),

  ('ADMIN_MESAS_REMOVED', 'Mesa removida.',      'pt-BR'),
  ('ADMIN_MESAS_REMOVED', 'Mesa removida.',      'pt-PT'),
  ('ADMIN_MESAS_REMOVED', 'Table removed.',      'en-US'),
  ('ADMIN_MESAS_REMOVED', 'Tavolo rimosso.',     'it-IT'),
  ('ADMIN_MESAS_REMOVED', 'Mesa eliminada.',     'es-ES'),
  ('ADMIN_MESAS_REMOVED', 'تمت إزالة الطاولة.','ar-MA'),

  ('ADMIN_MESAS_SAVE', 'Salvar',  'pt-BR'),
  ('ADMIN_MESAS_SAVE', 'Guardar', 'pt-PT'),
  ('ADMIN_MESAS_SAVE', 'Save',    'en-US'),
  ('ADMIN_MESAS_SAVE', 'Salva',   'it-IT'),
  ('ADMIN_MESAS_SAVE', 'Guardar', 'es-ES'),
  ('ADMIN_MESAS_SAVE', 'حفظ',    'ar-MA'),

  ('ADMIN_MESAS_SAVING', 'Salvando...',    'pt-BR'),
  ('ADMIN_MESAS_SAVING', 'A guardar...',   'pt-PT'),
  ('ADMIN_MESAS_SAVING', 'Saving...',      'en-US'),
  ('ADMIN_MESAS_SAVING', 'Salvataggio...', 'it-IT'),
  ('ADMIN_MESAS_SAVING', 'Guardando...',   'es-ES'),
  ('ADMIN_MESAS_SAVING', 'جاري الحفظ...', 'ar-MA'),

  ('ADMIN_MESAS_TABLE_NUMBER', 'Mesa',      'pt-BR'),
  ('ADMIN_MESAS_TABLE_NUMBER', 'Mesa',      'pt-PT'),
  ('ADMIN_MESAS_TABLE_NUMBER', 'Table',     'en-US'),
  ('ADMIN_MESAS_TABLE_NUMBER', 'Tavolo',    'it-IT'),
  ('ADMIN_MESAS_TABLE_NUMBER', 'Mesa',      'es-ES'),
  ('ADMIN_MESAS_TABLE_NUMBER', 'الطاولة',  'ar-MA'),

  ('ADMIN_MESAS_UPDATED', 'Mesa atualizada!',   'pt-BR'),
  ('ADMIN_MESAS_UPDATED', 'Mesa atualizada!',   'pt-PT'),
  ('ADMIN_MESAS_UPDATED', 'Table updated!',     'en-US'),
  ('ADMIN_MESAS_UPDATED', 'Tavolo aggiornato!', 'it-IT'),
  ('ADMIN_MESAS_UPDATED', '¡Mesa actualizada!', 'es-ES'),
  ('ADMIN_MESAS_UPDATED', 'تم تحديث الطاولة!', 'ar-MA'),

  -- ─── KITCHEN ─────────────────────────────────────────────────────────────
  ('KITCHEN_CANCEL_ERROR', 'Erro ao cancelar pedido.',              'pt-BR'),
  ('KITCHEN_CANCEL_ERROR', 'Erro ao cancelar pedido.',              'pt-PT'),
  ('KITCHEN_CANCEL_ERROR', 'Error cancelling order.',               'en-US'),
  ('KITCHEN_CANCEL_ERROR', 'Errore nella cancellazione dell''ordine.', 'it-IT'),
  ('KITCHEN_CANCEL_ERROR', 'Error al cancelar pedido.',             'es-ES'),
  ('KITCHEN_CANCEL_ERROR', 'خطأ في إلغاء الطلب.',                 'ar-MA'),

  ('KITCHEN_CANCEL_ORDER_BTN', 'Cancelar pedido', 'pt-BR'),
  ('KITCHEN_CANCEL_ORDER_BTN', 'Cancelar pedido', 'pt-PT'),
  ('KITCHEN_CANCEL_ORDER_BTN', 'Cancel order',    'en-US'),
  ('KITCHEN_CANCEL_ORDER_BTN', 'Annulla ordine',  'it-IT'),
  ('KITCHEN_CANCEL_ORDER_BTN', 'Cancelar pedido', 'es-ES'),
  ('KITCHEN_CANCEL_ORDER_BTN', 'إلغاء الطلب',    'ar-MA'),

  ('KITCHEN_CANCELLING', 'Cancelando...',   'pt-BR'),
  ('KITCHEN_CANCELLING', 'Cancelando...',   'pt-PT'),
  ('KITCHEN_CANCELLING', 'Cancelling...',   'en-US'),
  ('KITCHEN_CANCELLING', 'Annullamento...', 'it-IT'),
  ('KITCHEN_CANCELLING', 'Cancelando...',   'es-ES'),
  ('KITCHEN_CANCELLING', 'جاري الإلغاء...','ar-MA'),

  ('KITCHEN_CONFIRM_DELIVERY_BTN', 'Confirmar entrega', 'pt-BR'),
  ('KITCHEN_CONFIRM_DELIVERY_BTN', 'Confirmar entrega', 'pt-PT'),
  ('KITCHEN_CONFIRM_DELIVERY_BTN', 'Confirm delivery',  'en-US'),
  ('KITCHEN_CONFIRM_DELIVERY_BTN', 'Conferma consegna', 'it-IT'),
  ('KITCHEN_CONFIRM_DELIVERY_BTN', 'Confirmar entrega', 'es-ES'),
  ('KITCHEN_CONFIRM_DELIVERY_BTN', 'تأكيد التسليم',    'ar-MA'),

  ('KITCHEN_CONFIRM_PAYMENT_BTN', 'Confirmar pagamento', 'pt-BR'),
  ('KITCHEN_CONFIRM_PAYMENT_BTN', 'Confirmar pagamento', 'pt-PT'),
  ('KITCHEN_CONFIRM_PAYMENT_BTN', 'Confirm payment',     'en-US'),
  ('KITCHEN_CONFIRM_PAYMENT_BTN', 'Conferma pagamento',  'it-IT'),
  ('KITCHEN_CONFIRM_PAYMENT_BTN', 'Confirmar pago',      'es-ES'),
  ('KITCHEN_CONFIRM_PAYMENT_BTN', 'تأكيد الدفع',        'ar-MA'),

  ('KITCHEN_CONFIRMING_DELIVERY', 'Confirmando entrega...', 'pt-BR'),
  ('KITCHEN_CONFIRMING_DELIVERY', 'Confirmando entrega...', 'pt-PT'),
  ('KITCHEN_CONFIRMING_DELIVERY', 'Confirming delivery...', 'en-US'),
  ('KITCHEN_CONFIRMING_DELIVERY', 'Conferma consegna...',   'it-IT'),
  ('KITCHEN_CONFIRMING_DELIVERY', 'Confirmando entrega...', 'es-ES'),
  ('KITCHEN_CONFIRMING_DELIVERY', 'جاري تأكيد التسليم...', 'ar-MA'),

  ('KITCHEN_DELIVERY_CODE_SECTION', 'Código de entrega',   'pt-BR'),
  ('KITCHEN_DELIVERY_CODE_SECTION', 'Código de entrega',   'pt-PT'),
  ('KITCHEN_DELIVERY_CODE_SECTION', 'Delivery code',       'en-US'),
  ('KITCHEN_DELIVERY_CODE_SECTION', 'Codice di consegna',  'it-IT'),
  ('KITCHEN_DELIVERY_CODE_SECTION', 'Código de entrega',   'es-ES'),
  ('KITCHEN_DELIVERY_CODE_SECTION', 'رمز التسليم',         'ar-MA'),

  ('KITCHEN_DELIVERY_CONFIRMED_TOAST', 'Entrega confirmada!',  'pt-BR'),
  ('KITCHEN_DELIVERY_CONFIRMED_TOAST', 'Entrega confirmada!',  'pt-PT'),
  ('KITCHEN_DELIVERY_CONFIRMED_TOAST', 'Delivery confirmed!',  'en-US'),
  ('KITCHEN_DELIVERY_CONFIRMED_TOAST', 'Consegna confermata!', 'it-IT'),
  ('KITCHEN_DELIVERY_CONFIRMED_TOAST', '¡Entrega confirmada!', 'es-ES'),
  ('KITCHEN_DELIVERY_CONFIRMED_TOAST', 'تم تأكيد التسليم!',   'ar-MA'),

  ('KITCHEN_MOTOBOY_ASSIGNED', 'Motoboy atribuído!',        'pt-BR'),
  ('KITCHEN_MOTOBOY_ASSIGNED', 'Estafeta atribuído!',       'pt-PT'),
  ('KITCHEN_MOTOBOY_ASSIGNED', 'Delivery driver assigned!', 'en-US'),
  ('KITCHEN_MOTOBOY_ASSIGNED', 'Fattorino assegnato!',      'it-IT'),
  ('KITCHEN_MOTOBOY_ASSIGNED', '¡Repartidor asignado!',     'es-ES'),
  ('KITCHEN_MOTOBOY_ASSIGNED', 'تم تعيين الدراج!',          'ar-MA'),

  ('KITCHEN_MOTOBOY_ERROR', 'Erro ao atribuir motoboy.',             'pt-BR'),
  ('KITCHEN_MOTOBOY_ERROR', 'Erro ao atribuir estafeta.',            'pt-PT'),
  ('KITCHEN_MOTOBOY_ERROR', 'Error assigning delivery driver.',      'en-US'),
  ('KITCHEN_MOTOBOY_ERROR', 'Errore nell''assegnazione del fattorino.', 'it-IT'),
  ('KITCHEN_MOTOBOY_ERROR', 'Error al asignar repartidor.',          'es-ES'),
  ('KITCHEN_MOTOBOY_ERROR', 'خطأ في تعيين الدراج.',                 'ar-MA'),

  ('KITCHEN_ORDER_CANCELLED', 'Pedido cancelado.',  'pt-BR'),
  ('KITCHEN_ORDER_CANCELLED', 'Pedido cancelado.',  'pt-PT'),
  ('KITCHEN_ORDER_CANCELLED', 'Order cancelled.',   'en-US'),
  ('KITCHEN_ORDER_CANCELLED', 'Ordine annullato.',  'it-IT'),
  ('KITCHEN_ORDER_CANCELLED', 'Pedido cancelado.',  'es-ES'),
  ('KITCHEN_ORDER_CANCELLED', 'تم إلغاء الطلب.',   'ar-MA'),

  ('KITCHEN_PAY_LATER_BTN', 'Pagar depois',  'pt-BR'),
  ('KITCHEN_PAY_LATER_BTN', 'Pagar depois',  'pt-PT'),
  ('KITCHEN_PAY_LATER_BTN', 'Pay later',     'en-US'),
  ('KITCHEN_PAY_LATER_BTN', 'Paga dopo',     'it-IT'),
  ('KITCHEN_PAY_LATER_BTN', 'Pagar después', 'es-ES'),
  ('KITCHEN_PAY_LATER_BTN', 'ادفع لاحقاً',  'ar-MA'),

  ('KITCHEN_SELECT_MOTOBOY', 'Selecionar motoboy',       'pt-BR'),
  ('KITCHEN_SELECT_MOTOBOY', 'Selecionar estafeta',      'pt-PT'),
  ('KITCHEN_SELECT_MOTOBOY', 'Select delivery driver',   'en-US'),
  ('KITCHEN_SELECT_MOTOBOY', 'Seleziona fattorino',      'it-IT'),
  ('KITCHEN_SELECT_MOTOBOY', 'Seleccionar repartidor',   'es-ES'),
  ('KITCHEN_SELECT_MOTOBOY', 'اختر الدراج',              'ar-MA'),

  ('KITCHEN_STATUS_ERROR', 'Erro ao atualizar status.',              'pt-BR'),
  ('KITCHEN_STATUS_ERROR', 'Erro ao atualizar estado.',              'pt-PT'),
  ('KITCHEN_STATUS_ERROR', 'Error updating status.',                 'en-US'),
  ('KITCHEN_STATUS_ERROR', 'Errore nell''aggiornamento dello stato.','it-IT'),
  ('KITCHEN_STATUS_ERROR', 'Error al actualizar estado.',            'es-ES'),
  ('KITCHEN_STATUS_ERROR', 'خطأ في تحديث الحالة.',                  'ar-MA'),

  ('KITCHEN_STATUS_UPDATED', 'Status atualizado!', 'pt-BR'),
  ('KITCHEN_STATUS_UPDATED', 'Estado atualizado!', 'pt-PT'),
  ('KITCHEN_STATUS_UPDATED', 'Status updated!',    'en-US'),
  ('KITCHEN_STATUS_UPDATED', 'Stato aggiornato!',  'it-IT'),
  ('KITCHEN_STATUS_UPDATED', '¡Estado actualizado!','es-ES'),
  ('KITCHEN_STATUS_UPDATED', 'تم تحديث الحالة!',  'ar-MA'),

  ('KITCHEN_UPDATE_ERROR', 'Erro ao atualizar pedido.',              'pt-BR'),
  ('KITCHEN_UPDATE_ERROR', 'Erro ao atualizar pedido.',              'pt-PT'),
  ('KITCHEN_UPDATE_ERROR', 'Error updating order.',                  'en-US'),
  ('KITCHEN_UPDATE_ERROR', 'Errore nell''aggiornamento dell''ordine.','it-IT'),
  ('KITCHEN_UPDATE_ERROR', 'Error al actualizar pedido.',            'es-ES'),
  ('KITCHEN_UPDATE_ERROR', 'خطأ في تحديث الطلب.',                   'ar-MA'),

  ('KITCHEN_UPDATED_SUCCESS', 'Pedido atualizado!', 'pt-BR'),
  ('KITCHEN_UPDATED_SUCCESS', 'Pedido atualizado!', 'pt-PT'),
  ('KITCHEN_UPDATED_SUCCESS', 'Order updated!',     'en-US'),
  ('KITCHEN_UPDATED_SUCCESS', 'Ordine aggiornato!', 'it-IT'),
  ('KITCHEN_UPDATED_SUCCESS', '¡Pedido actualizado!','es-ES'),
  ('KITCHEN_UPDATED_SUCCESS', 'تم تحديث الطلب!',   'ar-MA')

) AS t(chave, valor, idioma)
ON CONFLICT ON CONSTRAINT uq_traducao DO NOTHING;
