-- Auto-generated supplemental keys for Plans/Register
INSERT INTO traducoes (chave, valor, sistema_id, idioma_id)
SELECT t.chave, t.valor, s.id, i.id
FROM (VALUES
  ('PLANS_ACTION_CREATE_ACCOUNT_THIAGOIAZZETTI','pt-BR','Criar conta para contratar'),
  ('PLANS_ACTION_CREATE_ACCOUNT_THIAGOIAZZETTI','pt-PT','Criar conta para contratar'),
  ('PLANS_ACTION_CREATE_ACCOUNT_THIAGOIAZZETTI','en-US','Criar conta para contratar'),
  ('PLANS_ACTION_CREATE_ACCOUNT_THIAGOIAZZETTI','it-IT','Criar conta para contratar'),
  ('PLANS_ACTION_CREATE_ACCOUNT_THIAGOIAZZETTI','es-ES','Criar conta para contratar'),
  ('PLANS_ACTION_CREATE_ACCOUNT_THIAGOIAZZETTI','ar-MA','Criar conta para contratar'),
  ('PLANS_ACTION_MANAGE_THIAGOIAZZETTI','pt-BR','Gerenciar plano'),
  ('PLANS_ACTION_MANAGE_THIAGOIAZZETTI','pt-PT','Gerenciar plano'),
  ('PLANS_ACTION_MANAGE_THIAGOIAZZETTI','en-US','Gerenciar plano'),
  ('PLANS_ACTION_MANAGE_THIAGOIAZZETTI','it-IT','Gerenciar plano'),
  ('PLANS_ACTION_MANAGE_THIAGOIAZZETTI','es-ES','Gerenciar plano'),
  ('PLANS_ACTION_MANAGE_THIAGOIAZZETTI','ar-MA','Gerenciar plano'),
  ('PLANS_ACTION_SELECT_THIAGOIAZZETTI','pt-BR','Selecionar plano'),
  ('PLANS_ACTION_SELECT_THIAGOIAZZETTI','pt-PT','Selecionar plano'),
  ('PLANS_ACTION_SELECT_THIAGOIAZZETTI','en-US','Selecionar plano'),
  ('PLANS_ACTION_SELECT_THIAGOIAZZETTI','it-IT','Selecionar plano'),
  ('PLANS_ACTION_SELECT_THIAGOIAZZETTI','es-ES','Selecionar plano'),
  ('PLANS_ACTION_SELECT_THIAGOIAZZETTI','ar-MA','Selecionar plano'),
  ('PLANS_ACTIVE_LABEL_THIAGOIAZZETTI','pt-BR','Plano ativo'),
  ('PLANS_ACTIVE_LABEL_THIAGOIAZZETTI','pt-PT','Plano ativo'),
  ('PLANS_ACTIVE_LABEL_THIAGOIAZZETTI','en-US','Plano ativo'),
  ('PLANS_ACTIVE_LABEL_THIAGOIAZZETTI','it-IT','Plano ativo'),
  ('PLANS_ACTIVE_LABEL_THIAGOIAZZETTI','es-ES','Plano ativo'),
  ('PLANS_ACTIVE_LABEL_THIAGOIAZZETTI','ar-MA','Plano ativo'),
  ('PLANS_CANCEL_EDIT_THIAGOIAZZETTI','pt-BR','Cancelar edicao'),
  ('PLANS_CANCEL_EDIT_THIAGOIAZZETTI','pt-PT','Cancelar edicao'),
  ('PLANS_CANCEL_EDIT_THIAGOIAZZETTI','en-US','Cancelar edicao'),
  ('PLANS_CANCEL_EDIT_THIAGOIAZZETTI','it-IT','Cancelar edicao'),
  ('PLANS_CANCEL_EDIT_THIAGOIAZZETTI','es-ES','Cancelar edicao'),
  ('PLANS_CANCEL_EDIT_THIAGOIAZZETTI','ar-MA','Cancelar edicao'),
  ('PLANS_CHECKOUT_HINT_THIAGOIAZZETTI','pt-BR','O checkout recorrente fica disponivel apos o login do aluno. Se ainda nao tiver conta, faca seu cadastro vinculado ao tenant e volte para escolher o plano.'),
  ('PLANS_CHECKOUT_HINT_THIAGOIAZZETTI','pt-PT','O checkout recorrente fica disponivel apos o login do aluno. Se ainda nao tiver conta, faca seu cadastro vinculado ao tenant e volte para escolher o plano.'),
  ('PLANS_CHECKOUT_HINT_THIAGOIAZZETTI','en-US','O checkout recorrente fica disponivel apos o login do aluno. Se ainda nao tiver conta, faca seu cadastro vinculado ao tenant e volte para escolher o plano.'),
  ('PLANS_CHECKOUT_HINT_THIAGOIAZZETTI','it-IT','O checkout recorrente fica disponivel apos o login do aluno. Se ainda nao tiver conta, faca seu cadastro vinculado ao tenant e volte para escolher o plano.'),
  ('PLANS_CHECKOUT_HINT_THIAGOIAZZETTI','es-ES','O checkout recorrente fica disponivel apos o login do aluno. Se ainda nao tiver conta, faca seu cadastro vinculado ao tenant e volte para escolher o plano.'),
  ('PLANS_CHECKOUT_HINT_THIAGOIAZZETTI','ar-MA','O checkout recorrente fica disponivel apos o login do aluno. Se ainda nao tiver conta, faca seu cadastro vinculado ao tenant e volte para escolher o plano.'),
  ('PLANS_CHECKOUT_PENDING_THIAGOIAZZETTI','pt-BR','Checkout online pendente de configuracao'),
  ('PLANS_CHECKOUT_PENDING_THIAGOIAZZETTI','pt-PT','Checkout online pendente de configuracao'),
  ('PLANS_CHECKOUT_PENDING_THIAGOIAZZETTI','en-US','Checkout online pendente de configuracao'),
  ('PLANS_CHECKOUT_PENDING_THIAGOIAZZETTI','it-IT','Checkout online pendente de configuracao'),
  ('PLANS_CHECKOUT_PENDING_THIAGOIAZZETTI','es-ES','Checkout online pendente de configuracao'),
  ('PLANS_CHECKOUT_PENDING_THIAGOIAZZETTI','ar-MA','Checkout online pendente de configuracao'),
  ('PLANS_CONFIRM_DELETE_THIAGOIAZZETTI','pt-BR','Tem certeza que deseja excluir este plano? Esta acao nao pode ser desfeita.'),
  ('PLANS_CONFIRM_DELETE_THIAGOIAZZETTI','pt-PT','Tem certeza que deseja excluir este plano? Esta acao nao pode ser desfeita.'),
  ('PLANS_CONFIRM_DELETE_THIAGOIAZZETTI','en-US','Tem certeza que deseja excluir este plano? Esta acao nao pode ser desfeita.'),
  ('PLANS_CONFIRM_DELETE_THIAGOIAZZETTI','it-IT','Tem certeza que deseja excluir este plano? Esta acao nao pode ser desfeita.'),
  ('PLANS_CONFIRM_DELETE_THIAGOIAZZETTI','es-ES','Tem certeza que deseja excluir este plano? Esta acao nao pode ser desfeita.'),
  ('PLANS_CONFIRM_DELETE_THIAGOIAZZETTI','ar-MA','Tem certeza que deseja excluir este plano? Esta acao nao pode ser desfeita.'),
  ('PLANS_CREATE_BUTTON_THIAGOIAZZETTI','pt-BR','Criar plano'),
  ('PLANS_CREATE_BUTTON_THIAGOIAZZETTI','pt-PT','Criar plano'),
  ('PLANS_CREATE_BUTTON_THIAGOIAZZETTI','en-US','Criar plano'),
  ('PLANS_CREATE_BUTTON_THIAGOIAZZETTI','it-IT','Criar plano'),
  ('PLANS_CREATE_BUTTON_THIAGOIAZZETTI','es-ES','Criar plano'),
  ('PLANS_CREATE_BUTTON_THIAGOIAZZETTI','ar-MA','Criar plano'),
  ('PLANS_DAYS_THIAGOIAZZETTI','pt-BR','dias'),
  ('PLANS_DAYS_THIAGOIAZZETTI','pt-PT','dias'),
  ('PLANS_DAYS_THIAGOIAZZETTI','en-US','dias'),
  ('PLANS_DAYS_THIAGOIAZZETTI','it-IT','dias'),
  ('PLANS_DAYS_THIAGOIAZZETTI','es-ES','dias'),
  ('PLANS_DAYS_THIAGOIAZZETTI','ar-MA','dias'),
  ('PLANS_DELETE_BUTTON_THIAGOIAZZETTI','pt-BR','Excluir plano'),
  ('PLANS_DELETE_BUTTON_THIAGOIAZZETTI','pt-PT','Excluir plano'),
  ('PLANS_DELETE_BUTTON_THIAGOIAZZETTI','en-US','Excluir plano'),
  ('PLANS_DELETE_BUTTON_THIAGOIAZZETTI','it-IT','Excluir plano'),
  ('PLANS_DELETE_BUTTON_THIAGOIAZZETTI','es-ES','Excluir plano'),
  ('PLANS_DELETE_BUTTON_THIAGOIAZZETTI','ar-MA','Excluir plano'),
  ('PLANS_DESCRIPTION_LABEL_THIAGOIAZZETTI','pt-BR','Descricao'),
  ('PLANS_DESCRIPTION_LABEL_THIAGOIAZZETTI','pt-PT','Descricao'),
  ('PLANS_DESCRIPTION_LABEL_THIAGOIAZZETTI','en-US','Descricao'),
  ('PLANS_DESCRIPTION_LABEL_THIAGOIAZZETTI','it-IT','Descricao'),
  ('PLANS_DESCRIPTION_LABEL_THIAGOIAZZETTI','es-ES','Descricao'),
  ('PLANS_DESCRIPTION_LABEL_THIAGOIAZZETTI','ar-MA','Descricao'),
  ('PLANS_DESCRIPTION_PLACEHOLDER_THIAGOIAZZETTI','pt-BR','Descreva o que inclui no plano'),
  ('PLANS_DESCRIPTION_PLACEHOLDER_THIAGOIAZZETTI','pt-PT','Descreva o que inclui no plano'),
  ('PLANS_DESCRIPTION_PLACEHOLDER_THIAGOIAZZETTI','en-US','Descreva o que inclui no plano'),
  ('PLANS_DESCRIPTION_PLACEHOLDER_THIAGOIAZZETTI','it-IT','Descreva o que inclui no plano'),
  ('PLANS_DESCRIPTION_PLACEHOLDER_THIAGOIAZZETTI','es-ES','Descreva o que inclui no plano'),
  ('PLANS_DESCRIPTION_PLACEHOLDER_THIAGOIAZZETTI','ar-MA','Descreva o que inclui no plano'),
  ('PLANS_EDIT_TITLE_THIAGOIAZZETTI','pt-BR','Editar plano'),
  ('PLANS_EDIT_TITLE_THIAGOIAZZETTI','pt-PT','Editar plano'),
  ('PLANS_EDIT_TITLE_THIAGOIAZZETTI','en-US','Editar plano'),
  ('PLANS_EDIT_TITLE_THIAGOIAZZETTI','it-IT','Editar plano'),
  ('PLANS_EDIT_TITLE_THIAGOIAZZETTI','es-ES','Editar plano'),
  ('PLANS_EDIT_TITLE_THIAGOIAZZETTI','ar-MA','Editar plano'),
  ('PLANS_EMPTY_THIAGOIAZZETTI','pt-BR','Nenhum plano de assinatura encontrado para esse tenant.'),
  ('PLANS_EMPTY_THIAGOIAZZETTI','pt-PT','Nenhum plano de assinatura encontrado para esse tenant.'),
  ('PLANS_EMPTY_THIAGOIAZZETTI','en-US','Nenhum plano de assinatura encontrado para esse tenant.'),
  ('PLANS_EMPTY_THIAGOIAZZETTI','it-IT','Nenhum plano de assinatura encontrado para esse tenant.'),
  ('PLANS_EMPTY_THIAGOIAZZETTI','es-ES','Nenhum plano de assinatura encontrado para esse tenant.'),
  ('PLANS_EMPTY_THIAGOIAZZETTI','ar-MA','Nenhum plano de assinatura encontrado para esse tenant.'),
  ('PLANS_ERROR_LOAD_THIAGOIAZZETTI','pt-BR','Nao foi possivel carregar os planos'),
  ('PLANS_ERROR_LOAD_THIAGOIAZZETTI','pt-PT','Nao foi possivel carregar os planos'),
  ('PLANS_ERROR_LOAD_THIAGOIAZZETTI','en-US','Nao foi possivel carregar os planos'),
  ('PLANS_ERROR_LOAD_THIAGOIAZZETTI','it-IT','Nao foi possivel carregar os planos'),
  ('PLANS_ERROR_LOAD_THIAGOIAZZETTI','es-ES','Nao foi possivel carregar os planos'),
  ('PLANS_ERROR_LOAD_THIAGOIAZZETTI','ar-MA','Nao foi possivel carregar os planos'),
  ('PLANS_EVERY_THIAGOIAZZETTI','pt-BR','/'),
  ('PLANS_EVERY_THIAGOIAZZETTI','pt-PT','/'),
  ('PLANS_EVERY_THIAGOIAZZETTI','en-US','/'),
  ('PLANS_EVERY_THIAGOIAZZETTI','it-IT','/'),
  ('PLANS_EVERY_THIAGOIAZZETTI','es-ES','/'),
  ('PLANS_EVERY_THIAGOIAZZETTI','ar-MA','/'),
  ('PLANS_LINK_CONTINUE_THIAGOIAZZETTI','pt-BR','Continuar'),
  ('PLANS_LINK_CONTINUE_THIAGOIAZZETTI','pt-PT','Continuar'),
  ('PLANS_LINK_CONTINUE_THIAGOIAZZETTI','en-US','Continuar'),
  ('PLANS_LINK_CONTINUE_THIAGOIAZZETTI','it-IT','Continuar'),
  ('PLANS_LINK_CONTINUE_THIAGOIAZZETTI','es-ES','Continuar'),
  ('PLANS_LINK_CONTINUE_THIAGOIAZZETTI','ar-MA','Continuar'),
  ('PLANS_LINK_OPEN_HOME_THIAGOIAZZETTI','pt-BR','Abrir pagina inicial'),
  ('PLANS_LINK_OPEN_HOME_THIAGOIAZZETTI','pt-PT','Abrir pagina inicial'),
  ('PLANS_LINK_OPEN_HOME_THIAGOIAZZETTI','en-US','Abrir pagina inicial'),
  ('PLANS_LINK_OPEN_HOME_THIAGOIAZZETTI','it-IT','Abrir pagina inicial'),
  ('PLANS_LINK_OPEN_HOME_THIAGOIAZZETTI','es-ES','Abrir pagina inicial'),
  ('PLANS_LINK_OPEN_HOME_THIAGOIAZZETTI','ar-MA','Abrir pagina inicial'),
  ('PLANS_LOADING_THIAGOIAZZETTI','pt-BR','Carregando planos...'),
  ('PLANS_LOADING_THIAGOIAZZETTI','pt-PT','Carregando planos...'),
  ('PLANS_LOADING_THIAGOIAZZETTI','en-US','Carregando planos...'),
  ('PLANS_LOADING_THIAGOIAZZETTI','it-IT','Carregando planos...'),
  ('PLANS_LOADING_THIAGOIAZZETTI','es-ES','Carregando planos...'),
  ('PLANS_LOADING_THIAGOIAZZETTI','ar-MA','Carregando planos...'),
  ('PLANS_MESSAGE_CREATED_SUCCESS_THIAGOIAZZETTI','pt-BR','Plano criado com sucesso'),
  ('PLANS_MESSAGE_CREATED_SUCCESS_THIAGOIAZZETTI','pt-PT','Plano criado com sucesso'),
  ('PLANS_MESSAGE_CREATED_SUCCESS_THIAGOIAZZETTI','en-US','Plano criado com sucesso'),
  ('PLANS_MESSAGE_CREATED_SUCCESS_THIAGOIAZZETTI','it-IT','Plano criado com sucesso'),
  ('PLANS_MESSAGE_CREATED_SUCCESS_THIAGOIAZZETTI','es-ES','Plano criado com sucesso'),
  ('PLANS_MESSAGE_CREATED_SUCCESS_THIAGOIAZZETTI','ar-MA','Plano criado com sucesso'),
  ('PLANS_MESSAGE_DELETE_ERROR_THIAGOIAZZETTI','pt-BR','Nao foi possivel excluir o plano'),
  ('PLANS_MESSAGE_DELETE_ERROR_THIAGOIAZZETTI','pt-PT','Nao foi possivel excluir o plano'),
  ('PLANS_MESSAGE_DELETE_ERROR_THIAGOIAZZETTI','en-US','Nao foi possivel excluir o plano'),
  ('PLANS_MESSAGE_DELETE_ERROR_THIAGOIAZZETTI','it-IT','Nao foi possivel excluir o plano'),
  ('PLANS_MESSAGE_DELETE_ERROR_THIAGOIAZZETTI','es-ES','Nao foi possivel excluir o plano'),
  ('PLANS_MESSAGE_DELETE_ERROR_THIAGOIAZZETTI','ar-MA','Nao foi possivel excluir o plano'),
  ('PLANS_MESSAGE_DELETED_SUCCESS_THIAGOIAZZETTI','pt-BR','Plano excluido com sucesso'),
  ('PLANS_MESSAGE_DELETED_SUCCESS_THIAGOIAZZETTI','pt-PT','Plano excluido com sucesso'),
  ('PLANS_MESSAGE_DELETED_SUCCESS_THIAGOIAZZETTI','en-US','Plano excluido com sucesso'),
  ('PLANS_MESSAGE_DELETED_SUCCESS_THIAGOIAZZETTI','it-IT','Plano excluido com sucesso'),
  ('PLANS_MESSAGE_DELETED_SUCCESS_THIAGOIAZZETTI','es-ES','Plano excluido com sucesso'),
  ('PLANS_MESSAGE_DELETED_SUCCESS_THIAGOIAZZETTI','ar-MA','Plano excluido com sucesso'),
  ('PLANS_MESSAGE_FILL_CARD_THIAGOIAZZETTI','pt-BR','selecionado. Preencha os dados do cartao para concluir a assinatura.'),
  ('PLANS_MESSAGE_FILL_CARD_THIAGOIAZZETTI','pt-PT','selecionado. Preencha os dados do cartao para concluir a assinatura.'),
  ('PLANS_MESSAGE_FILL_CARD_THIAGOIAZZETTI','en-US','selecionado. Preencha os dados do cartao para concluir a assinatura.'),
  ('PLANS_MESSAGE_FILL_CARD_THIAGOIAZZETTI','it-IT','selecionado. Preencha os dados do cartao para concluir a assinatura.'),
  ('PLANS_MESSAGE_FILL_CARD_THIAGOIAZZETTI','es-ES','selecionado. Preencha os dados do cartao para concluir a assinatura.'),
  ('PLANS_MESSAGE_FILL_CARD_THIAGOIAZZETTI','ar-MA','selecionado. Preencha os dados do cartao para concluir a assinatura.'),
  ('PLANS_MESSAGE_INVALID_PRICE_THIAGOIAZZETTI','pt-BR','Preco mensal invalido'),
  ('PLANS_MESSAGE_INVALID_PRICE_THIAGOIAZZETTI','pt-PT','Preco mensal invalido'),
  ('PLANS_MESSAGE_INVALID_PRICE_THIAGOIAZZETTI','en-US','Preco mensal invalido'),
  ('PLANS_MESSAGE_INVALID_PRICE_THIAGOIAZZETTI','it-IT','Preco mensal invalido'),
  ('PLANS_MESSAGE_INVALID_PRICE_THIAGOIAZZETTI','es-ES','Preco mensal invalido'),
  ('PLANS_MESSAGE_INVALID_PRICE_THIAGOIAZZETTI','ar-MA','Preco mensal invalido'),
  ('PLANS_MESSAGE_LOGIN_REQUIRED_THIAGOIAZZETTI','pt-BR','Crie uma conta ou faca login como aluno para contratar.'),
  ('PLANS_MESSAGE_LOGIN_REQUIRED_THIAGOIAZZETTI','pt-PT','Crie uma conta ou faca login como aluno para contratar.'),
  ('PLANS_MESSAGE_LOGIN_REQUIRED_THIAGOIAZZETTI','en-US','Crie uma conta ou faca login como aluno para contratar.'),
  ('PLANS_MESSAGE_LOGIN_REQUIRED_THIAGOIAZZETTI','it-IT','Crie uma conta ou faca login como aluno para contratar.'),
  ('PLANS_MESSAGE_LOGIN_REQUIRED_THIAGOIAZZETTI','es-ES','Crie uma conta ou faca login como aluno para contratar.'),
  ('PLANS_MESSAGE_LOGIN_REQUIRED_THIAGOIAZZETTI','ar-MA','Crie uma conta ou faca login como aluno para contratar.'),
  ('PLANS_MESSAGE_PLAN_SELECTED_THIAGOIAZZETTI','pt-BR','Plano'),
  ('PLANS_MESSAGE_PLAN_SELECTED_THIAGOIAZZETTI','pt-PT','Plano'),
  ('PLANS_MESSAGE_PLAN_SELECTED_THIAGOIAZZETTI','en-US','Plano'),
  ('PLANS_MESSAGE_PLAN_SELECTED_THIAGOIAZZETTI','it-IT','Plano'),
  ('PLANS_MESSAGE_PLAN_SELECTED_THIAGOIAZZETTI','es-ES','Plano'),
  ('PLANS_MESSAGE_PLAN_SELECTED_THIAGOIAZZETTI','ar-MA','Plano'),
  ('PLANS_MESSAGE_REQUIRED_FIELDS_THIAGOIAZZETTI','pt-BR','Nome e preco mensal sao obrigatorios'),
  ('PLANS_MESSAGE_REQUIRED_FIELDS_THIAGOIAZZETTI','pt-PT','Nome e preco mensal sao obrigatorios'),
  ('PLANS_MESSAGE_REQUIRED_FIELDS_THIAGOIAZZETTI','en-US','Nome e preco mensal sao obrigatorios'),
  ('PLANS_MESSAGE_REQUIRED_FIELDS_THIAGOIAZZETTI','it-IT','Nome e preco mensal sao obrigatorios'),
  ('PLANS_MESSAGE_REQUIRED_FIELDS_THIAGOIAZZETTI','es-ES','Nome e preco mensal sao obrigatorios'),
  ('PLANS_MESSAGE_REQUIRED_FIELDS_THIAGOIAZZETTI','ar-MA','Nome e preco mensal sao obrigatorios'),
  ('PLANS_MESSAGE_SAVE_ERROR_THIAGOIAZZETTI','pt-BR','Nao foi possivel salvar o plano'),
  ('PLANS_MESSAGE_SAVE_ERROR_THIAGOIAZZETTI','pt-PT','Nao foi possivel salvar o plano'),
  ('PLANS_MESSAGE_SAVE_ERROR_THIAGOIAZZETTI','en-US','Nao foi possivel salvar o plano'),
  ('PLANS_MESSAGE_SAVE_ERROR_THIAGOIAZZETTI','it-IT','Nao foi possivel salvar o plano'),
  ('PLANS_MESSAGE_SAVE_ERROR_THIAGOIAZZETTI','es-ES','Nao foi possivel salvar o plano'),
  ('PLANS_MESSAGE_SAVE_ERROR_THIAGOIAZZETTI','ar-MA','Nao foi possivel salvar o plano'),
  ('PLANS_MESSAGE_UPDATED_SUCCESS_THIAGOIAZZETTI','pt-BR','Plano atualizado com sucesso'),
  ('PLANS_MESSAGE_UPDATED_SUCCESS_THIAGOIAZZETTI','pt-PT','Plano atualizado com sucesso'),
  ('PLANS_MESSAGE_UPDATED_SUCCESS_THIAGOIAZZETTI','en-US','Plano atualizado com sucesso'),
  ('PLANS_MESSAGE_UPDATED_SUCCESS_THIAGOIAZZETTI','it-IT','Plano atualizado com sucesso'),
  ('PLANS_MESSAGE_UPDATED_SUCCESS_THIAGOIAZZETTI','es-ES','Plano atualizado com sucesso'),
  ('PLANS_MESSAGE_UPDATED_SUCCESS_THIAGOIAZZETTI','ar-MA','Plano atualizado com sucesso'),
  ('PLANS_MONTHS_THIAGOIAZZETTI','pt-BR','meses'),
  ('PLANS_MONTHS_THIAGOIAZZETTI','pt-PT','meses'),
  ('PLANS_MONTHS_THIAGOIAZZETTI','en-US','meses'),
  ('PLANS_MONTHS_THIAGOIAZZETTI','it-IT','meses'),
  ('PLANS_MONTHS_THIAGOIAZZETTI','es-ES','meses'),
  ('PLANS_MONTHS_THIAGOIAZZETTI','ar-MA','meses'),
  ('PLANS_NAME_LABEL_THIAGOIAZZETTI','pt-BR','Nome do plano'),
  ('PLANS_NAME_LABEL_THIAGOIAZZETTI','pt-PT','Nome do plano'),
  ('PLANS_NAME_LABEL_THIAGOIAZZETTI','en-US','Nome do plano'),
  ('PLANS_NAME_LABEL_THIAGOIAZZETTI','it-IT','Nome do plano'),
  ('PLANS_NAME_LABEL_THIAGOIAZZETTI','es-ES','Nome do plano'),
  ('PLANS_NAME_LABEL_THIAGOIAZZETTI','ar-MA','Nome do plano'),
  ('PLANS_NAME_PLACEHOLDER_THIAGOIAZZETTI','pt-BR','Ex: Plano Premium'),
  ('PLANS_NAME_PLACEHOLDER_THIAGOIAZZETTI','pt-PT','Ex: Plano Premium'),
  ('PLANS_NAME_PLACEHOLDER_THIAGOIAZZETTI','en-US','Ex: Plano Premium'),
  ('PLANS_NAME_PLACEHOLDER_THIAGOIAZZETTI','it-IT','Ex: Plano Premium'),
  ('PLANS_NAME_PLACEHOLDER_THIAGOIAZZETTI','es-ES','Ex: Plano Premium'),
  ('PLANS_NAME_PLACEHOLDER_THIAGOIAZZETTI','ar-MA','Ex: Plano Premium'),
  ('PLANS_NEW_TITLE_THIAGOIAZZETTI','pt-BR','Novo plano'),
  ('PLANS_NEW_TITLE_THIAGOIAZZETTI','pt-PT','Novo plano'),
  ('PLANS_NEW_TITLE_THIAGOIAZZETTI','en-US','Novo plano'),
  ('PLANS_NEW_TITLE_THIAGOIAZZETTI','it-IT','Novo plano'),
  ('PLANS_NEW_TITLE_THIAGOIAZZETTI','es-ES','Novo plano'),
  ('PLANS_NEW_TITLE_THIAGOIAZZETTI','ar-MA','Novo plano'),
  ('PLANS_PER_DAY_THIAGOIAZZETTI','pt-BR','/dia'),
  ('PLANS_PER_DAY_THIAGOIAZZETTI','pt-PT','/dia'),
  ('PLANS_PER_DAY_THIAGOIAZZETTI','en-US','/dia'),
  ('PLANS_PER_DAY_THIAGOIAZZETTI','it-IT','/dia'),
  ('PLANS_PER_DAY_THIAGOIAZZETTI','es-ES','/dia'),
  ('PLANS_PER_DAY_THIAGOIAZZETTI','ar-MA','/dia'),
  ('PLANS_PER_MONTH_THIAGOIAZZETTI','pt-BR','/mes'),
  ('PLANS_PER_MONTH_THIAGOIAZZETTI','pt-PT','/mes'),
  ('PLANS_PER_MONTH_THIAGOIAZZETTI','en-US','/mes'),
  ('PLANS_PER_MONTH_THIAGOIAZZETTI','it-IT','/mes'),
  ('PLANS_PER_MONTH_THIAGOIAZZETTI','es-ES','/mes'),
  ('PLANS_PER_MONTH_THIAGOIAZZETTI','ar-MA','/mes'),
  ('PLANS_PLAN_LABEL_THIAGOIAZZETTI','pt-BR','Plano'),
  ('PLANS_PLAN_LABEL_THIAGOIAZZETTI','pt-PT','Plano'),
  ('PLANS_PLAN_LABEL_THIAGOIAZZETTI','en-US','Plano'),
  ('PLANS_PLAN_LABEL_THIAGOIAZZETTI','it-IT','Plano'),
  ('PLANS_PLAN_LABEL_THIAGOIAZZETTI','es-ES','Plano'),
  ('PLANS_PLAN_LABEL_THIAGOIAZZETTI','ar-MA','Plano'),
  ('PLANS_PREMIUM_DESCRIPTION_THIAGOIAZZETTI','pt-BR','Plano premium com acompanhamento do personal.'),
  ('PLANS_PREMIUM_DESCRIPTION_THIAGOIAZZETTI','pt-PT','Plano premium com acompanhamento do personal.'),
  ('PLANS_PREMIUM_DESCRIPTION_THIAGOIAZZETTI','en-US','Plano premium com acompanhamento do personal.'),
  ('PLANS_PREMIUM_DESCRIPTION_THIAGOIAZZETTI','it-IT','Plano premium com acompanhamento do personal.'),
  ('PLANS_PREMIUM_DESCRIPTION_THIAGOIAZZETTI','es-ES','Plano premium com acompanhamento do personal.'),
  ('PLANS_PREMIUM_DESCRIPTION_THIAGOIAZZETTI','ar-MA','Plano premium com acompanhamento do personal.'),
  ('PLANS_PRICE_LABEL_THIAGOIAZZETTI','pt-BR','Preco mensal (R$)'),
  ('PLANS_PRICE_LABEL_THIAGOIAZZETTI','pt-PT','Preco mensal (R$)'),
  ('PLANS_PRICE_LABEL_THIAGOIAZZETTI','en-US','Preco mensal (R$)'),
  ('PLANS_PRICE_LABEL_THIAGOIAZZETTI','it-IT','Preco mensal (R$)'),
  ('PLANS_PRICE_LABEL_THIAGOIAZZETTI','es-ES','Preco mensal (R$)'),
  ('PLANS_PRICE_LABEL_THIAGOIAZZETTI','ar-MA','Preco mensal (R$)'),
  ('PLANS_PROTECTED_CONTRACT_THIAGOIAZZETTI','pt-BR','Contrato protegido'),
  ('PLANS_PROTECTED_CONTRACT_THIAGOIAZZETTI','pt-PT','Contrato protegido'),
  ('PLANS_PROTECTED_CONTRACT_THIAGOIAZZETTI','en-US','Contrato protegido'),
  ('PLANS_PROTECTED_CONTRACT_THIAGOIAZZETTI','it-IT','Contrato protegido'),
  ('PLANS_PROTECTED_CONTRACT_THIAGOIAZZETTI','es-ES','Contrato protegido'),
  ('PLANS_PROTECTED_CONTRACT_THIAGOIAZZETTI','ar-MA','Contrato protegido'),
  ('PLANS_RECURRING_AUTOMATIC_THIAGOIAZZETTI','pt-BR','Cobranca recorrente automatica no cartao'),
  ('PLANS_RECURRING_AUTOMATIC_THIAGOIAZZETTI','pt-PT','Cobranca recorrente automatica no cartao'),
  ('PLANS_RECURRING_AUTOMATIC_THIAGOIAZZETTI','en-US','Cobranca recorrente automatica no cartao'),
  ('PLANS_RECURRING_AUTOMATIC_THIAGOIAZZETTI','it-IT','Cobranca recorrente automatica no cartao'),
  ('PLANS_RECURRING_AUTOMATIC_THIAGOIAZZETTI','es-ES','Cobranca recorrente automatica no cartao'),
  ('PLANS_RECURRING_AUTOMATIC_THIAGOIAZZETTI','ar-MA','Cobranca recorrente automatica no cartao'),
  ('PLANS_SAVE_CHANGES_THIAGOIAZZETTI','pt-BR','Salvar alteracoes'),
  ('PLANS_SAVE_CHANGES_THIAGOIAZZETTI','pt-PT','Salvar alteracoes'),
  ('PLANS_SAVE_CHANGES_THIAGOIAZZETTI','en-US','Salvar alteracoes'),
  ('PLANS_SAVE_CHANGES_THIAGOIAZZETTI','it-IT','Salvar alteracoes'),
  ('PLANS_SAVE_CHANGES_THIAGOIAZZETTI','es-ES','Salvar alteracoes'),
  ('PLANS_SAVE_CHANGES_THIAGOIAZZETTI','ar-MA','Salvar alteracoes'),
  ('PLANS_SAVING_THIAGOIAZZETTI','pt-BR','Salvando...'),
  ('PLANS_SAVING_THIAGOIAZZETTI','pt-PT','Salvando...'),
  ('PLANS_SAVING_THIAGOIAZZETTI','en-US','Salvando...'),
  ('PLANS_SAVING_THIAGOIAZZETTI','it-IT','Salvando...'),
  ('PLANS_SAVING_THIAGOIAZZETTI','es-ES','Salvando...'),
  ('PLANS_SAVING_THIAGOIAZZETTI','ar-MA','Salvando...'),
  ('PLANS_SUBSCRIPTION_SUCCESS_PREFIX_THIAGOIAZZETTI','pt-BR','Assinatura do plano'),
  ('PLANS_SUBSCRIPTION_SUCCESS_PREFIX_THIAGOIAZZETTI','pt-PT','Assinatura do plano'),
  ('PLANS_SUBSCRIPTION_SUCCESS_PREFIX_THIAGOIAZZETTI','en-US','Assinatura do plano'),
  ('PLANS_SUBSCRIPTION_SUCCESS_PREFIX_THIAGOIAZZETTI','it-IT','Assinatura do plano'),
  ('PLANS_SUBSCRIPTION_SUCCESS_PREFIX_THIAGOIAZZETTI','es-ES','Assinatura do plano'),
  ('PLANS_SUBSCRIPTION_SUCCESS_PREFIX_THIAGOIAZZETTI','ar-MA','Assinatura do plano'),
  ('PLANS_SUBSCRIPTION_SUCCESS_SUFFIX_THIAGOIAZZETTI','pt-BR','criada com sucesso.'),
  ('PLANS_SUBSCRIPTION_SUCCESS_SUFFIX_THIAGOIAZZETTI','pt-PT','criada com sucesso.'),
  ('PLANS_SUBSCRIPTION_SUCCESS_SUFFIX_THIAGOIAZZETTI','en-US','criada com sucesso.'),
  ('PLANS_SUBSCRIPTION_SUCCESS_SUFFIX_THIAGOIAZZETTI','it-IT','criada com sucesso.'),
  ('PLANS_SUBSCRIPTION_SUCCESS_SUFFIX_THIAGOIAZZETTI','es-ES','criada com sucesso.'),
  ('PLANS_SUBSCRIPTION_SUCCESS_SUFFIX_THIAGOIAZZETTI','ar-MA','criada com sucesso.'),
  ('PLANS_SUBTITLE_THIAGOIAZZETTI','pt-BR','Aqui voce ve os planos criados pelo personal e pode contratar a opcao ideal quando estiver logado como aluno.'),
  ('PLANS_SUBTITLE_THIAGOIAZZETTI','pt-PT','Aqui voce ve os planos criados pelo personal e pode contratar a opcao ideal quando estiver logado como aluno.'),
  ('PLANS_SUBTITLE_THIAGOIAZZETTI','en-US','Aqui voce ve os planos criados pelo personal e pode contratar a opcao ideal quando estiver logado como aluno.'),
  ('PLANS_SUBTITLE_THIAGOIAZZETTI','it-IT','Aqui voce ve os planos criados pelo personal e pode contratar a opcao ideal quando estiver logado como aluno.'),
  ('PLANS_SUBTITLE_THIAGOIAZZETTI','es-ES','Aqui voce ve os planos criados pelo personal e pode contratar a opcao ideal quando estiver logado como aluno.'),
  ('PLANS_SUBTITLE_THIAGOIAZZETTI','ar-MA','Aqui voce ve os planos criados pelo personal e pode contratar a opcao ideal quando estiver logado como aluno.'),
  ('PLANS_TITLE_THIAGOIAZZETTI','pt-BR','Planos publicos'),
  ('PLANS_TITLE_THIAGOIAZZETTI','pt-PT','Planos publicos'),
  ('PLANS_TITLE_THIAGOIAZZETTI','en-US','Planos publicos'),
  ('PLANS_TITLE_THIAGOIAZZETTI','it-IT','Planos publicos'),
  ('PLANS_TITLE_THIAGOIAZZETTI','es-ES','Planos publicos'),
  ('PLANS_TITLE_THIAGOIAZZETTI','ar-MA','Planos publicos'),
  ('REGISTER_BUTTON_LOADING_THIAGOIAZZETTI','pt-BR','Cadastrando...'),
  ('REGISTER_BUTTON_LOADING_THIAGOIAZZETTI','pt-PT','Cadastrando...'),
  ('REGISTER_BUTTON_LOADING_THIAGOIAZZETTI','en-US','Cadastrando...'),
  ('REGISTER_BUTTON_LOADING_THIAGOIAZZETTI','it-IT','Cadastrando...'),
  ('REGISTER_BUTTON_LOADING_THIAGOIAZZETTI','es-ES','Cadastrando...'),
  ('REGISTER_BUTTON_LOADING_THIAGOIAZZETTI','ar-MA','Cadastrando...'),
  ('REGISTER_BUTTON_SUBMIT_THIAGOIAZZETTI','pt-BR','Criar conta'),
  ('REGISTER_BUTTON_SUBMIT_THIAGOIAZZETTI','pt-PT','Criar conta'),
  ('REGISTER_BUTTON_SUBMIT_THIAGOIAZZETTI','en-US','Criar conta'),
  ('REGISTER_BUTTON_SUBMIT_THIAGOIAZZETTI','it-IT','Criar conta'),
  ('REGISTER_BUTTON_SUBMIT_THIAGOIAZZETTI','es-ES','Criar conta'),
  ('REGISTER_BUTTON_SUBMIT_THIAGOIAZZETTI','ar-MA','Criar conta'),
  ('REGISTER_CARD_PLAN_TEXT_THIAGOIAZZETTI','pt-BR','Escolha o plano e confirme a adesao.'),
  ('REGISTER_CARD_PLAN_TEXT_THIAGOIAZZETTI','pt-PT','Escolha o plano e confirme a adesao.'),
  ('REGISTER_CARD_PLAN_TEXT_THIAGOIAZZETTI','en-US','Escolha o plano e confirme a adesao.'),
  ('REGISTER_CARD_PLAN_TEXT_THIAGOIAZZETTI','it-IT','Escolha o plano e confirme a adesao.'),
  ('REGISTER_CARD_PLAN_TEXT_THIAGOIAZZETTI','es-ES','Escolha o plano e confirme a adesao.'),
  ('REGISTER_CARD_PLAN_TEXT_THIAGOIAZZETTI','ar-MA','Escolha o plano e confirme a adesao.'),
  ('REGISTER_CARD_PLAN_TITLE_THIAGOIAZZETTI','pt-BR','Plano contratado'),
  ('REGISTER_CARD_PLAN_TITLE_THIAGOIAZZETTI','pt-PT','Plano contratado'),
  ('REGISTER_CARD_PLAN_TITLE_THIAGOIAZZETTI','en-US','Plano contratado'),
  ('REGISTER_CARD_PLAN_TITLE_THIAGOIAZZETTI','it-IT','Plano contratado'),
  ('REGISTER_CARD_PLAN_TITLE_THIAGOIAZZETTI','es-ES','Plano contratado'),
  ('REGISTER_CARD_PLAN_TITLE_THIAGOIAZZETTI','ar-MA','Plano contratado'),
  ('REGISTER_CARD_WORKOUT_TEXT_THIAGOIAZZETTI','pt-BR','Acompanhe as rotinas liberadas pelo seu personal.'),
  ('REGISTER_CARD_WORKOUT_TEXT_THIAGOIAZZETTI','pt-PT','Acompanhe as rotinas liberadas pelo seu personal.'),
  ('REGISTER_CARD_WORKOUT_TEXT_THIAGOIAZZETTI','en-US','Acompanhe as rotinas liberadas pelo seu personal.'),
  ('REGISTER_CARD_WORKOUT_TEXT_THIAGOIAZZETTI','it-IT','Acompanhe as rotinas liberadas pelo seu personal.'),
  ('REGISTER_CARD_WORKOUT_TEXT_THIAGOIAZZETTI','es-ES','Acompanhe as rotinas liberadas pelo seu personal.'),
  ('REGISTER_CARD_WORKOUT_TEXT_THIAGOIAZZETTI','ar-MA','Acompanhe as rotinas liberadas pelo seu personal.'),
  ('REGISTER_CARD_WORKOUT_TITLE_THIAGOIAZZETTI','pt-BR','Treinos e agenda'),
  ('REGISTER_CARD_WORKOUT_TITLE_THIAGOIAZZETTI','pt-PT','Treinos e agenda'),
  ('REGISTER_CARD_WORKOUT_TITLE_THIAGOIAZZETTI','en-US','Treinos e agenda'),
  ('REGISTER_CARD_WORKOUT_TITLE_THIAGOIAZZETTI','it-IT','Treinos e agenda'),
  ('REGISTER_CARD_WORKOUT_TITLE_THIAGOIAZZETTI','es-ES','Treinos e agenda'),
  ('REGISTER_CARD_WORKOUT_TITLE_THIAGOIAZZETTI','ar-MA','Treinos e agenda'),
  ('REGISTER_DETECTED_TENANT_THIAGOIAZZETTI','pt-BR','Cadastro vinculado detectado:'),
  ('REGISTER_DETECTED_TENANT_THIAGOIAZZETTI','pt-PT','Cadastro vinculado detectado:'),
  ('REGISTER_DETECTED_TENANT_THIAGOIAZZETTI','en-US','Cadastro vinculado detectado:'),
  ('REGISTER_DETECTED_TENANT_THIAGOIAZZETTI','it-IT','Cadastro vinculado detectado:'),
  ('REGISTER_DETECTED_TENANT_THIAGOIAZZETTI','es-ES','Cadastro vinculado detectado:'),
  ('REGISTER_DETECTED_TENANT_THIAGOIAZZETTI','ar-MA','Cadastro vinculado detectado:'),
  ('REGISTER_EMAIL_LABEL_THIAGOIAZZETTI','pt-BR','Email'),
  ('REGISTER_EMAIL_LABEL_THIAGOIAZZETTI','pt-PT','Email'),
  ('REGISTER_EMAIL_LABEL_THIAGOIAZZETTI','en-US','Email'),
  ('REGISTER_EMAIL_LABEL_THIAGOIAZZETTI','it-IT','Email'),
  ('REGISTER_EMAIL_LABEL_THIAGOIAZZETTI','es-ES','Email'),
  ('REGISTER_EMAIL_LABEL_THIAGOIAZZETTI','ar-MA','Email'),
  ('REGISTER_EMAIL_PLACEHOLDER_THIAGOIAZZETTI','pt-BR','voce@exemplo.com'),
  ('REGISTER_EMAIL_PLACEHOLDER_THIAGOIAZZETTI','pt-PT','voce@exemplo.com'),
  ('REGISTER_EMAIL_PLACEHOLDER_THIAGOIAZZETTI','en-US','voce@exemplo.com'),
  ('REGISTER_EMAIL_PLACEHOLDER_THIAGOIAZZETTI','it-IT','voce@exemplo.com'),
  ('REGISTER_EMAIL_PLACEHOLDER_THIAGOIAZZETTI','es-ES','voce@exemplo.com'),
  ('REGISTER_EMAIL_PLACEHOLDER_THIAGOIAZZETTI','ar-MA','voce@exemplo.com'),
  ('REGISTER_FULL_NAME_PLACEHOLDER_THIAGOIAZZETTI','pt-BR','Seu nome'),
  ('REGISTER_FULL_NAME_PLACEHOLDER_THIAGOIAZZETTI','pt-PT','Seu nome'),
  ('REGISTER_FULL_NAME_PLACEHOLDER_THIAGOIAZZETTI','en-US','Seu nome'),
  ('REGISTER_FULL_NAME_PLACEHOLDER_THIAGOIAZZETTI','it-IT','Seu nome'),
  ('REGISTER_FULL_NAME_PLACEHOLDER_THIAGOIAZZETTI','es-ES','Seu nome'),
  ('REGISTER_FULL_NAME_PLACEHOLDER_THIAGOIAZZETTI','ar-MA','Seu nome'),
  ('REGISTER_FULL_NAME_THIAGOIAZZETTI','pt-BR','Nome completo'),
  ('REGISTER_FULL_NAME_THIAGOIAZZETTI','pt-PT','Nome completo'),
  ('REGISTER_FULL_NAME_THIAGOIAZZETTI','en-US','Nome completo'),
  ('REGISTER_FULL_NAME_THIAGOIAZZETTI','it-IT','Nome completo'),
  ('REGISTER_FULL_NAME_THIAGOIAZZETTI','es-ES','Nome completo'),
  ('REGISTER_FULL_NAME_THIAGOIAZZETTI','ar-MA','Nome completo'),
  ('REGISTER_HEADING_THIAGOIAZZETTI','pt-BR','Cadastro'),
  ('REGISTER_HEADING_THIAGOIAZZETTI','pt-PT','Cadastro'),
  ('REGISTER_HEADING_THIAGOIAZZETTI','en-US','Cadastro'),
  ('REGISTER_HEADING_THIAGOIAZZETTI','it-IT','Cadastro'),
  ('REGISTER_HEADING_THIAGOIAZZETTI','es-ES','Cadastro'),
  ('REGISTER_HEADING_THIAGOIAZZETTI','ar-MA','Cadastro'),
  ('REGISTER_LINK_BACK_HOME_THIAGOIAZZETTI','pt-BR','Voltar para a pagina inicial'),
  ('REGISTER_LINK_BACK_HOME_THIAGOIAZZETTI','pt-PT','Voltar para a pagina inicial'),
  ('REGISTER_LINK_BACK_HOME_THIAGOIAZZETTI','en-US','Voltar para a pagina inicial'),
  ('REGISTER_LINK_BACK_HOME_THIAGOIAZZETTI','it-IT','Voltar para a pagina inicial'),
  ('REGISTER_LINK_BACK_HOME_THIAGOIAZZETTI','es-ES','Voltar para a pagina inicial'),
  ('REGISTER_LINK_BACK_HOME_THIAGOIAZZETTI','ar-MA','Voltar para a pagina inicial'),
  ('REGISTER_LINK_HAVE_ACCOUNT_THIAGOIAZZETTI','pt-BR','Ja tenho conta'),
  ('REGISTER_LINK_HAVE_ACCOUNT_THIAGOIAZZETTI','pt-PT','Ja tenho conta'),
  ('REGISTER_LINK_HAVE_ACCOUNT_THIAGOIAZZETTI','en-US','Ja tenho conta'),
  ('REGISTER_LINK_HAVE_ACCOUNT_THIAGOIAZZETTI','it-IT','Ja tenho conta'),
  ('REGISTER_LINK_HAVE_ACCOUNT_THIAGOIAZZETTI','es-ES','Ja tenho conta'),
  ('REGISTER_LINK_HAVE_ACCOUNT_THIAGOIAZZETTI','ar-MA','Ja tenho conta'),
  ('REGISTER_NEW_STUDENT_THIAGOIAZZETTI','pt-BR','Novo aluno'),
  ('REGISTER_NEW_STUDENT_THIAGOIAZZETTI','pt-PT','Novo aluno'),
  ('REGISTER_NEW_STUDENT_THIAGOIAZZETTI','en-US','Novo aluno'),
  ('REGISTER_NEW_STUDENT_THIAGOIAZZETTI','it-IT','Novo aluno'),
  ('REGISTER_NEW_STUDENT_THIAGOIAZZETTI','es-ES','Novo aluno'),
  ('REGISTER_NEW_STUDENT_THIAGOIAZZETTI','ar-MA','Novo aluno'),
  ('REGISTER_PASSWORD_LABEL_THIAGOIAZZETTI','pt-BR','Senha'),
  ('REGISTER_PASSWORD_LABEL_THIAGOIAZZETTI','pt-PT','Senha'),
  ('REGISTER_PASSWORD_LABEL_THIAGOIAZZETTI','en-US','Senha'),
  ('REGISTER_PASSWORD_LABEL_THIAGOIAZZETTI','it-IT','Senha'),
  ('REGISTER_PASSWORD_LABEL_THIAGOIAZZETTI','es-ES','Senha'),
  ('REGISTER_PASSWORD_LABEL_THIAGOIAZZETTI','ar-MA','Senha'),
  ('REGISTER_PASSWORD_PLACEHOLDER_THIAGOIAZZETTI','pt-BR','Crie uma senha'),
  ('REGISTER_PASSWORD_PLACEHOLDER_THIAGOIAZZETTI','pt-PT','Crie uma senha'),
  ('REGISTER_PASSWORD_PLACEHOLDER_THIAGOIAZZETTI','en-US','Crie uma senha'),
  ('REGISTER_PASSWORD_PLACEHOLDER_THIAGOIAZZETTI','it-IT','Crie uma senha'),
  ('REGISTER_PASSWORD_PLACEHOLDER_THIAGOIAZZETTI','es-ES','Crie uma senha'),
  ('REGISTER_PASSWORD_PLACEHOLDER_THIAGOIAZZETTI','ar-MA','Crie uma senha'),
  ('REGISTER_PERSONAL_ID_LABEL_THIAGOIAZZETTI','pt-BR','ID do personal'),
  ('REGISTER_PERSONAL_ID_LABEL_THIAGOIAZZETTI','pt-PT','ID do personal'),
  ('REGISTER_PERSONAL_ID_LABEL_THIAGOIAZZETTI','en-US','ID do personal'),
  ('REGISTER_PERSONAL_ID_LABEL_THIAGOIAZZETTI','it-IT','ID do personal'),
  ('REGISTER_PERSONAL_ID_LABEL_THIAGOIAZZETTI','es-ES','ID do personal'),
  ('REGISTER_PERSONAL_ID_LABEL_THIAGOIAZZETTI','ar-MA','ID do personal'),
  ('REGISTER_PERSONAL_ID_PLACEHOLDER_THIAGOIAZZETTI','pt-BR','UUID do personal'),
  ('REGISTER_PERSONAL_ID_PLACEHOLDER_THIAGOIAZZETTI','pt-PT','UUID do personal'),
  ('REGISTER_PERSONAL_ID_PLACEHOLDER_THIAGOIAZZETTI','en-US','UUID do personal'),
  ('REGISTER_PERSONAL_ID_PLACEHOLDER_THIAGOIAZZETTI','it-IT','UUID do personal'),
  ('REGISTER_PERSONAL_ID_PLACEHOLDER_THIAGOIAZZETTI','es-ES','UUID do personal'),
  ('REGISTER_PERSONAL_ID_PLACEHOLDER_THIAGOIAZZETTI','ar-MA','UUID do personal'),
  ('REGISTER_PHONE_LABEL_THIAGOIAZZETTI','pt-BR','Telefone'),
  ('REGISTER_PHONE_LABEL_THIAGOIAZZETTI','pt-PT','Telefone'),
  ('REGISTER_PHONE_LABEL_THIAGOIAZZETTI','en-US','Telefone'),
  ('REGISTER_PHONE_LABEL_THIAGOIAZZETTI','it-IT','Telefone'),
  ('REGISTER_PHONE_LABEL_THIAGOIAZZETTI','es-ES','Telefone'),
  ('REGISTER_PHONE_LABEL_THIAGOIAZZETTI','ar-MA','Telefone'),
  ('REGISTER_PHONE_PLACEHOLDER_THIAGOIAZZETTI','pt-BR','(11) 99999-9999'),
  ('REGISTER_PHONE_PLACEHOLDER_THIAGOIAZZETTI','pt-PT','(11) 99999-9999'),
  ('REGISTER_PHONE_PLACEHOLDER_THIAGOIAZZETTI','en-US','(11) 99999-9999'),
  ('REGISTER_PHONE_PLACEHOLDER_THIAGOIAZZETTI','it-IT','(11) 99999-9999'),
  ('REGISTER_PHONE_PLACEHOLDER_THIAGOIAZZETTI','es-ES','(11) 99999-9999'),
  ('REGISTER_PHONE_PLACEHOLDER_THIAGOIAZZETTI','ar-MA','(11) 99999-9999')
) AS t(chave, codigo_idioma, valor)
JOIN sistemas s ON s.codigo = 'website'
JOIN idiomas i ON i.codigo = t.codigo_idioma
ON CONFLICT (chave, sistema_id, idioma_id)
DO UPDATE SET valor = EXCLUDED.valor, atualizado_em = NOW();
