-- ============================================================
-- Seed: ThiagoIazzetti – Dashboard, Admin, Diet, Chat, Workout
-- Keys added in translation session (all pages completed)
-- ============================================================

INSERT INTO traducoes (chave, valor, sistema_id, idioma_id)
SELECT t.chave, t.valor, s.id, i.id
FROM (VALUES
  -- ─── AdminDashboardPage tabs ───────────────────────────────
  ('ADMIN_TAB_OVERVIEW_THIAGOIAZZETTI',          'pt-BR', 'Visão Geral'),
  ('ADMIN_TAB_STUDENTS_THIAGOIAZZETTI',          'pt-BR', 'Alunos'),
  ('ADMIN_TAB_PLANS_THIAGOIAZZETTI',             'pt-BR', 'Planos'),
  ('ADMIN_TAB_WORKOUTS_THIAGOIAZZETTI',          'pt-BR', 'Treinos'),
  ('ADMIN_TAB_COMMUNICATION_THIAGOIAZZETTI',     'pt-BR', 'Comunicação'),

  -- ─── AdminDashboardPage – overview ────────────────────────
  ('ADMIN_DASH_INACTIVE_LABEL_THIAGOIAZZETTI',   'pt-BR', 'alunos inativos nos últimos 5 dias'),
  ('ADMIN_DASH_BIRTHDAY_LABEL_THIAGOIAZZETTI',   'pt-BR', 'aniversariantes essa semana'),
  ('ADMIN_DASH_BILLING_LABEL_THIAGOIAZZETTI',    'pt-BR', 'vencimentos essa semana'),

  -- ─── AdminDashboardPage – student form ────────────────────
  ('ADMIN_DASH_NEW_STUDENT_TITLE_THIAGOIAZZETTI','pt-BR', 'Novo Aluno'),
  ('ADMIN_DASH_FULL_NAME_THIAGOIAZZETTI',        'pt-BR', 'Nome completo'),
  ('ADMIN_DASH_EMAIL_THIAGOIAZZETTI',            'pt-BR', 'Email'),
  ('ADMIN_DASH_PHONE_THIAGOIAZZETTI',            'pt-BR', 'Telefone'),
  ('ADMIN_DASH_BIRTH_DATE_THIAGOIAZZETTI',       'pt-BR', 'Data de nascimento'),
  ('ADMIN_DASH_PLAN_DUE_DATE_THIAGOIAZZETTI',   'pt-BR', 'Vencimento do plano'),
  ('ADMIN_DASH_CREATE_STUDENT_BTN_THIAGOIAZZETTI','pt-BR','Criar Aluno'),

  -- ─── AdminDashboardPage – student list ────────────────────
  ('ADMIN_DASH_STUDENTS_TITLE_THIAGOIAZZETTI',   'pt-BR', 'Alunos Cadastrados'),
  ('ADMIN_DASH_STATUS_ACTIVE_THIAGOIAZZETTI',    'pt-BR', 'ativos'),
  ('ADMIN_DASH_STATUS_INACTIVE_THIAGOIAZZETTI',  'pt-BR', 'inativos'),
  ('ADMIN_DASH_STATUS_PENDING_THIAGOIAZZETTI',   'pt-BR', 'pendentes'),
  ('ADMIN_DASH_COL_NAME_THIAGOIAZZETTI',         'pt-BR', 'Nome'),
  ('ADMIN_DASH_COL_PLAN_THIAGOIAZZETTI',         'pt-BR', 'Plano'),
  ('ADMIN_DASH_COL_DUE_THIAGOIAZZETTI',          'pt-BR', 'Vencimento'),
  ('ADMIN_DASH_COL_STATUS_THIAGOIAZZETTI',       'pt-BR', 'Status'),
  ('ADMIN_DASH_COL_ACTIONS_THIAGOIAZZETTI',      'pt-BR', 'Ações'),
  ('ADMIN_DASH_ACTIVE_BADGE_THIAGOIAZZETTI',     'pt-BR', 'Ativo'),
  ('ADMIN_DASH_INACTIVE_BADGE_THIAGOIAZZETTI',   'pt-BR', 'Inativo'),
  ('ADMIN_DASH_EDIT_BTN_THIAGOIAZZETTI',         'pt-BR', 'Editar'),
  ('ADMIN_DASH_SAVE_BTN_THIAGOIAZZETTI',         'pt-BR', 'Salvar'),
  ('ADMIN_DASH_CANCEL_BTN_THIAGOIAZZETTI',       'pt-BR', 'Cancelar'),
  ('ADMIN_DASH_ACTIVE_CHECKBOX_THIAGOIAZZETTI',  'pt-BR', 'Ativo'),

  -- ─── AdminDashboardPage – plans tab ───────────────────────
  ('ADMIN_DASH_CREATE_PLAN_TITLE_THIAGOIAZZETTI','pt-BR', 'Criar Plano'),
  ('ADMIN_DASH_PLAN_NAME_LABEL_THIAGOIAZZETTI',  'pt-BR', 'Nome do Plano'),
  ('ADMIN_DASH_PLAN_PRICE_LABEL_THIAGOIAZZETTI', 'pt-BR', 'Preço'),
  ('ADMIN_DASH_PLAN_DESC_LABEL_THIAGOIAZZETTI',  'pt-BR', 'Descrição'),
  ('ADMIN_DASH_SAVE_PLAN_BTN_THIAGOIAZZETTI',    'pt-BR', 'Salvar Plano'),
  ('ADMIN_DASH_PLANS_LIST_TITLE_THIAGOIAZZETTI', 'pt-BR', 'Planos Cadastrados'),
  ('ADMIN_DASH_NO_PLANS_THIAGOIAZZETTI',         'pt-BR', 'Nenhum plano cadastrado'),
  ('ADMIN_DASH_PREMIUM_PLAN_THIAGOIAZZETTI',     'pt-BR', 'Plano Premium'),
  ('ADMIN_DASH_PER_MONTH_THIAGOIAZZETTI',        'pt-BR', '/mês'),

  -- ─── AdminChatPanel ────────────────────────────────────────
  ('ADMIN_CHAT_CONVERSATIONS_THIAGOIAZZETTI',    'pt-BR', 'Conversas'),
  ('ADMIN_CHAT_NO_ACTIVE_STUDENTS_THIAGOIAZZETTI','pt-BR','Nenhum aluno ativo'),
  ('ADMIN_CHAT_SELECT_STUDENT_THIAGOIAZZETTI',   'pt-BR', 'Selecione um aluno'),
  ('ADMIN_CHAT_NO_MESSAGES_THIAGOIAZZETTI',      'pt-BR', 'Nenhuma mensagem'),
  ('ADMIN_CHAT_WORKOUT_LABEL_THIAGOIAZZETTI',    'pt-BR', 'Treino encaminhado'),
  ('ADMIN_CHAT_DIET_LABEL_THIAGOIAZZETTI',       'pt-BR', 'Dieta encaminhada'),
  ('ADMIN_CHAT_SEND_WORKOUT_BTN_THIAGOIAZZETTI', 'pt-BR', 'Enviar treino'),
  ('ADMIN_CHAT_SEND_DIET_BTN_THIAGOIAZZETTI',    'pt-BR', 'Enviar dieta'),
  ('ADMIN_CHAT_INPUT_PLACEHOLDER_THIAGOIAZZETTI','pt-BR', 'Digite uma mensagem...'),

  -- ─── AdminDietPage ─────────────────────────────────────────
  ('DIET_HEADER_BADGE_THIAGOIAZZETTI',           'pt-BR', 'Nutrição'),
  ('DIET_HEADER_TITLE_THIAGOIAZZETTI',           'pt-BR', 'Gerenciar Dietas'),
  ('DIET_FORM_TITLE_THIAGOIAZZETTI',             'pt-BR', 'Nova Dieta'),
  ('DIET_FORM_EDIT_TITLE_THIAGOIAZZETTI',        'pt-BR', 'Editar Dieta'),
  ('DIET_FORM_SELECT_STUDENT_THIAGOIAZZETTI',    'pt-BR', 'Selecione um aluno'),
  ('DIET_FORM_DIET_TITLE_LABEL_THIAGOIAZZETTI',  'pt-BR', 'Título da Dieta'),
  ('DIET_FORM_WEEKDAY_LABEL_THIAGOIAZZETTI',     'pt-BR', 'Dia da Semana'),
  ('DIET_FORM_CONTENT_LABEL_THIAGOIAZZETTI',     'pt-BR', 'Conteúdo da Dieta'),
  ('DIET_FORM_SAVING_THIAGOIAZZETTI',            'pt-BR', 'Salvando...'),
  ('DIET_FORM_SAVE_BTN_THIAGOIAZZETTI',          'pt-BR', 'Salvar Dieta'),
  ('DIET_FORM_UPDATE_BTN_THIAGOIAZZETTI',        'pt-BR', 'Atualizar Dieta'),
  ('DIET_FORM_CANCEL_BTN_THIAGOIAZZETTI',        'pt-BR', 'Cancelar'),
  ('DIET_LIST_TITLE_THIAGOIAZZETTI',             'pt-BR', 'Dietas Cadastradas'),
  ('DIET_NO_DIETS_THIAGOIAZZETTI',               'pt-BR', 'Nenhuma dieta cadastrada'),
  ('DIET_EDIT_BTN_THIAGOIAZZETTI',               'pt-BR', 'Editar'),
  ('DIET_DELETE_BTN_THIAGOIAZZETTI',             'pt-BR', 'Excluir'),
  ('DIET_EXPORT_PDF_BTN_THIAGOIAZZETTI',         'pt-BR', 'Exportar PDF'),
  ('DIET_WEEKDAY_MON_THIAGOIAZZETTI',            'pt-BR', 'Segunda-feira'),
  ('DIET_WEEKDAY_TUE_THIAGOIAZZETTI',            'pt-BR', 'Terça-feira'),
  ('DIET_WEEKDAY_WED_THIAGOIAZZETTI',            'pt-BR', 'Quarta-feira'),
  ('DIET_WEEKDAY_THU_THIAGOIAZZETTI',            'pt-BR', 'Quinta-feira'),
  ('DIET_WEEKDAY_FRI_THIAGOIAZZETTI',            'pt-BR', 'Sexta-feira'),
  ('DIET_WEEKDAY_SAT_THIAGOIAZZETTI',            'pt-BR', 'Sábado'),
  ('DIET_WEEKDAY_SUN_THIAGOIAZZETTI',            'pt-BR', 'Domingo'),

  -- ─── ClientDashboardPage ───────────────────────────────────
  ('CLIENT_DASH_BADGE_THIAGOIAZZETTI',           'pt-BR', 'Minha Área'),
  ('CLIENT_DASH_TITLE_THIAGOIAZZETTI',           'pt-BR', 'Dashboard'),
  ('CLIENT_DASH_SUBTITLE_THIAGOIAZZETTI',        'pt-BR', 'Acompanhe seu progresso'),
  ('CLIENT_DASH_LOADING_THIAGOIAZZETTI',         'pt-BR', 'Carregando...'),
  ('CLIENT_DASH_PLAN_BADGE_THIAGOIAZZETTI',      'pt-BR', 'Plano Ativo'),
  ('CLIENT_DASH_PLAN_TITLE_THIAGOIAZZETTI',      'pt-BR', 'Seu Plano'),
  ('CLIENT_DASH_PLAN_DESC_THIAGOIAZZETTI',       'pt-BR', 'Acompanhe os detalhes do seu plano'),
  ('CLIENT_DASH_MONTHLY_BADGE_THIAGOIAZZETTI',   'pt-BR', 'Mensal'),
  ('CLIENT_DASH_AGENDA_BADGE_THIAGOIAZZETTI',    'pt-BR', 'Agenda'),
  ('CLIENT_DASH_PROXIMAS_ROTINAS_THIAGOIAZZETTI','pt-BR', 'Próximas Rotinas'),
  ('CLIENT_DASH_NO_ROUTINES_THIAGOIAZZETTI',     'pt-BR', 'Nenhuma rotina agendada'),
  ('CLIENT_DASH_CREATED_AT_THIAGOIAZZETTI',      'pt-BR', 'Criado em'),
  ('CLIENT_DASH_STATUS_ATUAL_THIAGOIAZZETTI',    'pt-BR', 'Status Atual'),
  ('CLIENT_DASH_STATUS_PLANO_THIAGOIAZZETTI',    'pt-BR', 'Plano'),
  ('CLIENT_DASH_STATUS_VENCIMENTO_THIAGOIAZZETTI','pt-BR','Vencimento de Referência'),
  ('CLIENT_DASH_NAO_INFORMADO_THIAGOIAZZETTI',   'pt-BR', 'Não informado'),
  ('CLIENT_DASH_NO_WORKOUTS_THIAGOIAZZETTI',     'pt-BR', 'Nenhum treino disponível'),

  -- ─── ClientChatPanel ───────────────────────────────────────
  ('CLIENT_CHAT_TITLE_THIAGOIAZZETTI',           'pt-BR', 'Chat com Personal'),
  ('CLIENT_CHAT_OPEN_THIAGOIAZZETTI',            'pt-BR', 'Abrir Chat'),
  ('CLIENT_CHAT_CLOSE_THIAGOIAZZETTI',           'pt-BR', 'Fechar Chat'),
  ('CLIENT_CHAT_NO_MESSAGES_THIAGOIAZZETTI',     'pt-BR', 'Nenhuma mensagem'),
  ('CLIENT_CHAT_WORKOUT_FWD_THIAGOIAZZETTI',     'pt-BR', 'Treino encaminhado'),
  ('CLIENT_CHAT_DIET_FWD_THIAGOIAZZETTI',        'pt-BR', 'Dieta encaminhada'),
  ('CLIENT_CHAT_INPUT_PLACEHOLDER_THIAGOIAZZETTI','pt-BR','Digite uma mensagem...'),

  -- ─── ClientWorkoutsPage ────────────────────────────────────
  ('CLIENT_WORKOUTS_BADGE_THIAGOIAZZETTI',       'pt-BR', 'Meus Treinos'),
  ('CLIENT_WORKOUTS_TITLE_THIAGOIAZZETTI',       'pt-BR', 'Meus Planos de Treino'),
  ('CLIENT_WORKOUTS_SUBTITLE_THIAGOIAZZETTI',    'pt-BR', 'Acompanhe seus treinos'),
  ('CLIENT_WORKOUTS_LOADING_THIAGOIAZZETTI',     'pt-BR', 'Carregando treinos...'),
  ('CLIENT_WORKOUTS_NO_PLANS_THIAGOIAZZETTI',    'pt-BR', 'Nenhum plano de treino disponível'),
  ('CLIENT_WORKOUTS_PLAN_BADGE_THIAGOIAZZETTI',  'pt-BR', 'Plano de Treino'),
  ('CLIENT_WORKOUTS_OBJECTIVE_FALLBACK_THIAGOIAZZETTI','pt-BR','Sem objetivo definido'),
  ('CLIENT_WORKOUTS_EXERCISES_COUNT_THIAGOIAZZETTI','pt-BR','exercícios'),
  ('CLIENT_WORKOUTS_SESSIONS_COUNT_THIAGOIAZZETTI','pt-BR','sessões'),
  ('CLIENT_WORKOUTS_ACTIVE_THIAGOIAZZETTI',      'pt-BR', 'Ativo'),
  ('CLIENT_WORKOUTS_INACTIVE_THIAGOIAZZETTI',    'pt-BR', 'Inativo'),
  ('CLIENT_WORKOUTS_UPCOMING_TITLE_THIAGOIAZZETTI','pt-BR','Próximas Sessões'),
  ('CLIENT_WORKOUTS_NO_SESSIONS_THIAGOIAZZETTI', 'pt-BR', 'Nenhuma sessão agendada'),
  ('CLIENT_WORKOUTS_LOAD_ERROR_THIAGOIAZZETTI',  'pt-BR', 'Erro ao carregar treinos'),

  -- ─── StudentsPage ──────────────────────────────────────────
  ('STUDENTS_TITLE_THIAGOIAZZETTI',              'pt-BR', 'Alunos'),
  ('STUDENTS_SUBTITLE_THIAGOIAZZETTI',           'pt-BR', 'Lista de alunos'),
  ('STUDENTS_FOCUS_LABEL_THIAGOIAZZETTI',        'pt-BR', 'Foco:'),
  ('STUDENTS_PROGRESS_LABEL_THIAGOIAZZETTI',     'pt-BR', 'Progresso:'),

  -- ─── WorkoutBuilderPage ────────────────────────────────────
  ('WORKOUT_BUILDER_EDIT_TITLE_THIAGOIAZZETTI',  'pt-BR', 'Editar Treino'),
  ('WORKOUT_BUILDER_CREATE_TITLE_THIAGOIAZZETTI','pt-BR', 'Criar Novo Treino'),
  ('WORKOUT_BUILDER_SELECT_STUDENT_ERROR_THIAGOIAZZETTI','pt-BR','Selecione um aluno para vincular o treino'),
  ('WORKOUT_BUILDER_LINKED_TO_THIAGOIAZZETTI',   'pt-BR', 'Treino será vinculado a'),
  ('WORKOUT_BUILDER_NO_STUDENT_THIAGOIAZZETTI',  'pt-BR', 'Nenhum aluno selecionado'),
  ('WORKOUT_BUILDER_ALUNO_LABEL_THIAGOIAZZETTI', 'pt-BR', 'Aluno'),
  ('WORKOUT_BUILDER_TITLE_LABEL_THIAGOIAZZETTI', 'pt-BR', 'Título do treino'),
  ('WORKOUT_BUILDER_OBJECTIVE_LABEL_THIAGOIAZZETTI','pt-BR','Objetivo'),
  ('WORKOUT_BUILDER_PHASE_LABEL_THIAGOIAZZETTI', 'pt-BR', 'Fase de Treino'),
  ('WORKOUT_BUILDER_EXERCISES_HEADER_THIAGOIAZZETTI','pt-BR','Exercícios'),
  ('WORKOUT_BUILDER_CLICK_TO_ADD_THIAGOIAZZETTI','pt-BR', 'Clique em Adicionar exercício para começar'),
  ('WORKOUT_BUILDER_ADD_EXERCISE_BTN_THIAGOIAZZETTI','pt-BR','Adicionar Exercício'),
  ('WORKOUT_BUILDER_SAVE_BTN_THIAGOIAZZETTI',    'pt-BR', 'Salvar Treino'),
  ('WORKOUT_BUILDER_UPDATE_BTN_THIAGOIAZZETTI',  'pt-BR', 'Atualizar Treino'),
  ('WORKOUT_BUILDER_CANCEL_EDIT_THIAGOIAZZETTI', 'pt-BR', 'Cancelar edição'),
  ('WORKOUT_BUILDER_TEMPLATES_TITLE_THIAGOIAZZETTI','pt-BR','Templates de Treino'),
  ('WORKOUT_BUILDER_TEMPLATES_SUBTITLE_THIAGOIAZZETTI','pt-BR','Use templates pré-definidos como base e customize conforme necessário'),
  ('WORKOUT_BUILDER_EXERCISES_COUNT_THIAGOIAZZETTI','pt-BR','exercícios'),
  ('WORKOUT_BUILDER_PHASE_BADGE_THIAGOIAZZETTI', 'pt-BR', 'Fase'),
  ('WORKOUT_BUILDER_USE_TEMPLATE_BTN_THIAGOIAZZETTI','pt-BR','Usar Template'),
  ('WORKOUT_BUILDER_STUDENT_WORKOUTS_TITLE_THIAGOIAZZETTI','pt-BR','Treinos do Aluno'),
  ('WORKOUT_BUILDER_LOAD_ERROR_THIAGOIAZZETTI',  'pt-BR', 'Erro ao carregar dados'),

  -- ─── WorkoutBuilderPage – ScheduleSessionModal ─────────────
  ('WORKOUT_MODAL_SCHEDULE_BADGE_THIAGOIAZZETTI','pt-BR', 'Agendamento'),
  ('WORKOUT_MODAL_SUBTITLE_THIAGOIAZZETTI',      'pt-BR', 'Configure as sessões do treino'),
  ('WORKOUT_MODAL_REPLACE_CHECKBOX_THIAGOIAZZETTI','pt-BR','Substituir sessão existente'),
  ('WORKOUT_MODAL_LOADING_THIAGOIAZZETTI',       'pt-BR', 'Carregando agenda...'),
  ('WORKOUT_MODAL_SESSION_LABEL_THIAGOIAZZETTI', 'pt-BR', 'Sessão'),
  ('WORKOUT_MODAL_SESSION_TITLE_THIAGOIAZZETTI', 'pt-BR', 'Título da Sessão'),
  ('WORKOUT_MODAL_DAY_LABEL_THIAGOIAZZETTI',     'pt-BR', 'Dia'),
  ('WORKOUT_MODAL_START_LABEL_THIAGOIAZZETTI',   'pt-BR', 'Início'),
  ('WORKOUT_MODAL_END_LABEL_THIAGOIAZZETTI',     'pt-BR', 'Fim'),
  ('WORKOUT_MODAL_RECURRENCE_LABEL_THIAGOIAZZETTI','pt-BR','Recorrência'),
  ('WORKOUT_MODAL_UNTIL_LABEL_THIAGOIAZZETTI',   'pt-BR', 'Até'),
  ('WORKOUT_MODAL_SAVE_SESSION_BTN_THIAGOIAZZETTI','pt-BR','Salvar Sessão'),
  ('WORKOUT_MODAL_DELETE_SESSION_BTN_THIAGOIAZZETTI','pt-BR','Excluir Sessão'),
  ('WORKOUT_MODAL_ADD_SESSION_BTN_THIAGOIAZZETTI','pt-BR','Adicionar Sessão'),
  ('WORKOUT_MODAL_SCHEDULING_BTN_THIAGOIAZZETTI','pt-BR','Agendando...'),
  ('WORKOUT_MODAL_SAVE_SCHEDULE_BTN_THIAGOIAZZETTI','pt-BR','Salvar Agenda'),

  -- ─── ExerciseSelector ──────────────────────────────────────
  ('EXERCISE_SEL_TITLE_THIAGOIAZZETTI',          'pt-BR', 'Adicionar Exercício'),
  ('EXERCISE_SEL_MUSCLE_LABEL_THIAGOIAZZETTI',   'pt-BR', 'Grupo Muscular'),
  ('EXERCISE_SEL_EXERCISE_LABEL_THIAGOIAZZETTI', 'pt-BR', 'Exercício'),
  ('EXERCISE_SEL_SELECT_OPT_THIAGOIAZZETTI',     'pt-BR', 'Selecione um exercício'),
  ('EXERCISE_SEL_SETS_LABEL_THIAGOIAZZETTI',     'pt-BR', 'Séries'),
  ('EXERCISE_SEL_REPS_LABEL_THIAGOIAZZETTI',     'pt-BR', 'Repetições'),
  ('EXERCISE_SEL_REST_LABEL_THIAGOIAZZETTI',     'pt-BR', 'Descanso (s)'),
  ('EXERCISE_SEL_ADD_BTN_THIAGOIAZZETTI',        'pt-BR', 'Adicionar Exercício'),
  ('EXERCISE_SEL_CANCEL_BTN_THIAGOIAZZETTI',     'pt-BR', 'Cancelar'),
  ('WORKOUT_ITEM_REST_LABEL_THIAGOIAZZETTI',     'pt-BR', 's descanso'),

  -- ─── DashboardPage (admin overview) ───────────────────────
  ('DASH_TOTAL_STUDENTS_THIAGOIAZZETTI',         'pt-BR', 'Total de Alunos'),
  ('DASH_WORKOUTS_TODAY_THIAGOIAZZETTI',         'pt-BR', 'Treinos Hoje'),
  ('DASH_MONTHLY_REVENUE_THIAGOIAZZETTI',        'pt-BR', 'Faturamento Mês'),
  ('DASH_LOAD_EVOLUTION_TITLE_THIAGOIAZZETTI',   'pt-BR', 'Evolução de Cargas'),
  ('DASH_LOAD_EVOLUTION_SUBTITLE_THIAGOIAZZETTI','pt-BR', 'Performance média dos alunos nas últimas semanas.'),
  ('DASH_STUDENT_MANAGEMENT_TITLE_THIAGOIAZZETTI','pt-BR','Gestão de Alunos'),
  ('DASH_NEW_STUDENT_BUTTON_THIAGOIAZZETTI',     'pt-BR', 'Novo Aluno'),
  ('DASH_COL_STUDENT_THIAGOIAZZETTI',            'pt-BR', 'Aluno'),
  ('DASH_COL_PLAN_STATUS_THIAGOIAZZETTI',        'pt-BR', 'Status do Plano'),
  ('DASH_COL_START_THIAGOIAZZETTI',              'pt-BR', 'Início'),
  ('DASH_COL_ACTION_THIAGOIAZZETTI',             'pt-BR', 'Ação'),
  ('DASH_PRESCRIBE_WORKOUT_THIAGOIAZZETTI',      'pt-BR', 'Prescrever Treino')

) AS t(chave, codigo_idioma, valor)
JOIN sistemas s ON s.codigo = 'website'
JOIN idiomas i ON i.codigo = t.codigo_idioma
ON CONFLICT (chave, sistema_id, idioma_id)
DO UPDATE SET valor = EXCLUDED.valor, atualizado_em = NOW();

-- ============================================================
-- Complemento: Agenda e Dieta (chaves faltantes dos cards)
-- ============================================================
INSERT INTO traducoes (chave, valor, sistema_id, idioma_id)
SELECT
  k.chave,
  CASE
    WHEN i.codigo = 'en-US' THEN k.valor_en
    ELSE k.valor_pt
  END,
  s.id,
  i.id
FROM (VALUES
  ('ADMIN_AGENDA_LABEL_THIAGOIAZZETTI', 'Agenda', 'Schedule'),
  ('ADMIN_AGENDA_TITLE_THIAGOIAZZETTI', 'Agenda do Personal', 'Trainer Schedule'),
  ('ADMIN_AGENDA_SUBTITLE_THIAGOIAZZETTI', 'Calendario mensal, recorrencia semanal/mensal e presenca do aluno.', 'Monthly calendar, weekly/monthly recurrence, and student attendance.'),

  ('DIET_HEADER_SUBTITLE_THIAGOIAZZETTI', 'Crie um plano de dieta, vincule a um aluno e selecione um ou varios dias da semana. Cada plano fica isolado.', 'Create a diet plan, link it to a student, and select one or more weekdays. Each plan stays isolated.'),
  ('DIET_FORM_NEW_TITLE_THIAGOIAZZETTI', 'Nova dieta', 'New Diet'),
  ('DIET_FORM_STUDENT_LABEL_THIAGOIAZZETTI', 'Aluno', 'Student'),
  ('DIET_FORM_TITLE_LABEL_THIAGOIAZZETTI', 'Titulo', 'Title'),
  ('DIET_FORM_DESC_LABEL_THIAGOIAZZETTI', 'Descricao (opcional)', 'Description (optional)'),
  ('DIET_FORM_WEEKDAYS_LEGEND_THIAGOIAZZETTI', 'Dias da semana', 'Weekdays'),
  ('DIET_FORM_MEALPLAN_LABEL_THIAGOIAZZETTI', 'Cardapio para os dias selecionados', 'Meal plan for selected days'),
  ('DIET_FORM_CREATE_THIAGOIAZZETTI', 'Criar dieta', 'Create Diet'),
  ('DIET_FORM_SAVE_CHANGES_THIAGOIAZZETTI', 'Salvar alteracoes', 'Save Changes'),
  ('DIET_FORM_CANCEL_THIAGOIAZZETTI', 'Cancelar', 'Cancel'),
  ('DIET_FORM_ASSOC_STUDENT_THIAGOIAZZETTI', 'Plano sera associado ao aluno', 'Plan will be assigned to student'),
  ('DIET_LIST_EMPTY_THIAGOIAZZETTI', 'Nenhuma dieta cadastrada ainda.', 'No diets registered yet.'),
  ('DIET_LIST_LOADING_THIAGOIAZZETTI', 'Carregando...', 'Loading...'),
  ('DIET_LIST_EDIT_BUTTON_THIAGOIAZZETTI', 'Editar', 'Edit'),
  ('DIET_LIST_DELETE_BUTTON_THIAGOIAZZETTI', 'Excluir', 'Delete'),
  ('DIET_LIST_STUDENT_LABEL_THIAGOIAZZETTI', 'Aluno', 'Student'),
  ('DIET_LIST_STUDENT_DEFAULT_THIAGOIAZZETTI', 'Aluno', 'Student'),
  ('DIET_LOAD_ERROR_THIAGOIAZZETTI', 'Nao foi possivel carregar dietas', 'Could not load diets'),
  ('DIET_SAVE_ERROR_THIAGOIAZZETTI', 'Nao foi possivel salvar dieta', 'Could not save diet'),
  ('DIET_DELETE_ERROR_THIAGOIAZZETTI', 'Nao foi possivel remover dieta', 'Could not remove diet'),
  ('DIET_REQUIRED_FIELDS_THIAGOIAZZETTI', 'Aluno, titulo e cardapio sao obrigatorios', 'Student, title and meal plan are required'),
  ('DIET_SELECT_WEEKDAY_THIAGOIAZZETTI', 'Selecione pelo menos um dia da semana', 'Select at least one weekday'),
  ('DIET_CREATED_THIAGOIAZZETTI', 'Dieta criada', 'Diet created'),
  ('DIET_UPDATED_THIAGOIAZZETTI', 'Dieta atualizada', 'Diet updated'),
  ('DIET_DELETED_THIAGOIAZZETTI', 'Dieta removida', 'Diet removed'),
  ('DIET_FORM_TITLE_PLACEHOLDER_THIAGOIAZZETTI', 'Ex: Dieta de definicao', 'Ex: Cutting diet'),
  ('DIET_FORM_DESC_PLACEHOLDER_THIAGOIAZZETTI', 'Objetivo da dieta', 'Diet objective'),
  ('DIET_FORM_MEALPLAN_PLACEHOLDER_THIAGOIAZZETTI', 'Ex: Cafe da manha: ovos e aveia...', 'Ex: Breakfast: eggs and oats...')
) AS k(chave, valor_pt, valor_en)
JOIN sistemas s ON s.codigo = 'website'
JOIN idiomas i ON i.codigo IN ('pt-BR', 'pt-PT', 'en-US', 'it-IT', 'es-ES', 'ar-MA')
ON CONFLICT (chave, sistema_id, idioma_id)
DO UPDATE SET valor = EXCLUDED.valor, atualizado_em = NOW();

-- ============================================================
-- Complemento: placeholders e labels faltantes dos prints
-- ============================================================
INSERT INTO traducoes (chave, valor, sistema_id, idioma_id)
SELECT t.chave, t.valor, s.id, i.id
FROM (VALUES
  ('ADMIN_DASH_PLAN_NAME_PLACEHOLDER_THIAGOIAZZETTI', 'pt-BR', 'Ex: Plano Premium'),
  ('ADMIN_DASH_PLAN_DESC_PLACEHOLDER_THIAGOIAZZETTI', 'pt-BR', 'Descreva o plano...'),
  ('WORKOUT_BUILDER_TITLE_PLACEHOLDER_THIAGOIAZZETTI', 'pt-BR', 'Ex: Peito e Costas'),
  ('WORKOUT_BUILDER_OBJECTIVE_PLACEHOLDER_THIAGOIAZZETTI', 'pt-BR', 'Ex: Força e Hipertrofia'),
  ('WORKOUT_BUILDER_PHASE_HYPERTROPHY_THIAGOIAZZETTI', 'pt-BR', 'Hipertrofia'),
  ('WORKOUT_BUILDER_PHASE_STRENGTH_THIAGOIAZZETTI', 'pt-BR', 'Força'),
  ('WORKOUT_BUILDER_PHASE_CUTTING_THIAGOIAZZETTI', 'pt-BR', 'Definição'),
  ('WORKOUT_BUILDER_PHASE_ENDURANCE_THIAGOIAZZETTI', 'pt-BR', 'Resistência'),

  ('ADMIN_DASH_PLAN_NAME_PLACEHOLDER_THIAGOIAZZETTI', 'pt-PT', 'Ex: Plano Premium'),
  ('ADMIN_DASH_PLAN_DESC_PLACEHOLDER_THIAGOIAZZETTI', 'pt-PT', 'Descreva o plano...'),
  ('WORKOUT_BUILDER_TITLE_PLACEHOLDER_THIAGOIAZZETTI', 'pt-PT', 'Ex: Peito e Costas'),
  ('WORKOUT_BUILDER_OBJECTIVE_PLACEHOLDER_THIAGOIAZZETTI', 'pt-PT', 'Ex: Força e Hipertrofia'),
  ('WORKOUT_BUILDER_PHASE_HYPERTROPHY_THIAGOIAZZETTI', 'pt-PT', 'Hipertrofia'),
  ('WORKOUT_BUILDER_PHASE_STRENGTH_THIAGOIAZZETTI', 'pt-PT', 'Força'),
  ('WORKOUT_BUILDER_PHASE_CUTTING_THIAGOIAZZETTI', 'pt-PT', 'Definição'),
  ('WORKOUT_BUILDER_PHASE_ENDURANCE_THIAGOIAZZETTI', 'pt-PT', 'Resistência'),

  ('ADMIN_DASH_PLAN_NAME_PLACEHOLDER_THIAGOIAZZETTI', 'en-US', 'Ex: Premium Plan'),
  ('ADMIN_DASH_PLAN_DESC_PLACEHOLDER_THIAGOIAZZETTI', 'en-US', 'Describe the plan...'),
  ('WORKOUT_BUILDER_TITLE_PLACEHOLDER_THIAGOIAZZETTI', 'en-US', 'Ex: Chest and Back'),
  ('WORKOUT_BUILDER_OBJECTIVE_PLACEHOLDER_THIAGOIAZZETTI', 'en-US', 'Ex: Strength and Hypertrophy'),
  ('WORKOUT_BUILDER_PHASE_HYPERTROPHY_THIAGOIAZZETTI', 'en-US', 'Hypertrophy'),
  ('WORKOUT_BUILDER_PHASE_STRENGTH_THIAGOIAZZETTI', 'en-US', 'Strength'),
  ('WORKOUT_BUILDER_PHASE_CUTTING_THIAGOIAZZETTI', 'en-US', 'Cutting'),
  ('WORKOUT_BUILDER_PHASE_ENDURANCE_THIAGOIAZZETTI', 'en-US', 'Endurance'),

  ('ADMIN_DASH_PLAN_NAME_PLACEHOLDER_THIAGOIAZZETTI', 'it-IT', 'Es: Piano Premium'),
  ('ADMIN_DASH_PLAN_DESC_PLACEHOLDER_THIAGOIAZZETTI', 'it-IT', 'Descrivi il piano...'),
  ('WORKOUT_BUILDER_TITLE_PLACEHOLDER_THIAGOIAZZETTI', 'it-IT', 'Es: Petto e Schiena'),
  ('WORKOUT_BUILDER_OBJECTIVE_PLACEHOLDER_THIAGOIAZZETTI', 'it-IT', 'Es: Forza e Ipertrofia'),
  ('WORKOUT_BUILDER_PHASE_HYPERTROPHY_THIAGOIAZZETTI', 'it-IT', 'Ipertrofia'),
  ('WORKOUT_BUILDER_PHASE_STRENGTH_THIAGOIAZZETTI', 'it-IT', 'Forza'),
  ('WORKOUT_BUILDER_PHASE_CUTTING_THIAGOIAZZETTI', 'it-IT', 'Definizione'),
  ('WORKOUT_BUILDER_PHASE_ENDURANCE_THIAGOIAZZETTI', 'it-IT', 'Resistenza'),

  ('ADMIN_DASH_PLAN_NAME_PLACEHOLDER_THIAGOIAZZETTI', 'es-ES', 'Ej: Plan Premium'),
  ('ADMIN_DASH_PLAN_DESC_PLACEHOLDER_THIAGOIAZZETTI', 'es-ES', 'Describe el plan...'),
  ('WORKOUT_BUILDER_TITLE_PLACEHOLDER_THIAGOIAZZETTI', 'es-ES', 'Ej: Pecho y Espalda'),
  ('WORKOUT_BUILDER_OBJECTIVE_PLACEHOLDER_THIAGOIAZZETTI', 'es-ES', 'Ej: Fuerza e Hipertrofia'),
  ('WORKOUT_BUILDER_PHASE_HYPERTROPHY_THIAGOIAZZETTI', 'es-ES', 'Hipertrofia'),
  ('WORKOUT_BUILDER_PHASE_STRENGTH_THIAGOIAZZETTI', 'es-ES', 'Fuerza'),
  ('WORKOUT_BUILDER_PHASE_CUTTING_THIAGOIAZZETTI', 'es-ES', 'Definición'),
  ('WORKOUT_BUILDER_PHASE_ENDURANCE_THIAGOIAZZETTI', 'es-ES', 'Resistencia'),

  ('ADMIN_DASH_PLAN_NAME_PLACEHOLDER_THIAGOIAZZETTI', 'ar-MA', 'مثال: خطة بريميوم'),
  ('ADMIN_DASH_PLAN_DESC_PLACEHOLDER_THIAGOIAZZETTI', 'ar-MA', 'اكتب وصف الخطة...'),
  ('WORKOUT_BUILDER_TITLE_PLACEHOLDER_THIAGOIAZZETTI', 'ar-MA', 'مثال: صدر وظهر'),
  ('WORKOUT_BUILDER_OBJECTIVE_PLACEHOLDER_THIAGOIAZZETTI', 'ar-MA', 'مثال: قوة وتضخم'),
  ('WORKOUT_BUILDER_PHASE_HYPERTROPHY_THIAGOIAZZETTI', 'ar-MA', 'تضخم'),
  ('WORKOUT_BUILDER_PHASE_STRENGTH_THIAGOIAZZETTI', 'ar-MA', 'قوة'),
  ('WORKOUT_BUILDER_PHASE_CUTTING_THIAGOIAZZETTI', 'ar-MA', 'تنشيف'),
  ('WORKOUT_BUILDER_PHASE_ENDURANCE_THIAGOIAZZETTI', 'ar-MA', 'تحمل')
) AS t(chave, codigo_idioma, valor)
JOIN sistemas s ON s.codigo = 'website'
JOIN idiomas i ON i.codigo = t.codigo_idioma
ON CONFLICT (chave, sistema_id, idioma_id)
DO UPDATE SET valor = EXCLUDED.valor, atualizado_em = NOW();

-- ============================================================
-- Fix: en-US values for AdminDashboard keys that were inserted
-- with pt-BR fallback across all locales.
-- ============================================================
INSERT INTO traducoes (chave, valor, sistema_id, idioma_id)
SELECT t.chave, t.valor, s.id, i.id
FROM (VALUES
  ('ADMIN_CHAT_DIET_FORWARDED_THIAGOIAZZETTI', 'Diet forwarded'),
  ('ADMIN_CHAT_FORWARD_DIET_THIAGOIAZZETTI', 'Forward diet'),
  ('ADMIN_CHAT_FORWARD_WORKOUT_THIAGOIAZZETTI', 'Forward workout'),
  ('ADMIN_CHAT_NO_EMAIL_THIAGOIAZZETTI', 'no email'),
  ('ADMIN_CHAT_SEND_THIAGOIAZZETTI', 'Send'),
  ('ADMIN_CHAT_WORKOUT_FORWARDED_THIAGOIAZZETTI', 'Workout forwarded'),
  ('ADMIN_DASH_ACTIVE_STUDENT_THIAGOIAZZETTI', 'active student'),
  ('ADMIN_DASH_BIRTHDATE_THIAGOIAZZETTI', 'Birthdate'),
  ('ADMIN_DASH_CANCEL_THIAGOIAZZETTI', 'Cancel'),
  ('ADMIN_DASH_COL_DUE_DATE_THIAGOIAZZETTI', 'Due Date'),
  ('ADMIN_DASH_COL_MONTHLY_THIAGOIAZZETTI', 'Monthly Fee'),
  ('ADMIN_DASH_COL_PHONE_THIAGOIAZZETTI', 'Phone'),
  ('ADMIN_DASH_CREATE_PLAN_BUTTON_THIAGOIAZZETTI', 'Create Plan'),
  ('ADMIN_DASH_CREATE_PLAN_THIAGOIAZZETTI', 'Create new plan'),
  ('ADMIN_DASH_CREATE_STUDENT_BUTTON_THIAGOIAZZETTI', 'Create Student'),
  ('ADMIN_DASH_CREATE_STUDENT_THIAGOIAZZETTI', 'Register new student'),
  ('ADMIN_DASH_EDIT_STUDENT_THIAGOIAZZETTI', 'Edit student'),
  ('ADMIN_DASH_HEADER_LABEL_THIAGOIAZZETTI', 'Dashboard'),
  ('ADMIN_DASH_HEADER_TITLE_THIAGOIAZZETTI', 'Overview'),
  ('ADMIN_DASH_LOAD_ERROR_THIAGOIAZZETTI', 'Error loading dashboard'),
  ('ADMIN_DASH_LOADING_THIAGOIAZZETTI', 'Loading...'),
  ('ADMIN_DASH_NO_EMAIL_THIAGOIAZZETTI', 'no email'),
  ('ADMIN_DASH_NO_PLAN_THIAGOIAZZETTI', 'No plan'),
  ('ADMIN_DASH_NO_STUDENTS_THIAGOIAZZETTI', 'No students registered'),
  ('ADMIN_DASH_PLAN_CREATE_ERROR_THIAGOIAZZETTI', 'Error creating plan'),
  ('ADMIN_DASH_PLAN_CREATED_THIAGOIAZZETTI', 'Plan created successfully'),
  ('ADMIN_DASH_PLAN_NAME_REQUIRED_THIAGOIAZZETTI', 'Plan name is required'),
  ('ADMIN_DASH_SAVE_THIAGOIAZZETTI', 'Save'),
  ('ADMIN_DASH_STUDENT_CREATE_ERROR_THIAGOIAZZETTI', 'Error creating student'),
  ('ADMIN_DASH_STUDENT_CREATED_THIAGOIAZZETTI', 'Student created successfully'),
  ('ADMIN_DASH_STUDENT_PLAN_THIAGOIAZZETTI', 'Student plan'),
  ('ADMIN_DASH_STUDENT_REQUIRED_THIAGOIAZZETTI', 'Name and email are required'),
  ('ADMIN_DASH_STUDENT_UPDATE_ERROR_THIAGOIAZZETTI', 'Error updating student'),
  ('ADMIN_DASH_STUDENT_UPDATED_THIAGOIAZZETTI', 'Student updated'),
  ('ADMIN_DASH_STUDENTS_LIST_TITLE_THIAGOIAZZETTI', 'Registered students')
) AS t(chave, valor)
JOIN sistemas s ON s.codigo = 'website'
JOIN idiomas i ON i.codigo = 'en-US'
ON CONFLICT (chave, sistema_id, idioma_id)
DO UPDATE SET valor = EXCLUDED.valor, atualizado_em = NOW();

-- ============================================================
-- Complemento: chaves restantes do AdminDashboardPage
-- Base pt-BR replicada para os 6 idiomas (fallback consistente)
-- ============================================================
INSERT INTO traducoes (chave, valor, sistema_id, idioma_id)
SELECT k.chave, k.valor_ptbr, s.id, i.id
FROM (VALUES
  ('ADMIN_CHAT_DIET_FORWARDED_THIAGOIAZZETTI', 'Dieta encaminhada'),
  ('ADMIN_CHAT_FORWARD_DIET_THIAGOIAZZETTI', 'Encaminhar dieta'),
  ('ADMIN_CHAT_FORWARD_WORKOUT_THIAGOIAZZETTI', 'Encaminhar treino'),
  ('ADMIN_CHAT_NO_EMAIL_THIAGOIAZZETTI', 'sem e-mail'),
  ('ADMIN_CHAT_SEND_THIAGOIAZZETTI', 'Enviar'),
  ('ADMIN_CHAT_WORKOUT_FORWARDED_THIAGOIAZZETTI', 'Treino encaminhado'),
  ('ADMIN_DASH_ACTIVE_STUDENT_THIAGOIAZZETTI', 'aluno ativo'),
  ('ADMIN_DASH_BIRTHDATE_THIAGOIAZZETTI', 'Nascimento'),
  ('ADMIN_DASH_CANCEL_THIAGOIAZZETTI', 'Cancelar'),
  ('ADMIN_DASH_COL_DUE_DATE_THIAGOIAZZETTI', 'Vencimento'),
  ('ADMIN_DASH_COL_MONTHLY_THIAGOIAZZETTI', 'Mensalidade'),
  ('ADMIN_DASH_COL_PHONE_THIAGOIAZZETTI', 'Telefone'),
  ('ADMIN_DASH_CREATE_PLAN_BUTTON_THIAGOIAZZETTI', 'Criar Plano'),
  ('ADMIN_DASH_CREATE_PLAN_THIAGOIAZZETTI', 'Criar novo plano'),
  ('ADMIN_DASH_CREATE_STUDENT_BUTTON_THIAGOIAZZETTI', 'Criar Aluno'),
  ('ADMIN_DASH_CREATE_STUDENT_THIAGOIAZZETTI', 'Cadastrar novo aluno'),
  ('ADMIN_DASH_EDIT_STUDENT_THIAGOIAZZETTI', 'Editar aluno'),
  ('ADMIN_DASH_HEADER_LABEL_THIAGOIAZZETTI', 'Painel'),
  ('ADMIN_DASH_HEADER_TITLE_THIAGOIAZZETTI', 'Visao Geral'),
  ('ADMIN_DASH_LOAD_ERROR_THIAGOIAZZETTI', 'Erro ao carregar dashboard'),
  ('ADMIN_DASH_LOADING_THIAGOIAZZETTI', 'Carregando...'),
  ('ADMIN_DASH_NO_EMAIL_THIAGOIAZZETTI', 'sem e-mail'),
  ('ADMIN_DASH_NO_PLAN_THIAGOIAZZETTI', 'Sem plano'),
  ('ADMIN_DASH_NO_STUDENTS_THIAGOIAZZETTI', 'Nenhum aluno cadastrado'),
  ('ADMIN_DASH_PLAN_CREATE_ERROR_THIAGOIAZZETTI', 'Erro ao criar plano'),
  ('ADMIN_DASH_PLAN_CREATED_THIAGOIAZZETTI', 'Plano criado com sucesso'),
  ('ADMIN_DASH_PLAN_NAME_REQUIRED_THIAGOIAZZETTI', 'Nome do plano e obrigatorio'),
  ('ADMIN_DASH_SAVE_THIAGOIAZZETTI', 'Salvar'),
  ('ADMIN_DASH_STUDENT_CREATE_ERROR_THIAGOIAZZETTI', 'Erro ao criar aluno'),
  ('ADMIN_DASH_STUDENT_CREATED_THIAGOIAZZETTI', 'Aluno criado com sucesso'),
  ('ADMIN_DASH_STUDENT_PLAN_THIAGOIAZZETTI', 'Plano do aluno'),
  ('ADMIN_DASH_STUDENT_REQUIRED_THIAGOIAZZETTI', 'Nome e email sao obrigatorios'),
  ('ADMIN_DASH_STUDENT_UPDATE_ERROR_THIAGOIAZZETTI', 'Erro ao atualizar aluno'),
  ('ADMIN_DASH_STUDENT_UPDATED_THIAGOIAZZETTI', 'Aluno atualizado'),
  ('ADMIN_DASH_STUDENTS_LIST_TITLE_THIAGOIAZZETTI', 'Alunos cadastrados')
) AS k(chave, valor_ptbr)
JOIN sistemas s ON s.codigo = 'website'
JOIN idiomas i ON i.codigo IN ('pt-BR', 'pt-PT', 'en-US', 'it-IT', 'es-ES', 'ar-MA')
ON CONFLICT (chave, sistema_id, idioma_id)
DO UPDATE SET valor = EXCLUDED.valor, atualizado_em = NOW();

-- ============================================================
-- Complemento: chaves faltantes dos containers da Visao Geral
-- (cards estatisticos, status de pagamento, inativos e aniversariantes)
-- ============================================================
INSERT INTO traducoes (chave, valor, sistema_id, idioma_id)
SELECT t.chave, t.valor, s.id, i.id
FROM (VALUES
  -- pt-BR
  ('ADMIN_DASH_STAT_ACTIVE_STUDENTS_THIAGOIAZZETTI', 'pt-BR', 'Alunos ativos'),
  ('ADMIN_DASH_STAT_PLANS_THIAGOIAZZETTI',           'pt-BR', 'Planos'),
  ('ADMIN_DASH_STAT_INACTIVE_THIAGOIAZZETTI',        'pt-BR', 'Inativos (5+ dias)'),
  ('ADMIN_DASH_STAT_POTENTIAL_THIAGOIAZZETTI',       'pt-BR', 'Potencial mensal'),
  ('ADMIN_DASH_PAYMENT_STATUS_THIAGOIAZZETTI',       'pt-BR', 'Status de Pagamento'),
  ('ADMIN_DASH_PAID_THIAGOIAZZETTI',                 'pt-BR', 'pagos'),
  ('ADMIN_DASH_PENDING_THIAGOIAZZETTI',              'pt-BR', 'pendentes'),
  ('ADMIN_DASH_OVERDUE_THIAGOIAZZETTI',              'pt-BR', 'atrasados'),
  ('ADMIN_DASH_INACTIVE_STUDENTS_THIAGOIAZZETTI',    'pt-BR', 'Alunos inativos'),
  ('ADMIN_DASH_INACTIVE_LABEL_THIAGOIAZZETTI',       'pt-BR', 'inativo ha mais de 5 dias'),
  ('ADMIN_DASH_NO_INACTIVE_THIAGOIAZZETTI',          'pt-BR', 'Nenhum aluno inativo. Perfeito!'),
  ('ADMIN_DASH_BIRTHDAYS_THIAGOIAZZETTI',            'pt-BR', 'Aniversariantes'),
  ('ADMIN_DASH_NO_BIRTHDAYS_THIAGOIAZZETTI',         'pt-BR', 'Nenhum aniversario proximo nos proximos 7 dias.'),

  -- pt-PT
  ('ADMIN_DASH_STAT_ACTIVE_STUDENTS_THIAGOIAZZETTI', 'pt-PT', 'Alunos ativos'),
  ('ADMIN_DASH_STAT_PLANS_THIAGOIAZZETTI',           'pt-PT', 'Planos'),
  ('ADMIN_DASH_STAT_INACTIVE_THIAGOIAZZETTI',        'pt-PT', 'Inativos (5+ dias)'),
  ('ADMIN_DASH_STAT_POTENTIAL_THIAGOIAZZETTI',       'pt-PT', 'Potencial mensal'),
  ('ADMIN_DASH_PAYMENT_STATUS_THIAGOIAZZETTI',       'pt-PT', 'Estado de Pagamento'),
  ('ADMIN_DASH_PAID_THIAGOIAZZETTI',                 'pt-PT', 'pagos'),
  ('ADMIN_DASH_PENDING_THIAGOIAZZETTI',              'pt-PT', 'pendentes'),
  ('ADMIN_DASH_OVERDUE_THIAGOIAZZETTI',              'pt-PT', 'em atraso'),
  ('ADMIN_DASH_INACTIVE_STUDENTS_THIAGOIAZZETTI',    'pt-PT', 'Alunos inativos'),
  ('ADMIN_DASH_INACTIVE_LABEL_THIAGOIAZZETTI',       'pt-PT', 'inativo ha mais de 5 dias'),
  ('ADMIN_DASH_NO_INACTIVE_THIAGOIAZZETTI',          'pt-PT', 'Nenhum aluno inativo. Perfeito!'),
  ('ADMIN_DASH_BIRTHDAYS_THIAGOIAZZETTI',            'pt-PT', 'Aniversariantes'),
  ('ADMIN_DASH_NO_BIRTHDAYS_THIAGOIAZZETTI',         'pt-PT', 'Nenhum aniversario proximo nos proximos 7 dias.'),

  -- en-US
  ('ADMIN_DASH_STAT_ACTIVE_STUDENTS_THIAGOIAZZETTI', 'en-US', 'Active students'),
  ('ADMIN_DASH_STAT_PLANS_THIAGOIAZZETTI',           'en-US', 'Plans'),
  ('ADMIN_DASH_STAT_INACTIVE_THIAGOIAZZETTI',        'en-US', 'Inactive (5+ days)'),
  ('ADMIN_DASH_STAT_POTENTIAL_THIAGOIAZZETTI',       'en-US', 'Monthly potential'),
  ('ADMIN_DASH_PAYMENT_STATUS_THIAGOIAZZETTI',       'en-US', 'Payment Status'),
  ('ADMIN_DASH_PAID_THIAGOIAZZETTI',                 'en-US', 'paid'),
  ('ADMIN_DASH_PENDING_THIAGOIAZZETTI',              'en-US', 'pending'),
  ('ADMIN_DASH_OVERDUE_THIAGOIAZZETTI',              'en-US', 'overdue'),
  ('ADMIN_DASH_INACTIVE_STUDENTS_THIAGOIAZZETTI',    'en-US', 'Inactive students'),
  ('ADMIN_DASH_INACTIVE_LABEL_THIAGOIAZZETTI',       'en-US', 'inactive students in the last 5 days'),
  ('ADMIN_DASH_NO_INACTIVE_THIAGOIAZZETTI',          'en-US', 'No inactive students. Perfect!'),
  ('ADMIN_DASH_BIRTHDAYS_THIAGOIAZZETTI',            'en-US', 'Birthdays'),
  ('ADMIN_DASH_NO_BIRTHDAYS_THIAGOIAZZETTI',         'en-US', 'No upcoming birthdays in the next 7 days.'),

  -- it-IT
  ('ADMIN_DASH_STAT_ACTIVE_STUDENTS_THIAGOIAZZETTI', 'it-IT', 'Studenti attivi'),
  ('ADMIN_DASH_STAT_PLANS_THIAGOIAZZETTI',           'it-IT', 'Piani'),
  ('ADMIN_DASH_STAT_INACTIVE_THIAGOIAZZETTI',        'it-IT', 'Inattivi (5+ giorni)'),
  ('ADMIN_DASH_STAT_POTENTIAL_THIAGOIAZZETTI',       'it-IT', 'Potenziale mensile'),
  ('ADMIN_DASH_PAYMENT_STATUS_THIAGOIAZZETTI',       'it-IT', 'Stato Pagamenti'),
  ('ADMIN_DASH_PAID_THIAGOIAZZETTI',                 'it-IT', 'pagati'),
  ('ADMIN_DASH_PENDING_THIAGOIAZZETTI',              'it-IT', 'in attesa'),
  ('ADMIN_DASH_OVERDUE_THIAGOIAZZETTI',              'it-IT', 'in ritardo'),
  ('ADMIN_DASH_INACTIVE_STUDENTS_THIAGOIAZZETTI',    'it-IT', 'Studenti inattivi'),
  ('ADMIN_DASH_INACTIVE_LABEL_THIAGOIAZZETTI',       'it-IT', 'inattivi negli ultimi 5 giorni'),
  ('ADMIN_DASH_NO_INACTIVE_THIAGOIAZZETTI',          'it-IT', 'Nessuno studente inattivo. Perfetto!'),
  ('ADMIN_DASH_BIRTHDAYS_THIAGOIAZZETTI',            'it-IT', 'Compleanni'),
  ('ADMIN_DASH_NO_BIRTHDAYS_THIAGOIAZZETTI',         'it-IT', 'Nessun compleanno nei prossimi 7 giorni.'),

  -- es-ES
  ('ADMIN_DASH_STAT_ACTIVE_STUDENTS_THIAGOIAZZETTI', 'es-ES', 'Alumnos activos'),
  ('ADMIN_DASH_STAT_PLANS_THIAGOIAZZETTI',           'es-ES', 'Planes'),
  ('ADMIN_DASH_STAT_INACTIVE_THIAGOIAZZETTI',        'es-ES', 'Inactivos (5+ dias)'),
  ('ADMIN_DASH_STAT_POTENTIAL_THIAGOIAZZETTI',       'es-ES', 'Potencial mensual'),
  ('ADMIN_DASH_PAYMENT_STATUS_THIAGOIAZZETTI',       'es-ES', 'Estado de Pago'),
  ('ADMIN_DASH_PAID_THIAGOIAZZETTI',                 'es-ES', 'pagados'),
  ('ADMIN_DASH_PENDING_THIAGOIAZZETTI',              'es-ES', 'pendientes'),
  ('ADMIN_DASH_OVERDUE_THIAGOIAZZETTI',              'es-ES', 'atrasados'),
  ('ADMIN_DASH_INACTIVE_STUDENTS_THIAGOIAZZETTI',    'es-ES', 'Alumnos inactivos'),
  ('ADMIN_DASH_INACTIVE_LABEL_THIAGOIAZZETTI',       'es-ES', 'inactivos en los ultimos 5 dias'),
  ('ADMIN_DASH_NO_INACTIVE_THIAGOIAZZETTI',          'es-ES', 'Ningun alumno inactivo. Perfecto!'),
  ('ADMIN_DASH_BIRTHDAYS_THIAGOIAZZETTI',            'es-ES', 'Cumpleanos'),
  ('ADMIN_DASH_NO_BIRTHDAYS_THIAGOIAZZETTI',         'es-ES', 'No hay cumpleanos proximos en los siguientes 7 dias.'),

  -- ar-MA
  ('ADMIN_DASH_STAT_ACTIVE_STUDENTS_THIAGOIAZZETTI', 'ar-MA', 'الطلاب النشطون'),
  ('ADMIN_DASH_STAT_PLANS_THIAGOIAZZETTI',           'ar-MA', 'الخطط'),
  ('ADMIN_DASH_STAT_INACTIVE_THIAGOIAZZETTI',        'ar-MA', 'غير النشطين (5+ ايام)'),
  ('ADMIN_DASH_STAT_POTENTIAL_THIAGOIAZZETTI',       'ar-MA', 'الامكانية الشهرية'),
  ('ADMIN_DASH_PAYMENT_STATUS_THIAGOIAZZETTI',       'ar-MA', 'حالة الدفع'),
  ('ADMIN_DASH_PAID_THIAGOIAZZETTI',                 'ar-MA', 'مدفوعة'),
  ('ADMIN_DASH_PENDING_THIAGOIAZZETTI',              'ar-MA', 'قيد الانتظار'),
  ('ADMIN_DASH_OVERDUE_THIAGOIAZZETTI',              'ar-MA', 'متاخرة'),
  ('ADMIN_DASH_INACTIVE_STUDENTS_THIAGOIAZZETTI',    'ar-MA', 'الطلاب غير النشطين'),
  ('ADMIN_DASH_INACTIVE_LABEL_THIAGOIAZZETTI',       'ar-MA', 'غير نشط خلال اخر 5 ايام'),
  ('ADMIN_DASH_NO_INACTIVE_THIAGOIAZZETTI',          'ar-MA', 'لا يوجد طلاب غير نشطين. ممتاز!'),
  ('ADMIN_DASH_BIRTHDAYS_THIAGOIAZZETTI',            'ar-MA', 'اعياد الميلاد'),
  ('ADMIN_DASH_NO_BIRTHDAYS_THIAGOIAZZETTI',         'ar-MA', 'لا توجد اعياد ميلاد قريبة خلال 7 ايام القادمة.')
) AS t(chave, codigo_idioma, valor)
JOIN sistemas s ON s.codigo = 'website'
JOIN idiomas i ON i.codigo = t.codigo_idioma
ON CONFLICT (chave, sistema_id, idioma_id)
DO UPDATE SET valor = EXCLUDED.valor, atualizado_em = NOW();

-- ──────────────────────────────────────────────────────────────
-- Same keys for pt-PT (same Portuguese, minor differences)
-- ──────────────────────────────────────────────────────────────
INSERT INTO traducoes (chave, valor, sistema_id, idioma_id)
SELECT t.chave, t.valor, s.id, i.id
FROM (VALUES
  ('ADMIN_TAB_OVERVIEW_THIAGOIAZZETTI',          'pt-PT', 'Visão Geral'),
  ('ADMIN_TAB_STUDENTS_THIAGOIAZZETTI',          'pt-PT', 'Alunos'),
  ('ADMIN_TAB_PLANS_THIAGOIAZZETTI',             'pt-PT', 'Planos'),
  ('ADMIN_TAB_WORKOUTS_THIAGOIAZZETTI',          'pt-PT', 'Treinos'),
  ('ADMIN_TAB_COMMUNICATION_THIAGOIAZZETTI',     'pt-PT', 'Comunicação'),
  ('ADMIN_DASH_INACTIVE_LABEL_THIAGOIAZZETTI',   'pt-PT', 'alunos inativos nos últimos 5 dias'),
  ('ADMIN_DASH_BIRTHDAY_LABEL_THIAGOIAZZETTI',   'pt-PT', 'aniversariantes esta semana'),
  ('ADMIN_DASH_BILLING_LABEL_THIAGOIAZZETTI',    'pt-PT', 'vencimentos esta semana'),
  ('ADMIN_DASH_NEW_STUDENT_TITLE_THIAGOIAZZETTI','pt-PT', 'Novo Aluno'),
  ('ADMIN_DASH_FULL_NAME_THIAGOIAZZETTI',        'pt-PT', 'Nome completo'),
  ('ADMIN_DASH_EMAIL_THIAGOIAZZETTI',            'pt-PT', 'Email'),
  ('ADMIN_DASH_PHONE_THIAGOIAZZETTI',            'pt-PT', 'Telefone'),
  ('ADMIN_DASH_BIRTH_DATE_THIAGOIAZZETTI',       'pt-PT', 'Data de nascimento'),
  ('ADMIN_DASH_PLAN_DUE_DATE_THIAGOIAZZETTI',   'pt-PT', 'Vencimento do plano'),
  ('ADMIN_DASH_CREATE_STUDENT_BTN_THIAGOIAZZETTI','pt-PT','Criar Aluno'),
  ('ADMIN_DASH_STUDENTS_TITLE_THIAGOIAZZETTI',   'pt-PT', 'Alunos Registados'),
  ('ADMIN_DASH_STATUS_ACTIVE_THIAGOIAZZETTI',    'pt-PT', 'ativos'),
  ('ADMIN_DASH_STATUS_INACTIVE_THIAGOIAZZETTI',  'pt-PT', 'inativos'),
  ('ADMIN_DASH_STATUS_PENDING_THIAGOIAZZETTI',   'pt-PT', 'pendentes'),
  ('ADMIN_DASH_COL_NAME_THIAGOIAZZETTI',         'pt-PT', 'Nome'),
  ('ADMIN_DASH_COL_PLAN_THIAGOIAZZETTI',         'pt-PT', 'Plano'),
  ('ADMIN_DASH_COL_DUE_THIAGOIAZZETTI',          'pt-PT', 'Vencimento'),
  ('ADMIN_DASH_COL_STATUS_THIAGOIAZZETTI',       'pt-PT', 'Estado'),
  ('ADMIN_DASH_COL_ACTIONS_THIAGOIAZZETTI',      'pt-PT', 'Ações'),
  ('ADMIN_DASH_ACTIVE_BADGE_THIAGOIAZZETTI',     'pt-PT', 'Ativo'),
  ('ADMIN_DASH_INACTIVE_BADGE_THIAGOIAZZETTI',   'pt-PT', 'Inativo'),
  ('ADMIN_DASH_EDIT_BTN_THIAGOIAZZETTI',         'pt-PT', 'Editar'),
  ('ADMIN_DASH_SAVE_BTN_THIAGOIAZZETTI',         'pt-PT', 'Guardar'),
  ('ADMIN_DASH_CANCEL_BTN_THIAGOIAZZETTI',       'pt-PT', 'Cancelar'),
  ('ADMIN_DASH_ACTIVE_CHECKBOX_THIAGOIAZZETTI',  'pt-PT', 'Ativo'),
  ('ADMIN_DASH_CREATE_PLAN_TITLE_THIAGOIAZZETTI','pt-PT', 'Criar Plano'),
  ('ADMIN_DASH_PLAN_NAME_LABEL_THIAGOIAZZETTI',  'pt-PT', 'Nome do Plano'),
  ('ADMIN_DASH_PLAN_PRICE_LABEL_THIAGOIAZZETTI', 'pt-PT', 'Preço'),
  ('ADMIN_DASH_PLAN_DESC_LABEL_THIAGOIAZZETTI',  'pt-PT', 'Descrição'),
  ('ADMIN_DASH_SAVE_PLAN_BTN_THIAGOIAZZETTI',    'pt-PT', 'Guardar Plano'),
  ('ADMIN_DASH_PLANS_LIST_TITLE_THIAGOIAZZETTI', 'pt-PT', 'Planos Registados'),
  ('ADMIN_DASH_NO_PLANS_THIAGOIAZZETTI',         'pt-PT', 'Nenhum plano registado'),
  ('ADMIN_DASH_PREMIUM_PLAN_THIAGOIAZZETTI',     'pt-PT', 'Plano Premium'),
  ('ADMIN_DASH_PER_MONTH_THIAGOIAZZETTI',        'pt-PT', '/mês'),
  ('ADMIN_CHAT_CONVERSATIONS_THIAGOIAZZETTI',    'pt-PT', 'Conversas'),
  ('ADMIN_CHAT_NO_ACTIVE_STUDENTS_THIAGOIAZZETTI','pt-PT','Nenhum aluno ativo'),
  ('ADMIN_CHAT_SELECT_STUDENT_THIAGOIAZZETTI',   'pt-PT', 'Selecione um aluno'),
  ('ADMIN_CHAT_NO_MESSAGES_THIAGOIAZZETTI',      'pt-PT', 'Nenhuma mensagem'),
  ('ADMIN_CHAT_WORKOUT_LABEL_THIAGOIAZZETTI',    'pt-PT', 'Treino encaminhado'),
  ('ADMIN_CHAT_DIET_LABEL_THIAGOIAZZETTI',       'pt-PT', 'Dieta encaminhada'),
  ('ADMIN_CHAT_SEND_WORKOUT_BTN_THIAGOIAZZETTI', 'pt-PT', 'Enviar treino'),
  ('ADMIN_CHAT_SEND_DIET_BTN_THIAGOIAZZETTI',    'pt-PT', 'Enviar dieta'),
  ('ADMIN_CHAT_INPUT_PLACEHOLDER_THIAGOIAZZETTI','pt-PT', 'Escreva uma mensagem...'),
  ('DIET_HEADER_BADGE_THIAGOIAZZETTI',           'pt-PT', 'Nutrição'),
  ('DIET_HEADER_TITLE_THIAGOIAZZETTI',           'pt-PT', 'Gerir Dietas'),
  ('DIET_FORM_TITLE_THIAGOIAZZETTI',             'pt-PT', 'Nova Dieta'),
  ('DIET_FORM_EDIT_TITLE_THIAGOIAZZETTI',        'pt-PT', 'Editar Dieta'),
  ('DIET_FORM_SELECT_STUDENT_THIAGOIAZZETTI',    'pt-PT', 'Selecione um aluno'),
  ('DIET_FORM_DIET_TITLE_LABEL_THIAGOIAZZETTI',  'pt-PT', 'Título da Dieta'),
  ('DIET_FORM_WEEKDAY_LABEL_THIAGOIAZZETTI',     'pt-PT', 'Dia da Semana'),
  ('DIET_FORM_CONTENT_LABEL_THIAGOIAZZETTI',     'pt-PT', 'Conteúdo da Dieta'),
  ('DIET_FORM_SAVING_THIAGOIAZZETTI',            'pt-PT', 'A guardar...'),
  ('DIET_FORM_SAVE_BTN_THIAGOIAZZETTI',          'pt-PT', 'Guardar Dieta'),
  ('DIET_FORM_UPDATE_BTN_THIAGOIAZZETTI',        'pt-PT', 'Atualizar Dieta'),
  ('DIET_FORM_CANCEL_BTN_THIAGOIAZZETTI',        'pt-PT', 'Cancelar'),
  ('DIET_LIST_TITLE_THIAGOIAZZETTI',             'pt-PT', 'Dietas Registadas'),
  ('DIET_NO_DIETS_THIAGOIAZZETTI',               'pt-PT', 'Nenhuma dieta registada'),
  ('DIET_EDIT_BTN_THIAGOIAZZETTI',               'pt-PT', 'Editar'),
  ('DIET_DELETE_BTN_THIAGOIAZZETTI',             'pt-PT', 'Eliminar'),
  ('DIET_EXPORT_PDF_BTN_THIAGOIAZZETTI',         'pt-PT', 'Exportar PDF'),
  ('DIET_WEEKDAY_MON_THIAGOIAZZETTI',            'pt-PT', 'Segunda-feira'),
  ('DIET_WEEKDAY_TUE_THIAGOIAZZETTI',            'pt-PT', 'Terça-feira'),
  ('DIET_WEEKDAY_WED_THIAGOIAZZETTI',            'pt-PT', 'Quarta-feira'),
  ('DIET_WEEKDAY_THU_THIAGOIAZZETTI',            'pt-PT', 'Quinta-feira'),
  ('DIET_WEEKDAY_FRI_THIAGOIAZZETTI',            'pt-PT', 'Sexta-feira'),
  ('DIET_WEEKDAY_SAT_THIAGOIAZZETTI',            'pt-PT', 'Sábado'),
  ('DIET_WEEKDAY_SUN_THIAGOIAZZETTI',            'pt-PT', 'Domingo'),
  ('CLIENT_DASH_BADGE_THIAGOIAZZETTI',           'pt-PT', 'Minha Área'),
  ('CLIENT_DASH_TITLE_THIAGOIAZZETTI',           'pt-PT', 'Dashboard'),
  ('CLIENT_DASH_SUBTITLE_THIAGOIAZZETTI',        'pt-PT', 'Acompanhe o seu progresso'),
  ('CLIENT_DASH_LOADING_THIAGOIAZZETTI',         'pt-PT', 'A carregar...'),
  ('CLIENT_DASH_PLAN_BADGE_THIAGOIAZZETTI',      'pt-PT', 'Plano Ativo'),
  ('CLIENT_DASH_PLAN_TITLE_THIAGOIAZZETTI',      'pt-PT', 'O Seu Plano'),
  ('CLIENT_DASH_PLAN_DESC_THIAGOIAZZETTI',       'pt-PT', 'Acompanhe os detalhes do seu plano'),
  ('CLIENT_DASH_MONTHLY_BADGE_THIAGOIAZZETTI',   'pt-PT', 'Mensal'),
  ('CLIENT_DASH_AGENDA_BADGE_THIAGOIAZZETTI',    'pt-PT', 'Agenda'),
  ('CLIENT_DASH_PROXIMAS_ROTINAS_THIAGOIAZZETTI','pt-PT', 'Próximas Rotinas'),
  ('CLIENT_DASH_NO_ROUTINES_THIAGOIAZZETTI',     'pt-PT', 'Nenhuma rotina agendada'),
  ('CLIENT_DASH_CREATED_AT_THIAGOIAZZETTI',      'pt-PT', 'Criado em'),
  ('CLIENT_DASH_STATUS_ATUAL_THIAGOIAZZETTI',    'pt-PT', 'Estado Atual'),
  ('CLIENT_DASH_STATUS_PLANO_THIAGOIAZZETTI',    'pt-PT', 'Plano'),
  ('CLIENT_DASH_STATUS_VENCIMENTO_THIAGOIAZZETTI','pt-PT','Vencimento de Referência'),
  ('CLIENT_DASH_NAO_INFORMADO_THIAGOIAZZETTI',   'pt-PT', 'Não informado'),
  ('CLIENT_DASH_NO_WORKOUTS_THIAGOIAZZETTI',     'pt-PT', 'Nenhum treino disponível'),
  ('CLIENT_CHAT_TITLE_THIAGOIAZZETTI',           'pt-PT', 'Chat com Personal'),
  ('CLIENT_CHAT_OPEN_THIAGOIAZZETTI',            'pt-PT', 'Abrir Chat'),
  ('CLIENT_CHAT_CLOSE_THIAGOIAZZETTI',           'pt-PT', 'Fechar Chat'),
  ('CLIENT_CHAT_NO_MESSAGES_THIAGOIAZZETTI',     'pt-PT', 'Nenhuma mensagem'),
  ('CLIENT_CHAT_WORKOUT_FWD_THIAGOIAZZETTI',     'pt-PT', 'Treino encaminhado'),
  ('CLIENT_CHAT_DIET_FWD_THIAGOIAZZETTI',        'pt-PT', 'Dieta encaminhada'),
  ('CLIENT_CHAT_INPUT_PLACEHOLDER_THIAGOIAZZETTI','pt-PT','Escreva uma mensagem...'),
  ('CLIENT_WORKOUTS_BADGE_THIAGOIAZZETTI',       'pt-PT', 'Os Meus Treinos'),
  ('CLIENT_WORKOUTS_TITLE_THIAGOIAZZETTI',       'pt-PT', 'Os Meus Planos de Treino'),
  ('CLIENT_WORKOUTS_SUBTITLE_THIAGOIAZZETTI',    'pt-PT', 'Acompanhe os seus treinos'),
  ('CLIENT_WORKOUTS_LOADING_THIAGOIAZZETTI',     'pt-PT', 'A carregar treinos...'),
  ('CLIENT_WORKOUTS_NO_PLANS_THIAGOIAZZETTI',    'pt-PT', 'Nenhum plano de treino disponível'),
  ('CLIENT_WORKOUTS_PLAN_BADGE_THIAGOIAZZETTI',  'pt-PT', 'Plano de Treino'),
  ('CLIENT_WORKOUTS_OBJECTIVE_FALLBACK_THIAGOIAZZETTI','pt-PT','Sem objetivo definido'),
  ('CLIENT_WORKOUTS_EXERCISES_COUNT_THIAGOIAZZETTI','pt-PT','exercícios'),
  ('CLIENT_WORKOUTS_SESSIONS_COUNT_THIAGOIAZZETTI','pt-PT','sessões'),
  ('CLIENT_WORKOUTS_ACTIVE_THIAGOIAZZETTI',      'pt-PT', 'Ativo'),
  ('CLIENT_WORKOUTS_INACTIVE_THIAGOIAZZETTI',    'pt-PT', 'Inativo'),
  ('CLIENT_WORKOUTS_UPCOMING_TITLE_THIAGOIAZZETTI','pt-PT','Próximas Sessões'),
  ('CLIENT_WORKOUTS_NO_SESSIONS_THIAGOIAZZETTI', 'pt-PT', 'Nenhuma sessão agendada'),
  ('CLIENT_WORKOUTS_LOAD_ERROR_THIAGOIAZZETTI',  'pt-PT', 'Erro ao carregar treinos'),
  ('STUDENTS_TITLE_THIAGOIAZZETTI',              'pt-PT', 'Alunos'),
  ('STUDENTS_SUBTITLE_THIAGOIAZZETTI',           'pt-PT', 'Lista de alunos'),
  ('STUDENTS_FOCUS_LABEL_THIAGOIAZZETTI',        'pt-PT', 'Foco:'),
  ('STUDENTS_PROGRESS_LABEL_THIAGOIAZZETTI',     'pt-PT', 'Progresso:'),
  ('WORKOUT_BUILDER_EDIT_TITLE_THIAGOIAZZETTI',  'pt-PT', 'Editar Treino'),
  ('WORKOUT_BUILDER_CREATE_TITLE_THIAGOIAZZETTI','pt-PT', 'Criar Novo Treino'),
  ('WORKOUT_BUILDER_SELECT_STUDENT_ERROR_THIAGOIAZZETTI','pt-PT','Selecione um aluno para vincular o treino'),
  ('WORKOUT_BUILDER_LINKED_TO_THIAGOIAZZETTI',   'pt-PT', 'Treino será vinculado a'),
  ('WORKOUT_BUILDER_NO_STUDENT_THIAGOIAZZETTI',  'pt-PT', 'Nenhum aluno selecionado'),
  ('WORKOUT_BUILDER_ALUNO_LABEL_THIAGOIAZZETTI', 'pt-PT', 'Aluno'),
  ('WORKOUT_BUILDER_TITLE_LABEL_THIAGOIAZZETTI', 'pt-PT', 'Título do treino'),
  ('WORKOUT_BUILDER_OBJECTIVE_LABEL_THIAGOIAZZETTI','pt-PT','Objetivo'),
  ('WORKOUT_BUILDER_PHASE_LABEL_THIAGOIAZZETTI', 'pt-PT', 'Fase de Treino'),
  ('WORKOUT_BUILDER_EXERCISES_HEADER_THIAGOIAZZETTI','pt-PT','Exercícios'),
  ('WORKOUT_BUILDER_CLICK_TO_ADD_THIAGOIAZZETTI','pt-PT', 'Clique em Adicionar exercício para começar'),
  ('WORKOUT_BUILDER_ADD_EXERCISE_BTN_THIAGOIAZZETTI','pt-PT','Adicionar Exercício'),
  ('WORKOUT_BUILDER_SAVE_BTN_THIAGOIAZZETTI',    'pt-PT', 'Guardar Treino'),
  ('WORKOUT_BUILDER_UPDATE_BTN_THIAGOIAZZETTI',  'pt-PT', 'Atualizar Treino'),
  ('WORKOUT_BUILDER_CANCEL_EDIT_THIAGOIAZZETTI', 'pt-PT', 'Cancelar edição'),
  ('WORKOUT_BUILDER_TEMPLATES_TITLE_THIAGOIAZZETTI','pt-PT','Templates de Treino'),
  ('WORKOUT_BUILDER_TEMPLATES_SUBTITLE_THIAGOIAZZETTI','pt-PT','Use templates pré-definidos como base e customize conforme necessário'),
  ('WORKOUT_BUILDER_EXERCISES_COUNT_THIAGOIAZZETTI','pt-PT','exercícios'),
  ('WORKOUT_BUILDER_PHASE_BADGE_THIAGOIAZZETTI', 'pt-PT', 'Fase'),
  ('WORKOUT_BUILDER_USE_TEMPLATE_BTN_THIAGOIAZZETTI','pt-PT','Usar Template'),
  ('WORKOUT_BUILDER_STUDENT_WORKOUTS_TITLE_THIAGOIAZZETTI','pt-PT','Treinos do Aluno'),
  ('WORKOUT_BUILDER_LOAD_ERROR_THIAGOIAZZETTI',  'pt-PT', 'Erro ao carregar dados'),
  ('WORKOUT_MODAL_SCHEDULE_BADGE_THIAGOIAZZETTI','pt-PT', 'Agendamento'),
  ('WORKOUT_MODAL_SUBTITLE_THIAGOIAZZETTI',      'pt-PT', 'Configure as sessões do treino'),
  ('WORKOUT_MODAL_REPLACE_CHECKBOX_THIAGOIAZZETTI','pt-PT','Substituir sessão existente'),
  ('WORKOUT_MODAL_LOADING_THIAGOIAZZETTI',       'pt-PT', 'A carregar agenda...'),
  ('WORKOUT_MODAL_SESSION_LABEL_THIAGOIAZZETTI', 'pt-PT', 'Sessão'),
  ('WORKOUT_MODAL_SESSION_TITLE_THIAGOIAZZETTI', 'pt-PT', 'Título da Sessão'),
  ('WORKOUT_MODAL_DAY_LABEL_THIAGOIAZZETTI',     'pt-PT', 'Dia'),
  ('WORKOUT_MODAL_START_LABEL_THIAGOIAZZETTI',   'pt-PT', 'Início'),
  ('WORKOUT_MODAL_END_LABEL_THIAGOIAZZETTI',     'pt-PT', 'Fim'),
  ('WORKOUT_MODAL_RECURRENCE_LABEL_THIAGOIAZZETTI','pt-PT','Recorrência'),
  ('WORKOUT_MODAL_UNTIL_LABEL_THIAGOIAZZETTI',   'pt-PT', 'Até'),
  ('WORKOUT_MODAL_SAVE_SESSION_BTN_THIAGOIAZZETTI','pt-PT','Guardar Sessão'),
  ('WORKOUT_MODAL_DELETE_SESSION_BTN_THIAGOIAZZETTI','pt-PT','Eliminar Sessão'),
  ('WORKOUT_MODAL_ADD_SESSION_BTN_THIAGOIAZZETTI','pt-PT','Adicionar Sessão'),
  ('WORKOUT_MODAL_SCHEDULING_BTN_THIAGOIAZZETTI','pt-PT','A agendar...'),
  ('WORKOUT_MODAL_SAVE_SCHEDULE_BTN_THIAGOIAZZETTI','pt-PT','Guardar Agenda'),
  ('EXERCISE_SEL_TITLE_THIAGOIAZZETTI',          'pt-PT', 'Adicionar Exercício'),
  ('EXERCISE_SEL_MUSCLE_LABEL_THIAGOIAZZETTI',   'pt-PT', 'Grupo Muscular'),
  ('EXERCISE_SEL_EXERCISE_LABEL_THIAGOIAZZETTI', 'pt-PT', 'Exercício'),
  ('EXERCISE_SEL_SELECT_OPT_THIAGOIAZZETTI',     'pt-PT', 'Selecione um exercício'),
  ('EXERCISE_SEL_SETS_LABEL_THIAGOIAZZETTI',     'pt-PT', 'Séries'),
  ('EXERCISE_SEL_REPS_LABEL_THIAGOIAZZETTI',     'pt-PT', 'Repetições'),
  ('EXERCISE_SEL_REST_LABEL_THIAGOIAZZETTI',     'pt-PT', 'Descanso (s)'),
  ('EXERCISE_SEL_ADD_BTN_THIAGOIAZZETTI',        'pt-PT', 'Adicionar Exercício'),
  ('EXERCISE_SEL_CANCEL_BTN_THIAGOIAZZETTI',     'pt-PT', 'Cancelar'),
  ('WORKOUT_ITEM_REST_LABEL_THIAGOIAZZETTI',     'pt-PT', 's descanso'),
  ('DASH_TOTAL_STUDENTS_THIAGOIAZZETTI',         'pt-PT', 'Total de Alunos'),
  ('DASH_WORKOUTS_TODAY_THIAGOIAZZETTI',         'pt-PT', 'Treinos Hoje'),
  ('DASH_MONTHLY_REVENUE_THIAGOIAZZETTI',        'pt-PT', 'Faturamento Mês'),
  ('DASH_LOAD_EVOLUTION_TITLE_THIAGOIAZZETTI',   'pt-PT', 'Evolução de Cargas'),
  ('DASH_LOAD_EVOLUTION_SUBTITLE_THIAGOIAZZETTI','pt-PT', 'Performance média dos alunos nas últimas semanas.'),
  ('DASH_STUDENT_MANAGEMENT_TITLE_THIAGOIAZZETTI','pt-PT','Gestão de Alunos'),
  ('DASH_NEW_STUDENT_BUTTON_THIAGOIAZZETTI',     'pt-PT', 'Novo Aluno'),
  ('DASH_COL_STUDENT_THIAGOIAZZETTI',            'pt-PT', 'Aluno'),
  ('DASH_COL_PLAN_STATUS_THIAGOIAZZETTI',        'pt-PT', 'Estado do Plano'),
  ('DASH_COL_START_THIAGOIAZZETTI',              'pt-PT', 'Início'),
  ('DASH_COL_ACTION_THIAGOIAZZETTI',             'pt-PT', 'Ação'),
  ('DASH_PRESCRIBE_WORKOUT_THIAGOIAZZETTI',      'pt-PT', 'Prescrever Treino')
) AS t(chave, codigo_idioma, valor)
JOIN sistemas s ON s.codigo = 'website'
JOIN idiomas i ON i.codigo = t.codigo_idioma
ON CONFLICT (chave, sistema_id, idioma_id)
DO UPDATE SET valor = EXCLUDED.valor, atualizado_em = NOW();

-- ──────────────────────────────────────────────────────────────
-- en-US translations
-- ──────────────────────────────────────────────────────────────
INSERT INTO traducoes (chave, valor, sistema_id, idioma_id)
SELECT t.chave, t.valor, s.id, i.id
FROM (VALUES
  ('ADMIN_TAB_OVERVIEW_THIAGOIAZZETTI',          'en-US', 'Overview'),
  ('ADMIN_TAB_STUDENTS_THIAGOIAZZETTI',          'en-US', 'Students'),
  ('ADMIN_TAB_PLANS_THIAGOIAZZETTI',             'en-US', 'Plans'),
  ('ADMIN_TAB_WORKOUTS_THIAGOIAZZETTI',          'en-US', 'Workouts'),
  ('ADMIN_TAB_COMMUNICATION_THIAGOIAZZETTI',     'en-US', 'Communication'),
  ('ADMIN_DASH_INACTIVE_LABEL_THIAGOIAZZETTI',   'en-US', 'inactive students in the last 5 days'),
  ('ADMIN_DASH_BIRTHDAY_LABEL_THIAGOIAZZETTI',   'en-US', 'birthdays this week'),
  ('ADMIN_DASH_BILLING_LABEL_THIAGOIAZZETTI',    'en-US', 'payments due this week'),
  ('ADMIN_DASH_NEW_STUDENT_TITLE_THIAGOIAZZETTI','en-US', 'New Student'),
  ('ADMIN_DASH_FULL_NAME_THIAGOIAZZETTI',        'en-US', 'Full name'),
  ('ADMIN_DASH_EMAIL_THIAGOIAZZETTI',            'en-US', 'Email'),
  ('ADMIN_DASH_PHONE_THIAGOIAZZETTI',            'en-US', 'Phone'),
  ('ADMIN_DASH_BIRTH_DATE_THIAGOIAZZETTI',       'en-US', 'Birth date'),
  ('ADMIN_DASH_PLAN_DUE_DATE_THIAGOIAZZETTI',   'en-US', 'Plan due date'),
  ('ADMIN_DASH_CREATE_STUDENT_BTN_THIAGOIAZZETTI','en-US','Create Student'),
  ('ADMIN_DASH_STUDENTS_TITLE_THIAGOIAZZETTI',   'en-US', 'Registered Students'),
  ('ADMIN_DASH_STATUS_ACTIVE_THIAGOIAZZETTI',    'en-US', 'active'),
  ('ADMIN_DASH_STATUS_INACTIVE_THIAGOIAZZETTI',  'en-US', 'inactive'),
  ('ADMIN_DASH_STATUS_PENDING_THIAGOIAZZETTI',   'en-US', 'pending'),
  ('ADMIN_DASH_COL_NAME_THIAGOIAZZETTI',         'en-US', 'Name'),
  ('ADMIN_DASH_COL_PLAN_THIAGOIAZZETTI',         'en-US', 'Plan'),
  ('ADMIN_DASH_COL_DUE_THIAGOIAZZETTI',          'en-US', 'Due Date'),
  ('ADMIN_DASH_COL_STATUS_THIAGOIAZZETTI',       'en-US', 'Status'),
  ('ADMIN_DASH_COL_ACTIONS_THIAGOIAZZETTI',      'en-US', 'Actions'),
  ('ADMIN_DASH_ACTIVE_BADGE_THIAGOIAZZETTI',     'en-US', 'Active'),
  ('ADMIN_DASH_INACTIVE_BADGE_THIAGOIAZZETTI',   'en-US', 'Inactive'),
  ('ADMIN_DASH_EDIT_BTN_THIAGOIAZZETTI',         'en-US', 'Edit'),
  ('ADMIN_DASH_SAVE_BTN_THIAGOIAZZETTI',         'en-US', 'Save'),
  ('ADMIN_DASH_CANCEL_BTN_THIAGOIAZZETTI',       'en-US', 'Cancel'),
  ('ADMIN_DASH_ACTIVE_CHECKBOX_THIAGOIAZZETTI',  'en-US', 'Active'),
  ('ADMIN_DASH_CREATE_PLAN_TITLE_THIAGOIAZZETTI','en-US', 'Create Plan'),
  ('ADMIN_DASH_PLAN_NAME_LABEL_THIAGOIAZZETTI',  'en-US', 'Plan Name'),
  ('ADMIN_DASH_PLAN_PRICE_LABEL_THIAGOIAZZETTI', 'en-US', 'Price'),
  ('ADMIN_DASH_PLAN_DESC_LABEL_THIAGOIAZZETTI',  'en-US', 'Description'),
  ('ADMIN_DASH_SAVE_PLAN_BTN_THIAGOIAZZETTI',    'en-US', 'Save Plan'),
  ('ADMIN_DASH_PLANS_LIST_TITLE_THIAGOIAZZETTI', 'en-US', 'Registered Plans'),
  ('ADMIN_DASH_NO_PLANS_THIAGOIAZZETTI',         'en-US', 'No plans registered'),
  ('ADMIN_DASH_PREMIUM_PLAN_THIAGOIAZZETTI',     'en-US', 'Premium Plan'),
  ('ADMIN_DASH_PER_MONTH_THIAGOIAZZETTI',        'en-US', '/month'),
  ('ADMIN_CHAT_CONVERSATIONS_THIAGOIAZZETTI',    'en-US', 'Conversations'),
  ('ADMIN_CHAT_NO_ACTIVE_STUDENTS_THIAGOIAZZETTI','en-US','No active students'),
  ('ADMIN_CHAT_SELECT_STUDENT_THIAGOIAZZETTI',   'en-US', 'Select a student'),
  ('ADMIN_CHAT_NO_MESSAGES_THIAGOIAZZETTI',      'en-US', 'No messages'),
  ('ADMIN_CHAT_WORKOUT_LABEL_THIAGOIAZZETTI',    'en-US', 'Workout forwarded'),
  ('ADMIN_CHAT_DIET_LABEL_THIAGOIAZZETTI',       'en-US', 'Diet forwarded'),
  ('ADMIN_CHAT_SEND_WORKOUT_BTN_THIAGOIAZZETTI', 'en-US', 'Send workout'),
  ('ADMIN_CHAT_SEND_DIET_BTN_THIAGOIAZZETTI',    'en-US', 'Send diet'),
  ('ADMIN_CHAT_INPUT_PLACEHOLDER_THIAGOIAZZETTI','en-US', 'Type a message...'),
  ('DIET_HEADER_BADGE_THIAGOIAZZETTI',           'en-US', 'Nutrition'),
  ('DIET_HEADER_TITLE_THIAGOIAZZETTI',           'en-US', 'Manage Diets'),
  ('DIET_FORM_TITLE_THIAGOIAZZETTI',             'en-US', 'New Diet'),
  ('DIET_FORM_EDIT_TITLE_THIAGOIAZZETTI',        'en-US', 'Edit Diet'),
  ('DIET_FORM_SELECT_STUDENT_THIAGOIAZZETTI',    'en-US', 'Select a student'),
  ('DIET_FORM_DIET_TITLE_LABEL_THIAGOIAZZETTI',  'en-US', 'Diet Title'),
  ('DIET_FORM_WEEKDAY_LABEL_THIAGOIAZZETTI',     'en-US', 'Day of Week'),
  ('DIET_FORM_CONTENT_LABEL_THIAGOIAZZETTI',     'en-US', 'Diet Content'),
  ('DIET_FORM_SAVING_THIAGOIAZZETTI',            'en-US', 'Saving...'),
  ('DIET_FORM_SAVE_BTN_THIAGOIAZZETTI',          'en-US', 'Save Diet'),
  ('DIET_FORM_UPDATE_BTN_THIAGOIAZZETTI',        'en-US', 'Update Diet'),
  ('DIET_FORM_CANCEL_BTN_THIAGOIAZZETTI',        'en-US', 'Cancel'),
  ('DIET_LIST_TITLE_THIAGOIAZZETTI',             'en-US', 'Registered Diets'),
  ('DIET_NO_DIETS_THIAGOIAZZETTI',               'en-US', 'No diets registered'),
  ('DIET_EDIT_BTN_THIAGOIAZZETTI',               'en-US', 'Edit'),
  ('DIET_DELETE_BTN_THIAGOIAZZETTI',             'en-US', 'Delete'),
  ('DIET_EXPORT_PDF_BTN_THIAGOIAZZETTI',         'en-US', 'Export PDF'),
  ('DIET_WEEKDAY_MON_THIAGOIAZZETTI',            'en-US', 'Monday'),
  ('DIET_WEEKDAY_TUE_THIAGOIAZZETTI',            'en-US', 'Tuesday'),
  ('DIET_WEEKDAY_WED_THIAGOIAZZETTI',            'en-US', 'Wednesday'),
  ('DIET_WEEKDAY_THU_THIAGOIAZZETTI',            'en-US', 'Thursday'),
  ('DIET_WEEKDAY_FRI_THIAGOIAZZETTI',            'en-US', 'Friday'),
  ('DIET_WEEKDAY_SAT_THIAGOIAZZETTI',            'en-US', 'Saturday'),
  ('DIET_WEEKDAY_SUN_THIAGOIAZZETTI',            'en-US', 'Sunday'),
  ('CLIENT_DASH_BADGE_THIAGOIAZZETTI',           'en-US', 'My Area'),
  ('CLIENT_DASH_TITLE_THIAGOIAZZETTI',           'en-US', 'Dashboard'),
  ('CLIENT_DASH_SUBTITLE_THIAGOIAZZETTI',        'en-US', 'Track your progress'),
  ('CLIENT_DASH_LOADING_THIAGOIAZZETTI',         'en-US', 'Loading...'),
  ('CLIENT_DASH_PLAN_BADGE_THIAGOIAZZETTI',      'en-US', 'Active Plan'),
  ('CLIENT_DASH_PLAN_TITLE_THIAGOIAZZETTI',      'en-US', 'Your Plan'),
  ('CLIENT_DASH_PLAN_DESC_THIAGOIAZZETTI',       'en-US', 'Track your plan details'),
  ('CLIENT_DASH_MONTHLY_BADGE_THIAGOIAZZETTI',   'en-US', 'Monthly'),
  ('CLIENT_DASH_AGENDA_BADGE_THIAGOIAZZETTI',    'en-US', 'Schedule'),
  ('CLIENT_DASH_PROXIMAS_ROTINAS_THIAGOIAZZETTI','en-US', 'Upcoming Routines'),
  ('CLIENT_DASH_NO_ROUTINES_THIAGOIAZZETTI',     'en-US', 'No routines scheduled'),
  ('CLIENT_DASH_CREATED_AT_THIAGOIAZZETTI',      'en-US', 'Created at'),
  ('CLIENT_DASH_STATUS_ATUAL_THIAGOIAZZETTI',    'en-US', 'Current Status'),
  ('CLIENT_DASH_STATUS_PLANO_THIAGOIAZZETTI',    'en-US', 'Plan'),
  ('CLIENT_DASH_STATUS_VENCIMENTO_THIAGOIAZZETTI','en-US','Reference Due Date'),
  ('CLIENT_DASH_NAO_INFORMADO_THIAGOIAZZETTI',   'en-US', 'Not provided'),
  ('CLIENT_DASH_NO_WORKOUTS_THIAGOIAZZETTI',     'en-US', 'No workouts available'),
  ('CLIENT_CHAT_TITLE_THIAGOIAZZETTI',           'en-US', 'Chat with Personal Trainer'),
  ('CLIENT_CHAT_OPEN_THIAGOIAZZETTI',            'en-US', 'Open Chat'),
  ('CLIENT_CHAT_CLOSE_THIAGOIAZZETTI',           'en-US', 'Close Chat'),
  ('CLIENT_CHAT_NO_MESSAGES_THIAGOIAZZETTI',     'en-US', 'No messages'),
  ('CLIENT_CHAT_WORKOUT_FWD_THIAGOIAZZETTI',     'en-US', 'Workout forwarded'),
  ('CLIENT_CHAT_DIET_FWD_THIAGOIAZZETTI',        'en-US', 'Diet forwarded'),
  ('CLIENT_CHAT_INPUT_PLACEHOLDER_THIAGOIAZZETTI','en-US','Type a message...'),
  ('CLIENT_WORKOUTS_BADGE_THIAGOIAZZETTI',       'en-US', 'My Workouts'),
  ('CLIENT_WORKOUTS_TITLE_THIAGOIAZZETTI',       'en-US', 'My Workout Plans'),
  ('CLIENT_WORKOUTS_SUBTITLE_THIAGOIAZZETTI',    'en-US', 'Track your workouts'),
  ('CLIENT_WORKOUTS_LOADING_THIAGOIAZZETTI',     'en-US', 'Loading workouts...'),
  ('CLIENT_WORKOUTS_NO_PLANS_THIAGOIAZZETTI',    'en-US', 'No workout plans available'),
  ('CLIENT_WORKOUTS_PLAN_BADGE_THIAGOIAZZETTI',  'en-US', 'Workout Plan'),
  ('CLIENT_WORKOUTS_OBJECTIVE_FALLBACK_THIAGOIAZZETTI','en-US','No objective defined'),
  ('CLIENT_WORKOUTS_EXERCISES_COUNT_THIAGOIAZZETTI','en-US','exercises'),
  ('CLIENT_WORKOUTS_SESSIONS_COUNT_THIAGOIAZZETTI','en-US','sessions'),
  ('CLIENT_WORKOUTS_ACTIVE_THIAGOIAZZETTI',      'en-US', 'Active'),
  ('CLIENT_WORKOUTS_INACTIVE_THIAGOIAZZETTI',    'en-US', 'Inactive'),
  ('CLIENT_WORKOUTS_UPCOMING_TITLE_THIAGOIAZZETTI','en-US','Upcoming Sessions'),
  ('CLIENT_WORKOUTS_NO_SESSIONS_THIAGOIAZZETTI', 'en-US', 'No sessions scheduled'),
  ('CLIENT_WORKOUTS_LOAD_ERROR_THIAGOIAZZETTI',  'en-US', 'Error loading workouts'),
  ('STUDENTS_TITLE_THIAGOIAZZETTI',              'en-US', 'Students'),
  ('STUDENTS_SUBTITLE_THIAGOIAZZETTI',           'en-US', 'Student list'),
  ('STUDENTS_FOCUS_LABEL_THIAGOIAZZETTI',        'en-US', 'Focus:'),
  ('STUDENTS_PROGRESS_LABEL_THIAGOIAZZETTI',     'en-US', 'Progress:'),
  ('WORKOUT_BUILDER_EDIT_TITLE_THIAGOIAZZETTI',  'en-US', 'Edit Workout'),
  ('WORKOUT_BUILDER_CREATE_TITLE_THIAGOIAZZETTI','en-US', 'Create New Workout'),
  ('WORKOUT_BUILDER_SELECT_STUDENT_ERROR_THIAGOIAZZETTI','en-US','Select a student to link the workout'),
  ('WORKOUT_BUILDER_LINKED_TO_THIAGOIAZZETTI',   'en-US', 'Workout will be linked to'),
  ('WORKOUT_BUILDER_NO_STUDENT_THIAGOIAZZETTI',  'en-US', 'No student selected'),
  ('WORKOUT_BUILDER_ALUNO_LABEL_THIAGOIAZZETTI', 'en-US', 'Student'),
  ('WORKOUT_BUILDER_TITLE_LABEL_THIAGOIAZZETTI', 'en-US', 'Workout title'),
  ('WORKOUT_BUILDER_OBJECTIVE_LABEL_THIAGOIAZZETTI','en-US','Objective'),
  ('WORKOUT_BUILDER_PHASE_LABEL_THIAGOIAZZETTI', 'en-US', 'Training Phase'),
  ('WORKOUT_BUILDER_EXERCISES_HEADER_THIAGOIAZZETTI','en-US','Exercises'),
  ('WORKOUT_BUILDER_CLICK_TO_ADD_THIAGOIAZZETTI','en-US', 'Click Add exercise to start'),
  ('WORKOUT_BUILDER_ADD_EXERCISE_BTN_THIAGOIAZZETTI','en-US','Add Exercise'),
  ('WORKOUT_BUILDER_SAVE_BTN_THIAGOIAZZETTI',    'en-US', 'Save Workout'),
  ('WORKOUT_BUILDER_UPDATE_BTN_THIAGOIAZZETTI',  'en-US', 'Update Workout'),
  ('WORKOUT_BUILDER_CANCEL_EDIT_THIAGOIAZZETTI', 'en-US', 'Cancel editing'),
  ('WORKOUT_BUILDER_TEMPLATES_TITLE_THIAGOIAZZETTI','en-US','Workout Templates'),
  ('WORKOUT_BUILDER_TEMPLATES_SUBTITLE_THIAGOIAZZETTI','en-US','Use pre-defined templates as a base and customize as needed'),
  ('WORKOUT_BUILDER_EXERCISES_COUNT_THIAGOIAZZETTI','en-US','exercises'),
  ('WORKOUT_BUILDER_PHASE_BADGE_THIAGOIAZZETTI', 'en-US', 'Phase'),
  ('WORKOUT_BUILDER_USE_TEMPLATE_BTN_THIAGOIAZZETTI','en-US','Use Template'),
  ('WORKOUT_BUILDER_STUDENT_WORKOUTS_TITLE_THIAGOIAZZETTI','en-US','Student Workouts'),
  ('WORKOUT_BUILDER_LOAD_ERROR_THIAGOIAZZETTI',  'en-US', 'Error loading data'),
  ('WORKOUT_MODAL_SCHEDULE_BADGE_THIAGOIAZZETTI','en-US', 'Scheduling'),
  ('WORKOUT_MODAL_SUBTITLE_THIAGOIAZZETTI',      'en-US', 'Configure workout sessions'),
  ('WORKOUT_MODAL_REPLACE_CHECKBOX_THIAGOIAZZETTI','en-US','Replace existing session'),
  ('WORKOUT_MODAL_LOADING_THIAGOIAZZETTI',       'en-US', 'Loading schedule...'),
  ('WORKOUT_MODAL_SESSION_LABEL_THIAGOIAZZETTI', 'en-US', 'Session'),
  ('WORKOUT_MODAL_SESSION_TITLE_THIAGOIAZZETTI', 'en-US', 'Session Title'),
  ('WORKOUT_MODAL_DAY_LABEL_THIAGOIAZZETTI',     'en-US', 'Day'),
  ('WORKOUT_MODAL_START_LABEL_THIAGOIAZZETTI',   'en-US', 'Start'),
  ('WORKOUT_MODAL_END_LABEL_THIAGOIAZZETTI',     'en-US', 'End'),
  ('WORKOUT_MODAL_RECURRENCE_LABEL_THIAGOIAZZETTI','en-US','Recurrence'),
  ('WORKOUT_MODAL_UNTIL_LABEL_THIAGOIAZZETTI',   'en-US', 'Until'),
  ('WORKOUT_MODAL_SAVE_SESSION_BTN_THIAGOIAZZETTI','en-US','Save Session'),
  ('WORKOUT_MODAL_DELETE_SESSION_BTN_THIAGOIAZZETTI','en-US','Delete Session'),
  ('WORKOUT_MODAL_ADD_SESSION_BTN_THIAGOIAZZETTI','en-US','Add Session'),
  ('WORKOUT_MODAL_SCHEDULING_BTN_THIAGOIAZZETTI','en-US','Scheduling...'),
  ('WORKOUT_MODAL_SAVE_SCHEDULE_BTN_THIAGOIAZZETTI','en-US','Save Schedule'),
  ('EXERCISE_SEL_TITLE_THIAGOIAZZETTI',          'en-US', 'Add Exercise'),
  ('EXERCISE_SEL_MUSCLE_LABEL_THIAGOIAZZETTI',   'en-US', 'Muscle Group'),
  ('EXERCISE_SEL_EXERCISE_LABEL_THIAGOIAZZETTI', 'en-US', 'Exercise'),
  ('EXERCISE_SEL_SELECT_OPT_THIAGOIAZZETTI',     'en-US', 'Select an exercise'),
  ('EXERCISE_SEL_SETS_LABEL_THIAGOIAZZETTI',     'en-US', 'Sets'),
  ('EXERCISE_SEL_REPS_LABEL_THIAGOIAZZETTI',     'en-US', 'Reps'),
  ('EXERCISE_SEL_REST_LABEL_THIAGOIAZZETTI',     'en-US', 'Rest (s)'),
  ('EXERCISE_SEL_ADD_BTN_THIAGOIAZZETTI',        'en-US', 'Add Exercise'),
  ('EXERCISE_SEL_CANCEL_BTN_THIAGOIAZZETTI',     'en-US', 'Cancel'),
  ('WORKOUT_ITEM_REST_LABEL_THIAGOIAZZETTI',     'en-US', 's rest'),
  ('DASH_TOTAL_STUDENTS_THIAGOIAZZETTI',         'en-US', 'Total Students'),
  ('DASH_WORKOUTS_TODAY_THIAGOIAZZETTI',         'en-US', 'Workouts Today'),
  ('DASH_MONTHLY_REVENUE_THIAGOIAZZETTI',        'en-US', 'Monthly Revenue'),
  ('DASH_LOAD_EVOLUTION_TITLE_THIAGOIAZZETTI',   'en-US', 'Load Evolution'),
  ('DASH_LOAD_EVOLUTION_SUBTITLE_THIAGOIAZZETTI','en-US', 'Average student performance over the last weeks.'),
  ('DASH_STUDENT_MANAGEMENT_TITLE_THIAGOIAZZETTI','en-US','Student Management'),
  ('DASH_NEW_STUDENT_BUTTON_THIAGOIAZZETTI',     'en-US', 'New Student'),
  ('DASH_COL_STUDENT_THIAGOIAZZETTI',            'en-US', 'Student'),
  ('DASH_COL_PLAN_STATUS_THIAGOIAZZETTI',        'en-US', 'Plan Status'),
  ('DASH_COL_START_THIAGOIAZZETTI',              'en-US', 'Start'),
  ('DASH_COL_ACTION_THIAGOIAZZETTI',             'en-US', 'Action'),
  ('DASH_PRESCRIBE_WORKOUT_THIAGOIAZZETTI',      'en-US', 'Prescribe Workout')
) AS t(chave, codigo_idioma, valor)
JOIN sistemas s ON s.codigo = 'website'
JOIN idiomas i ON i.codigo = t.codigo_idioma
ON CONFLICT (chave, sistema_id, idioma_id)
DO UPDATE SET valor = EXCLUDED.valor, atualizado_em = NOW();

-- ──────────────────────────────────────────────────────────────
-- it-IT, es-ES, ar-MA – pt-BR fallbacks (override with real translations when available)
-- ──────────────────────────────────────────────────────────────
INSERT INTO traducoes (chave, valor, sistema_id, idioma_id)
SELECT t.chave, t.valor, s.id, i.id
FROM (VALUES
  -- it-IT
  ('ADMIN_TAB_OVERVIEW_THIAGOIAZZETTI',          'it-IT', 'Panoramica'),
  ('ADMIN_TAB_STUDENTS_THIAGOIAZZETTI',          'it-IT', 'Studenti'),
  ('ADMIN_TAB_PLANS_THIAGOIAZZETTI',             'it-IT', 'Piani'),
  ('ADMIN_TAB_WORKOUTS_THIAGOIAZZETTI',          'it-IT', 'Allenamenti'),
  ('ADMIN_TAB_COMMUNICATION_THIAGOIAZZETTI',     'it-IT', 'Comunicazione'),
  ('ADMIN_DASH_FULL_NAME_THIAGOIAZZETTI',        'it-IT', 'Nome completo'),
  ('ADMIN_DASH_EMAIL_THIAGOIAZZETTI',            'it-IT', 'Email'),
  ('ADMIN_DASH_PHONE_THIAGOIAZZETTI',            'it-IT', 'Telefono'),
  ('ADMIN_DASH_BIRTH_DATE_THIAGOIAZZETTI',       'it-IT', 'Data di nascita'),
  ('ADMIN_DASH_SAVE_BTN_THIAGOIAZZETTI',         'it-IT', 'Salva'),
  ('ADMIN_DASH_CANCEL_BTN_THIAGOIAZZETTI',       'it-IT', 'Annulla'),
  ('ADMIN_DASH_EDIT_BTN_THIAGOIAZZETTI',         'it-IT', 'Modifica'),
  ('ADMIN_DASH_PER_MONTH_THIAGOIAZZETTI',        'it-IT', '/mese'),
  ('ADMIN_CHAT_INPUT_PLACEHOLDER_THIAGOIAZZETTI','it-IT', 'Scrivi un messaggio...'),
  ('DIET_WEEKDAY_MON_THIAGOIAZZETTI',            'it-IT', 'Lunedì'),
  ('DIET_WEEKDAY_TUE_THIAGOIAZZETTI',            'it-IT', 'Martedì'),
  ('DIET_WEEKDAY_WED_THIAGOIAZZETTI',            'it-IT', 'Mercoledì'),
  ('DIET_WEEKDAY_THU_THIAGOIAZZETTI',            'it-IT', 'Giovedì'),
  ('DIET_WEEKDAY_FRI_THIAGOIAZZETTI',            'it-IT', 'Venerdì'),
  ('DIET_WEEKDAY_SAT_THIAGOIAZZETTI',            'it-IT', 'Sabato'),
  ('DIET_WEEKDAY_SUN_THIAGOIAZZETTI',            'it-IT', 'Domenica'),
  ('DASH_TOTAL_STUDENTS_THIAGOIAZZETTI',         'it-IT', 'Totale Studenti'),
  ('DASH_WORKOUTS_TODAY_THIAGOIAZZETTI',         'it-IT', 'Allenamenti Oggi'),
  ('DASH_MONTHLY_REVENUE_THIAGOIAZZETTI',        'it-IT', 'Fatturato Mensile'),
  ('DASH_LOAD_EVOLUTION_TITLE_THIAGOIAZZETTI',   'it-IT', 'Evoluzione dei Carichi'),
  ('DASH_NEW_STUDENT_BUTTON_THIAGOIAZZETTI',     'it-IT', 'Nuovo Studente'),
  ('DASH_PRESCRIBE_WORKOUT_THIAGOIAZZETTI',      'it-IT', 'Prescrivere Allenamento'),
  -- es-ES
  ('ADMIN_TAB_OVERVIEW_THIAGOIAZZETTI',          'es-ES', 'Resumen'),
  ('ADMIN_TAB_STUDENTS_THIAGOIAZZETTI',          'es-ES', 'Alumnos'),
  ('ADMIN_TAB_PLANS_THIAGOIAZZETTI',             'es-ES', 'Planes'),
  ('ADMIN_TAB_WORKOUTS_THIAGOIAZZETTI',          'es-ES', 'Entrenamientos'),
  ('ADMIN_TAB_COMMUNICATION_THIAGOIAZZETTI',     'es-ES', 'Comunicación'),
  ('ADMIN_DASH_FULL_NAME_THIAGOIAZZETTI',        'es-ES', 'Nombre completo'),
  ('ADMIN_DASH_EMAIL_THIAGOIAZZETTI',            'es-ES', 'Correo electrónico'),
  ('ADMIN_DASH_PHONE_THIAGOIAZZETTI',            'es-ES', 'Teléfono'),
  ('ADMIN_DASH_BIRTH_DATE_THIAGOIAZZETTI',       'es-ES', 'Fecha de nacimiento'),
  ('ADMIN_DASH_SAVE_BTN_THIAGOIAZZETTI',         'es-ES', 'Guardar'),
  ('ADMIN_DASH_CANCEL_BTN_THIAGOIAZZETTI',       'es-ES', 'Cancelar'),
  ('ADMIN_DASH_EDIT_BTN_THIAGOIAZZETTI',         'es-ES', 'Editar'),
  ('ADMIN_DASH_PER_MONTH_THIAGOIAZZETTI',        'es-ES', '/mes'),
  ('ADMIN_CHAT_INPUT_PLACEHOLDER_THIAGOIAZZETTI','es-ES', 'Escribe un mensaje...'),
  ('DIET_WEEKDAY_MON_THIAGOIAZZETTI',            'es-ES', 'Lunes'),
  ('DIET_WEEKDAY_TUE_THIAGOIAZZETTI',            'es-ES', 'Martes'),
  ('DIET_WEEKDAY_WED_THIAGOIAZZETTI',            'es-ES', 'Miércoles'),
  ('DIET_WEEKDAY_THU_THIAGOIAZZETTI',            'es-ES', 'Jueves'),
  ('DIET_WEEKDAY_FRI_THIAGOIAZZETTI',            'es-ES', 'Viernes'),
  ('DIET_WEEKDAY_SAT_THIAGOIAZZETTI',            'es-ES', 'Sábado'),
  ('DIET_WEEKDAY_SUN_THIAGOIAZZETTI',            'es-ES', 'Domingo'),
  ('DASH_TOTAL_STUDENTS_THIAGOIAZZETTI',         'es-ES', 'Total de Alumnos'),
  ('DASH_WORKOUTS_TODAY_THIAGOIAZZETTI',         'es-ES', 'Entrenamientos Hoy'),
  ('DASH_MONTHLY_REVENUE_THIAGOIAZZETTI',        'es-ES', 'Ingresos Mensuales'),
  ('DASH_LOAD_EVOLUTION_TITLE_THIAGOIAZZETTI',   'es-ES', 'Evolución de Cargas'),
  ('DASH_NEW_STUDENT_BUTTON_THIAGOIAZZETTI',     'es-ES', 'Nuevo Alumno'),
  ('DASH_PRESCRIBE_WORKOUT_THIAGOIAZZETTI',      'es-ES', 'Prescribir Entrenamiento'),
  -- ar-MA (Arabic fallback to Brazilian Portuguese for remaining keys)
  ('ADMIN_TAB_OVERVIEW_THIAGOIAZZETTI',          'ar-MA', 'نظرة عامة'),
  ('ADMIN_TAB_STUDENTS_THIAGOIAZZETTI',          'ar-MA', 'الطلاب'),
  ('ADMIN_TAB_PLANS_THIAGOIAZZETTI',             'ar-MA', 'الخطط'),
  ('ADMIN_TAB_WORKOUTS_THIAGOIAZZETTI',          'ar-MA', 'التمارين'),
  ('ADMIN_TAB_COMMUNICATION_THIAGOIAZZETTI',     'ar-MA', 'التواصل'),
  ('ADMIN_DASH_FULL_NAME_THIAGOIAZZETTI',        'ar-MA', 'الاسم الكامل'),
  ('ADMIN_DASH_EMAIL_THIAGOIAZZETTI',            'ar-MA', 'البريد الإلكتروني'),
  ('ADMIN_DASH_PHONE_THIAGOIAZZETTI',            'ar-MA', 'الهاتف'),
  ('ADMIN_DASH_SAVE_BTN_THIAGOIAZZETTI',         'ar-MA', 'حفظ'),
  ('ADMIN_DASH_CANCEL_BTN_THIAGOIAZZETTI',       'ar-MA', 'إلغاء'),
  ('ADMIN_DASH_EDIT_BTN_THIAGOIAZZETTI',         'ar-MA', 'تعديل'),
  ('ADMIN_CHAT_INPUT_PLACEHOLDER_THIAGOIAZZETTI','ar-MA', 'اكتب رسالة...'),
  ('DIET_WEEKDAY_MON_THIAGOIAZZETTI',            'ar-MA', 'الاثنين'),
  ('DIET_WEEKDAY_TUE_THIAGOIAZZETTI',            'ar-MA', 'الثلاثاء'),
  ('DIET_WEEKDAY_WED_THIAGOIAZZETTI',            'ar-MA', 'الأربعاء'),
  ('DIET_WEEKDAY_THU_THIAGOIAZZETTI',            'ar-MA', 'الخميس'),
  ('DIET_WEEKDAY_FRI_THIAGOIAZZETTI',            'ar-MA', 'الجمعة'),
  ('DIET_WEEKDAY_SAT_THIAGOIAZZETTI',            'ar-MA', 'السبت'),
  ('DIET_WEEKDAY_SUN_THIAGOIAZZETTI',            'ar-MA', 'الأحد'),
  ('DASH_TOTAL_STUDENTS_THIAGOIAZZETTI',         'ar-MA', 'إجمالي الطلاب'),
  ('DASH_WORKOUTS_TODAY_THIAGOIAZZETTI',         'ar-MA', 'التمارين اليوم'),
  ('DASH_MONTHLY_REVENUE_THIAGOIAZZETTI',        'ar-MA', 'الإيرادات الشهرية'),
  ('DASH_NEW_STUDENT_BUTTON_THIAGOIAZZETTI',     'ar-MA', 'طالب جديد'),
  ('DASH_PRESCRIBE_WORKOUT_THIAGOIAZZETTI',      'ar-MA', 'وصف تمرين')
) AS t(chave, codigo_idioma, valor)
JOIN sistemas s ON s.codigo = 'website'
JOIN idiomas i ON i.codigo = t.codigo_idioma
ON CONFLICT (chave, sistema_id, idioma_id)
DO UPDATE SET valor = EXCLUDED.valor, atualizado_em = NOW();
