-- =========================================================================
-- Traduções faltantes para o sistema 'website' nos 5 idiomas adicionais
-- Idiomas: en-US, it-IT, pt-PT, es-ES, ar-MA
-- =========================================================================

INSERT INTO traducoes (chave, valor, sistema_id, idioma_id)
SELECT v.chave, v.valor, s.id, i.id
FROM (VALUES
  -- ==========================================================
  -- INGLÊS (en-US)
  -- ==========================================================
  ('ADMIN_HISTORY_ADDRESS', 'en-US', 'Address'),
  ('ADMIN_HISTORY_BACK', 'en-US', '← Admin'),
  ('ADMIN_HISTORY_CLEAR', 'en-US', 'Clear'),
  ('ADMIN_HISTORY_CLIENT_NAME', 'en-US', 'Customer name'),
  ('ADMIN_HISTORY_EMPTY', 'en-US', 'No orders found.'),
  ('ADMIN_HISTORY_FILTER', 'en-US', 'Filter'),
  ('ADMIN_HISTORY_FILTERS', 'en-US', 'Filters'),
  ('ADMIN_HISTORY_FOUND_MULTI', 'en-US', 'orders found'),
  ('ADMIN_HISTORY_FOUND_SINGLE', 'en-US', 'order found'),
  ('ADMIN_HISTORY_FROM', 'en-US', 'From'),
  ('ADMIN_HISTORY_HALF_HALF', 'en-US', 'Half and Half'),
  ('ADMIN_HISTORY_LOAD_ERROR', 'en-US', 'Error loading order history.'),
  ('ADMIN_HISTORY_MARK_PAID', 'en-US', '✓ Paid'),
  ('ADMIN_HISTORY_NOTES', 'en-US', 'Notes'),
  ('ADMIN_HISTORY_ONLY_REFUNDS_SUFFIX', 'en-US', ' — showing only pending refunds'),
  ('ADMIN_HISTORY_PAYMENT_MARKED', 'en-US', 'Payment marked as approved'),
  ('ADMIN_HISTORY_PAYMENT_UPDATE_ERROR', 'en-US', 'Failed to update payment'),
  ('ADMIN_HISTORY_PIZZA', 'en-US', 'Pizza'),
  ('ADMIN_HISTORY_REFUND_HINT', 'en-US', 'Customer had already paid and payment was approved.'),
  ('ADMIN_HISTORY_REFUND_NEEDS_MULTI', 'en-US', 'cancelled orders need refund'),
  ('ADMIN_HISTORY_REFUND_NEEDS_SINGLE', 'en-US', 'cancelled order needs refund'),
  ('ADMIN_HISTORY_REFUND_PENDING', 'en-US', 'REFUND PENDING'),
  ('ADMIN_HISTORY_REFUND_WARNING', 'en-US', 'Order cancelled after payment approved — refund customer.'),
  ('ADMIN_HISTORY_SHOW_ALL', 'en-US', 'Show all'),
  ('ADMIN_HISTORY_SHOW_REFUNDS', 'en-US', 'Show only refunds'),
  ('ADMIN_HISTORY_SUBTITLE', 'en-US', 'All orders — delivered, cancelled and ongoing.'),
  ('ADMIN_HISTORY_TITLE', 'en-US', 'Order History'),
  ('ADMIN_HISTORY_TO', 'en-US', 'To'),
  ('ADMIN_HISTORY_TOTAL', 'en-US', 'Total'),
  ('ADMIN_MESAS_BACK_PANEL', 'en-US', '← Admin Panel'),
  ('ADMIN_MESAS_EMPTY', 'en-US', 'No tables registered yet.'),
  ('ADMIN_MESAS_EMPTY_HINT_1', 'en-US', 'Click on'),
  ('ADMIN_MESAS_EMPTY_HINT_2', 'en-US', 'to start.'),
  ('ADMIN_MESAS_HELP_TEXT_1', 'en-US', 'In the Mercado Pago app'),
  ('ADMIN_MESAS_HELP_TEXT_2', 'en-US', 'Your business → Point'),
  ('ADMIN_MESAS_HELP_TEXT_3', 'en-US', 'select the device → copy the ID shown (e.g.:'),
  ('ADMIN_MESAS_HELP_TITLE', 'en-US', 'How to find the terminal ID?'),
  ('ADMIN_MESAS_LOAD_ERROR', 'en-US', 'Failed to load tables.'),
  ('ADMIN_MESAS_LOADING', 'en-US', 'Loading tables...'),
  ('ADMIN_MESAS_NEW_BUTTON', 'en-US', 'New Table'),
  ('ADMIN_MESAS_TITLE', 'en-US', 'Tables'),
  ('ADMIN_PRODUCTS_ACTIVE', 'en-US', 'Active'),
  ('ADMIN_PRODUCTS_ACTIVE_COUNT', 'en-US', '{{count}} active'),
  ('ADMIN_PRODUCTS_CATEGORY_LABEL', 'en-US', 'Category'),
  ('ADMIN_PRODUCTS_CATEGORY_PLACEHOLDER', 'en-US', 'E.g.: Sweet, Savory, Drinks...'),
  ('ADMIN_PRODUCTS_COST_OPTIONAL', 'en-US', 'Cost (optional)'),
  ('ADMIN_PRODUCTS_CREATE', 'en-US', 'Create'),
  ('ADMIN_PRODUCTS_CREATED', 'en-US', 'Product created!'),
  ('ADMIN_PRODUCTS_DESCRIPTION_LABEL', 'en-US', 'Description'),
  ('ADMIN_PRODUCTS_DESCRIPTION_PLACEHOLDER', 'en-US', 'Brief flavor description...'),
  ('ADMIN_PRODUCTS_DISABLE', 'en-US', 'Disable'),
  ('ADMIN_PRODUCTS_DISABLED', 'en-US', 'Product disabled'),
  ('ADMIN_PRODUCTS_EDIT_TITLE', 'en-US', 'Edit Product'),
  ('ADMIN_PRODUCTS_EMPTY', 'en-US', 'No products registered yet.'),
  ('ADMIN_PRODUCTS_IMAGE_URL', 'en-US', 'Image URL'),
  ('ADMIN_PRODUCTS_INACTIVE', 'en-US', 'Inactive'),
  ('ADMIN_PRODUCTS_INACTIVE_COUNT', 'en-US', '{{count}} inactive'),
  ('ADMIN_PRODUCTS_LOAD_ERROR', 'en-US', 'Failed to load products.'),
  ('ADMIN_PRODUCTS_NAME_LABEL', 'en-US', 'Name *'),
  ('ADMIN_PRODUCTS_NAME_PLACEHOLDER', 'en-US', 'E.g.: Imperial Pepperoni'),
  ('ADMIN_PRODUCTS_NEW_BUTTON', 'en-US', 'New Product'),
  ('ADMIN_PRODUCTS_NEW_TITLE', 'en-US', 'New Product'),
  ('ADMIN_PRODUCTS_PRICE_COST', 'en-US', 'Price and cost *'),
  ('ADMIN_PRODUCTS_PRICES_BY_SIZE', 'en-US', 'Prices by Size *'),
  ('ADMIN_PRODUCTS_RESTORE', 'en-US', 'Restore'),
  ('ADMIN_PRODUCTS_RESTORED', 'en-US', 'Product restored'),
  ('ADMIN_PRODUCTS_SALE_PRICE', 'en-US', 'Sale price'),
  ('ADMIN_PRODUCTS_SAVE_ERROR', 'en-US', 'Error saving product'),
  ('ADMIN_PRODUCTS_SAVING', 'en-US', 'Saving...'),
  ('ADMIN_PRODUCTS_STATUS_ERROR', 'en-US', 'Failed to change status'),
  ('ADMIN_PRODUCTS_SUBTITLE', 'en-US', 'Manage the Pizzaria Fellice menu'),
  ('ADMIN_PRODUCTS_TITLE', 'en-US', 'Products'),
  ('ADMIN_PRODUCTS_TYPE_CRUST', 'en-US', 'Stuffed crust'),
  ('ADMIN_PRODUCTS_TYPE_FLAVOR', 'en-US', 'Flavor'),
  ('ADMIN_PRODUCTS_TYPE_LABEL', 'en-US', 'Product type'),
  ('ADMIN_PRODUCTS_TYPE_OTHER', 'en-US', 'Other'),
  ('ADMIN_PRODUCTS_TYPE_PIZZA', 'en-US', 'Pizza'),
  ('ADMIN_PRODUCTS_UPDATED', 'en-US', 'Product updated!'),
  ('ADMIN_USERS_BACK_PANEL', 'en-US', '← Admin Panel'),
  ('ADMIN_USERS_CREATE_ANOTHER', 'en-US', 'Create another user'),
  ('ADMIN_USERS_CREATE_BUTTON', 'en-US', 'Create'),
  ('ADMIN_USERS_CREATE_ERROR', 'en-US', 'Error creating user. Check data.'),
  ('ADMIN_USERS_CREATED_SUCCESS', 'en-US', 'User created successfully!'),
  ('ADMIN_USERS_CREATING', 'en-US', 'Creating...'),
  ('ADMIN_USERS_EMAIL_LABEL', 'en-US', 'E-mail'),
  ('ADMIN_USERS_EMAIL_OR_PHONE_REQUIRED', 'en-US', 'Provide email or phone for login.'),
  ('ADMIN_USERS_EMAIL_PLACEHOLDER', 'en-US', 'ex@email.com'),
  ('ADMIN_USERS_FIELD_EMAIL', 'en-US', 'E-mail'),
  ('ADMIN_USERS_FIELD_NAME', 'en-US', 'Name'),
  ('ADMIN_USERS_FIELD_PASSWORD', 'en-US', 'Password'),
  ('ADMIN_USERS_FIELD_PHONE', 'en-US', 'Phone'),
  ('ADMIN_USERS_FIELD_ROLE', 'en-US', 'Role'),
  ('ADMIN_USERS_GENERIC_USER', 'en-US', 'User'),
  ('ADMIN_USERS_NAME_LABEL', 'en-US', 'Full name *'),
  ('ADMIN_USERS_NAME_PLACEHOLDER', 'en-US', 'E.g.: John Doe'),
  ('ADMIN_USERS_PASSWORD_LABEL', 'en-US', 'Password *'),
  ('ADMIN_USERS_PASSWORD_PLACEHOLDER', 'en-US', 'Min 6 characters'),
  ('ADMIN_USERS_PHONE_HINT', 'en-US', 'Can be used for login instead of email.'),
  ('ADMIN_USERS_PHONE_LABEL', 'en-US', 'Phone'),
  ('ADMIN_USERS_PHONE_MIN_DIGITS', 'en-US', 'Phone must have at least 10 digits.'),
  ('ADMIN_USERS_PHONE_PLACEHOLDER', 'en-US', '(11) 99999-9999'),
  ('ADMIN_USERS_ROLE_LABEL', 'en-US', 'Role *'),
  ('ADMIN_USERS_TITLE', 'en-US', 'Create User'),
  ('APP_BRAND_NAME', 'en-US', 'Pizzaria Fellice'),
  ('CHECKOUT_RETURN_BACK_MENU', 'en-US', 'Back to menu'),
  ('CHECKOUT_RETURN_CONFIRM_ERROR', 'en-US', 'Confirmation error'),
  ('CHECKOUT_RETURN_FAILURE_BUTTON', 'en-US', 'Try again'),
  ('CHECKOUT_RETURN_FAILURE_SUBTITLE', 'en-US', 'There was an issue with the payment. Your cart is still saved.'),
  ('CHECKOUT_RETURN_FAILURE_TITLE', 'en-US', 'Payment not completed'),
  ('CHECKOUT_RETURN_ORDER_PREFIX', 'en-US', 'Order'),
  ('CHECKOUT_RETURN_PENDING_BUTTON', 'en-US', 'View my orders'),
  ('CHECKOUT_RETURN_PENDING_SUBTITLE', 'en-US', 'Your payment is being processed. Preparation will start once confirmed.'),
  ('CHECKOUT_RETURN_PENDING_TITLE', 'en-US', 'Payment pending'),
  ('CHECKOUT_RETURN_SUCCESS_BUTTON', 'en-US', 'Track my order'),
  ('CHECKOUT_RETURN_SUCCESS_SUBTITLE', 'en-US', 'Your order has been received and is being carefully prepared.'),
  ('CHECKOUT_RETURN_SUCCESS_TITLE', 'en-US', 'Payment confirmed!'),
  ('CLIENT_DASHBOARD_ASK_REASON', 'en-US', 'Ask reason'),
  ('CLIENT_DASHBOARD_CANCELLED_WHATSAPP', 'en-US', 'Cancelled via WhatsApp'),
  ('CLIENT_DASHBOARD_CLIENT', 'en-US', 'Client'),
  ('CLIENT_DASHBOARD_CONFIRM', 'en-US', 'Confirm?'),
  ('CLIENT_DASHBOARD_CRUST', 'en-US', 'Crust'),
  ('CLIENT_DASHBOARD_DELIVERY', 'en-US', 'Delivery'),
  ('CLIENT_DASHBOARD_DELIVERY_CODE_HINT', 'en-US', 'Provide this code to the rider to confirm delivery'),
  ('CLIENT_DASHBOARD_DELIVERY_CODE_LABEL', 'en-US', 'Delivery confirmation code'),
  ('CLIENT_DASHBOARD_EMPTY_ALL', 'en-US', 'You have no orders yet.'),
  ('CLIENT_DASHBOARD_EMPTY_FILTER', 'en-US', 'No orders found for this filter.'),
  ('CLIENT_DASHBOARD_FILTER_ALL', 'en-US', 'All'),
  ('CLIENT_DASHBOARD_HALF_HALF', 'en-US', 'Half and Half'),
  ('CLIENT_DASHBOARD_HELLO', 'en-US', 'Hello'),
  ('CLIENT_DASHBOARD_LOAD_ERROR', 'en-US', 'Error loading orders.'),
  ('CLIENT_DASHBOARD_ORDER_PREFIX', 'en-US', 'Order'),
  ('CLIENT_DASHBOARD_PAYMENT', 'en-US', 'Payment'),
  ('CLIENT_DASHBOARD_PIZZA', 'en-US', 'Pizza'),
  ('CLIENT_DASHBOARD_REPEAT_ERROR', 'en-US', 'Could not repeat this order.'),
  ('CLIENT_DASHBOARD_REPEAT_ORDER', 'en-US', 'Repeat order'),
  ('CLIENT_DASHBOARD_REPEAT_SUCCESS', 'en-US', 'Order added to cart again.'),
  ('DELETE', 'en-US', 'Delete'),
  ('EDIT', 'en-US', 'Edit'),
  ('FIRST_HALF_CHOOSE_NEXT', 'en-US', 'Choose the next pizza to complete.'),
  ('FIRST_HALF_SELECTED_MSG', 'en-US', 'First half selected:'),
  ('HOME_ABOUT_P1', 'en-US', 'Since 1997, Pizzaria Fellice has been synonymous with quality and flavor. We combine fresh, handpicked ingredients with exclusive recipes to create pizzas that delight everyone. Whether in our welcoming dining room for special moments, or through our efficient delivery service, we guarantee a unique gastronomic experience.'),
  ('HOME_ABOUT_P2', 'en-US', 'Beyond our pizzas, we offer a delicious variety of sides, sandwiches, snacks, fries and desserts, all prepared with the same care and dedication that made us a regional reference.'),
  ('HOME_ABOUT_P3', 'en-US', 'Discover why Pizzaria Fellice is the right choice for those seeking tradition, quality and a touch of exclusivity. Visit us or order online and savor the best Italian cuisine with our special touch.'),
  ('HOME_HERO_TITLE_1', 'en-US', 'Authentic'),
  ('HOME_HERO_TITLE_2', 'en-US', 'Italian pizza'),
  ('HOME_SINCE_1997', 'en-US', 'Since 1997 · 27 years of Italian tradition'),
  ('KITCHEN_ADVANCE_TO_TABLE', 'en-US', 'Take to Table'),
  ('KITCHEN_CLEAR_ALERTS', 'en-US', 'Clear alerts'),
  ('KITCHEN_DELIVERED_AT_TABLE', 'en-US', 'Delivered at Table'),
  ('KITCHEN_DELIVERY', 'en-US', 'Delivery'),
  ('KITCHEN_DROP_TO_STAGE', 'en-US', 'Drop here to move to {{stage}}'),
  ('KITCHEN_HIGHLIGHT_SECONDS', 'en-US', 'Highlight active for {{seconds}} seconds.'),
  ('KITCHEN_LIVE', 'en-US', 'Live'),
  ('KITCHEN_LOAD_ERROR', 'en-US', 'Failed to load orders.'),
  ('KITCHEN_MARK_PICKED_UP', 'en-US', 'Mark Picked Up'),
  ('KITCHEN_NEW_ORDER', 'en-US', 'New order'),
  ('KITCHEN_NEW_ORDER_ARRIVED', 'en-US', 'New order {{id}} arrived in queue'),
  ('KITCHEN_NO_ACTIVE_ORDERS', 'en-US', 'No active orders currently.'),
  ('KITCHEN_NO_ALERTS', 'en-US', 'No pending alerts'),
  ('KITCHEN_NO_ORDER', 'en-US', 'No order'),
  ('KITCHEN_NO_OVERDUE', 'en-US', 'No overdue orders'),
  ('KITCHEN_OFF', 'en-US', 'off'),
  ('KITCHEN_ON', 'en-US', 'on'),
  ('KITCHEN_ORDERS_IN_STAGE', 'en-US', 'Orders in this stage'),
  ('KITCHEN_OVERDUE_ALERT', 'en-US', '{{count}} order(s) became overdue'),
  ('KITCHEN_OVERDUE_COUNT', 'en-US', '{{count}} overdue orders'),
  ('KITCHEN_PAYMENT_PENDING', 'en-US', 'Pmt. pending'),
  ('KITCHEN_PICKUP', 'en-US', 'Pickup'),
  ('KITCHEN_READY_PICKUP', 'en-US', 'Ready for Pickup'),
  ('KITCHEN_SOUND', 'en-US', 'Sound'),
  ('KITCHEN_TITLE', 'en-US', 'Kitchen'),
  ('KITCHEN_UNREAD_ALERTS', 'en-US', '{{count}} new unread alerts'),
  ('KITCHEN_UPDATED_AT', 'en-US', 'Updated at {{time}} • real-time with 2 min fallback'),
  ('KITCHEN_UPDATING', 'en-US', 'Updating...'),
  ('MESA_ACCESS_INVALID_QR_TEXT_1', 'en-US', 'This QR code expired or is no longer valid.'),
  ('MESA_ACCESS_INVALID_QR_TEXT_2', 'en-US', 'Ask staff to generate a new one.'),
  ('MESA_ACCESS_INVALID_QR_TITLE', 'en-US', 'Invalid QR Code'),
  ('MESA_ACCESS_LOADING', 'en-US', 'Identifying table...'),
  ('MESA_CHECKOUT_BACK_MENU', 'en-US', '← Menu'),
  ('MESA_CHECKOUT_CONFIRM_ORDER', 'en-US', 'Confirm order'),
  ('MESA_CHECKOUT_NOTES_LABEL', 'en-US', 'Notes (optional)'),
  ('MESA_CHECKOUT_NOTES_PLACEHOLDER', 'en-US', 'E.g.: no onion, thin crust...'),
  ('MESA_CHECKOUT_ORDER_ERROR', 'en-US', 'Error placing order.'),
  ('MESA_CHECKOUT_ORDER_SENT', 'en-US', 'Order sent to kitchen!'),
  ('MESA_CHECKOUT_PAY_LATER', 'en-US', 'Pay later'),
  ('MESA_CHECKOUT_PAY_NOW', 'en-US', 'Do you want to pay now?'),
  ('MESA_CHECKOUT_PAYMENT_CONFIRMED', 'en-US', 'Payment confirmed! 🍕'),
  ('MESA_CHECKOUT_PENDING_TOTAL', 'en-US', 'Pending total'),
  ('MESA_CHECKOUT_PIX_SHORT', 'en-US', 'PIX'),
  ('MESA_CHECKOUT_SENDING', 'en-US', 'Sending...'),
  ('MESA_CHECKOUT_SESSION_ORDERS', 'en-US', 'Orders from this session'),
  ('MESA_CHECKOUT_TABLE', 'en-US', 'Table'),
  ('MESA_CHECKOUT_TERMINAL_SHORT', 'en-US', 'Card terminal'),
  ('MESA_CHECKOUT_VIEW_MENU', 'en-US', 'View menu'),
  ('MESA_CHECKOUT_YOUR_ORDER', 'en-US', 'Your order'),
  ('MESA_PIX_COPIED', 'en-US', 'Code copied!'),
  ('MESA_PIX_COPY_BUTTON', 'en-US', 'Copy PIX code'),
  ('MESA_PIX_COPY_HINT', 'en-US', 'Or copy the code:'),
  ('MESA_PIX_ERROR', 'en-US', 'Error generating PIX. Try again.'),
  ('MESA_PIX_GENERATING', 'en-US', 'Generating QR Code...'),
  ('MESA_PIX_QR_ALT', 'en-US', 'PIX QR Code'),
  ('MESA_PIX_TITLE', 'en-US', 'Pay with PIX'),
  ('MESA_PIX_WAITING', 'en-US', 'Waiting for payment confirmation...'),
  ('MESA_TERMINAL_SEND_BUTTON', 'en-US', 'Send to terminal'),
  ('MESA_TERMINAL_SEND_ERROR', 'en-US', 'Error sending to terminal.'),
  ('MESA_TERMINAL_SENDING', 'en-US', 'Sending...'),
  ('MESA_TERMINAL_SENT', 'en-US', 'Charge sent to terminal!'),
  ('MESA_TERMINAL_TITLE', 'en-US', 'Pay at Terminal'),
  ('MESA_TERMINAL_WAITING', 'en-US', 'Waiting for terminal payment...'),
  ('MONTH_LABEL_APR', 'en-US', 'April'),
  ('MONTH_LABEL_AUG', 'en-US', 'August'),
  ('MONTH_LABEL_DEC', 'en-US', 'December'),
  ('MONTH_LABEL_FEB', 'en-US', 'February'),
  ('MONTH_LABEL_JAN', 'en-US', 'January'),
  ('MONTH_LABEL_JUL', 'en-US', 'July'),
  ('MONTH_LABEL_JUN', 'en-US', 'June'),
  ('MONTH_LABEL_MAR', 'en-US', 'March'),
  ('MONTH_LABEL_MAY', 'en-US', 'May'),
  ('MONTH_LABEL_NOV', 'en-US', 'November'),
  ('MONTH_LABEL_OCT', 'en-US', 'October'),
  ('MONTH_LABEL_SEP', 'en-US', 'September'),
  ('MONTH_SHORT_APR', 'en-US', 'Apr'),
  ('MONTH_SHORT_AUG', 'en-US', 'Aug'),
  ('MONTH_SHORT_DEC', 'en-US', 'Dec'),
  ('MONTH_SHORT_FEB', 'en-US', 'Feb'),
  ('MONTH_SHORT_JAN', 'en-US', 'Jan'),
  ('MONTH_SHORT_JUL', 'en-US', 'Jul'),
  ('MONTH_SHORT_JUN', 'en-US', 'Jun'),
  ('MONTH_SHORT_MAR', 'en-US', 'Mar'),
  ('MONTH_SHORT_MAY', 'en-US', 'May'),
  ('MONTH_SHORT_NOV', 'en-US', 'Nov'),
  ('MONTH_SHORT_OCT', 'en-US', 'Oct'),
  ('MONTH_SHORT_SEP', 'en-US', 'Sep'),
  ('MOTOBOY_ADDRESS', 'en-US', 'Address'),
  ('MOTOBOY_ALREADY_PAID', 'en-US', 'Already paid'),
  ('MOTOBOY_AUTO_REFRESH_HINT', 'en-US', 'This page auto-refreshes every 20 seconds.'),
  ('MOTOBOY_CODE_PLACEHOLDER', 'en-US', 'E.g.: 1234'),
  ('MOTOBOY_COLLECT_ON_DELIVERY', 'en-US', 'Collect from customer on delivery'),
  ('MOTOBOY_CONFIRM', 'en-US', 'Confirm'),
  ('MOTOBOY_CONFIRM_DELIVERY_CODE', 'en-US', 'Confirm delivery with code'),
  ('MOTOBOY_CONFIRM_PAYMENT_TEXT', 'en-US', 'Mark as paid only after receiving the amount.'),
  ('MOTOBOY_CONFIRM_PAYMENT_TITLE', 'en-US', 'Confirm payment?'),
  ('MOTOBOY_CONFIRM_PAYMENT_YES', 'en-US', 'Yes, mark as paid'),
  ('MOTOBOY_CONFIRMING', 'en-US', 'Confirming...'),
  ('MOTOBOY_DELIVERY_CONFIRM_ERROR', 'en-US', 'Could not confirm delivery.'),
  ('MOTOBOY_DELIVERY_CONFIRMED', 'en-US', 'Delivery confirmed successfully.'),
  ('MOTOBOY_DELIVERY_FEE', 'en-US', 'Delivery Fee'),
  ('MOTOBOY_EMPTY', 'en-US', 'No orders ready for delivery at the moment.'),
  ('MOTOBOY_GOOGLE_MAPS', 'en-US', 'Google Maps'),
  ('MOTOBOY_LOAD_ERROR', 'en-US', 'Error loading orders. Try refreshing.'),
  ('MOTOBOY_LOADING', 'en-US', 'Loading...'),
  ('MOTOBOY_MARK_PAID', 'en-US', 'Mark as paid'),
  ('MOTOBOY_MARK_PAID_FIRST', 'en-US', 'To confirm delivery, mark the order as paid first.'),
  ('MOTOBOY_ORDER_PREFIX', 'en-US', 'Order'),
  ('MOTOBOY_ORDER_TOTAL', 'en-US', 'Order Total'),
  ('MOTOBOY_PAYMENT_CONFIRM_ERROR', 'en-US', 'Could not confirm payment.'),
  ('MOTOBOY_PAYMENT_MARKED', 'en-US', 'Payment marked as approved.'),
  ('MOTOBOY_REFRESH', 'en-US', 'Refresh'),
  ('MOTOBOY_SAVING', 'en-US', 'Saving...'),
  ('MOTOBOY_SEARCH_ADDRESS', 'en-US', 'Search address on Google Maps'),
  ('MOTOBOY_TITLE', 'en-US', 'Deliveries'),
  ('MOTOBOY_WAZE', 'en-US', 'Waze'),
  ('NO', 'en-US', 'No'),
  ('SALES_ANALYTICS_AVG_TICKET', 'en-US', 'Avg Ticket'),
  ('SALES_ANALYTICS_BACK_PANEL', 'en-US', 'Panel'),
  ('SALES_ANALYTICS_BY_MONTH', 'en-US', 'By month'),
  ('SALES_ANALYTICS_COST_HINT', 'en-US', 'Sum of items'' cost price'),
  ('SALES_ANALYTICS_COST_PREFIX', 'en-US', 'Cost'),
  ('SALES_ANALYTICS_COST_TOTAL', 'en-US', 'Total Cost'),
  ('SALES_ANALYTICS_FULL_YEAR', 'en-US', 'Full year'),
  ('SALES_ANALYTICS_GO_PRODUCTS', 'en-US', 'Products'),
  ('SALES_ANALYTICS_LEGEND_COST', 'en-US', 'Cost'),
  ('SALES_ANALYTICS_LEGEND_PROFIT', 'en-US', 'Profit'),
  ('SALES_ANALYTICS_LEGEND_REVENUE', 'en-US', 'Revenue'),
  ('SALES_ANALYTICS_LOAD_ERROR', 'en-US', 'Failed to load sales analytics.'),
  ('SALES_ANALYTICS_MONTH', 'en-US', 'Month'),
  ('SALES_ANALYTICS_NO_PAID_ORDERS', 'en-US', 'No paid orders to analyze yet.'),
  ('SALES_ANALYTICS_PROFIT_HINT', 'en-US', 'Revenue − Cost'),
  ('SALES_ANALYTICS_PROFIT_PREFIX', 'en-US', 'Profit'),
  ('SALES_ANALYTICS_PROFIT_TOTAL', 'en-US', 'Net Profit'),
  ('SALES_ANALYTICS_REVENUE_HINT', 'en-US', 'Orders with approved payment'),
  ('SALES_ANALYTICS_REVENUE_TOTAL', 'en-US', 'Total Revenue'),
  ('SALES_ANALYTICS_SALES_COUNT', 'en-US', '{{count}} sales'),
  ('SALES_ANALYTICS_STATUS_PAID', 'en-US', 'Paid (approved)'),
  ('SALES_ANALYTICS_STATUS_TITLE', 'en-US', 'Order Status'),
  ('SALES_ANALYTICS_SUBTITLE', 'en-US', 'Revenue, order volume and top flavors in real time.'),
  ('SALES_ANALYTICS_TICKET_HINT', 'en-US', '{{paid}} paid out of {{total}} total'),
  ('SALES_ANALYTICS_TITLE', 'en-US', 'Sales Analytics'),
  ('SALES_ANALYTICS_TODAY', 'en-US', 'Today'),
  ('SALES_ANALYTICS_TOP_FLAVORS', 'en-US', 'Top Flavors'),
  ('SALES_ANALYTICS_TOP_FLAVORS_HINT', 'en-US', 'Based on paid orders'),
  ('YES', 'en-US', 'Yes'),

  -- ==========================================================
  -- ITALIANO (it-IT)
  -- ==========================================================
  ('ADMIN_HISTORY_ADDRESS', 'it-IT', 'Indirizzo'),
  ('ADMIN_HISTORY_BACK', 'it-IT', '← Admin'),
  ('ADMIN_HISTORY_CLEAR', 'it-IT', 'Pulisci'),
  ('ADMIN_HISTORY_CLIENT_NAME', 'it-IT', 'Nome cliente'),
  ('ADMIN_HISTORY_EMPTY', 'it-IT', 'Nessun ordine trovato.'),
  ('ADMIN_HISTORY_FILTER', 'it-IT', 'Filtra'),
  ('ADMIN_HISTORY_FILTERS', 'it-IT', 'Filtri'),
  ('ADMIN_HISTORY_FOUND_MULTI', 'it-IT', 'ordini trovati'),
  ('ADMIN_HISTORY_FOUND_SINGLE', 'it-IT', 'ordine trovato'),
  ('ADMIN_HISTORY_FROM', 'it-IT', 'Da'),
  ('ADMIN_HISTORY_HALF_HALF', 'it-IT', 'Metà e Metà'),
  ('ADMIN_HISTORY_LOAD_ERROR', 'it-IT', 'Errore durante il caricamento dello storico ordini.'),
  ('ADMIN_HISTORY_MARK_PAID', 'it-IT', '✓ Pagato'),
  ('ADMIN_HISTORY_NOTES', 'it-IT', 'Note'),
  ('ADMIN_HISTORY_ONLY_REFUNDS_SUFFIX', 'it-IT', ' — mostra solo rimborsi in sospeso'),
  ('ADMIN_HISTORY_PAYMENT_MARKED', 'it-IT', 'Pagamento contrassegnato come approvato'),
  ('ADMIN_HISTORY_PAYMENT_UPDATE_ERROR', 'it-IT', 'Impossibile aggiornare il pagamento'),
  ('ADMIN_HISTORY_PIZZA', 'it-IT', 'Pizza'),
  ('ADMIN_HISTORY_REFUND_HINT', 'it-IT', 'Il cliente aveva già pagato e il pagamento è stato approvato.'),
  ('ADMIN_HISTORY_REFUND_NEEDS_MULTI', 'it-IT', 'ordini annullati richiedono rimborso'),
  ('ADMIN_HISTORY_REFUND_NEEDS_SINGLE', 'it-IT', 'ordine annullato richiede rimborso'),
  ('ADMIN_HISTORY_REFUND_PENDING', 'it-IT', 'RIMBORSO IN SOSPESO'),
  ('ADMIN_HISTORY_REFUND_WARNING', 'it-IT', 'Ordine annullato dopo pagamento approvato — rimborsare il cliente.'),
  ('ADMIN_HISTORY_SHOW_ALL', 'it-IT', 'Mostra tutti'),
  ('ADMIN_HISTORY_SHOW_REFUNDS', 'it-IT', 'Mostra solo rimborsi'),
  ('ADMIN_HISTORY_SUBTITLE', 'it-IT', 'Tutti gli ordini — consegnati, annullati e in corso.'),
  ('ADMIN_HISTORY_TITLE', 'it-IT', 'Storico Ordini'),
  ('ADMIN_HISTORY_TO', 'it-IT', 'A'),
  ('ADMIN_HISTORY_TOTAL', 'it-IT', 'Totale'),
  ('ADMIN_MESAS_BACK_PANEL', 'it-IT', '← Pannello Admin'),
  ('ADMIN_MESAS_EMPTY', 'it-IT', 'Nessun tavolo registrato ancora.'),
  ('ADMIN_MESAS_EMPTY_HINT_1', 'it-IT', 'Clicca su'),
  ('ADMIN_MESAS_EMPTY_HINT_2', 'it-IT', 'per iniziare.'),
  ('ADMIN_MESAS_HELP_TEXT_1', 'it-IT', 'Nell''app Mercado Pago'),
  ('ADMIN_MESAS_HELP_TEXT_2', 'it-IT', 'Il tuo business → Point'),
  ('ADMIN_MESAS_HELP_TEXT_3', 'it-IT', 'seleziona il dispositivo → copia l''ID mostrato (es:'),
  ('ADMIN_MESAS_HELP_TITLE', 'it-IT', 'Come trovare l''ID del terminale?'),
  ('ADMIN_MESAS_LOAD_ERROR', 'it-IT', 'Impossibile caricare i tavoli.'),
  ('ADMIN_MESAS_LOADING', 'it-IT', 'Caricamento tavoli...'),
  ('ADMIN_MESAS_NEW_BUTTON', 'it-IT', 'Nuovo Tavolo'),
  ('ADMIN_MESAS_TITLE', 'it-IT', 'Tavoli'),
  ('ADMIN_PRODUCTS_ACTIVE', 'it-IT', 'Attivo'),
  ('ADMIN_PRODUCTS_ACTIVE_COUNT', 'it-IT', '{{count}} attivi'),
  ('ADMIN_PRODUCTS_CATEGORY_LABEL', 'it-IT', 'Categoria'),
  ('ADMIN_PRODUCTS_CATEGORY_PLACEHOLDER', 'it-IT', 'Es.: Dolce, Salato, Bevande...'),
  ('ADMIN_PRODUCTS_COST_OPTIONAL', 'it-IT', 'Costo (opzionale)'),
  ('ADMIN_PRODUCTS_CREATE', 'it-IT', 'Crea'),
  ('ADMIN_PRODUCTS_CREATED', 'it-IT', 'Prodotto creato!'),
  ('ADMIN_PRODUCTS_DESCRIPTION_LABEL', 'it-IT', 'Descrizione'),
  ('ADMIN_PRODUCTS_DESCRIPTION_PLACEHOLDER', 'it-IT', 'Breve descrizione del gusto...'),
  ('ADMIN_PRODUCTS_DISABLE', 'it-IT', 'Disattiva'),
  ('ADMIN_PRODUCTS_DISABLED', 'it-IT', 'Prodotto disattivato'),
  ('ADMIN_PRODUCTS_EDIT_TITLE', 'it-IT', 'Modifica Prodotto'),
  ('ADMIN_PRODUCTS_EMPTY', 'it-IT', 'Nessun prodotto registrato ancora.'),
  ('ADMIN_PRODUCTS_IMAGE_URL', 'it-IT', 'URL Immagine'),
  ('ADMIN_PRODUCTS_INACTIVE', 'it-IT', 'Inattivo'),
  ('ADMIN_PRODUCTS_INACTIVE_COUNT', 'it-IT', '{{count}} inattivi'),
  ('ADMIN_PRODUCTS_LOAD_ERROR', 'it-IT', 'Impossibile caricare i prodotti.'),
  ('ADMIN_PRODUCTS_NAME_LABEL', 'it-IT', 'Nome *'),
  ('ADMIN_PRODUCTS_NAME_PLACEHOLDER', 'it-IT', 'Es.: Salame Imperiale'),
  ('ADMIN_PRODUCTS_NEW_BUTTON', 'it-IT', 'Nuovo Prodotto'),
  ('ADMIN_PRODUCTS_NEW_TITLE', 'it-IT', 'Nuovo Prodotto'),
  ('ADMIN_PRODUCTS_PRICE_COST', 'it-IT', 'Prezzo e costo *'),
  ('ADMIN_PRODUCTS_PRICES_BY_SIZE', 'it-IT', 'Prezzi per Taglia *'),
  ('ADMIN_PRODUCTS_RESTORE', 'it-IT', 'Ripristina'),
  ('ADMIN_PRODUCTS_RESTORED', 'it-IT', 'Prodotto ripristinato'),
  ('ADMIN_PRODUCTS_SALE_PRICE', 'it-IT', 'Prezzo di vendita'),
  ('ADMIN_PRODUCTS_SAVE_ERROR', 'it-IT', 'Errore salvataggio prodotto'),
  ('ADMIN_PRODUCTS_SAVING', 'it-IT', 'Salvataggio in corso...'),
  ('ADMIN_PRODUCTS_STATUS_ERROR', 'it-IT', 'Impossibile cambiare lo stato'),
  ('ADMIN_PRODUCTS_SUBTITLE', 'it-IT', 'Gestisci il menu della Pizzaria Fellice'),
  ('ADMIN_PRODUCTS_TITLE', 'it-IT', 'Prodotti'),
  ('ADMIN_PRODUCTS_TYPE_CRUST', 'it-IT', 'Bordo ripieno'),
  ('ADMIN_PRODUCTS_TYPE_FLAVOR', 'it-IT', 'Gusto'),
  ('ADMIN_PRODUCTS_TYPE_LABEL', 'it-IT', 'Tipo di prodotto'),
  ('ADMIN_PRODUCTS_TYPE_OTHER', 'it-IT', 'Altro'),
  ('ADMIN_PRODUCTS_TYPE_PIZZA', 'it-IT', 'Pizza'),
  ('ADMIN_PRODUCTS_UPDATED', 'it-IT', 'Prodotto aggiornato!'),
  ('ADMIN_USERS_BACK_PANEL', 'it-IT', '← Pannello Admin'),
  ('ADMIN_USERS_CREATE_ANOTHER', 'it-IT', 'Crea un altro utente'),
  ('ADMIN_USERS_CREATE_BUTTON', 'it-IT', 'Crea'),
  ('ADMIN_USERS_CREATE_ERROR', 'it-IT', 'Errore durante la creazione dell''utente. Controlla i dati.'),
  ('ADMIN_USERS_CREATED_SUCCESS', 'it-IT', 'Utente creato con successo!'),
  ('ADMIN_USERS_CREATING', 'it-IT', 'Creazione in corso...'),
  ('ADMIN_USERS_EMAIL_LABEL', 'it-IT', 'E-mail'),
  ('ADMIN_USERS_EMAIL_OR_PHONE_REQUIRED', 'it-IT', 'Inserisci email o telefono per l''accesso.'),
  ('ADMIN_USERS_EMAIL_PLACEHOLDER', 'it-IT', 'es@email.com'),
  ('ADMIN_USERS_FIELD_EMAIL', 'it-IT', 'E-mail'),
  ('ADMIN_USERS_FIELD_NAME', 'it-IT', 'Nome'),
  ('ADMIN_USERS_FIELD_PASSWORD', 'it-IT', 'Password'),
  ('ADMIN_USERS_FIELD_PHONE', 'it-IT', 'Telefono'),
  ('ADMIN_USERS_FIELD_ROLE', 'it-IT', 'Ruolo'),
  ('ADMIN_USERS_GENERIC_USER', 'it-IT', 'Utente'),
  ('ADMIN_USERS_NAME_LABEL', 'it-IT', 'Nome completo *'),
  ('ADMIN_USERS_NAME_PLACEHOLDER', 'it-IT', 'Es.: Mario Rossi'),
  ('ADMIN_USERS_PASSWORD_LABEL', 'it-IT', 'Password *'),
  ('ADMIN_USERS_PASSWORD_PLACEHOLDER', 'it-IT', 'Minimo 6 caratteri'),
  ('ADMIN_USERS_PHONE_HINT', 'it-IT', 'Può essere usato per l''accesso invece dell''email.'),
  ('ADMIN_USERS_PHONE_LABEL', 'it-IT', 'Telefono'),
  ('ADMIN_USERS_PHONE_MIN_DIGITS', 'it-IT', 'Il telefono deve avere almeno 10 cifre.'),
  ('ADMIN_USERS_PHONE_PLACEHOLDER', 'it-IT', '+39 333 1234567'),
  ('ADMIN_USERS_ROLE_LABEL', 'it-IT', 'Ruolo *'),
  ('ADMIN_USERS_TITLE', 'it-IT', 'Crea Utente'),
  ('APP_BRAND_NAME', 'it-IT', 'Pizzaria Fellice'),
  ('CHECKOUT_RETURN_BACK_MENU', 'it-IT', 'Torna al menu'),
  ('CHECKOUT_RETURN_CONFIRM_ERROR', 'it-IT', 'Errore di conferma'),
  ('CHECKOUT_RETURN_FAILURE_BUTTON', 'it-IT', 'Riprova'),
  ('CHECKOUT_RETURN_FAILURE_SUBTITLE', 'it-IT', 'C''è stato un problema con il pagamento. Il tuo carrello è ancora salvato.'),
  ('CHECKOUT_RETURN_FAILURE_TITLE', 'it-IT', 'Pagamento non completato'),
  ('CHECKOUT_RETURN_ORDER_PREFIX', 'it-IT', 'Ordine'),
  ('CHECKOUT_RETURN_PENDING_BUTTON', 'it-IT', 'Vedi i miei ordini'),
  ('CHECKOUT_RETURN_PENDING_SUBTITLE', 'it-IT', 'Il pagamento è in fase di elaborazione. La preparazione inizierà non appena confermato.'),
  ('CHECKOUT_RETURN_PENDING_TITLE', 'it-IT', 'Pagamento in sospeso'),
  ('CHECKOUT_RETURN_SUCCESS_BUTTON', 'it-IT', 'Traccia il mio ordine'),
  ('CHECKOUT_RETURN_SUCCESS_SUBTITLE', 'it-IT', 'Il tuo ordine è stato ricevuto e viene preparato con cura.'),
  ('CHECKOUT_RETURN_SUCCESS_TITLE', 'it-IT', 'Pagamento confermato!'),
  ('CLIENT_DASHBOARD_ASK_REASON', 'it-IT', 'Chiedi motivo'),
  ('CLIENT_DASHBOARD_CANCELLED_WHATSAPP', 'it-IT', 'Annullato via WhatsApp'),
  ('CLIENT_DASHBOARD_CLIENT', 'it-IT', 'Cliente'),
  ('CLIENT_DASHBOARD_CONFIRM', 'it-IT', 'Conferma?'),
  ('CLIENT_DASHBOARD_CRUST', 'it-IT', 'Bordo'),
  ('CLIENT_DASHBOARD_DELIVERY', 'it-IT', 'Consegna'),
  ('CLIENT_DASHBOARD_DELIVERY_CODE_HINT', 'it-IT', 'Fornisci questo codice al rider per confermare la consegna'),
  ('CLIENT_DASHBOARD_DELIVERY_CODE_LABEL', 'it-IT', 'Codice di conferma consegna'),
  ('CLIENT_DASHBOARD_EMPTY_ALL', 'it-IT', 'Non hai ancora ordini.'),
  ('CLIENT_DASHBOARD_EMPTY_FILTER', 'it-IT', 'Nessun ordine trovato per questo filtro.'),
  ('CLIENT_DASHBOARD_FILTER_ALL', 'it-IT', 'Tutti'),
  ('CLIENT_DASHBOARD_HALF_HALF', 'it-IT', 'Metà e Metà'),
  ('CLIENT_DASHBOARD_HELLO', 'it-IT', 'Ciao'),
  ('CLIENT_DASHBOARD_LOAD_ERROR', 'it-IT', 'Errore caricamento ordini.'),
  ('CLIENT_DASHBOARD_ORDER_PREFIX', 'it-IT', 'Ordine'),
  ('CLIENT_DASHBOARD_PAYMENT', 'it-IT', 'Pagamento'),
  ('CLIENT_DASHBOARD_PIZZA', 'it-IT', 'Pizza'),
  ('CLIENT_DASHBOARD_REPEAT_ERROR', 'it-IT', 'Impossibile ripetere questo ordine.'),
  ('CLIENT_DASHBOARD_REPEAT_ORDER', 'it-IT', 'Ripeti ordine'),
  ('CLIENT_DASHBOARD_REPEAT_SUCCESS', 'it-IT', 'Ordine aggiunto di nuovo al carrello.'),
  ('DELETE', 'it-IT', 'Elimina'),
  ('EDIT', 'it-IT', 'Modifica'),
  ('FIRST_HALF_CHOOSE_NEXT', 'it-IT', 'Scegli la prossima pizza per completare.'),
  ('FIRST_HALF_SELECTED_MSG', 'it-IT', 'Prima metà selezionata:'),
  ('HOME_ABOUT_P1', 'it-IT', 'Dal 1997, la Pizzaria Fellice è sinonimo di qualità e sapore. Combiniamo ingredienti freschi e selezionati con ricette esclusive per creare pizze che incantano tutti. Che sia nel nostro salone accogliente per momenti speciali, o attraverso il nostro efficiente servizio di consegna, garantiamo un''esperienza gastronomica unica.'),
  ('HOME_ABOUT_P2', 'it-IT', 'Oltre alle nostre pizze, offriamo una deliziosa varietà di antipasti, panini, stuzzichini, patatine e dessert, tutto preparato con la stessa cura e dedizione che ci ha reso un punto di riferimento nella regione.'),
  ('HOME_ABOUT_P3', 'it-IT', 'Scopri perché la Pizzaria Fellice è la scelta giusta per chi cerca tradizione, qualità e un tocco di esclusività. Vieni a trovarci o ordina online e assapora il meglio della gastronomia italiana con il nostro tocco speciale.'),
  ('HOME_HERO_TITLE_1', 'it-IT', 'Autentica'),
  ('HOME_HERO_TITLE_2', 'it-IT', 'pizza italiana'),
  ('HOME_SINCE_1997', 'it-IT', 'Dal 1997 · 27 anni di tradizione italiana'),
  ('KITCHEN_ADVANCE_TO_TABLE', 'it-IT', 'Porta al Tavolo'),
  ('KITCHEN_CLEAR_ALERTS', 'it-IT', 'Pulisci avvisi'),
  ('KITCHEN_DELIVERED_AT_TABLE', 'it-IT', 'Consegnato al Tavolo'),
  ('KITCHEN_DELIVERY', 'it-IT', 'Consegna'),
  ('KITCHEN_DROP_TO_STAGE', 'it-IT', 'Rilascia qui per spostare in {{stage}}'),
  ('KITCHEN_HIGHLIGHT_SECONDS', 'it-IT', 'Evidenziazione attiva per {{seconds}} secondi.'),
  ('KITCHEN_LIVE', 'it-IT', 'In diretta'),
  ('KITCHEN_LOAD_ERROR', 'it-IT', 'Impossibile caricare gli ordini.'),
  ('KITCHEN_MARK_PICKED_UP', 'it-IT', 'Segna Ritirato'),
  ('KITCHEN_NEW_ORDER', 'it-IT', 'Nuovo ordine'),
  ('KITCHEN_NEW_ORDER_ARRIVED', 'it-IT', 'Nuovo ordine {{id}} arrivato in coda'),
  ('KITCHEN_NO_ACTIVE_ORDERS', 'it-IT', 'Nessun ordine attivo al momento.'),
  ('KITCHEN_NO_ALERTS', 'it-IT', 'Nessun avviso in sospeso'),
  ('KITCHEN_NO_ORDER', 'it-IT', 'Nessun ordine'),
  ('KITCHEN_NO_OVERDUE', 'it-IT', 'Nessun ordine in ritardo'),
  ('KITCHEN_OFF', 'it-IT', 'spento'),
  ('KITCHEN_ON', 'it-IT', 'acceso'),
  ('KITCHEN_ORDERS_IN_STAGE', 'it-IT', 'Ordini in questa fase'),
  ('KITCHEN_OVERDUE_ALERT', 'it-IT', '{{count}} ordine/i sono in ritardo'),
  ('KITCHEN_OVERDUE_COUNT', 'it-IT', '{{count}} ordini in ritardo'),
  ('KITCHEN_PAYMENT_PENDING', 'it-IT', 'Pag. in sospeso'),
  ('KITCHEN_PICKUP', 'it-IT', 'Ritiro'),
  ('KITCHEN_READY_PICKUP', 'it-IT', 'Pronto per il Ritiro'),
  ('KITCHEN_SOUND', 'it-IT', 'Suono'),
  ('KITCHEN_TITLE', 'it-IT', 'Cucina'),
  ('KITCHEN_UNREAD_ALERTS', 'it-IT', '{{count}} nuovi avvisi non letti'),
  ('KITCHEN_UPDATED_AT', 'it-IT', 'Aggiornato alle {{time}} • tempo reale con fallback 2 min'),
  ('KITCHEN_UPDATING', 'it-IT', 'Aggiornamento...'),
  ('MESA_ACCESS_INVALID_QR_TEXT_1', 'it-IT', 'Questo codice QR è scaduto o non è più valido.'),
  ('MESA_ACCESS_INVALID_QR_TEXT_2', 'it-IT', 'Chiedi al personale di generarne uno nuovo.'),
  ('MESA_ACCESS_INVALID_QR_TITLE', 'it-IT', 'Codice QR non valido'),
  ('MESA_ACCESS_LOADING', 'it-IT', 'Identificazione tavolo...'),
  ('MESA_CHECKOUT_BACK_MENU', 'it-IT', '← Menu'),
  ('MESA_CHECKOUT_CONFIRM_ORDER', 'it-IT', 'Conferma ordine'),
  ('MESA_CHECKOUT_NOTES_LABEL', 'it-IT', 'Note (opzionale)'),
  ('MESA_CHECKOUT_NOTES_PLACEHOLDER', 'it-IT', 'Es.: senza cipolla, impasto sottile...'),
  ('MESA_CHECKOUT_ORDER_ERROR', 'it-IT', 'Errore durante l''ordine.'),
  ('MESA_CHECKOUT_ORDER_SENT', 'it-IT', 'Ordine inviato in cucina!'),
  ('MESA_CHECKOUT_PAY_LATER', 'it-IT', 'Paga dopo'),
  ('MESA_CHECKOUT_PAY_NOW', 'it-IT', 'Vuoi pagare ora?'),
  ('MESA_CHECKOUT_PAYMENT_CONFIRMED', 'it-IT', 'Pagamento confermato! 🍕'),
  ('MESA_CHECKOUT_PENDING_TOTAL', 'it-IT', 'Totale in sospeso'),
  ('MESA_CHECKOUT_PIX_SHORT', 'it-IT', 'PIX'),
  ('MESA_CHECKOUT_SENDING', 'it-IT', 'Invio...'),
  ('MESA_CHECKOUT_SESSION_ORDERS', 'it-IT', 'Ordini di questa sessione'),
  ('MESA_CHECKOUT_TABLE', 'it-IT', 'Tavolo'),
  ('MESA_CHECKOUT_TERMINAL_SHORT', 'it-IT', 'Pos'),
  ('MESA_CHECKOUT_VIEW_MENU', 'it-IT', 'Vedi menu'),
  ('MESA_CHECKOUT_YOUR_ORDER', 'it-IT', 'Il tuo ordine'),
  ('MESA_PIX_COPIED', 'it-IT', 'Codice copiato!'),
  ('MESA_PIX_COPY_BUTTON', 'it-IT', 'Copia codice PIX'),
  ('MESA_PIX_COPY_HINT', 'it-IT', 'O copia il codice:'),
  ('MESA_PIX_ERROR', 'it-IT', 'Errore generazione PIX. Riprova.'),
  ('MESA_PIX_GENERATING', 'it-IT', 'Generazione QR Code...'),
  ('MESA_PIX_QR_ALT', 'it-IT', 'QR Code PIX'),
  ('MESA_PIX_TITLE', 'it-IT', 'Paga con PIX'),
  ('MESA_PIX_WAITING', 'it-IT', 'In attesa di conferma pagamento...'),
  ('MESA_TERMINAL_SEND_BUTTON', 'it-IT', 'Invia al Pos'),
  ('MESA_TERMINAL_SEND_ERROR', 'it-IT', 'Errore invio al Pos.'),
  ('MESA_TERMINAL_SENDING', 'it-IT', 'Invio...'),
  ('MESA_TERMINAL_SENT', 'it-IT', 'Addebito inviato al Pos!'),
  ('MESA_TERMINAL_TITLE', 'it-IT', 'Paga al Pos'),
  ('MESA_TERMINAL_WAITING', 'it-IT', 'In attesa di pagamento al Pos...'),
  ('MONTH_LABEL_APR', 'it-IT', 'Aprile'),
  ('MONTH_LABEL_AUG', 'it-IT', 'Agosto'),
  ('MONTH_LABEL_DEC', 'it-IT', 'Dicembre'),
  ('MONTH_LABEL_FEB', 'it-IT', 'Febbraio'),
  ('MONTH_LABEL_JAN', 'it-IT', 'Gennaio'),
  ('MONTH_LABEL_JUL', 'it-IT', 'Luglio'),
  ('MONTH_LABEL_JUN', 'it-IT', 'Giugno'),
  ('MONTH_LABEL_MAR', 'it-IT', 'Marzo'),
  ('MONTH_LABEL_MAY', 'it-IT', 'Maggio'),
  ('MONTH_LABEL_NOV', 'it-IT', 'Novembre'),
  ('MONTH_LABEL_OCT', 'it-IT', 'Ottobre'),
  ('MONTH_LABEL_SEP', 'it-IT', 'Settembre'),
  ('MONTH_SHORT_APR', 'it-IT', 'Apr'),
  ('MONTH_SHORT_AUG', 'it-IT', 'Ago'),
  ('MONTH_SHORT_DEC', 'it-IT', 'Dic'),
  ('MONTH_SHORT_FEB', 'it-IT', 'Feb'),
  ('MONTH_SHORT_JAN', 'it-IT', 'Gen'),
  ('MONTH_SHORT_JUL', 'it-IT', 'Lug'),
  ('MONTH_SHORT_JUN', 'it-IT', 'Giu'),
  ('MONTH_SHORT_MAR', 'it-IT', 'Mar'),
  ('MONTH_SHORT_MAY', 'it-IT', 'Mag'),
  ('MONTH_SHORT_NOV', 'it-IT', 'Nov'),
  ('MONTH_SHORT_OCT', 'it-IT', 'Ott'),
  ('MONTH_SHORT_SEP', 'it-IT', 'Set'),
  ('MOTOBOY_ADDRESS', 'it-IT', 'Indirizzo'),
  ('MOTOBOY_ALREADY_PAID', 'it-IT', 'Già pagato'),
  ('MOTOBOY_AUTO_REFRESH_HINT', 'it-IT', 'Questa pagina si aggiorna ogni 20 secondi.'),
  ('MOTOBOY_CODE_PLACEHOLDER', 'it-IT', 'Es.: 1234'),
  ('MOTOBOY_COLLECT_ON_DELIVERY', 'it-IT', 'Riscuoti dal cliente alla consegna'),
  ('MOTOBOY_CONFIRM', 'it-IT', 'Conferma'),
  ('MOTOBOY_CONFIRM_DELIVERY_CODE', 'it-IT', 'Conferma consegna con codice'),
  ('MOTOBOY_CONFIRM_PAYMENT_TEXT', 'it-IT', 'Segna come pagato solo dopo aver ricevuto l''importo.'),
  ('MOTOBOY_CONFIRM_PAYMENT_TITLE', 'it-IT', 'Confermare il pagamento?'),
  ('MOTOBOY_CONFIRM_PAYMENT_YES', 'it-IT', 'Sì, segna come pagato'),
  ('MOTOBOY_CONFIRMING', 'it-IT', 'Conferma...'),
  ('MOTOBOY_DELIVERY_CONFIRM_ERROR', 'it-IT', 'Impossibile confermare la consegna.'),
  ('MOTOBOY_DELIVERY_CONFIRMED', 'it-IT', 'Consegna confermata con successo.'),
  ('MOTOBOY_DELIVERY_FEE', 'it-IT', 'Spedizione'),
  ('MOTOBOY_EMPTY', 'it-IT', 'Nessun ordine pronto per la consegna al momento.'),
  ('MOTOBOY_GOOGLE_MAPS', 'it-IT', 'Google Maps'),
  ('MOTOBOY_LOAD_ERROR', 'it-IT', 'Errore caricamento ordini. Prova ad aggiornare.'),
  ('MOTOBOY_LOADING', 'it-IT', 'Caricamento...'),
  ('MOTOBOY_MARK_PAID', 'it-IT', 'Segna come pagato'),
  ('MOTOBOY_MARK_PAID_FIRST', 'it-IT', 'Per confermare la consegna, segna prima l''ordine come pagato.'),
  ('MOTOBOY_ORDER_PREFIX', 'it-IT', 'Ordine'),
  ('MOTOBOY_ORDER_TOTAL', 'it-IT', 'Totale Ordine'),
  ('MOTOBOY_PAYMENT_CONFIRM_ERROR', 'it-IT', 'Impossibile confermare il pagamento.'),
  ('MOTOBOY_PAYMENT_MARKED', 'it-IT', 'Pagamento approvato.'),
  ('MOTOBOY_REFRESH', 'it-IT', 'Aggiorna'),
  ('MOTOBOY_SAVING', 'it-IT', 'Salvataggio in corso...'),
  ('MOTOBOY_SEARCH_ADDRESS', 'it-IT', 'Cerca indirizzo su Google Maps'),
  ('MOTOBOY_TITLE', 'it-IT', 'Consegne'),
  ('MOTOBOY_WAZE', 'it-IT', 'Waze'),
  ('NO', 'it-IT', 'No'),
  ('SALES_ANALYTICS_AVG_TICKET', 'it-IT', 'Scontrino Medio'),
  ('SALES_ANALYTICS_BACK_PANEL', 'it-IT', 'Pannello'),
  ('SALES_ANALYTICS_BY_MONTH', 'it-IT', 'Per mese'),
  ('SALES_ANALYTICS_COST_HINT', 'it-IT', 'Somma del prezzo di costo degli articoli'),
  ('SALES_ANALYTICS_COST_PREFIX', 'it-IT', 'Costo'),
  ('SALES_ANALYTICS_COST_TOTAL', 'it-IT', 'Costo Totale'),
  ('SALES_ANALYTICS_FULL_YEAR', 'it-IT', 'Intero anno'),
  ('SALES_ANALYTICS_GO_PRODUCTS', 'it-IT', 'Prodotti'),
  ('SALES_ANALYTICS_LEGEND_COST', 'it-IT', 'Costo'),
  ('SALES_ANALYTICS_LEGEND_PROFIT', 'it-IT', 'Profitto'),
  ('SALES_ANALYTICS_LEGEND_REVENUE', 'it-IT', 'Ricavi'),
  ('SALES_ANALYTICS_LOAD_ERROR', 'it-IT', 'Impossibile caricare le analisi di vendita.'),
  ('SALES_ANALYTICS_MONTH', 'it-IT', 'Mese'),
  ('SALES_ANALYTICS_NO_PAID_ORDERS', 'it-IT', 'Ancora nessun ordine pagato da analizzare.'),
  ('SALES_ANALYTICS_PROFIT_HINT', 'it-IT', 'Ricavi − Costo'),
  ('SALES_ANALYTICS_PROFIT_PREFIX', 'it-IT', 'Profitto'),
  ('SALES_ANALYTICS_PROFIT_TOTAL', 'it-IT', 'Profitto Netto'),
  ('SALES_ANALYTICS_REVENUE_HINT', 'it-IT', 'Ordini con pagamento approvato'),
  ('SALES_ANALYTICS_REVENUE_TOTAL', 'it-IT', 'Ricavi Totali'),
  ('SALES_ANALYTICS_SALES_COUNT', 'it-IT', '{{count}} vendite'),
  ('SALES_ANALYTICS_STATUS_PAID', 'it-IT', 'Pagati (approvati)'),
  ('SALES_ANALYTICS_STATUS_TITLE', 'it-IT', 'Stato Ordini'),
  ('SALES_ANALYTICS_SUBTITLE', 'it-IT', 'Ricavi, volume ordini e migliori gusti in tempo reale.'),
  ('SALES_ANALYTICS_TICKET_HINT', 'it-IT', '{{paid}} pagati su {{total}} totali'),
  ('SALES_ANALYTICS_TITLE', 'it-IT', 'Analisi Vendite'),
  ('SALES_ANALYTICS_TODAY', 'it-IT', 'Oggi'),
  ('SALES_ANALYTICS_TOP_FLAVORS', 'it-IT', 'Migliori Gusti'),
  ('SALES_ANALYTICS_TOP_FLAVORS_HINT', 'it-IT', 'Basato su ordini pagati'),
  ('YES', 'it-IT', 'Sì'),

  -- ==========================================================
  -- PORTUGUÊS DE PORTUGAL (pt-PT)
  -- ==========================================================
  ('ADMIN_HISTORY_ADDRESS', 'pt-PT', 'Morada'),
  ('ADMIN_HISTORY_BACK', 'pt-PT', '← Admin'),
  ('ADMIN_HISTORY_CLEAR', 'pt-PT', 'Limpar'),
  ('ADMIN_HISTORY_CLIENT_NAME', 'pt-PT', 'Nome do cliente'),
  ('ADMIN_HISTORY_EMPTY', 'pt-PT', 'Nenhum pedido encontrado.'),
  ('ADMIN_HISTORY_FILTER', 'pt-PT', 'Filtrar'),
  ('ADMIN_HISTORY_FILTERS', 'pt-PT', 'Filtros'),
  ('ADMIN_HISTORY_FOUND_MULTI', 'pt-PT', 'pedidos encontrados'),
  ('ADMIN_HISTORY_FOUND_SINGLE', 'pt-PT', 'pedido encontrado'),
  ('ADMIN_HISTORY_FROM', 'pt-PT', 'De'),
  ('ADMIN_HISTORY_HALF_HALF', 'pt-PT', 'Metade a Metade'),
  ('ADMIN_HISTORY_LOAD_ERROR', 'pt-PT', 'Erro ao carregar histórico de pedidos.'),
  ('ADMIN_HISTORY_MARK_PAID', 'pt-PT', '✓ Pago'),
  ('ADMIN_HISTORY_NOTES', 'pt-PT', 'Notas'),
  ('ADMIN_HISTORY_ONLY_REFUNDS_SUFFIX', 'pt-PT', ' — a mostrar apenas estornos pendentes'),
  ('ADMIN_HISTORY_PAYMENT_MARKED', 'pt-PT', 'Pagamento marcado como aprovado'),
  ('ADMIN_HISTORY_PAYMENT_UPDATE_ERROR', 'pt-PT', 'Falha ao atualizar pagamento'),
  ('ADMIN_HISTORY_PIZZA', 'pt-PT', 'Pizza'),
  ('ADMIN_HISTORY_REFUND_HINT', 'pt-PT', 'O cliente já havia pago e o pagamento foi aprovado.'),
  ('ADMIN_HISTORY_REFUND_NEEDS_MULTI', 'pt-PT', 'pedidos cancelados precisam de estorno'),
  ('ADMIN_HISTORY_REFUND_NEEDS_SINGLE', 'pt-PT', 'pedido cancelado precisa de estorno'),
  ('ADMIN_HISTORY_REFUND_PENDING', 'pt-PT', 'ESTORNO PENDENTE'),
  ('ADMIN_HISTORY_REFUND_WARNING', 'pt-PT', 'Pedido cancelado após pagamento aprovado — efetuar estorno ao cliente.'),
  ('ADMIN_HISTORY_SHOW_ALL', 'pt-PT', 'Ver todos'),
  ('ADMIN_HISTORY_SHOW_REFUNDS', 'pt-PT', 'Ver só estornos'),
  ('ADMIN_HISTORY_SUBTITLE', 'pt-PT', 'Todos os pedidos — entregues, cancelados e em andamento.'),
  ('ADMIN_HISTORY_TITLE', 'pt-PT', 'Histórico de Pedidos'),
  ('ADMIN_HISTORY_TO', 'pt-PT', 'Até'),
  ('ADMIN_HISTORY_TOTAL', 'pt-PT', 'Total'),
  ('ADMIN_MESAS_BACK_PANEL', 'pt-PT', '← Painel Admin'),
  ('ADMIN_MESAS_EMPTY', 'pt-PT', 'Nenhuma mesa registada ainda.'),
  ('ADMIN_MESAS_EMPTY_HINT_1', 'pt-PT', 'Clique em'),
  ('ADMIN_MESAS_EMPTY_HINT_2', 'pt-PT', 'para começar.'),
  ('ADMIN_MESAS_HELP_TEXT_1', 'pt-PT', 'Na app do Mercado Pago'),
  ('ADMIN_MESAS_HELP_TEXT_2', 'pt-PT', 'O seu negócio → Point'),
  ('ADMIN_MESAS_HELP_TEXT_3', 'pt-PT', 'selecione o dispositivo → copie o ID que aparece (ex:'),
  ('ADMIN_MESAS_HELP_TITLE', 'pt-PT', 'Como encontrar o ID do terminal?'),
  ('ADMIN_MESAS_LOAD_ERROR', 'pt-PT', 'Falha ao carregar mesas.'),
  ('ADMIN_MESAS_LOADING', 'pt-PT', 'A carregar mesas...'),
  ('ADMIN_MESAS_NEW_BUTTON', 'pt-PT', 'Nova Mesa'),
  ('ADMIN_MESAS_TITLE', 'pt-PT', 'Mesas'),
  ('ADMIN_PRODUCTS_ACTIVE', 'pt-PT', 'Ativo'),
  ('ADMIN_PRODUCTS_ACTIVE_COUNT', 'pt-PT', '{{count}} ativos'),
  ('ADMIN_PRODUCTS_CATEGORY_LABEL', 'pt-PT', 'Categoria'),
  ('ADMIN_PRODUCTS_CATEGORY_PLACEHOLDER', 'pt-PT', 'Ex: Doce, Salgado, Bebidas...'),
  ('ADMIN_PRODUCTS_COST_OPTIONAL', 'pt-PT', 'Custo (opcional)'),
  ('ADMIN_PRODUCTS_CREATE', 'pt-PT', 'Criar'),
  ('ADMIN_PRODUCTS_CREATED', 'pt-PT', 'Produto criado!'),
  ('ADMIN_PRODUCTS_DESCRIPTION_LABEL', 'pt-PT', 'Descrição'),
  ('ADMIN_PRODUCTS_DESCRIPTION_PLACEHOLDER', 'pt-PT', 'Breve descrição do sabor...'),
  ('ADMIN_PRODUCTS_DISABLE', 'pt-PT', 'Desativar'),
  ('ADMIN_PRODUCTS_DISABLED', 'pt-PT', 'Produto desativado'),
  ('ADMIN_PRODUCTS_EDIT_TITLE', 'pt-PT', 'Editar Produto'),
  ('ADMIN_PRODUCTS_EMPTY', 'pt-PT', 'Nenhum produto registado ainda.'),
  ('ADMIN_PRODUCTS_IMAGE_URL', 'pt-PT', 'URL da Imagem'),
  ('ADMIN_PRODUCTS_INACTIVE', 'pt-PT', 'Inativo'),
  ('ADMIN_PRODUCTS_INACTIVE_COUNT', 'pt-PT', '{{count}} inativos'),
  ('ADMIN_PRODUCTS_LOAD_ERROR', 'pt-PT', 'Falha ao carregar produtos.'),
  ('ADMIN_PRODUCTS_NAME_LABEL', 'pt-PT', 'Nome *'),
  ('ADMIN_PRODUCTS_NAME_PLACEHOLDER', 'pt-PT', 'Ex: Calabresa Imperial'),
  ('ADMIN_PRODUCTS_NEW_BUTTON', 'pt-PT', 'Novo Produto'),
  ('ADMIN_PRODUCTS_NEW_TITLE', 'pt-PT', 'Novo Produto'),
  ('ADMIN_PRODUCTS_PRICE_COST', 'pt-PT', 'Preço e custo *'),
  ('ADMIN_PRODUCTS_PRICES_BY_SIZE', 'pt-PT', 'Preços por Tamanho *'),
  ('ADMIN_PRODUCTS_RESTORE', 'pt-PT', 'Restaurar'),
  ('ADMIN_PRODUCTS_RESTORED', 'pt-PT', 'Produto restaurado'),
  ('ADMIN_PRODUCTS_SALE_PRICE', 'pt-PT', 'Preço de venda'),
  ('ADMIN_PRODUCTS_SAVE_ERROR', 'pt-PT', 'Erro ao guardar produto'),
  ('ADMIN_PRODUCTS_SAVING', 'pt-PT', 'A guardar...'),
  ('ADMIN_PRODUCTS_STATUS_ERROR', 'pt-PT', 'Falha ao alterar estado'),
  ('ADMIN_PRODUCTS_SUBTITLE', 'pt-PT', 'Gerir a ementa da Pizzaria Fellice'),
  ('ADMIN_PRODUCTS_TITLE', 'pt-PT', 'Produtos'),
  ('ADMIN_PRODUCTS_TYPE_CRUST', 'pt-PT', 'Bordo recheado'),
  ('ADMIN_PRODUCTS_TYPE_FLAVOR', 'pt-PT', 'Sabor'),
  ('ADMIN_PRODUCTS_TYPE_LABEL', 'pt-PT', 'Tipo do produto'),
  ('ADMIN_PRODUCTS_TYPE_OTHER', 'pt-PT', 'Outros'),
  ('ADMIN_PRODUCTS_TYPE_PIZZA', 'pt-PT', 'Pizza'),
  ('ADMIN_PRODUCTS_UPDATED', 'pt-PT', 'Produto atualizado!'),
  ('ADMIN_USERS_BACK_PANEL', 'pt-PT', '← Painel Admin'),
  ('ADMIN_USERS_CREATE_ANOTHER', 'pt-PT', 'Criar outro utilizador'),
  ('ADMIN_USERS_CREATE_BUTTON', 'pt-PT', 'Criar'),
  ('ADMIN_USERS_CREATE_ERROR', 'pt-PT', 'Erro ao criar utilizador. Verifique os dados.'),
  ('ADMIN_USERS_CREATED_SUCCESS', 'pt-PT', 'Utilizador criado com sucesso!'),
  ('ADMIN_USERS_CREATING', 'pt-PT', 'A criar...'),
  ('ADMIN_USERS_EMAIL_LABEL', 'pt-PT', 'E-mail'),
  ('ADMIN_USERS_EMAIL_OR_PHONE_REQUIRED', 'pt-PT', 'Forneça e-mail ou telefone para login.'),
  ('ADMIN_USERS_EMAIL_PLACEHOLDER', 'pt-PT', 'ex@email.com'),
  ('ADMIN_USERS_FIELD_EMAIL', 'pt-PT', 'E-mail'),
  ('ADMIN_USERS_FIELD_NAME', 'pt-PT', 'Nome'),
  ('ADMIN_USERS_FIELD_PASSWORD', 'pt-PT', 'Palavra-passe'),
  ('ADMIN_USERS_FIELD_PHONE', 'pt-PT', 'Telefone'),
  ('ADMIN_USERS_FIELD_ROLE', 'pt-PT', 'Perfil'),
  ('ADMIN_USERS_GENERIC_USER', 'pt-PT', 'Utilizador'),
  ('ADMIN_USERS_NAME_LABEL', 'pt-PT', 'Nome completo *'),
  ('ADMIN_USERS_NAME_PLACEHOLDER', 'pt-PT', 'Ex: João Silva'),
  ('ADMIN_USERS_PASSWORD_LABEL', 'pt-PT', 'Palavra-passe *'),
  ('ADMIN_USERS_PASSWORD_PLACEHOLDER', 'pt-PT', 'Mínimo 6 caracteres'),
  ('ADMIN_USERS_PHONE_HINT', 'pt-PT', 'Pode ser usado para login no lugar do e-mail.'),
  ('ADMIN_USERS_PHONE_LABEL', 'pt-PT', 'Telefone'),
  ('ADMIN_USERS_PHONE_MIN_DIGITS', 'pt-PT', 'O telefone deve ter pelo menos 10 dígitos.'),
  ('ADMIN_USERS_PHONE_PLACEHOLDER', 'pt-PT', '+351 912345678'),
  ('ADMIN_USERS_ROLE_LABEL', 'pt-PT', 'Perfil *'),
  ('ADMIN_USERS_TITLE', 'pt-PT', 'Criar Utilizador'),
  ('APP_BRAND_NAME', 'pt-PT', 'Pizzaria Fellice'),
  ('CHECKOUT_RETURN_BACK_MENU', 'pt-PT', 'Voltar à ementa'),
  ('CHECKOUT_RETURN_CONFIRM_ERROR', 'pt-PT', 'Erro ao confirmar'),
  ('CHECKOUT_RETURN_FAILURE_BUTTON', 'pt-PT', 'Tentar novamente'),
  ('CHECKOUT_RETURN_FAILURE_SUBTITLE', 'pt-PT', 'Ocorreu um problema com o pagamento. O seu carrinho ainda está guardado.'),
  ('CHECKOUT_RETURN_FAILURE_TITLE', 'pt-PT', 'Pagamento não concluído'),
  ('CHECKOUT_RETURN_ORDER_PREFIX', 'pt-PT', 'Pedido'),
  ('CHECKOUT_RETURN_PENDING_BUTTON', 'pt-PT', 'Ver os meus pedidos'),
  ('CHECKOUT_RETURN_PENDING_SUBTITLE', 'pt-PT', 'O seu pagamento está a ser processado. Assim que for confirmado, a preparação será iniciada.'),
  ('CHECKOUT_RETURN_PENDING_TITLE', 'pt-PT', 'Pagamento em análise'),
  ('CHECKOUT_RETURN_SUCCESS_BUTTON', 'pt-PT', 'Acompanhar o meu pedido'),
  ('CHECKOUT_RETURN_SUCCESS_SUBTITLE', 'pt-PT', 'O seu pedido foi recebido e já está a ser preparado com carinho.'),
  ('CHECKOUT_RETURN_SUCCESS_TITLE', 'pt-PT', 'Pagamento confirmado!'),
  ('CLIENT_DASHBOARD_ASK_REASON', 'pt-PT', 'Perguntar motivo'),
  ('CLIENT_DASHBOARD_CANCELLED_WHATSAPP', 'pt-PT', 'Cancelado (WhatsApp)'),
  ('CLIENT_DASHBOARD_CLIENT', 'pt-PT', 'Cliente'),
  ('CLIENT_DASHBOARD_CONFIRM', 'pt-PT', 'Confirmar?'),
  ('CLIENT_DASHBOARD_CRUST', 'pt-PT', 'Bordo'),
  ('CLIENT_DASHBOARD_DELIVERY', 'pt-PT', 'Entrega'),
  ('CLIENT_DASHBOARD_DELIVERY_CODE_HINT', 'pt-PT', 'Forneça este código ao estafeta para confirmar a entrega'),
  ('CLIENT_DASHBOARD_DELIVERY_CODE_LABEL', 'pt-PT', 'Código de confirmação de entrega'),
  ('CLIENT_DASHBOARD_EMPTY_ALL', 'pt-PT', 'Ainda não tem pedidos.'),
  ('CLIENT_DASHBOARD_EMPTY_FILTER', 'pt-PT', 'Nenhum pedido encontrado para este filtro.'),
  ('CLIENT_DASHBOARD_FILTER_ALL', 'pt-PT', 'Todos'),
  ('CLIENT_DASHBOARD_HALF_HALF', 'pt-PT', 'Metade a Metade'),
  ('CLIENT_DASHBOARD_HELLO', 'pt-PT', 'Olá'),
  ('CLIENT_DASHBOARD_LOAD_ERROR', 'pt-PT', 'Erro ao carregar pedidos.'),
  ('CLIENT_DASHBOARD_ORDER_PREFIX', 'pt-PT', 'Pedido'),
  ('CLIENT_DASHBOARD_PAYMENT', 'pt-PT', 'Pagamento'),
  ('CLIENT_DASHBOARD_PIZZA', 'pt-PT', 'Pizza'),
  ('CLIENT_DASHBOARD_REPEAT_ERROR', 'pt-PT', 'Não foi possível repetir este pedido.'),
  ('CLIENT_DASHBOARD_REPEAT_ORDER', 'pt-PT', 'Repetir pedido'),
  ('CLIENT_DASHBOARD_REPEAT_SUCCESS', 'pt-PT', 'Pedido adicionado novamente ao carrinho.'),
  ('DELETE', 'pt-PT', 'Eliminar'),
  ('EDIT', 'pt-PT', 'Editar'),
  ('FIRST_HALF_CHOOSE_NEXT', 'pt-PT', 'Escolha a próxima pizza para completar.'),
  ('FIRST_HALF_SELECTED_MSG', 'pt-PT', 'Primeira metade selecionada:'),
  ('HOME_ABOUT_P1', 'pt-PT', 'Desde 1997, a Pizzaria Fellice é sinónimo de qualidade e sabor. Combinamos ingredientes frescos e seleccionados com receitas exclusivas para criar pizzas que encantam a todos. Seja no nosso salão, que oferece um ambiente acolhedor para momentos especiais, ou através do nosso eficiente serviço de entrega, garantimos uma experiência gastronómica única.'),
  ('HOME_ABOUT_P2', 'pt-PT', 'Além das nossas pizzas, oferecemos uma deliciosa variedade de porções, beirutes, petiscos, batatas e sobremesas, tudo preparado com o mesmo cuidado e dedicação que nos tornaram referência na região.'),
  ('HOME_ABOUT_P3', 'pt-PT', 'Descubra por que a Pizzaria Fellice é a escolha certa para quem procura tradição, qualidade e um toque de exclusividade. Visite-nos ou faça o seu pedido online e saboreie o melhor da gastronomia italiana com o nosso toque especial.'),
  ('HOME_HERO_TITLE_1', 'pt-PT', 'Autêntica'),
  ('HOME_HERO_TITLE_2', 'pt-PT', 'pizza italiana'),
  ('HOME_SINCE_1997', 'pt-PT', 'Desde 1997 · 27 anos de tradição italiana'),
  ('KITCHEN_ADVANCE_TO_TABLE', 'pt-PT', 'Levar para a Mesa'),
  ('KITCHEN_CLEAR_ALERTS', 'pt-PT', 'Limpar alertas'),
  ('KITCHEN_DELIVERED_AT_TABLE', 'pt-PT', 'Entregue na Mesa'),
  ('KITCHEN_DELIVERY', 'pt-PT', 'Entrega'),
  ('KITCHEN_DROP_TO_STAGE', 'pt-PT', 'Solte aqui para mover para {{stage}}'),
  ('KITCHEN_HIGHLIGHT_SECONDS', 'pt-PT', 'Destaque ativo por {{seconds}} segundos.'),
  ('KITCHEN_LIVE', 'pt-PT', 'Ao vivo'),
  ('KITCHEN_LOAD_ERROR', 'pt-PT', 'Falha ao carregar pedidos.'),
  ('KITCHEN_MARK_PICKED_UP', 'pt-PT', 'Marcar Levantado'),
  ('KITCHEN_NEW_ORDER', 'pt-PT', 'Novo pedido'),
  ('KITCHEN_NEW_ORDER_ARRIVED', 'pt-PT', 'Novo pedido {{id}} chegou à fila'),
  ('KITCHEN_NO_ACTIVE_ORDERS', 'pt-PT', 'Sem pedidos ativos no momento.'),
  ('KITCHEN_NO_ALERTS', 'pt-PT', 'Nenhum alerta pendente'),
  ('KITCHEN_NO_ORDER', 'pt-PT', 'Nenhum pedido'),
  ('KITCHEN_NO_OVERDUE', 'pt-PT', 'Sem pedidos em atraso'),
  ('KITCHEN_OFF', 'pt-PT', 'desligado'),
  ('KITCHEN_ON', 'pt-PT', 'ligado'),
  ('KITCHEN_ORDERS_IN_STAGE', 'pt-PT', 'Pedidos nesta fase'),
  ('KITCHEN_OVERDUE_ALERT', 'pt-PT', '{{count}} pedido(s) entraram em atraso'),
  ('KITCHEN_OVERDUE_COUNT', 'pt-PT', '{{count}} pedidos em atraso'),
  ('KITCHEN_PAYMENT_PENDING', 'pt-PT', 'Pag. pendente'),
  ('KITCHEN_PICKUP', 'pt-PT', 'Levantamento'),
  ('KITCHEN_READY_PICKUP', 'pt-PT', 'Pronto para Levantamento'),
  ('KITCHEN_SOUND', 'pt-PT', 'Som'),
  ('KITCHEN_TITLE', 'pt-PT', 'Cozinha'),
  ('KITCHEN_UNREAD_ALERTS', 'pt-PT', '{{count}} novos alertas não lidos'),
  ('KITCHEN_UPDATED_AT', 'pt-PT', 'Atualizado às {{time}} • tempo real com fallback 2 min'),
  ('KITCHEN_UPDATING', 'pt-PT', 'A atualizar...'),
  ('MESA_ACCESS_INVALID_QR_TEXT_1', 'pt-PT', 'Este código QR expirou ou já não é válido.'),
  ('MESA_ACCESS_INVALID_QR_TEXT_2', 'pt-PT', 'Peça a um funcionário para gerar um novo.'),
  ('MESA_ACCESS_INVALID_QR_TITLE', 'pt-PT', 'Código QR inválido'),
  ('MESA_ACCESS_LOADING', 'pt-PT', 'A identificar mesa...'),
  ('MESA_CHECKOUT_BACK_MENU', 'pt-PT', '← Ementa'),
  ('MESA_CHECKOUT_CONFIRM_ORDER', 'pt-PT', 'Confirmar pedido'),
  ('MESA_CHECKOUT_NOTES_LABEL', 'pt-PT', 'Notas (opcional)'),
  ('MESA_CHECKOUT_NOTES_PLACEHOLDER', 'pt-PT', 'Ex: sem cebola, massa fina...'),
  ('MESA_CHECKOUT_ORDER_ERROR', 'pt-PT', 'Erro ao fazer pedido.'),
  ('MESA_CHECKOUT_ORDER_SENT', 'pt-PT', 'Pedido enviado para a cozinha!'),
  ('MESA_CHECKOUT_PAY_LATER', 'pt-PT', 'Pagar depois'),
  ('MESA_CHECKOUT_PAY_NOW', 'pt-PT', 'Deseja pagar agora?'),
  ('MESA_CHECKOUT_PAYMENT_CONFIRMED', 'pt-PT', 'Pagamento confirmado! 🍕'),
  ('MESA_CHECKOUT_PENDING_TOTAL', 'pt-PT', 'Total pendente'),
  ('MESA_CHECKOUT_PIX_SHORT', 'pt-PT', 'MB WAY'),
  ('MESA_CHECKOUT_SENDING', 'pt-PT', 'A enviar...'),
  ('MESA_CHECKOUT_SESSION_ORDERS', 'pt-PT', 'Pedidos desta sessão'),
  ('MESA_CHECKOUT_TABLE', 'pt-PT', 'Mesa'),
  ('MESA_CHECKOUT_TERMINAL_SHORT', 'pt-PT', 'Terminal'),
  ('MESA_CHECKOUT_VIEW_MENU', 'pt-PT', 'Ver ementa'),
  ('MESA_CHECKOUT_YOUR_ORDER', 'pt-PT', 'O seu pedido'),
  ('MESA_PIX_COPIED', 'pt-PT', 'Código copiado!'),
  ('MESA_PIX_COPY_BUTTON', 'pt-PT', 'Copiar código'),
  ('MESA_PIX_COPY_HINT', 'pt-PT', 'Ou copie o código:'),
  ('MESA_PIX_ERROR', 'pt-PT', 'Erro ao gerar referência. Tente novamente.'),
  ('MESA_PIX_GENERATING', 'pt-PT', 'A gerar QR Code...'),
  ('MESA_PIX_QR_ALT', 'pt-PT', 'QR Code'),
  ('MESA_PIX_TITLE', 'pt-PT', 'Pagar'),
  ('MESA_PIX_WAITING', 'pt-PT', 'A aguardar confirmação de pagamento...'),
  ('MESA_TERMINAL_SEND_BUTTON', 'pt-PT', 'Enviar para terminal'),
  ('MESA_TERMINAL_SEND_ERROR', 'pt-PT', 'Erro ao enviar para terminal.'),
  ('MESA_TERMINAL_SENDING', 'pt-PT', 'A enviar...'),
  ('MESA_TERMINAL_SENT', 'pt-PT', 'Cobrança enviada para o terminal!'),
  ('MESA_TERMINAL_TITLE', 'pt-PT', 'Pagar no Terminal'),
  ('MESA_TERMINAL_WAITING', 'pt-PT', 'A aguardar pagamento no terminal...'),
  ('MONTH_LABEL_APR', 'pt-PT', 'Abril'),
  ('MONTH_LABEL_AUG', 'pt-PT', 'Agosto'),
  ('MONTH_LABEL_DEC', 'pt-PT', 'Dezembro'),
  ('MONTH_LABEL_FEB', 'pt-PT', 'Fevereiro'),
  ('MONTH_LABEL_JAN', 'pt-PT', 'Janeiro'),
  ('MONTH_LABEL_JUL', 'pt-PT', 'Julho'),
  ('MONTH_LABEL_JUN', 'pt-PT', 'Junho'),
  ('MONTH_LABEL_MAR', 'pt-PT', 'Março'),
  ('MONTH_LABEL_MAY', 'pt-PT', 'Maio'),
  ('MONTH_LABEL_NOV', 'pt-PT', 'Novembro'),
  ('MONTH_LABEL_OCT', 'pt-PT', 'Outubro'),
  ('MONTH_LABEL_SEP', 'pt-PT', 'Setembro'),
  ('MONTH_SHORT_APR', 'pt-PT', 'Abr'),
  ('MONTH_SHORT_AUG', 'pt-PT', 'Ago'),
  ('MONTH_SHORT_DEC', 'pt-PT', 'Dez'),
  ('MONTH_SHORT_FEB', 'pt-PT', 'Fev'),
  ('MONTH_SHORT_JAN', 'pt-PT', 'Jan'),
  ('MONTH_SHORT_JUL', 'pt-PT', 'Jul'),
  ('MONTH_SHORT_JUN', 'pt-PT', 'Jun'),
  ('MONTH_SHORT_MAR', 'pt-PT', 'Mar'),
  ('MONTH_SHORT_MAY', 'pt-PT', 'Mai'),
  ('MONTH_SHORT_NOV', 'pt-PT', 'Nov'),
  ('MONTH_SHORT_OCT', 'pt-PT', 'Out'),
  ('MONTH_SHORT_SEP', 'pt-PT', 'Set'),
  ('MOTOBOY_ADDRESS', 'pt-PT', 'Morada'),
  ('MOTOBOY_ALREADY_PAID', 'pt-PT', 'Já pago'),
  ('MOTOBOY_AUTO_REFRESH_HINT', 'pt-PT', 'Esta página atualiza automaticamente a cada 20 segundos.'),
  ('MOTOBOY_CODE_PLACEHOLDER', 'pt-PT', 'Ex.: 1234'),
  ('MOTOBOY_COLLECT_ON_DELIVERY', 'pt-PT', 'Cobrar ao cliente na entrega'),
  ('MOTOBOY_CONFIRM', 'pt-PT', 'Confirmar'),
  ('MOTOBOY_CONFIRM_DELIVERY_CODE', 'pt-PT', 'Confirmar entrega com código'),
  ('MOTOBOY_CONFIRM_PAYMENT_TEXT', 'pt-PT', 'Marque como pago apenas depois de receber o valor.'),
  ('MOTOBOY_CONFIRM_PAYMENT_TITLE', 'pt-PT', 'Confirmar pagamento?'),
  ('MOTOBOY_CONFIRM_PAYMENT_YES', 'pt-PT', 'Sim, marcar como pago'),
  ('MOTOBOY_CONFIRMING', 'pt-PT', 'A confirmar...'),
  ('MOTOBOY_DELIVERY_CONFIRM_ERROR', 'pt-PT', 'Não foi possível confirmar a entrega.'),
  ('MOTOBOY_DELIVERY_CONFIRMED', 'pt-PT', 'Entrega confirmada com sucesso.'),
  ('MOTOBOY_DELIVERY_FEE', 'pt-PT', 'Taxa de Entrega'),
  ('MOTOBOY_EMPTY', 'pt-PT', 'Nenhum pedido pronto para entrega no momento.'),
  ('MOTOBOY_GOOGLE_MAPS', 'pt-PT', 'Google Maps'),
  ('MOTOBOY_LOAD_ERROR', 'pt-PT', 'Erro ao carregar pedidos. Tente atualizar.'),
  ('MOTOBOY_LOADING', 'pt-PT', 'A carregar...'),
  ('MOTOBOY_MARK_PAID', 'pt-PT', 'Marcar como pago'),
  ('MOTOBOY_MARK_PAID_FIRST', 'pt-PT', 'Para confirmar a entrega, marque o pedido como pago primeiro.'),
  ('MOTOBOY_ORDER_PREFIX', 'pt-PT', 'Pedido'),
  ('MOTOBOY_ORDER_TOTAL', 'pt-PT', 'Total do pedido'),
  ('MOTOBOY_PAYMENT_CONFIRM_ERROR', 'pt-PT', 'Não foi possível confirmar o pagamento.'),
  ('MOTOBOY_PAYMENT_MARKED', 'pt-PT', 'Pagamento marcado como aprovado.'),
  ('MOTOBOY_REFRESH', 'pt-PT', 'Atualizar'),
  ('MOTOBOY_SAVING', 'pt-PT', 'A guardar...'),
  ('MOTOBOY_SEARCH_ADDRESS', 'pt-PT', 'Buscar morada no Google Maps'),
  ('MOTOBOY_TITLE', 'pt-PT', 'Entregas'),
  ('MOTOBOY_WAZE', 'pt-PT', 'Waze'),
  ('NO', 'pt-PT', 'Não'),
  ('SALES_ANALYTICS_AVG_TICKET', 'pt-PT', 'Ticket Médio'),
  ('SALES_ANALYTICS_BACK_PANEL', 'pt-PT', 'Painel'),
  ('SALES_ANALYTICS_BY_MONTH', 'pt-PT', 'Por mês'),
  ('SALES_ANALYTICS_COST_HINT', 'pt-PT', 'Soma do preço de custo dos itens'),
  ('SALES_ANALYTICS_COST_PREFIX', 'pt-PT', 'Custo'),
  ('SALES_ANALYTICS_COST_TOTAL', 'pt-PT', 'Custo Total'),
  ('SALES_ANALYTICS_FULL_YEAR', 'pt-PT', 'Ano todo'),
  ('SALES_ANALYTICS_GO_PRODUCTS', 'pt-PT', 'Produtos'),
  ('SALES_ANALYTICS_LEGEND_COST', 'pt-PT', 'Custo'),
  ('SALES_ANALYTICS_LEGEND_PROFIT', 'pt-PT', 'Lucro'),
  ('SALES_ANALYTICS_LEGEND_REVENUE', 'pt-PT', 'Receita'),
  ('SALES_ANALYTICS_LOAD_ERROR', 'pt-PT', 'Falha ao carregar a análise de vendas.'),
  ('SALES_ANALYTICS_MONTH', 'pt-PT', 'Mês'),
  ('SALES_ANALYTICS_NO_PAID_ORDERS', 'pt-PT', 'Ainda não há pedidos pagos para análise.'),
  ('SALES_ANALYTICS_PROFIT_HINT', 'pt-PT', 'Receita − Custo'),
  ('SALES_ANALYTICS_PROFIT_PREFIX', 'pt-PT', 'Lucro'),
  ('SALES_ANALYTICS_PROFIT_TOTAL', 'pt-PT', 'Lucro Líquido'),
  ('SALES_ANALYTICS_REVENUE_HINT', 'pt-PT', 'Pedidos com pagamento aprovado'),
  ('SALES_ANALYTICS_REVENUE_TOTAL', 'pt-PT', 'Receita Total'),
  ('SALES_ANALYTICS_SALES_COUNT', 'pt-PT', '{{count}} vendas'),
  ('SALES_ANALYTICS_STATUS_PAID', 'pt-PT', 'Pagos (aprovados)'),
  ('SALES_ANALYTICS_STATUS_TITLE', 'pt-PT', 'Estado dos Pedidos'),
  ('SALES_ANALYTICS_SUBTITLE', 'pt-PT', 'Receita, volume de pedidos e sabores mais vendidos em tempo real.'),
  ('SALES_ANALYTICS_TICKET_HINT', 'pt-PT', '{{paid}} pagos de {{total}} totais'),
  ('SALES_ANALYTICS_TITLE', 'pt-PT', 'Análise de Vendas'),
  ('SALES_ANALYTICS_TODAY', 'pt-PT', 'Hoje'),
  ('SALES_ANALYTICS_TOP_FLAVORS', 'pt-PT', 'Top Sabores'),
  ('SALES_ANALYTICS_TOP_FLAVORS_HINT', 'pt-PT', 'Baseado em pedidos pagos'),
  ('YES', 'pt-PT', 'Sim'),

  -- ==========================================================
  -- ESPAÑOL (es-ES)
  -- ==========================================================
  ('ADMIN_HISTORY_ADDRESS', 'es-ES', 'Dirección'),
  ('ADMIN_HISTORY_BACK', 'es-ES', '← Admin'),
  ('ADMIN_HISTORY_CLEAR', 'es-ES', 'Limpiar'),
  ('ADMIN_HISTORY_CLIENT_NAME', 'es-ES', 'Nombre del cliente'),
  ('ADMIN_HISTORY_EMPTY', 'es-ES', 'Ningún pedido encontrado.'),
  ('ADMIN_HISTORY_FILTER', 'es-ES', 'Filtrar'),
  ('ADMIN_HISTORY_FILTERS', 'es-ES', 'Filtros'),
  ('ADMIN_HISTORY_FOUND_MULTI', 'es-ES', 'pedidos encontrados'),
  ('ADMIN_HISTORY_FOUND_SINGLE', 'es-ES', 'pedido encontrado'),
  ('ADMIN_HISTORY_FROM', 'es-ES', 'Desde'),
  ('ADMIN_HISTORY_HALF_HALF', 'es-ES', 'Mitad y Mitad'),
  ('ADMIN_HISTORY_LOAD_ERROR', 'es-ES', 'Error al cargar el historial de pedidos.'),
  ('ADMIN_HISTORY_MARK_PAID', 'es-ES', '✓ Pagado'),
  ('ADMIN_HISTORY_NOTES', 'es-ES', 'Notas'),
  ('ADMIN_HISTORY_ONLY_REFUNDS_SUFFIX', 'es-ES', ' — mostrando solo reembolsos pendientes'),
  ('ADMIN_HISTORY_PAYMENT_MARKED', 'es-ES', 'Pago marcado como aprobado'),
  ('ADMIN_HISTORY_PAYMENT_UPDATE_ERROR', 'es-ES', 'Error al actualizar el pago'),
  ('ADMIN_HISTORY_PIZZA', 'es-ES', 'Pizza'),
  ('ADMIN_HISTORY_REFUND_HINT', 'es-ES', 'El cliente ya había pagado y el pago fue aprobado.'),
  ('ADMIN_HISTORY_REFUND_NEEDS_MULTI', 'es-ES', 'pedidos cancelados necesitan reembolso'),
  ('ADMIN_HISTORY_REFUND_NEEDS_SINGLE', 'es-ES', 'pedido cancelado necesita reembolso'),
  ('ADMIN_HISTORY_REFUND_PENDING', 'es-ES', 'REEMBOLSO PENDIENTE'),
  ('ADMIN_HISTORY_REFUND_WARNING', 'es-ES', 'Pedido cancelado tras pago aprobado — reembolsar al cliente.'),
  ('ADMIN_HISTORY_SHOW_ALL', 'es-ES', 'Mostrar todos'),
  ('ADMIN_HISTORY_SHOW_REFUNDS', 'es-ES', 'Mostrar solo reembolsos'),
  ('ADMIN_HISTORY_SUBTITLE', 'es-ES', 'Todos los pedidos — entregados, cancelados y en curso.'),
  ('ADMIN_HISTORY_TITLE', 'es-ES', 'Historial de Pedidos'),
  ('ADMIN_HISTORY_TO', 'es-ES', 'Hasta'),
  ('ADMIN_HISTORY_TOTAL', 'es-ES', 'Total'),
  ('ADMIN_MESAS_BACK_PANEL', 'es-ES', '← Panel Admin'),
  ('ADMIN_MESAS_EMPTY', 'es-ES', 'Ninguna mesa registrada aún.'),
  ('ADMIN_MESAS_EMPTY_HINT_1', 'es-ES', 'Haz clic en'),
  ('ADMIN_MESAS_EMPTY_HINT_2', 'es-ES', 'para empezar.'),
  ('ADMIN_MESAS_HELP_TEXT_1', 'es-ES', 'En la app de Mercado Pago'),
  ('ADMIN_MESAS_HELP_TEXT_2', 'es-ES', 'Tu negocio → Point'),
  ('ADMIN_MESAS_HELP_TEXT_3', 'es-ES', 'selecciona el dispositivo → copia el ID mostrado (ej:'),
  ('ADMIN_MESAS_HELP_TITLE', 'es-ES', '¿Cómo encontrar el ID del terminal?'),
  ('ADMIN_MESAS_LOAD_ERROR', 'es-ES', 'Error al cargar las mesas.'),
  ('ADMIN_MESAS_LOADING', 'es-ES', 'Cargando mesas...'),
  ('ADMIN_MESAS_NEW_BUTTON', 'es-ES', 'Nueva Mesa'),
  ('ADMIN_MESAS_TITLE', 'es-ES', 'Mesas'),
  ('ADMIN_PRODUCTS_ACTIVE', 'es-ES', 'Activo'),
  ('ADMIN_PRODUCTS_ACTIVE_COUNT', 'es-ES', '{{count}} activos'),
  ('ADMIN_PRODUCTS_CATEGORY_LABEL', 'es-ES', 'Categoría'),
  ('ADMIN_PRODUCTS_CATEGORY_PLACEHOLDER', 'es-ES', 'Ej: Dulce, Salado, Bebidas...'),
  ('ADMIN_PRODUCTS_COST_OPTIONAL', 'es-ES', 'Costo (opcional)'),
  ('ADMIN_PRODUCTS_CREATE', 'es-ES', 'Crear'),
  ('ADMIN_PRODUCTS_CREATED', 'es-ES', '¡Producto creado!'),
  ('ADMIN_PRODUCTS_DESCRIPTION_LABEL', 'es-ES', 'Descripción'),
  ('ADMIN_PRODUCTS_DESCRIPTION_PLACEHOLDER', 'es-ES', 'Breve descripción del sabor...'),
  ('ADMIN_PRODUCTS_DISABLE', 'es-ES', 'Desactivar'),
  ('ADMIN_PRODUCTS_DISABLED', 'es-ES', 'Producto desactivado'),
  ('ADMIN_PRODUCTS_EDIT_TITLE', 'es-ES', 'Editar Producto'),
  ('ADMIN_PRODUCTS_EMPTY', 'es-ES', 'Ningún producto registrado aún.'),
  ('ADMIN_PRODUCTS_IMAGE_URL', 'es-ES', 'URL de la Imagen'),
  ('ADMIN_PRODUCTS_INACTIVE', 'es-ES', 'Inactivo'),
  ('ADMIN_PRODUCTS_INACTIVE_COUNT', 'es-ES', '{{count}} inactivos'),
  ('ADMIN_PRODUCTS_LOAD_ERROR', 'es-ES', 'Error al cargar productos.'),
  ('ADMIN_PRODUCTS_NAME_LABEL', 'es-ES', 'Nombre *'),
  ('ADMIN_PRODUCTS_NAME_PLACEHOLDER', 'es-ES', 'Ej: Pepperoni Imperial'),
  ('ADMIN_PRODUCTS_NEW_BUTTON', 'es-ES', 'Nuevo Producto'),
  ('ADMIN_PRODUCTS_NEW_TITLE', 'es-ES', 'Nuevo Producto'),
  ('ADMIN_PRODUCTS_PRICE_COST', 'es-ES', 'Precio y costo *'),
  ('ADMIN_PRODUCTS_PRICES_BY_SIZE', 'es-ES', 'Precios por Tamaño *'),
  ('ADMIN_PRODUCTS_RESTORE', 'es-ES', 'Restaurar'),
  ('ADMIN_PRODUCTS_RESTORED', 'es-ES', 'Producto restaurado'),
  ('ADMIN_PRODUCTS_SALE_PRICE', 'es-ES', 'Precio de venta'),
  ('ADMIN_PRODUCTS_SAVE_ERROR', 'es-ES', 'Error al guardar producto'),
  ('ADMIN_PRODUCTS_SAVING', 'es-ES', 'Guardando...'),
  ('ADMIN_PRODUCTS_STATUS_ERROR', 'es-ES', 'Error al cambiar estado'),
  ('ADMIN_PRODUCTS_SUBTITLE', 'es-ES', 'Gestionar el menú de Pizzaria Fellice'),
  ('ADMIN_PRODUCTS_TITLE', 'es-ES', 'Productos'),
  ('ADMIN_PRODUCTS_TYPE_CRUST', 'es-ES', 'Borde relleno'),
  ('ADMIN_PRODUCTS_TYPE_FLAVOR', 'es-ES', 'Sabor'),
  ('ADMIN_PRODUCTS_TYPE_LABEL', 'es-ES', 'Tipo de producto'),
  ('ADMIN_PRODUCTS_TYPE_OTHER', 'es-ES', 'Otros'),
  ('ADMIN_PRODUCTS_TYPE_PIZZA', 'es-ES', 'Pizza'),
  ('ADMIN_PRODUCTS_UPDATED', 'es-ES', '¡Producto actualizado!'),
  ('ADMIN_USERS_BACK_PANEL', 'es-ES', '← Panel Admin'),
  ('ADMIN_USERS_CREATE_ANOTHER', 'es-ES', 'Crear otro usuario'),
  ('ADMIN_USERS_CREATE_BUTTON', 'es-ES', 'Crear'),
  ('ADMIN_USERS_CREATE_ERROR', 'es-ES', 'Error al crear usuario. Verifica los datos.'),
  ('ADMIN_USERS_CREATED_SUCCESS', 'es-ES', '¡Usuario creado con éxito!'),
  ('ADMIN_USERS_CREATING', 'es-ES', 'Creando...'),
  ('ADMIN_USERS_EMAIL_LABEL', 'es-ES', 'Correo electrónico'),
  ('ADMIN_USERS_EMAIL_OR_PHONE_REQUIRED', 'es-ES', 'Informe correo electrónico o teléfono para iniciar sesión.'),
  ('ADMIN_USERS_EMAIL_PLACEHOLDER', 'es-ES', 'ej@email.com'),
  ('ADMIN_USERS_FIELD_EMAIL', 'es-ES', 'Correo electrónico'),
  ('ADMIN_USERS_FIELD_NAME', 'es-ES', 'Nombre'),
  ('ADMIN_USERS_FIELD_PASSWORD', 'es-ES', 'Contraseña'),
  ('ADMIN_USERS_FIELD_PHONE', 'es-ES', 'Teléfono'),
  ('ADMIN_USERS_FIELD_ROLE', 'es-ES', 'Perfil'),
  ('ADMIN_USERS_GENERIC_USER', 'es-ES', 'Usuario'),
  ('ADMIN_USERS_NAME_LABEL', 'es-ES', 'Nombre completo *'),
  ('ADMIN_USERS_NAME_PLACEHOLDER', 'es-ES', 'Ej: Juan Pérez'),
  ('ADMIN_USERS_PASSWORD_LABEL', 'es-ES', 'Contraseña *'),
  ('ADMIN_USERS_PASSWORD_PLACEHOLDER', 'es-ES', 'Mínimo 6 caracteres'),
  ('ADMIN_USERS_PHONE_HINT', 'es-ES', 'Se puede usar para iniciar sesión en lugar del correo.'),
  ('ADMIN_USERS_PHONE_LABEL', 'es-ES', 'Teléfono'),
  ('ADMIN_USERS_PHONE_MIN_DIGITS', 'es-ES', 'El teléfono debe tener al menos 10 dígitos.'),
  ('ADMIN_USERS_PHONE_PLACEHOLDER', 'es-ES', '+34 600 123 456'),
  ('ADMIN_USERS_ROLE_LABEL', 'es-ES', 'Perfil *'),
  ('ADMIN_USERS_TITLE', 'es-ES', 'Crear Usuario'),
  ('APP_BRAND_NAME', 'es-ES', 'Pizzaria Fellice'),
  ('CHECKOUT_RETURN_BACK_MENU', 'es-ES', 'Volver a la carta'),
  ('CHECKOUT_RETURN_CONFIRM_ERROR', 'es-ES', 'Error de confirmación'),
  ('CHECKOUT_RETURN_FAILURE_BUTTON', 'es-ES', 'Intentar de nuevo'),
  ('CHECKOUT_RETURN_FAILURE_SUBTITLE', 'es-ES', 'Hubo un problema con el pago. Tu carrito sigue guardado.'),
  ('CHECKOUT_RETURN_FAILURE_TITLE', 'es-ES', 'Pago no completado'),
  ('CHECKOUT_RETURN_ORDER_PREFIX', 'es-ES', 'Pedido'),
  ('CHECKOUT_RETURN_PENDING_BUTTON', 'es-ES', 'Ver mis pedidos'),
  ('CHECKOUT_RETURN_PENDING_SUBTITLE', 'es-ES', 'Tu pago se está procesando. La preparación comenzará una vez confirmado.'),
  ('CHECKOUT_RETURN_PENDING_TITLE', 'es-ES', 'Pago en análisis'),
  ('CHECKOUT_RETURN_SUCCESS_BUTTON', 'es-ES', 'Rastrear mi pedido'),
  ('CHECKOUT_RETURN_SUCCESS_SUBTITLE', 'es-ES', 'Tu pedido ha sido recibido y ya se está preparando con cariño.'),
  ('CHECKOUT_RETURN_SUCCESS_TITLE', 'es-ES', '¡Pago confirmado!'),
  ('CLIENT_DASHBOARD_ASK_REASON', 'es-ES', 'Preguntar motivo'),
  ('CLIENT_DASHBOARD_CANCELLED_WHATSAPP', 'es-ES', 'Cancelado (WhatsApp)'),
  ('CLIENT_DASHBOARD_CLIENT', 'es-ES', 'Cliente'),
  ('CLIENT_DASHBOARD_CONFIRM', 'es-ES', '¿Confirmar?'),
  ('CLIENT_DASHBOARD_CRUST', 'es-ES', 'Borde'),
  ('CLIENT_DASHBOARD_DELIVERY', 'es-ES', 'Entrega'),
  ('CLIENT_DASHBOARD_DELIVERY_CODE_HINT', 'es-ES', 'Da este código al repartidor para confirmar la entrega'),
  ('CLIENT_DASHBOARD_DELIVERY_CODE_LABEL', 'es-ES', 'Código de confirmación de entrega'),
  ('CLIENT_DASHBOARD_EMPTY_ALL', 'es-ES', 'Aún no tienes pedidos.'),
  ('CLIENT_DASHBOARD_EMPTY_FILTER', 'es-ES', 'Ningún pedido encontrado para este filtro.'),
  ('CLIENT_DASHBOARD_FILTER_ALL', 'es-ES', 'Todos'),
  ('CLIENT_DASHBOARD_HALF_HALF', 'es-ES', 'Mitad y Mitad'),
  ('CLIENT_DASHBOARD_HELLO', 'es-ES', 'Hola'),
  ('CLIENT_DASHBOARD_LOAD_ERROR', 'es-ES', 'Error al cargar pedidos.'),
  ('CLIENT_DASHBOARD_ORDER_PREFIX', 'es-ES', 'Pedido'),
  ('CLIENT_DASHBOARD_PAYMENT', 'es-ES', 'Pago'),
  ('CLIENT_DASHBOARD_PIZZA', 'es-ES', 'Pizza'),
  ('CLIENT_DASHBOARD_REPEAT_ERROR', 'es-ES', 'No se pudo repetir este pedido.'),
  ('CLIENT_DASHBOARD_REPEAT_ORDER', 'es-ES', 'Repetir pedido'),
  ('CLIENT_DASHBOARD_REPEAT_SUCCESS', 'es-ES', 'Pedido añadido de nuevo al carrito.'),
  ('DELETE', 'es-ES', 'Eliminar'),
  ('EDIT', 'es-ES', 'Editar'),
  ('FIRST_HALF_CHOOSE_NEXT', 'es-ES', 'Elige la próxima pizza para completar.'),
  ('FIRST_HALF_SELECTED_MSG', 'es-ES', 'Primera mitad seleccionada:'),
  ('HOME_ABOUT_P1', 'es-ES', 'Desde 1997, la Pizzaria Fellice es sinónimo de calidad y sabor. Combinamos ingredientes frescos y seleccionados con recetas exclusivas para crear pizzas que encantan a todos. Ya sea en nuestro salón acogedor para momentos especiales, o a través de nuestro eficiente servicio de entrega, garantizamos una experiencia gastronómica única.'),
  ('HOME_ABOUT_P2', 'es-ES', 'Además de nuestras pizzas, ofrecemos una deliciosa variedad de porciones, sándwiches, aperitivos, papas fritas y postres, todo preparado con el mismo cuidado y dedicación que nos convirtió en referencia en la región.'),
  ('HOME_ABOUT_P3', 'es-ES', 'Descubra por qué la Pizzaria Fellice es la elección correcta para quienes buscan tradición, calidad y un toque de exclusividad. Visítenos u ordene en línea y saboree lo mejor de la gastronomía italiana con nuestro toque especial.'),
  ('HOME_HERO_TITLE_1', 'es-ES', 'Auténtica'),
  ('HOME_HERO_TITLE_2', 'es-ES', 'pizza italiana'),
  ('HOME_SINCE_1997', 'es-ES', 'Desde 1997 · 27 años de tradición italiana'),
  ('KITCHEN_ADVANCE_TO_TABLE', 'es-ES', 'Llevar a la Mesa'),
  ('KITCHEN_CLEAR_ALERTS', 'es-ES', 'Limpiar alertas'),
  ('KITCHEN_DELIVERED_AT_TABLE', 'es-ES', 'Entregado en Mesa'),
  ('KITCHEN_DELIVERY', 'es-ES', 'Entrega'),
  ('KITCHEN_DROP_TO_STAGE', 'es-ES', 'Suelta aquí para mover a {{stage}}'),
  ('KITCHEN_HIGHLIGHT_SECONDS', 'es-ES', 'Resaltado activo por {{seconds}} segundos.'),
  ('KITCHEN_LIVE', 'es-ES', 'En vivo'),
  ('KITCHEN_LOAD_ERROR', 'es-ES', 'Error al cargar pedidos.'),
  ('KITCHEN_MARK_PICKED_UP', 'es-ES', 'Marcar Recogido'),
  ('KITCHEN_NEW_ORDER', 'es-ES', 'Nuevo pedido'),
  ('KITCHEN_NEW_ORDER_ARRIVED', 'es-ES', 'Nuevo pedido {{id}} llegó a la cola'),
  ('KITCHEN_NO_ACTIVE_ORDERS', 'es-ES', 'Sin pedidos activos actualmente.'),
  ('KITCHEN_NO_ALERTS', 'es-ES', 'Sin alertas pendientes'),
  ('KITCHEN_NO_ORDER', 'es-ES', 'Ningún pedido'),
  ('KITCHEN_NO_OVERDUE', 'es-ES', 'Sin pedidos atrasados'),
  ('KITCHEN_OFF', 'es-ES', 'apagado'),
  ('KITCHEN_ON', 'es-ES', 'encendido'),
  ('KITCHEN_ORDERS_IN_STAGE', 'es-ES', 'Pedidos en esta etapa'),
  ('KITCHEN_OVERDUE_ALERT', 'es-ES', '{{count}} pedido(s) se atrasaron'),
  ('KITCHEN_OVERDUE_COUNT', 'es-ES', '{{count}} pedidos atrasados'),
  ('KITCHEN_PAYMENT_PENDING', 'es-ES', 'Pago pend.'),
  ('KITCHEN_PICKUP', 'es-ES', 'Recogida'),
  ('KITCHEN_READY_PICKUP', 'es-ES', 'Listo para Recoger'),
  ('KITCHEN_SOUND', 'es-ES', 'Sonido'),
  ('KITCHEN_TITLE', 'es-ES', 'Cocina'),
  ('KITCHEN_UNREAD_ALERTS', 'es-ES', '{{count}} nuevas alertas no leídas'),
  ('KITCHEN_UPDATED_AT', 'es-ES', 'Actualizado a las {{time}} • tiempo real con respaldo de 2 min'),
  ('KITCHEN_UPDATING', 'es-ES', 'Actualizando...'),
  ('MESA_ACCESS_INVALID_QR_TEXT_1', 'es-ES', 'Este código QR ha expirado o ya no es válido.'),
  ('MESA_ACCESS_INVALID_QR_TEXT_2', 'es-ES', 'Pide al personal que genere uno nuevo.'),
  ('MESA_ACCESS_INVALID_QR_TITLE', 'es-ES', 'Código QR inválido'),
  ('MESA_ACCESS_LOADING', 'es-ES', 'Identificando mesa...'),
  ('MESA_CHECKOUT_BACK_MENU', 'es-ES', '← Carta'),
  ('MESA_CHECKOUT_CONFIRM_ORDER', 'es-ES', 'Confirmar pedido'),
  ('MESA_CHECKOUT_NOTES_LABEL', 'es-ES', 'Notas (opcional)'),
  ('MESA_CHECKOUT_NOTES_PLACEHOLDER', 'es-ES', 'Ej: sin cebolla, masa fina...'),
  ('MESA_CHECKOUT_ORDER_ERROR', 'es-ES', 'Error al hacer el pedido.'),
  ('MESA_CHECKOUT_ORDER_SENT', 'es-ES', '¡Pedido enviado a la cocina!'),
  ('MESA_CHECKOUT_PAY_LATER', 'es-ES', 'Pagar después'),
  ('MESA_CHECKOUT_PAY_NOW', 'es-ES', '¿Deseas pagar ahora?'),
  ('MESA_CHECKOUT_PAYMENT_CONFIRMED', 'es-ES', '¡Pago confirmado! 🍕'),
  ('MESA_CHECKOUT_PENDING_TOTAL', 'es-ES', 'Total pendiente'),
  ('MESA_CHECKOUT_PIX_SHORT', 'es-ES', 'PIX'),
  ('MESA_CHECKOUT_SENDING', 'es-ES', 'Enviando...'),
  ('MESA_CHECKOUT_SESSION_ORDERS', 'es-ES', 'Pedidos de esta sesión'),
  ('MESA_CHECKOUT_TABLE', 'es-ES', 'Mesa'),
  ('MESA_CHECKOUT_TERMINAL_SHORT', 'es-ES', 'Terminal'),
  ('MESA_CHECKOUT_VIEW_MENU', 'es-ES', 'Ver carta'),
  ('MESA_CHECKOUT_YOUR_ORDER', 'es-ES', 'Tu pedido'),
  ('MESA_PIX_COPIED', 'es-ES', '¡Código copiado!'),
  ('MESA_PIX_COPY_BUTTON', 'es-ES', 'Copiar código PIX'),
  ('MESA_PIX_COPY_HINT', 'es-ES', 'O copia el código:'),
  ('MESA_PIX_ERROR', 'es-ES', 'Error generando PIX. Intenta de nuevo.'),
  ('MESA_PIX_GENERATING', 'es-ES', 'Generando QR Code...'),
  ('MESA_PIX_QR_ALT', 'es-ES', 'QR Code PIX'),
  ('MESA_PIX_TITLE', 'es-ES', 'Pagar con PIX'),
  ('MESA_PIX_WAITING', 'es-ES', 'Esperando confirmación de pago...'),
  ('MESA_TERMINAL_SEND_BUTTON', 'es-ES', 'Enviar al terminal'),
  ('MESA_TERMINAL_SEND_ERROR', 'es-ES', 'Error enviando al terminal.'),
  ('MESA_TERMINAL_SENDING', 'es-ES', 'Enviando...'),
  ('MESA_TERMINAL_SENT', 'es-ES', '¡Cobro enviado al terminal!'),
  ('MESA_TERMINAL_TITLE', 'es-ES', 'Pagar en Terminal'),
  ('MESA_TERMINAL_WAITING', 'es-ES', 'Esperando pago en terminal...'),
  ('MONTH_LABEL_APR', 'es-ES', 'Abril'),
  ('MONTH_LABEL_AUG', 'es-ES', 'Agosto'),
  ('MONTH_LABEL_DEC', 'es-ES', 'Diciembre'),
  ('MONTH_LABEL_FEB', 'es-ES', 'Febrero'),
  ('MONTH_LABEL_JAN', 'es-ES', 'Enero'),
  ('MONTH_LABEL_JUL', 'es-ES', 'Julio'),
  ('MONTH_LABEL_JUN', 'es-ES', 'Junio'),
  ('MONTH_LABEL_MAR', 'es-ES', 'Marzo'),
  ('MONTH_LABEL_MAY', 'es-ES', 'Mayo'),
  ('MONTH_LABEL_NOV', 'es-ES', 'Noviembre'),
  ('MONTH_LABEL_OCT', 'es-ES', 'Octubre'),
  ('MONTH_LABEL_SEP', 'es-ES', 'Septiembre'),
  ('MONTH_SHORT_APR', 'es-ES', 'Abr'),
  ('MONTH_SHORT_AUG', 'es-ES', 'Ago'),
  ('MONTH_SHORT_DEC', 'es-ES', 'Dic'),
  ('MONTH_SHORT_FEB', 'es-ES', 'Feb'),
  ('MONTH_SHORT_JAN', 'es-ES', 'Ene'),
  ('MONTH_SHORT_JUL', 'es-ES', 'Jul'),
  ('MONTH_SHORT_JUN', 'es-ES', 'Jun'),
  ('MONTH_SHORT_MAR', 'es-ES', 'Mar'),
  ('MONTH_SHORT_MAY', 'es-ES', 'May'),
  ('MONTH_SHORT_NOV', 'es-ES', 'Nov'),
  ('MONTH_SHORT_OCT', 'es-ES', 'Oct'),
  ('MONTH_SHORT_SEP', 'es-ES', 'Sep'),
  ('MOTOBOY_ADDRESS', 'es-ES', 'Dirección'),
  ('MOTOBOY_ALREADY_PAID', 'es-ES', 'Ya pagado'),
  ('MOTOBOY_AUTO_REFRESH_HINT', 'es-ES', 'Esta página se actualiza cada 20 segundos.'),
  ('MOTOBOY_CODE_PLACEHOLDER', 'es-ES', 'Ej.: 1234'),
  ('MOTOBOY_COLLECT_ON_DELIVERY', 'es-ES', 'Cobrar al cliente en entrega'),
  ('MOTOBOY_CONFIRM', 'es-ES', 'Confirmar'),
  ('MOTOBOY_CONFIRM_DELIVERY_CODE', 'es-ES', 'Confirmar entrega con código'),
  ('MOTOBOY_CONFIRM_PAYMENT_TEXT', 'es-ES', 'Marca como pagado solo después de recibir el importe.'),
  ('MOTOBOY_CONFIRM_PAYMENT_TITLE', 'es-ES', '¿Confirmar pago?'),
  ('MOTOBOY_CONFIRM_PAYMENT_YES', 'es-ES', 'Sí, marcar como pagado'),
  ('MOTOBOY_CONFIRMING', 'es-ES', 'Confirmando...'),
  ('MOTOBOY_DELIVERY_CONFIRM_ERROR', 'es-ES', 'No se pudo confirmar la entrega.'),
  ('MOTOBOY_DELIVERY_CONFIRMED', 'es-ES', 'Entrega confirmada con éxito.'),
  ('MOTOBOY_DELIVERY_FEE', 'es-ES', 'Costo de envío'),
  ('MOTOBOY_EMPTY', 'es-ES', 'Ningún pedido listo para entrega en este momento.'),
  ('MOTOBOY_GOOGLE_MAPS', 'es-ES', 'Google Maps'),
  ('MOTOBOY_LOAD_ERROR', 'es-ES', 'Error al cargar pedidos. Intenta actualizar.'),
  ('MOTOBOY_LOADING', 'es-ES', 'Cargando...'),
  ('MOTOBOY_MARK_PAID', 'es-ES', 'Marcar como pagado'),
  ('MOTOBOY_MARK_PAID_FIRST', 'es-ES', 'Para confirmar la entrega, marca el pedido como pagado primero.'),
  ('MOTOBOY_ORDER_PREFIX', 'es-ES', 'Pedido'),
  ('MOTOBOY_ORDER_TOTAL', 'es-ES', 'Total del pedido'),
  ('MOTOBOY_PAYMENT_CONFIRM_ERROR', 'es-ES', 'No se pudo confirmar el pago.'),
  ('MOTOBOY_PAYMENT_MARKED', 'es-ES', 'Pago marcado como aprobado.'),
  ('MOTOBOY_REFRESH', 'es-ES', 'Actualizar'),
  ('MOTOBOY_SAVING', 'es-ES', 'Guardando...'),
  ('MOTOBOY_SEARCH_ADDRESS', 'es-ES', 'Buscar dirección en Google Maps'),
  ('MOTOBOY_TITLE', 'es-ES', 'Entregas'),
  ('MOTOBOY_WAZE', 'es-ES', 'Waze'),
  ('NO', 'es-ES', 'No'),
  ('SALES_ANALYTICS_AVG_TICKET', 'es-ES', 'Ticket Medio'),
  ('SALES_ANALYTICS_BACK_PANEL', 'es-ES', 'Panel'),
  ('SALES_ANALYTICS_BY_MONTH', 'es-ES', 'Por mes'),
  ('SALES_ANALYTICS_COST_HINT', 'es-ES', 'Suma del precio de costo de los ítems'),
  ('SALES_ANALYTICS_COST_PREFIX', 'es-ES', 'Costo'),
  ('SALES_ANALYTICS_COST_TOTAL', 'es-ES', 'Costo Total'),
  ('SALES_ANALYTICS_FULL_YEAR', 'es-ES', 'Todo el año'),
  ('SALES_ANALYTICS_GO_PRODUCTS', 'es-ES', 'Productos'),
  ('SALES_ANALYTICS_LEGEND_COST', 'es-ES', 'Costo'),
  ('SALES_ANALYTICS_LEGEND_PROFIT', 'es-ES', 'Beneficio'),
  ('SALES_ANALYTICS_LEGEND_REVENUE', 'es-ES', 'Ingresos'),
  ('SALES_ANALYTICS_LOAD_ERROR', 'es-ES', 'Error al cargar el análisis de ventas.'),
  ('SALES_ANALYTICS_MONTH', 'es-ES', 'Mes'),
  ('SALES_ANALYTICS_NO_PAID_ORDERS', 'es-ES', 'Aún no hay pedidos pagados para analizar.'),
  ('SALES_ANALYTICS_PROFIT_HINT', 'es-ES', 'Ingresos − Costo'),
  ('SALES_ANALYTICS_PROFIT_PREFIX', 'es-ES', 'Beneficio'),
  ('SALES_ANALYTICS_PROFIT_TOTAL', 'es-ES', 'Beneficio Neto'),
  ('SALES_ANALYTICS_REVENUE_HINT', 'es-ES', 'Pedidos con pago aprobado'),
  ('SALES_ANALYTICS_REVENUE_TOTAL', 'es-ES', 'Ingresos Totales'),
  ('SALES_ANALYTICS_SALES_COUNT', 'es-ES', '{{count}} ventas'),
  ('SALES_ANALYTICS_STATUS_PAID', 'es-ES', 'Pagados (aprobados)'),
  ('SALES_ANALYTICS_STATUS_TITLE', 'es-ES', 'Estado de Pedidos'),
  ('SALES_ANALYTICS_SUBTITLE', 'es-ES', 'Ingresos, volumen de pedidos y mejores sabores en tiempo real.'),
  ('SALES_ANALYTICS_TICKET_HINT', 'es-ES', '{{paid}} pagados de {{total}} totales'),
  ('SALES_ANALYTICS_TITLE', 'es-ES', 'Análisis de Ventas'),
  ('SALES_ANALYTICS_TODAY', 'es-ES', 'Hoy'),
  ('SALES_ANALYTICS_TOP_FLAVORS', 'es-ES', 'Mejores Sabores'),
  ('SALES_ANALYTICS_TOP_FLAVORS_HINT', 'es-ES', 'Basado en pedidos pagados'),
  ('YES', 'es-ES', 'Sí'),

  -- ==========================================================
  -- ÁRABE MARROQUINO (ar-MA)
  -- ==========================================================
  ('ADMIN_HISTORY_ADDRESS', 'ar-MA', 'العنوان'),
  ('ADMIN_HISTORY_BACK', 'ar-MA', '← مدير'),
  ('ADMIN_HISTORY_CLEAR', 'ar-MA', 'مسح'),
  ('ADMIN_HISTORY_CLIENT_NAME', 'ar-MA', 'اسم العميل'),
  ('ADMIN_HISTORY_EMPTY', 'ar-MA', 'لم يتم العثور على طلبات.'),
  ('ADMIN_HISTORY_FILTER', 'ar-MA', 'تصفية'),
  ('ADMIN_HISTORY_FILTERS', 'ar-MA', 'فلاتر'),
  ('ADMIN_HISTORY_FOUND_MULTI', 'ar-MA', 'طلبات موجودة'),
  ('ADMIN_HISTORY_FOUND_SINGLE', 'ar-MA', 'طلب موجود'),
  ('ADMIN_HISTORY_FROM', 'ar-MA', 'من'),
  ('ADMIN_HISTORY_HALF_HALF', 'ar-MA', 'نصف ونصف'),
  ('ADMIN_HISTORY_LOAD_ERROR', 'ar-MA', 'خطأ في تحميل سجل الطلبات.'),
  ('ADMIN_HISTORY_MARK_PAID', 'ar-MA', '✓ مدفوع'),
  ('ADMIN_HISTORY_NOTES', 'ar-MA', 'ملاحظات'),
  ('ADMIN_HISTORY_ONLY_REFUNDS_SUFFIX', 'ar-MA', ' — إظهار المبالغ المستردة المعلقة فقط'),
  ('ADMIN_HISTORY_PAYMENT_MARKED', 'ar-MA', 'تم تحديد الدفع كمقبول'),
  ('ADMIN_HISTORY_PAYMENT_UPDATE_ERROR', 'ar-MA', 'فشل تحديث الدفع'),
  ('ADMIN_HISTORY_PIZZA', 'ar-MA', 'بيتزا'),
  ('ADMIN_HISTORY_REFUND_HINT', 'ar-MA', 'لقد دفع العميل بالفعل وتمت الموافقة على الدفع.'),
  ('ADMIN_HISTORY_REFUND_NEEDS_MULTI', 'ar-MA', 'طلبات ملغاة تحتاج إلى استرداد'),
  ('ADMIN_HISTORY_REFUND_NEEDS_SINGLE', 'ar-MA', 'طلب ملغى يحتاج إلى استرداد'),
  ('ADMIN_HISTORY_REFUND_PENDING', 'ar-MA', 'استرداد معلق'),
  ('ADMIN_HISTORY_REFUND_WARNING', 'ar-MA', 'تم إلغاء الطلب بعد الموافقة على الدفع — قم برد المبلغ للعميل.'),
  ('ADMIN_HISTORY_SHOW_ALL', 'ar-MA', 'عرض الكل'),
  ('ADMIN_HISTORY_SHOW_REFUNDS', 'ar-MA', 'عرض الاستردادات فقط'),
  ('ADMIN_HISTORY_SUBTITLE', 'ar-MA', 'جميع الطلبات — المسلمة والملغاة والجارية.'),
  ('ADMIN_HISTORY_TITLE', 'ar-MA', 'سجل الطلبات'),
  ('ADMIN_HISTORY_TO', 'ar-MA', 'إلى'),
  ('ADMIN_HISTORY_TOTAL', 'ar-MA', 'المجموع'),
  ('ADMIN_MESAS_BACK_PANEL', 'ar-MA', '← لوحة الإدارة'),
  ('ADMIN_MESAS_EMPTY', 'ar-MA', 'لم يتم تسجيل أي طاولات بعد.'),
  ('ADMIN_MESAS_EMPTY_HINT_1', 'ar-MA', 'انقر على'),
  ('ADMIN_MESAS_EMPTY_HINT_2', 'ar-MA', 'للبدء.'),
  ('ADMIN_MESAS_HELP_TEXT_1', 'ar-MA', 'في تطبيق Mercado Pago'),
  ('ADMIN_MESAS_HELP_TEXT_2', 'ar-MA', 'عملك → Point'),
  ('ADMIN_MESAS_HELP_TEXT_3', 'ar-MA', 'حدد الجهاز → انسخ المعرف الظاهر (مثال:'),
  ('ADMIN_MESAS_HELP_TITLE', 'ar-MA', 'كيف تجد معرف الجهاز؟'),
  ('ADMIN_MESAS_LOAD_ERROR', 'ar-MA', 'فشل تحميل الطاولات.'),
  ('ADMIN_MESAS_LOADING', 'ar-MA', 'جاري تحميل الطاولات...'),
  ('ADMIN_MESAS_NEW_BUTTON', 'ar-MA', 'طاولة جديدة'),
  ('ADMIN_MESAS_TITLE', 'ar-MA', 'طاولات'),
  ('ADMIN_PRODUCTS_ACTIVE', 'ar-MA', 'نشط'),
  ('ADMIN_PRODUCTS_ACTIVE_COUNT', 'ar-MA', '{{count}} نشط'),
  ('ADMIN_PRODUCTS_CATEGORY_LABEL', 'ar-MA', 'فئة'),
  ('ADMIN_PRODUCTS_CATEGORY_PLACEHOLDER', 'ar-MA', 'مثال: حلو، مالح، مشروبات...'),
  ('ADMIN_PRODUCTS_COST_OPTIONAL', 'ar-MA', 'التكلفة (اختياري)'),
  ('ADMIN_PRODUCTS_CREATE', 'ar-MA', 'إنشاء'),
  ('ADMIN_PRODUCTS_CREATED', 'ar-MA', 'تم إنشاء المنتج!'),
  ('ADMIN_PRODUCTS_DESCRIPTION_LABEL', 'ar-MA', 'وصف'),
  ('ADMIN_PRODUCTS_DESCRIPTION_PLACEHOLDER', 'ar-MA', 'وصف موجز للنكهة...'),
  ('ADMIN_PRODUCTS_DISABLE', 'ar-MA', 'تعطيل'),
  ('ADMIN_PRODUCTS_DISABLED', 'ar-MA', 'تم تعطيل المنتج'),
  ('ADMIN_PRODUCTS_EDIT_TITLE', 'ar-MA', 'تعديل المنتج'),
  ('ADMIN_PRODUCTS_EMPTY', 'ar-MA', 'لم يتم تسجيل أي منتجات بعد.'),
  ('ADMIN_PRODUCTS_IMAGE_URL', 'ar-MA', 'رابط الصورة'),
  ('ADMIN_PRODUCTS_INACTIVE', 'ar-MA', 'غير نشط'),
  ('ADMIN_PRODUCTS_INACTIVE_COUNT', 'ar-MA', '{{count}} غير نشط'),
  ('ADMIN_PRODUCTS_LOAD_ERROR', 'ar-MA', 'فشل تحميل المنتجات.'),
  ('ADMIN_PRODUCTS_NAME_LABEL', 'ar-MA', 'الاسم *'),
  ('ADMIN_PRODUCTS_NAME_PLACEHOLDER', 'ar-MA', 'مثال: بيبروني إمبريال'),
  ('ADMIN_PRODUCTS_NEW_BUTTON', 'ar-MA', 'منتج جديد'),
  ('ADMIN_PRODUCTS_NEW_TITLE', 'ar-MA', 'منتج جديد'),
  ('ADMIN_PRODUCTS_PRICE_COST', 'ar-MA', 'السعر والتكلفة *'),
  ('ADMIN_PRODUCTS_PRICES_BY_SIZE', 'ar-MA', 'الأسعار حسب الحجم *'),
  ('ADMIN_PRODUCTS_RESTORE', 'ar-MA', 'استعادة'),
  ('ADMIN_PRODUCTS_RESTORED', 'ar-MA', 'تم استعادة المنتج'),
  ('ADMIN_PRODUCTS_SALE_PRICE', 'ar-MA', 'سعر البيع'),
  ('ADMIN_PRODUCTS_SAVE_ERROR', 'ar-MA', 'خطأ في حفظ المنتج'),
  ('ADMIN_PRODUCTS_SAVING', 'ar-MA', 'جاري الحفظ...'),
  ('ADMIN_PRODUCTS_STATUS_ERROR', 'ar-MA', 'فشل في تغيير الحالة'),
  ('ADMIN_PRODUCTS_SUBTITLE', 'ar-MA', 'إدارة قائمة بيتزاريا فيليشي'),
  ('ADMIN_PRODUCTS_TITLE', 'ar-MA', 'المنتجات'),
  ('ADMIN_PRODUCTS_TYPE_CRUST', 'ar-MA', 'حافة محشوة'),
  ('ADMIN_PRODUCTS_TYPE_FLAVOR', 'ar-MA', 'نكهة'),
  ('ADMIN_PRODUCTS_TYPE_LABEL', 'ar-MA', 'نوع المنتج'),
  ('ADMIN_PRODUCTS_TYPE_OTHER', 'ar-MA', 'أخرى'),
  ('ADMIN_PRODUCTS_TYPE_PIZZA', 'ar-MA', 'بيتزا'),
  ('ADMIN_PRODUCTS_UPDATED', 'ar-MA', 'تم تحديث المنتج!'),
  ('ADMIN_USERS_BACK_PANEL', 'ar-MA', '← لوحة الإدارة'),
  ('ADMIN_USERS_CREATE_ANOTHER', 'ar-MA', 'إنشاء مستخدم آخر'),
  ('ADMIN_USERS_CREATE_BUTTON', 'ar-MA', 'إنشاء'),
  ('ADMIN_USERS_CREATE_ERROR', 'ar-MA', 'خطأ في إنشاء المستخدم. تحقق من البيانات.'),
  ('ADMIN_USERS_CREATED_SUCCESS', 'ar-MA', 'تم إنشاء المستخدم بنجاح!'),
  ('ADMIN_USERS_CREATING', 'ar-MA', 'جاري الإنشاء...'),
  ('ADMIN_USERS_EMAIL_LABEL', 'ar-MA', 'البريد الإلكتروني'),
  ('ADMIN_USERS_EMAIL_OR_PHONE_REQUIRED', 'ar-MA', 'أدخل البريد الإلكتروني أو الهاتف لتسجيل الدخول.'),
  ('ADMIN_USERS_EMAIL_PLACEHOLDER', 'ar-MA', 'ex@email.com'),
  ('ADMIN_USERS_FIELD_EMAIL', 'ar-MA', 'البريد الإلكتروني'),
  ('ADMIN_USERS_FIELD_NAME', 'ar-MA', 'الاسم'),
  ('ADMIN_USERS_FIELD_PASSWORD', 'ar-MA', 'كلمة المرور'),
  ('ADMIN_USERS_FIELD_PHONE', 'ar-MA', 'هاتف'),
  ('ADMIN_USERS_FIELD_ROLE', 'ar-MA', 'الدور'),
  ('ADMIN_USERS_GENERIC_USER', 'ar-MA', 'مستخدم'),
  ('ADMIN_USERS_NAME_LABEL', 'ar-MA', 'الاسم الكامل *'),
  ('ADMIN_USERS_NAME_PLACEHOLDER', 'ar-MA', 'مثال: جون دو'),
  ('ADMIN_USERS_PASSWORD_LABEL', 'ar-MA', 'كلمة المرور *'),
  ('ADMIN_USERS_PASSWORD_PLACEHOLDER', 'ar-MA', '6 أحرف كحد أدنى'),
  ('ADMIN_USERS_PHONE_HINT', 'ar-MA', 'يمكن استخدامه لتسجيل الدخول بدلاً من البريد الإلكتروني.'),
  ('ADMIN_USERS_PHONE_LABEL', 'ar-MA', 'هاتف'),
  ('ADMIN_USERS_PHONE_MIN_DIGITS', 'ar-MA', 'يجب أن يحتوي الهاتف على 10 أرقام على الأقل.'),
  ('ADMIN_USERS_PHONE_PLACEHOLDER', 'ar-MA', '+212 600 000000'),
  ('ADMIN_USERS_ROLE_LABEL', 'ar-MA', 'الدور *'),
  ('ADMIN_USERS_TITLE', 'ar-MA', 'إنشاء مستخدم'),
  ('APP_BRAND_NAME', 'ar-MA', 'بيتزاريا فيليشي'),
  ('CHECKOUT_RETURN_BACK_MENU', 'ar-MA', 'العودة إلى القائمة'),
  ('CHECKOUT_RETURN_CONFIRM_ERROR', 'ar-MA', 'خطأ في التأكيد'),
  ('CHECKOUT_RETURN_FAILURE_BUTTON', 'ar-MA', 'حاول مرة أخرى'),
  ('CHECKOUT_RETURN_FAILURE_SUBTITLE', 'ar-MA', 'حدثت مشكلة في الدفع. سلة التسوق الخاصة بك لا تزال محفوظة.'),
  ('CHECKOUT_RETURN_FAILURE_TITLE', 'ar-MA', 'لم يكتمل الدفع'),
  ('CHECKOUT_RETURN_ORDER_PREFIX', 'ar-MA', 'طلب'),
  ('CHECKOUT_RETURN_PENDING_BUTTON', 'ar-MA', 'عرض طلباتي'),
  ('CHECKOUT_RETURN_PENDING_SUBTITLE', 'ar-MA', 'تتم معالجة دفعتك. سيبدأ التحضير بمجرد التأكيد.'),
  ('CHECKOUT_RETURN_PENDING_TITLE', 'ar-MA', 'الدفع قيد المراجعة'),
  ('CHECKOUT_RETURN_SUCCESS_BUTTON', 'ar-MA', 'تتبع طلبي'),
  ('CHECKOUT_RETURN_SUCCESS_SUBTITLE', 'ar-MA', 'تم استلام طلبك ويتم تحضيره بعناية.'),
  ('CHECKOUT_RETURN_SUCCESS_TITLE', 'ar-MA', 'تم تأكيد الدفع!'),
  ('CLIENT_DASHBOARD_ASK_REASON', 'ar-MA', 'اسأل عن السبب'),
  ('CLIENT_DASHBOARD_CANCELLED_WHATSAPP', 'ar-MA', 'تم الإلغاء عبر واتساب'),
  ('CLIENT_DASHBOARD_CLIENT', 'ar-MA', 'عميل'),
  ('CLIENT_DASHBOARD_CONFIRM', 'ar-MA', 'تأكيد؟'),
  ('CLIENT_DASHBOARD_CRUST', 'ar-MA', 'حافة'),
  ('CLIENT_DASHBOARD_DELIVERY', 'ar-MA', 'توصيل'),
  ('CLIENT_DASHBOARD_DELIVERY_CODE_HINT', 'ar-MA', 'قدم هذا الرمز للمندوب لتأكيد التسليم'),
  ('CLIENT_DASHBOARD_DELIVERY_CODE_LABEL', 'ar-MA', 'رمز تأكيد التسليم'),
  ('CLIENT_DASHBOARD_EMPTY_ALL', 'ar-MA', 'ليس لديك طلبات بعد.'),
  ('CLIENT_DASHBOARD_EMPTY_FILTER', 'ar-MA', 'لم يتم العثور على طلبات لهذا الفلتر.'),
  ('CLIENT_DASHBOARD_FILTER_ALL', 'ar-MA', 'الكل'),
  ('CLIENT_DASHBOARD_HALF_HALF', 'ar-MA', 'نصف ونصف'),
  ('CLIENT_DASHBOARD_HELLO', 'ar-MA', 'مرحبًا'),
  ('CLIENT_DASHBOARD_LOAD_ERROR', 'ar-MA', 'خطأ في تحميل الطلبات.'),
  ('CLIENT_DASHBOARD_ORDER_PREFIX', 'ar-MA', 'طلب'),
  ('CLIENT_DASHBOARD_PAYMENT', 'ar-MA', 'دفع'),
  ('CLIENT_DASHBOARD_PIZZA', 'ar-MA', 'بيتزا'),
  ('CLIENT_DASHBOARD_REPEAT_ERROR', 'ar-MA', 'لا يمكن تكرار هذا الطلب.'),
  ('CLIENT_DASHBOARD_REPEAT_ORDER', 'ar-MA', 'تكرار الطلب'),
  ('CLIENT_DASHBOARD_REPEAT_SUCCESS', 'ar-MA', 'تمت إضافة الطلب إلى السلة مرة أخرى.'),
  ('DELETE', 'ar-MA', 'حذف'),
  ('EDIT', 'ar-MA', 'تعديل'),
  ('FIRST_HALF_CHOOSE_NEXT', 'ar-MA', 'اختر البيتزا التالية لإكمال الطلب.'),
  ('FIRST_HALF_SELECTED_MSG', 'ar-MA', 'تم اختيار النصف الأول:'),
  ('HOME_ABOUT_P1', 'ar-MA', 'منذ عام 1997، أصبحت بيتزاريا فيليشي مرادفًا للجودة والنكهة. نجمع بين المكونات الطازجة والوصفات الحصرية لنقدم بيتزا تسحر الجميع. سواء في قاعة طعامنا الدافئة أو عبر خدمة التوصيل، نضمن تجربة طعام استثنائية.'),
  ('HOME_ABOUT_P2', 'ar-MA', 'بالإضافة إلى بيتزاتنا، نقدم تشكيلة رائعة من المقبلات والسندويشات والوجبات الخفيفة والبطاطا والحلويات، كلها محضّرة بنفس الاهتمام والتفاني.'),
  ('HOME_ABOUT_P3', 'ar-MA', 'اكتشف لماذا بيتزاريا فيليشي هي الخيار الصحيح لمن يبحث عن التقليد والجودة ولمسة من التميز. زرنا أو اطلب عبر الإنترنت واستمتع بأفضل ما في المطبخ الإيطالي.'),
  ('HOME_HERO_TITLE_1', 'ar-MA', 'أصيلة'),
  ('HOME_HERO_TITLE_2', 'ar-MA', 'بيتزا إيطالية'),
  ('HOME_SINCE_1997', 'ar-MA', 'منذ 1997 · 27 عامًا من التقليد الإيطالي'),
  ('KITCHEN_ADVANCE_TO_TABLE', 'ar-MA', 'خذ إلى الطاولة'),
  ('KITCHEN_CLEAR_ALERTS', 'ar-MA', 'مسح التنبيهات'),
  ('KITCHEN_DELIVERED_AT_TABLE', 'ar-MA', 'تم التوصيل للطاولة'),
  ('KITCHEN_DELIVERY', 'ar-MA', 'توصيل'),
  ('KITCHEN_DROP_TO_STAGE', 'ar-MA', 'أفلت هنا للانتقال إلى {{stage}}'),
  ('KITCHEN_HIGHLIGHT_SECONDS', 'ar-MA', 'التمييز نشط لمدة {{seconds}} ثانية.'),
  ('KITCHEN_LIVE', 'ar-MA', 'مباشر'),
  ('KITCHEN_LOAD_ERROR', 'ar-MA', 'فشل تحميل الطلبات.'),
  ('KITCHEN_MARK_PICKED_UP', 'ar-MA', 'وضع علامة كتم الاستلام'),
  ('KITCHEN_NEW_ORDER', 'ar-MA', 'طلب جديد'),
  ('KITCHEN_NEW_ORDER_ARRIVED', 'ar-MA', 'طلب جديد {{id}} وصل إلى قائمة الانتظار'),
  ('KITCHEN_NO_ACTIVE_ORDERS', 'ar-MA', 'لا توجد طلبات نشطة حاليا.'),
  ('KITCHEN_NO_ALERTS', 'ar-MA', 'لا توجد تنبيهات معلقة'),
  ('KITCHEN_NO_ORDER', 'ar-MA', 'لا يوجد طلب'),
  ('KITCHEN_NO_OVERDUE', 'ar-MA', 'لا توجد طلبات متأخرة'),
  ('KITCHEN_OFF', 'ar-MA', 'متوقف'),
  ('KITCHEN_ON', 'ar-MA', 'شغال'),
  ('KITCHEN_ORDERS_IN_STAGE', 'ar-MA', 'الطلبات في هذه المرحلة'),
  ('KITCHEN_OVERDUE_ALERT', 'ar-MA', '{{count}} طلب متأخر'),
  ('KITCHEN_OVERDUE_COUNT', 'ar-MA', '{{count}} طلبات متأخرة'),
  ('KITCHEN_PAYMENT_PENDING', 'ar-MA', 'دفع معلق'),
  ('KITCHEN_PICKUP', 'ar-MA', 'استلام'),
  ('KITCHEN_READY_PICKUP', 'ar-MA', 'جاهز للاستلام'),
  ('KITCHEN_SOUND', 'ar-MA', 'صوت'),
  ('KITCHEN_TITLE', 'ar-MA', 'مطبخ'),
  ('KITCHEN_UNREAD_ALERTS', 'ar-MA', '{{count}} تنبيهات جديدة غير مقروءة'),
  ('KITCHEN_UPDATED_AT', 'ar-MA', 'تم التحديث في {{time}} • في الوقت الفعلي مع احتياطي دقيقتين'),
  ('KITCHEN_UPDATING', 'ar-MA', 'جاري التحديث...'),
  ('MESA_ACCESS_INVALID_QR_TEXT_1', 'ar-MA', 'رمز الاستجابة السريعة هذا منتهي الصلاحية أو لم يعد صالحًا.'),
  ('MESA_ACCESS_INVALID_QR_TEXT_2', 'ar-MA', 'اطلب من الموظف إنشاء رمز جديد.'),
  ('MESA_ACCESS_INVALID_QR_TITLE', 'ar-MA', 'رمز QR غير صالح'),
  ('MESA_ACCESS_LOADING', 'ar-MA', 'جاري التعرف على الطاولة...'),
  ('MESA_CHECKOUT_BACK_MENU', 'ar-MA', '← القائمة'),
  ('MESA_CHECKOUT_CONFIRM_ORDER', 'ar-MA', 'تأكيد الطلب'),
  ('MESA_CHECKOUT_NOTES_LABEL', 'ar-MA', 'ملاحظات (اختياري)'),
  ('MESA_CHECKOUT_NOTES_PLACEHOLDER', 'ar-MA', 'مثال: بدون بصل، عجينة رقيقة...'),
  ('MESA_CHECKOUT_ORDER_ERROR', 'ar-MA', 'خطأ في تقديم الطلب.'),
  ('MESA_CHECKOUT_ORDER_SENT', 'ar-MA', 'تم إرسال الطلب إلى المطبخ!'),
  ('MESA_CHECKOUT_PAY_LATER', 'ar-MA', 'ادفع لاحقًا'),
  ('MESA_CHECKOUT_PAY_NOW', 'ar-MA', 'هل تريد الدفع الآن؟'),
  ('MESA_CHECKOUT_PAYMENT_CONFIRMED', 'ar-MA', 'تم تأكيد الدفع! 🍕'),
  ('MESA_CHECKOUT_PENDING_TOTAL', 'ar-MA', 'الإجمالي المعلق'),
  ('MESA_CHECKOUT_PIX_SHORT', 'ar-MA', 'PIX'),
  ('MESA_CHECKOUT_SENDING', 'ar-MA', 'جاري الإرسال...'),
  ('MESA_CHECKOUT_SESSION_ORDERS', 'ar-MA', 'طلبات هذه الجلسة'),
  ('MESA_CHECKOUT_TABLE', 'ar-MA', 'طاولة'),
  ('MESA_CHECKOUT_TERMINAL_SHORT', 'ar-MA', 'جهاز الدفع'),
  ('MESA_CHECKOUT_VIEW_MENU', 'ar-MA', 'عرض القائمة'),
  ('MESA_CHECKOUT_YOUR_ORDER', 'ar-MA', 'طلبك'),
  ('MESA_PIX_COPIED', 'ar-MA', 'تم نسخ الرمز!'),
  ('MESA_PIX_COPY_BUTTON', 'ar-MA', 'انسخ رمز الدفع'),
  ('MESA_PIX_COPY_HINT', 'ar-MA', 'أو انسخ الرمز:'),
  ('MESA_PIX_ERROR', 'ar-MA', 'خطأ في إنشاء رمز الدفع. حاول مرة أخرى.'),
  ('MESA_PIX_GENERATING', 'ar-MA', 'جاري إنشاء رمز الاستجابة السريعة...'),
  ('MESA_PIX_QR_ALT', 'ar-MA', 'رمز QR للدفع'),
  ('MESA_PIX_TITLE', 'ar-MA', 'ادفع الآن'),
  ('MESA_PIX_WAITING', 'ar-MA', 'بانتظار تأكيد الدفع...'),
  ('MESA_TERMINAL_SEND_BUTTON', 'ar-MA', 'أرسل إلى جهاز الدفع'),
  ('MESA_TERMINAL_SEND_ERROR', 'ar-MA', 'خطأ في الإرسال إلى الجهاز.'),
  ('MESA_TERMINAL_SENDING', 'ar-MA', 'جاري الإرسال...'),
  ('MESA_TERMINAL_SENT', 'ar-MA', 'تم إرسال الدفعة إلى الجهاز!'),
  ('MESA_TERMINAL_TITLE', 'ar-MA', 'الدفع في الجهاز'),
  ('MESA_TERMINAL_WAITING', 'ar-MA', 'في انتظار الدفع في الجهاز...'),
  ('MONTH_LABEL_APR', 'ar-MA', 'أبريل'),
  ('MONTH_LABEL_AUG', 'ar-MA', 'أغسطس'),
  ('MONTH_LABEL_DEC', 'ar-MA', 'ديسمبر'),
  ('MONTH_LABEL_FEB', 'ar-MA', 'فبراير'),
  ('MONTH_LABEL_JAN', 'ar-MA', 'يناير'),
  ('MONTH_LABEL_JUL', 'ar-MA', 'يوليو'),
  ('MONTH_LABEL_JUN', 'ar-MA', 'يونيو'),
  ('MONTH_LABEL_MAR', 'ar-MA', 'مارس'),
  ('MONTH_LABEL_MAY', 'ar-MA', 'مايو'),
  ('MONTH_LABEL_NOV', 'ar-MA', 'نوفمبر'),
  ('MONTH_LABEL_OCT', 'ar-MA', 'أكتوبر'),
  ('MONTH_LABEL_SEP', 'ar-MA', 'سبتمبر'),
  ('MONTH_SHORT_APR', 'ar-MA', 'أبر'),
  ('MONTH_SHORT_AUG', 'ar-MA', 'أغس'),
  ('MONTH_SHORT_DEC', 'ar-MA', 'ديس'),
  ('MONTH_SHORT_FEB', 'ar-MA', 'فبر'),
  ('MONTH_SHORT_JAN', 'ar-MA', 'ينا'),
  ('MONTH_SHORT_JUL', 'ar-MA', 'يول'),
  ('MONTH_SHORT_JUN', 'ar-MA', 'يون'),
  ('MONTH_SHORT_MAR', 'ar-MA', 'مار'),
  ('MONTH_SHORT_MAY', 'ar-MA', 'ماي'),
  ('MONTH_SHORT_NOV', 'ar-MA', 'نوف'),
  ('MONTH_SHORT_OCT', 'ar-MA', 'أكت'),
  ('MONTH_SHORT_SEP', 'ar-MA', 'سبت'),
  ('MOTOBOY_ADDRESS', 'ar-MA', 'العنوان'),
  ('MOTOBOY_ALREADY_PAID', 'ar-MA', 'مدفوع مسبقًا'),
  ('MOTOBOY_AUTO_REFRESH_HINT', 'ar-MA', 'تتحدث هذه الصفحة تلقائيًا كل 20 ثانية.'),
  ('MOTOBOY_CODE_PLACEHOLDER', 'ar-MA', 'مثال: 1234'),
  ('MOTOBOY_COLLECT_ON_DELIVERY', 'ar-MA', 'تحصيل المبلغ عند التوصيل'),
  ('MOTOBOY_CONFIRM', 'ar-MA', 'تأكيد'),
  ('MOTOBOY_CONFIRM_DELIVERY_CODE', 'ar-MA', 'تأكيد التسليم باستخدام الرمز'),
  ('MOTOBOY_CONFIRM_PAYMENT_TEXT', 'ar-MA', 'حدد كمدفوع فقط بعد استلام المبلغ.'),
  ('MOTOBOY_CONFIRM_PAYMENT_TITLE', 'ar-MA', 'تأكيد الدفع؟'),
  ('MOTOBOY_CONFIRM_PAYMENT_YES', 'ar-MA', 'نعم، حدد كمدفوع'),
  ('MOTOBOY_CONFIRMING', 'ar-MA', 'جاري التأكيد...'),
  ('MOTOBOY_DELIVERY_CONFIRM_ERROR', 'ar-MA', 'تعذر تأكيد التسليم.'),
  ('MOTOBOY_DELIVERY_CONFIRMED', 'ar-MA', 'تم تأكيد التسليم بنجاح.'),
  ('MOTOBOY_DELIVERY_FEE', 'ar-MA', 'رسوم التوصيل'),
  ('MOTOBOY_EMPTY', 'ar-MA', 'لا توجد طلبات جاهزة للتوصيل في الوقت الحالي.'),
  ('MOTOBOY_GOOGLE_MAPS', 'ar-MA', 'خرائط جوجل'),
  ('MOTOBOY_LOAD_ERROR', 'ar-MA', 'خطأ في تحميل الطلبات. حاول التحديث.'),
  ('MOTOBOY_LOADING', 'ar-MA', 'جاري التحميل...'),
  ('MOTOBOY_MARK_PAID', 'ar-MA', 'حدد كمدفوع'),
  ('MOTOBOY_MARK_PAID_FIRST', 'ar-MA', 'لتأكيد التسليم، حدد الطلب كمدفوع أولاً.'),
  ('MOTOBOY_ORDER_PREFIX', 'ar-MA', 'طلب'),
  ('MOTOBOY_ORDER_TOTAL', 'ar-MA', 'إجمالي الطلب'),
  ('MOTOBOY_PAYMENT_CONFIRM_ERROR', 'ar-MA', 'تعذر تأكيد الدفع.'),
  ('MOTOBOY_PAYMENT_MARKED', 'ar-MA', 'تم تحديد الدفع كمقبول.'),
  ('MOTOBOY_REFRESH', 'ar-MA', 'تحديث'),
  ('MOTOBOY_SAVING', 'ar-MA', 'جاري الحفظ...'),
  ('MOTOBOY_SEARCH_ADDRESS', 'ar-MA', 'ابحث عن العنوان في خرائط جوجل'),
  ('MOTOBOY_TITLE', 'ar-MA', 'التوصيلات'),
  ('MOTOBOY_WAZE', 'ar-MA', 'ويز'),
  ('NO', 'ar-MA', 'لا'),
  ('SALES_ANALYTICS_AVG_TICKET', 'ar-MA', 'متوسط التذكرة'),
  ('SALES_ANALYTICS_BACK_PANEL', 'ar-MA', 'لوحة'),
  ('SALES_ANALYTICS_BY_MONTH', 'ar-MA', 'حسب الشهر'),
  ('SALES_ANALYTICS_COST_HINT', 'ar-MA', 'مجموع سعر تكلفة العناصر'),
  ('SALES_ANALYTICS_COST_PREFIX', 'ar-MA', 'تكلفة'),
  ('SALES_ANALYTICS_COST_TOTAL', 'ar-MA', 'التكلفة الإجمالية'),
  ('SALES_ANALYTICS_FULL_YEAR', 'ar-MA', 'عام كامل'),
  ('SALES_ANALYTICS_GO_PRODUCTS', 'ar-MA', 'منتجات'),
  ('SALES_ANALYTICS_LEGEND_COST', 'ar-MA', 'تكلفة'),
  ('SALES_ANALYTICS_LEGEND_PROFIT', 'ar-MA', 'ربح'),
  ('SALES_ANALYTICS_LEGEND_REVENUE', 'ar-MA', 'إيرادات'),
  ('SALES_ANALYTICS_LOAD_ERROR', 'ar-MA', 'فشل تحميل تحليلات المبيعات.'),
  ('SALES_ANALYTICS_MONTH', 'ar-MA', 'شهر'),
  ('SALES_ANALYTICS_NO_PAID_ORDERS', 'ar-MA', 'لا توجد طلبات مدفوعة للتحليل بعد.'),
  ('SALES_ANALYTICS_PROFIT_HINT', 'ar-MA', 'الإيرادات − التكلفة'),
  ('SALES_ANALYTICS_PROFIT_PREFIX', 'ar-MA', 'ربح'),
  ('SALES_ANALYTICS_PROFIT_TOTAL', 'ar-MA', 'صافي الربح'),
  ('SALES_ANALYTICS_REVENUE_HINT', 'ar-MA', 'الطلبات المدفوعة'),
  ('SALES_ANALYTICS_REVENUE_TOTAL', 'ar-MA', 'إجمالي الإيرادات'),
  ('SALES_ANALYTICS_SALES_COUNT', 'ar-MA', '{{count}} مبيعات'),
  ('SALES_ANALYTICS_STATUS_PAID', 'ar-MA', 'مدفوعة (مقبولة)'),
  ('SALES_ANALYTICS_STATUS_TITLE', 'ar-MA', 'حالة الطلب'),
  ('SALES_ANALYTICS_SUBTITLE', 'ar-MA', 'الإيرادات وحجم الطلب وأفضل النكهات في الوقت الفعلي.'),
  ('SALES_ANALYTICS_TICKET_HINT', 'ar-MA', '{{paid}} مدفوع من إجمالي {{total}}'),
  ('SALES_ANALYTICS_TITLE', 'ar-MA', 'تحليلات المبيعات'),
  ('SALES_ANALYTICS_TODAY', 'ar-MA', 'اليوم'),
  ('SALES_ANALYTICS_TOP_FLAVORS', 'ar-MA', 'أفضل النكهات'),
  ('SALES_ANALYTICS_TOP_FLAVORS_HINT', 'ar-MA', 'استنادًا إلى الطلبات المدفوعة'),
  ('YES', 'ar-MA', 'نعم')
) AS v(chave, codigo_idioma, valor)
JOIN sistemas s ON s.codigo = 'website'
JOIN idiomas i ON i.codigo = v.codigo_idioma
ON CONFLICT (chave, sistema_id, idioma_id)
DO UPDATE SET valor = EXCLUDED.valor, atualizado_em = NOW();